Repository scylladb/scylla-cluster-tests, pull requests merged in 2019-03, with the labels that each got.

#843 Fix hydra to pass jenkins BUILD_* variables
  docker/env/hydra.sh
Labels: Backport-2018.1, Backport-2019.1, Backport-3.0

#828 Support running SCT with scylla-cloud
  docker/env/hydra.sh
  docker/env/version
  get-qa-ssh-keys.sh
  mgmt_cli_test.py
  sdcm/cluster.py
  sdcm/cluster_aws.py
  sdcm/cluster_baremetal.py
  sdcm/nemesis.py
  sdcm/sct_config.py
  sdcm/tester.py
  sdcm/utils.py
  test-cases/longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml
Labels: Backport-2018.1, Backport-2019.1, Backport-3.0

#848 Remove the 'hostnamectl set-hostname' call from PhysicalMachineNode
  sdcm/cluster_baremetal.py
  sdcm/sct_config.py
Labels: Backport-2019.1

#849 update loader AMI: fix collectd-exporter
  defaults/aws_config.yaml
  defaults/docker_config.yaml
  defaults/libvirt_config.yaml
  defaults/openstack_config.yaml
  tests/aws-grow-cluster-200nodes.yaml
  tests/corrupt-then-rebuild.yaml
  tests/destroy-data-then-repair.yaml
  tests/dns-cluster-5min.yaml
  tests/enospc-30mins.yaml
  tests/hinted-handoff.yaml
  tests/janus-graph.yaml
  tests/longevity-1TB-7days-authorization-and-tls-ssl.yaml
  tests/longevity-1TB-7days.yaml
  tests/longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml
  tests/longevity-48h-verify-multiDC.yaml
  tests/longevity-50GB-4days-authorization-and-tls-ssl.yaml
  tests/longevity-50GB-4days.yaml
  tests/longevity-in-memory-36GB-4days.yaml
  tests/longevity-multi-keyspaces.yaml
  tests/longevity-mv-si-4days.yaml
  tests/longevity-staging.yaml
  tests/manager-regression-multiDC-set-distro.yaml
  tests/perf-regression-2mv.yaml
  tests/perf-regression-latency-1TB.yaml
  tests/perf-regression-latency-500gb-30min.yaml
  tests/perf-regression-latency-in-memory.yaml
  tests/perf-regression-mv.100threads.30M-keys-i3.yaml
  tests/perf-regression-user-profiles.yaml
  tests/perf-regression.100threads.30M-keys-i3.yaml
  tests/perf-regression.100threads.30M-keys.yaml
  tests/refresh-30mins-100mb.yaml
  tests/refresh-30mins-120gb.yaml
  tests/repair-240mins-100G.yaml
  tests/sample.yaml
Labels: Backport-2019.1

#851 Saving test_id when creating initial tests stats structure
  sdcm/db_stats.py
Labels: Backport-2019.1

#850 Collect scylla monitoring stack logs
  sdcm/cluster.py
Labels: No Backport Needed

#852 Adding reuse cluster to README.rst
  README.rst
Labels: Backport-2019.1

#855 Fix cyclic-decencies that failed microbenchmarking.py
  sdcm/cluster.py
  sdcm/db_stats.py
Labels: No Backport Needed

#841 Longevity counters
  longevity_test.py
  tests/longevity-counters-4d-multidc.yaml
Labels: Backport-2019.1

#853 Change the spot price to default to 60% of OnDemend price
  sdcm/cluster_aws.py
  sdcm/ec2_client.py
  sdcm/sct_config.py
Labels: Backport-2019.1

#859 set default value for 'spot_max_price' (fix_typo)
  sdcm/cluster_aws.py
Labels: Backport-2019.1

#862 Fixing collecting monitor related artifacts when NoMonitorSet is used
  sdcm/db_stats.py
Labels: Backport-2019.1

#864 Pin pricing api to specific region
  sdcm/ec2_client.py
Labels: Backport-2019.1

#869 Fix node.is_seed logic
  sdcm/cluster.py
  sdcm/cluster_aws.py
  sdcm/cluster_libvirt.py
  sdcm/cluster_openstack.py
Labels: Backport-2019.1

#872 Change all journalctl calls to use sudo
  sdcm/cluster.py
  sdcm/nemesis.py
Labels: Backport-2019.1
