Repository scylladb/scylla-cluster-tests, pull requests merged in 2019-09, with the labels that each got.

#1271 get_monitoring_data_stack: only save valid annotations to file
  sdcm/cluster.py
Labels: Backport-2019.1, Backport-3.1, Ready to be Merged

#1266 Changed post-reboot check's timeout to 180 seconds
  sdcm/cluster_aws.py
Labels: Backport-2019.1, Backport-3.1

#1277 Remove unused logs files and archives
  sdcm/tester.py
  sdcm/utils/common.py
Labels: Backport-3.1, Ready for review

#1259 Make CorruptThenRepiar nemesis run on MV or other keyspace, not on keyspace1 only
  data_dir/break_scylla.sh
  sdcm/nemesis.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1281 Print full exception instead of message in Cluster Health Check
  sdcm/cluster.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1282 Minor updates to 1000 keyspaces use case
  test-cases/longevity/longevity-multi-keyspaces.yaml
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1276 Handle interlaced reactor stalls, to avoid backtrace events
  sdcm/cluster.py
  unit_tests/test_cluster.py
  unit_tests/test_data/database_interlace_stall.log
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1289 Don't print system.peers output into the loge is the validation not failed
  sdcm/cluster.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1290 Fixing remote runner not to print stdout multiple times + timeout exc…
  sdcm/remote.py
  sdcm/utils/common.py
Labels: Backport-2019.1, Backport-3.1

#1284 Fixes for management repair
  sdcm/nemesis.py
Labels: Backport-2019.1, Backport-3.1

#1288 Add full gemini command to email report
  gemini_test.py
  sdcm/gemini_thread.py
  sdcm/results_gemini.html
Labels: 3.1-backported, Ready for review

#1287 Reconfigure gemini jobs
  test-cases/gemini/gemini-1tb-10h.yaml
  test-cases/gemini/gemini-3h-with-nondisruptive-nemesis.yaml
  test-cases/gemini/gemini-basic-3h.yaml
Labels: Backport-3.1, Ready for review

#1285 Support all file formats in CorruptThenRepiar nemesis
  sdcm/nemesis.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1294 Cluster health check: don't send error if new node isn't initiated yet
  sdcm/cluster.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1295 Fix to `hydra investigate show-monitor` to work on master scylla version
  sdcm/utils/common.py
Labels: Ready for review

#1269 Improve the toppartittion nemesis error reporting
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#1297 Stop scylla before running scylla_create_devices to prevent false pos…
  sdcm/cluster_aws.py
Labels: Backport-2019.1, Backport-3.1, Ready to be Merged

#1249 Adding email reporting functionality longevity test
  gemini_test.py
  longevity_test.py
  sdcm/cluster.py
  sdcm/gemini_thread.py
  sdcm/results_analyze.py
  sdcm/results_base.html
  sdcm/results_longevity.html
  sdcm/sct_events.py
  sdcm/send_email.py
  sdcm/stress_thread.py
  sdcm/tester.py
  sdcm/utils/common.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1302 Fix None result during creating prometheous snapshot
  sdcm/cluster.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1300 disable upgrade from 2.3 to 3.1
  jenkins-pipelines/rolling-upgrade-centos7.jenkinsfile
  jenkins-pipelines/rolling-upgrade-debian9.jenkinsfile
  jenkins-pipelines/rolling-upgrade-ubuntu16.04.jenkinsfile
  jenkins-pipelines/rolling-upgrade-ubuntu18.04.jenkinsfile
Labels: No Backport Needed

#1251 Retry to update repo cache after system is up
  partial_upgrade_downgrade_test.py
  sdcm/cluster.py
  upgrade_test.py
Labels: Backport-2019.1, Backport-3.0, Backport-3.1, Ready to be Merged

#1262 upgrade_test: ignore backtrace of stall
  upgrade_test.py
Labels: Backport-2019.1, Backport-3.1, Ready to be Merged

#1318 Fixed collect_partitions_info
  sdcm/tester.py
Labels: Backport-2019.1, Backport-3.1

#1319 Log unhandled exceptions
  sdcm/tester.py
  sdcm/utils/common.py
  sdcm/utils/log.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1307 Make DatabaseLogEvent read log time and filter by it
  docker/env/version
  requirements-python.txt
  sdcm/sct_events.py
  sdcm/utils/common.py
  sdcm/utils/py3_backports.py
  unit_tests/test_data/database_interlace_stall.log
  unit_tests/test_events.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1324 Add more missing filters to abort_repair nemesis
  sdcm/nemesis.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1327 fixing wrong assignment of hostname with public_ip always
  sdcm/cluster_aws.py
Labels: Backport-2019.1, Backport-3.1, Ready to be Merged

#1329 Fix wait_for() verbosity to be clearer
  sdcm/wait.py
  unit_tests/test_wait.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1169 Change test runner from unittest to pytest
  docker/env/version
  requirements-python.txt
  sct.py
Labels: No Backport Needed, Ready for review

#1296 Add new extra interface on AWS for network related Nemesis
  docker/env/version
  jenkins-pipelines/longevity-200gb-48h-network-monkey.jenkinsfile
  requirements-python.txt
  sct.py
  sdcm/cluster.py
  sdcm/cluster_aws.py
  sdcm/nemesis.py
  sdcm/sct_config.py
  sdcm/tester.py
  sdcm/utils/common.py
  test-cases/longevity/longevity-200GB-48h-network-monkey.yaml
Labels: No Backport Needed, Ready for review

#1316 improve gemini test config settings
  gemini_test.py
  sdcm/results_gemini.html
  sdcm/send_email.py
  test-cases/gemini/gemini-1tb-10h.yaml
  test-cases/gemini/gemini-3h-with-nondisruptive-nemesis.yaml
  test-cases/gemini/gemini-basic-3h.yaml
Labels: No Backport Needed, Ready for review

#1323 Add support to run gemini without oracle cluster
  sdcm/gemini_thread.py
Labels: No Backport Needed, Ready for review

#1340 Changed to use latest version of apache-libcloud
  .pre-commit-config.yaml
  docker/env/version
  requirements-python.txt
Labels: Backport-2019.1, Backport-3.1

#1337 Changed the default timezone of monitor to UTC
  data_dir/scylla-dash-per-server-nemesis.2.1.json
  data_dir/scylla-dash-per-server-nemesis.2.2.json
  data_dir/scylla-dash-per-server-nemesis.2.3.json
  data_dir/scylla-dash-per-server-nemesis.2017.1.json
  data_dir/scylla-dash-per-server-nemesis.2018.1.json
  data_dir/scylla-dash-per-server-nemesis.2019.1.json
  data_dir/scylla-dash-per-server-nemesis.3.0.json
  data_dir/scylla-dash-per-server-nemesis.3.1.json
  data_dir/scylla-dash-per-server-nemesis.master.json
  data_dir/scylla-dash-per-server.json
  data_dir/scylla-dash-per-server.master.json
  data_dir/scylla-dash-timeout-metrics.json
  data_dir/scylla-dash.json
  data_dir/scylla-dash.master.json
Labels: No Backport Needed

#1332 Adding availability of ami-id check
  sdcm/tester.py
  sdcm/utils/common.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1280 New `tag_ami_with_result` option
  performance_regression_test.py
  sct.py
  sdcm/cluster.py
  sdcm/cluster_aws.py
  sdcm/cluster_gce.py
  sdcm/cluster_openstack.py
  sdcm/docker.py
  sdcm/sct_config.py
  sdcm/tester.py
  sdcm/utils/common.py
  unit_tests/test_utils_common.py
  vars/longevityPipeline.groovy
Labels: No Backport Needed, Ready for review

#1346 cluster_aws: fix permmsion problem in writing scylla.yaml
  sdcm/cluster_aws.py
Labels: Backport-2019.1, Backport-3.1

#1335 update_scylla_packages: don't update scylla packages before replacement
  sdcm/cluster.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1331 remove partial_upgrade_downgrade_test.py
  partial_upgrade_downgrade_test.py
Labels: No Backport Needed, Ready to be Merged

#1230 Update encryption key for each test
  docker/env/version
  install-prereqs.sh
  sdcm/tester.py
  sdcm/utils/common.py
Labels: Backport-2019.1, Backport-3.1, Ready for review, Ready to be Merged

#1227 Adding functionality to clear instances by several test-ids
  sct.py
  sdcm/utils/common.py
Labels: No Backport Needed

#1348 Fix issue running on jenkins for longevity pipeline
  vars/longevityPipeline.groovy
Labels: No Backport Needed, Ready for review

#1349 Remove janusgraph test from SCT
  janus_graph_test.py
  jenkins-pipelines/features-janusgraph-integration.jenkinsfile
  test-cases/features/janus-graph.yaml
  tests/janus-graph.yaml
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1328 Adding gemini seed config parameter
  sdcm/cluster.py
  sdcm/gemini_thread.py
  sdcm/sct_config.py
  sdcm/tester.py
Labels: Backport-3.1, Ready for review

#1350 [For branch-3.1] Revert "Disabled show_toppartitions Nemesis on 3.1-rc8"
  sdcm/nemesis.py
Labels: No Backport Needed
