Repository scylladb/scylla-cluster-tests, pull requests merged in 2019-12, with the labels that each got.

#1487 Fix uploading dashboard json file
  data_dir/scylla-dash-per-server-nemesis.master.json
  sdcm/cluster.py
Labels: No Backport Needed, Ready for review

#1456 Add to ParallelObject possibility not to fail on exception
  sdcm/logcollector.py
  sdcm/utils/common.py
  unit_tests/test_parallelobject.py
Labels: Backport-3.1, Backport-3.2, Ready to be Merged

#1469 cluster_aws: retry to stop scylla-server after instance restart
  sdcm/cluster.py
  sdcm/remote.py
Labels: Backport-3.2, Ready to be Merged

#1427 Remove libvirt and openstack support from SCT
  defaults/libvirt_config.yaml
  defaults/openstack_config.yaml
  sdcm/cluster.py
  sdcm/cluster_libvirt.py
  sdcm/cluster_openstack.py
  sdcm/sct_config.py
  sdcm/tester.py
  unit_tests/test_config.py
Labels: No Backport Needed, Ready for review

#1491 Fix cache/disk only and both tests
  sla_per_user_system_test.py
  test-cases/features/system-sla-test.yaml
Labels: Backport-2019.1

#1494 Fix max_rows_for_read parameter name in branch-2019.1
  sla_per_user_system_test.py
Labels: No Backport Needed

#1489 Change the 1TB schema to be 5 columns as the default instead of 1 column
  test-cases/longevity/longevity-1TB-7days-authorization-and-tls-ssl.yaml
Labels: No Backport Needed

#1505 Add missed code to the branch-2019.1
  sla_per_user_system_test.py
Labels: 2019.1-backported, Backport-2019.1

#1501 Fix screenshot for per-server-metrics-nemesis dashboard
  sdcm/db_stats.py
  sdcm/tester.py
Labels: Backport-3.2, Urgent

#1498 AWS: move `self._wait_public_ip()` back to before `super()`
  sdcm/cluster_aws.py
Labels: Backport-3.2, Urgent

#1506 Move the `scylla --version` output into info level log
  sdcm/cluster.py
Labels: Backport-2019.1, Backport-3.1, Backport-3.2

#1499 sdcm/fill_db_data: fix expect result bype of empty blob
  sdcm/fill_db_data.py
Labels: No Backport Needed

#1508 Remoter: added ability to compeltely silence the remoter
  sdcm/remote.py
Labels: No Backport Needed

#1490 Adding swap file to loader nodes during setup process #1118
  defaults/test_default.yaml
  sdcm/cluster.py
  sdcm/sct_config.py
Labels: Backport-3.2

#1449 Search builder by tags on aws and gce
  sdcm/utils/common.py
Labels: No Backport Needed, Ready for review

#1512 Change scylla-cloud pipeline db nodes to i3.xlarge
  jenkins-pipelines/scylla-cloud-longevity-100gb-48h.jenkinsfile
  jenkins-pipelines/scylla-cloud-longevity-10gb-3h.jenkinsfile
  vars/scyllaCloudLongevityPipeline.groovy
Labels: No Backport Needed, Urgent

#1514 Added to all AWS instances new instance_profile
  sdcm/cluster_aws.py
  sdcm/ec2_client.py
  sdcm/sct_config.py
Labels: No Backport Needed

#1478 Added manager 2.0 installation
  defaults/test_default.yaml
  jenkins-pipelines/manager-sanity.jenkinsfile
  mgmt_cli_test.py
  sdcm/cluster.py
  sdcm/mgmt.py
  sdcm/nemesis.py
  sdcm/sct_config.py
  sdcm/tester.py
  test-cases/manager/manager-regression-multiDC-set-distro.yaml
  vars/longevityPipeline.groovy
Labels: No Backport Needed, Urgent

#1516 Checking if instance_profile is empty before call
  sdcm/cluster_aws.py
  sdcm/ec2_client.py
Labels: No Backport Needed, Urgent

#1482 [ICS] New Nemesis that alter table to IncrementalCompactionStrategy randomly
  jenkins-pipelines/longevity-ics-toggle-strategy-500gb-24h.jenkinsfile
  longevity_ics_test.py
  sdcm/nemesis.py
  sdcm/tester.py
  test-cases/longevity/longevity-ics-toggle-strategy-500gb-24h.yaml
  test_lib/compaction.py
Labels: Backport-2019-ICS, Ready to be Merged

#1515 Coredump handling
  sdcm/cluster.py
Labels: Backport-3.2

#1519 Fix to skip sending message on first retry
  sdcm/utils/common.py
Labels: No Backport Needed, Ready for review

#1510 issue #1504: Catch file with not expected name
  sdcm/nemesis.py
Labels: Backport-2019.1, Backport-3.2

#1497 Introducing `GrafanaEventAggragator` thread
  sdcm/cluster.py
  sdcm/cluster_aws.py
  sdcm/sct_events.py
  sdcm/utils/grafana.py
Labels: No Backport Needed, Ready for review

#1523 raise UnsupportedNemesis on non ics supported version
  sdcm/nemesis.py
Labels: No Backport Needed

#1488 System auth rf now used the credentials.
  defaults/test_default.yaml
  sdcm/cluster.py
  sdcm/cluster_aws.py
  sdcm/tester.py
Labels: Backport-3.1, Backport-3.2, Ready for review

#1518 sdcm/cluster: fix get_nodetool_status
  sdcm/cluster.py
Labels: Backport-3.2, Ready for review

#1520 Move phantomjs to root folder in docker container
  data_dir/make_screenshot.js
  docker/env/version
  install-prereqs.sh
  sdcm/logcollector.py
  sdcm/utils/common.py
Labels: No Backport Needed

#1524 Created first set of backup tests including
  mgmt_cli_test.py
  sdcm/sct_config.py
  test-cases/manager/manager-regression-multiDC-set-distro.yaml
Labels: No Backport Needed

#1525 Backport pull request (enhance upgrade test #1438) to branch-3.2
  docs/configuration_options.md
  jenkins-pipelines/rolling-upgrade-centos7.jenkinsfile
  jenkins-pipelines/rolling-upgrade-debian9.jenkinsfile
  jenkins-pipelines/rolling-upgrade-ubuntu16.04.jenkinsfile
  jenkins-pipelines/rolling-upgrade-ubuntu18.04.jenkinsfile
  sdcm/cluster.py
  sdcm/fill_db_data.py
  sdcm/microbenchmarking.py
  sdcm/sct_config.py
  test-cases/upgrades/rolling-upgrade.yaml
  upgrade_test.py
Labels: No Backport Needed

#1526 Enable logging by sct in rolling-upgrade tests #1495
  vars/rollingUpgradePipeline.groovy
Labels: Backport-3.2, Ready to be Merged

#1530 Changing AbortRepair from non-disruptive nemesis to Disruptive.
  sdcm/nemesis.py
Labels: Backport-3.1, Backport-3.2, Urgent

#1533 Fix issue #1532: improving tags setting
  sdcm/cluster_aws.py
  sdcm/cluster_gce.py
Labels: Backport-3.2

#1531 Fixed get_compaction_strategy()
  test_lib/compaction.py
Labels: No Backport Needed

#1527 Fix double email message sent by gemini job
  jenkins-pipelines/gemini-1tb-10h.jenkinsfile
  jenkins-pipelines/gemini-3h-nondisruptive-nemesis.jenkinsfile
  jenkins-pipelines/gemini-3h.jenkinsfile
  test-cases/gemini/gemini-1tb-10h.yaml
  test-cases/gemini/gemini-3h-with-nondisruptive-nemesis.yaml
  test-cases/gemini/gemini-basic-3h.yaml
  vars/longevityPipeline.groovy
Labels: Backport-3.2

#1542 Fix for a small issue during reuse_cluster
  sdcm/cluster.py
Labels: No Backport Needed, Ready for review

#1548 Enable clear_resources by sct #1545
  vars/rollingUpgradePipeline.groovy
Labels: Backport-3.2

#1550 Fix #1462: SCT failed to clean the resources when job ends
  sct.py
  sdcm/utils/common.py
Labels: Backport-3.2

#1551 Fix #1546: mgmt_auth_token breaking the node_setup of monitor
  sdcm/cluster.py
Labels: No Backport Needed

#1552 Fix #1551: mgmt_auth_token breaking the node_setup of monitor (fix)
  sdcm/cluster.py
Labels: No Backport Needed, Urgent

#1541 mgmt_cli_test.py - added verify_backup_success function
  mgmt_cli_test.py
  sdcm/cluster.py
Labels: No Backport Needed, Ready for review

#1553 Fixed a typo in the class name
  jenkins-pipelines/longevity-ics-toggle-strategy-500gb-24h.jenkinsfile
  jenkins-pipelines/longevity-in-memory-36gb-4d.jenkinsfile
  jenkins-pipelines/longevity-large-partition-4days.jenkinsfile
  longevity_ics_test.py
  longevity_in_memory_test.py
  longevity_large_partition_test.py
Labels: Backport-3.0, Backport-3.1, Backport-3.2, Ready to be Merged

#1556 Adding username to email reports
  gemini_test.py
  longevity_test.py
  sdcm/results_gemini.html
  sdcm/results_longevity.html
  sdcm/send_email.py
Labels: Backport-3.2

#1554 Created a backup (like sanity) and a pipeline for it
  jenkins-pipelines/manager-backup.jenkinsfile
  mgmt_cli_test.py
Labels: No Backport Needed, Ready for review

#1558 Fix 5000 table in one keyspace, to pre_create new tables
  longevity_test.py
Labels: Backport-3.2, Ready for review

#1560 Move monitor latest release branch-3.1
  defaults/test_default.yaml
Labels: No Backport Needed, Ready for review

#1555 Added more backup tests.
  mgmt_cli_test.py
Labels: No Backport Needed

#1559 Updated subtests with new tests + description
  mgmt_cli_test.py
Labels: No Backport Needed

#1509 New SLA test: read:write - 1:1
  jenkins-pipelines/features-sla-read-50perc-write-50perc-load.jenkinsfile
  sla_per_user_system_test.py
Labels: Backport-2019.1, Ready to be Merged

#1561 Cleaning up libvirt and openstack leftovers
  README.rst
  docker/env/version
  docs/configuration_options.md
  docs/new-test-configuration.md
  install-prereqs.sh
  pylintrc
  requirements-python.txt
Labels: No Backport Needed, Ready to be Merged

#1564 Update oracle cluster version for gemini jobs
  test-cases/gemini/gemini-1tb-10h.yaml
  test-cases/gemini/gemini-3h-with-nondisruptive-nemesis.yaml
  test-cases/gemini/gemini-basic-3h.yaml
Labels: Backport-3.2, Urgent

#1529 Change hostname on aws instances from default to sct node name
  sdcm/cluster.py
  sdcm/cluster_aws.py
  sdcm/cluster_gce.py
Labels: No Backport Needed

#1568 5000 tables, change num_of_newly_created_tables to 1
  longevity_test.py
Labels: Backport-3.2

#1570 Backup test add retry cmd
  mgmt_cli_test.py
Labels: No Backport Needed, Ready for review, Urgent

#1571 Added ICS longevity jenkinsfile and yaml
  jenkins-pipelines/ics-longevity-100gb-4h.jenkinsfile
  jenkins-pipelines/ics-longevity-10gb-3h.jenkinsfile
  jenkins-pipelines/ics-longevity-1tb-7days.jenkinsfile
  jenkins-pipelines/ics-longevity-200gb-48h.jenkinsfile
  jenkins-pipelines/ics-longevity-50gb-4days.jenkinsfile
  jenkins-pipelines/ics-longevity-large-partition-4days.jenkinsfile
  longevity_large_partition_test.py
  test-cases/enterprise-features/ics/longevity/ics-longevity-100gb-4h.yaml
  test-cases/enterprise-features/ics/longevity/ics-longevity-10gb-3h.yaml
  test-cases/enterprise-features/ics/longevity/ics-longevity-1TB-7days-authorization-and-tls-ssl.yaml
  test-cases/enterprise-features/ics/longevity/ics-longevity-50GB-4days-authorization-and-tls-ssl.yaml
  test-cases/enterprise-features/ics/longevity/ics-longevity-large-partition-4days.yaml
  test-cases/enterprise-features/ics/longevity/ics_longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml
Labels: Backport-2019.1, Urgent

#1577 Added mv/si longevity configuration files for ICS
  data_dir/ics_c-s_profile_2mv_2queries.yaml
  data_dir/ics_c-s_profile_2si_2queries.yaml
  data_dir/ics_c-s_profile_3si_5queries.yaml
  data_dir/ics_c-s_profile_4mv_5queries.yaml
  jenkins-pipelines/ics-longevity-mv-si-4days.jenkinsfile
  test-cases/enterprise-features/ics/longevity/ics-longevity-mv-si-4days.yaml
Labels: Backport-2019.1, Urgent

#1585 update scylla-tools packages to support ics
  defaults/aws_config.yaml
Labels: Backport-2019.1, Ready for review, Urgent

#1578 Truncate nemesis - Flushing files before truncate
  sdcm/nemesis.py
Labels: Backport-2019.1, Backport-3.2

#1583 switch to use stable hytrust kmip server
  configurations/hytrust-kmip-ear.yaml
  jenkins-pipelines/EaR-longevity-kmip-200gb-6h.jenkinsfile
  jenkins-pipelines/EaR-longevity-kmip-50gb-4d.jenkinsfile
  sdcm/keystore.py
  sdcm/utils/common.py
Labels: Backport-2019.1, Ready for review

#1587 Added new param: 'compaction_strategy'
  sdcm/sct_config.py
Labels: Backport-2019.1, Urgent

#1588 Renamed to: ics-longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml
  test-cases/enterprise-features/ics/longevity/ics-longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml
Labels: Backport-2019.1, Urgent

#1591 Adding email_recipients as job UI parameter
  vars/byoLongevityPipeline.groovy
  vars/longevityPipeline.groovy
  vars/rollingUpgradePipeline.groovy
Labels: Backport-3.2

#1586 use urllib3==1.24.3 to avoid url parse error
  docker/env/version
  requirements-python.txt
Labels: Backport-3.2

#1593 Added a fix to test_client_encryption
  mgmt_cli_test.py
Labels: No Backport Needed, Ready for review, Urgent

#1584 Adding to report information about instances left running
  gemini_test.py
  longevity_test.py
  sct.py
  sdcm/results_gemini.html
  sdcm/results_longevity.html
  sdcm/send_email.py
  sdcm/tester.py
Labels: No Backport Needed

#1592 Fix issue #1589 for clean-resources with multiple config files
  sct.py
  vars/longevityPipeline.groovy
Labels: Backport-2019.1, Backport-3.2

#1595 Fixing multi keyspace pipeline to use batched version of test_custom_time
  jenkins-pipelines/longevity-multi-keyspaces-60h.jenkinsfile
Labels: Backport-2019.1, Backport-3.2

#1582 Fix #1580: setting default region for AWS client
  sdcm/utils/common.py
Labels: Backport-2019.1, Backport-3.2

#1544 New performance test: ICS space amplification
  ics_space_amplification_test.py
  jenkins-pipelines/features-ics-space-amplification-test.jenkinsfile
  longevity_ics_test.py
  sdcm/tester.py
  test-cases/features/ics_space_amplification_test.yaml
Labels: Backport-2019.1

#1597 Fix: set hostname for AWS + minor fixes
  sdcm/auto_ssh.py
  sdcm/cluster.py
  sdcm/cluster_aws.py
Labels: No Backport Needed, Ready to be Merged, Urgent

#1566 Adding send email stage for RollingUpgrade pipeline
  vars/byoLongevityPipeline.groovy
  vars/longevityPipeline.groovy
  vars/rollingUpgradePipeline.groovy
  vars/scyllaCloudLongevityPipeline.groovy
Labels: No Backport Needed

#1572 Changes for scale tests
  configurations/scale-180-200.yaml
  grow_cluster_test.py
  jenkins-pipelines/features-scale-180-200-cluster-test.jenkinsfile
  jenkins-pipelines/features-scale-450-500-cluster-test.jenkinsfile
Labels: Backport-2019.1, Backport-3.1, Backport-3.2

#1600 Fix issues in byo pipeline
  vars/byoLongevityPipeline.groovy
Labels: Urgent

#1601 don't test upgrade from 2018.1 to 2019.1 of Ubuntu 18.04
  jenkins-pipelines/rolling-upgrade-ubuntu18.04.jenkinsfile
Labels: No Backport Needed, Ready for review

#1594 Fix missing data_time for screenshots in update_test_details
  sdcm/cluster.py
  sdcm/utils/common.py
Labels: No Backport Needed

#1603 Fix instance's search for email report by test_id
  sct.py
Labels: No Backport Needed

#1604 Added a get_results to the c-s on backup tests
  mgmt_cli_test.py
Labels: No Backport Needed

#1538 Add remove column nemesis
  data_dir/cs_profile_add_remove_column.yaml
  sdcm/nemesis.py
  sdcm/stress_thread.py
  sdcm/utils/common.py
  test_lib/cql_types.py
  unit_tests/test_test_lib_cql_types.py
Labels: No Backport Needed

#1606 Fix aws add_nodes() to handle new type ami
  sdcm/cluster_aws.py
Labels: No Backport Needed

#1611 Fix timeout for jenkins-pipelines/ics-longevity-200gb-48h.jenkinsfile
  jenkins-pipelines/ics-longevity-200gb-48h.jenkinsfile
Labels: Backport-2019.1

#1612 sdcm/fill_db_data.py: disable list_test
  sdcm/fill_db_data.py
Labels: Backport-2019.1, Backport-3.2, Ready for review, Urgent

#1615 get_branch_version: support repo out of downloads.scylladb.com
  sdcm/utils/version_utils.py
  unit_tests/test_version_utils.py
Labels: Backport-2019.1, Backport-3.2, Ready for review

#1610 Fixed the automatic repair task deletion
  sdcm/mgmt.py
Labels: Backport-2019.1, Backport-3.2

#1621 Fix get_compaction_strategy()
  test_lib/compaction.py
Labels: Backport-2019.1

#1623 Remove MakeFileHandler, trying to fix #1291
  sdcm/utils/log.py
Labels: Backport-2019.1, Backport-3.1, Backport-3.2, Ready for review

#1557 Decode on monitoring node
  sdcm/cluster.py
  sdcm/tester.py
  unit_tests/test_data/database_core.log
  unit_tests/test_decode_backtrace.py
Labels: No Backport Needed

#1637 [backport 2019.1] new SLA test: read:write - 1:1
  jenkins-pipelines/features-sla-read-50perc-write-50perc-load.jenkinsfile
  sla_per_user_system_test.py
Labels: No Backport Needed, Ready for review

#1633 sdcm/fill_db_data: fix delay for each insert to workaround list order issue
  sdcm/fill_db_data.py
Labels: Backport-2019.1, Backport-3.2, Ready for review

#1636 Fix several minor issues in pipeline for Rolling upgrade #1634
  vars/rollingUpgradePipeline.groovy
Labels: Backport-2019.1

#1640 [branch-2019.1] Change instance type and test time (missed #1491 PR)
  test-cases/features/system-sla-test.yaml
Labels: Ready for review

#1624 Fix #1622: send_email command to handle empty email_recipients
  sct.py
Labels: Backport-3.2

#1642 Fix coredump download link
  sdcm/cluster.py
Labels: No Backport Needed, Urgent

#1644 Remove old test yamls
  README.rst
  docs/new-test-configuration.md
  sct.py
  sdcm/sct_config.py
  tests/aws-grow-cluster-200nodes.yaml
  tests/corrupt-then-rebuild.yaml
  tests/destroy-data-then-repair.yaml
  tests/dns-cluster-5min.yaml
  tests/enospc-30mins.yaml
  tests/gce-multiple-dc-shutdown-30mins.yaml
  tests/gemini-3h-with-nemesis.yaml
  tests/gemini_test_3h.yaml
  tests/google-cloud-snitch.yaml
  tests/hinted-handoff.yaml
  tests/longevity-1TB-7days-authorization-and-tls-ssl.yaml
  tests/longevity-1TB-7days.yaml
  tests/longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml
  tests/longevity-48h-verify-multiDC.yaml
  tests/longevity-50GB-4days-authorization-and-tls-ssl.yaml
  tests/longevity-50GB-4days.yaml
  tests/longevity-counters-4d-multidc.yaml
  tests/longevity-encryption-at-rest-200GB-6h.yaml
  tests/longevity-in-memory-36GB-4days.yaml
  tests/longevity-large-partition-4days.yaml
  tests/longevity-multi-keyspaces.yaml
  tests/longevity-mv-si-4days.yaml
  tests/longevity-staging.yaml
  tests/manager-regression-multiDC-set-distro.yaml
  tests/master_doc.yaml
  tests/perf-regression-2mv.yaml
  tests/perf-regression-latency-1TB.yaml
  tests/perf-regression-latency-500gb-30min.yaml
  tests/perf-regression-latency-in-memory.yaml
  tests/perf-regression-mv.100threads.30M-keys-i3.yaml
  tests/perf-regression-user-profiles.yaml
  tests/perf-regression.100threads.30M-keys-i3.yaml
  tests/perf-regression.100threads.30M-keys.yaml
  tests/refresh-30mins-100mb.yaml
  tests/refresh-30mins-120gb.yaml
  tests/repair-240mins-100G.yaml
  tests/rolling-upgrade-gce.yaml
  tests/sample.yaml
  vars/perfRegressionParallelPipeline.groovy
  vars/rollingUpgradePipeline.groovy
Labels: No Backport Needed, Ready for review
