Repository scylladb/scylla-cluster-tests, pull requests merged in 2019-10, with the labels that each got.

#1352 Fix `hydra investigate show-monitor` (fixes #1351)
  sdcm/utils/common.py
Labels: No Backport Needed, Ready for review

#1354 Journal timestamp not parsed correctly by events
  sdcm/sct_events.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1344 Add BYO pipeline
  README.rst
  jenkins-pipelines/byo-longevity.jenkinsfile
  sdcm/cluster.py
  sdcm/nemesis.py
  sdcm/sct_config.py
  sdcm/tester.py
  sdcm/utils/common.py
  sdcm/utils/log.py
  unit_tests/test_config.py
  unit_tests/test_utils_common.py
  upgrade_test.py
  vars/byoLongevityPipeline.groovy
Labels: No Backport Needed, Ready for review

#1360 Fixed error messages of manager Enum's:
  sdcm/mgmt.py
Labels: Backport-2019.1, Backport-3.1

#1359 Fixed the creation of grafana livesnapshots for monitoring v3.0
  data_dir/share_snapshot.js
Labels: Ready for review

#1355 Added support for choices in SCT config
  sdcm/sct_config.py
Labels: No Backport Needed

#1363 Fix `wait_ami_available` code failing for scylla-cloud-run
  sdcm/tester.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1364 Fix unittest to fail jenkins
  sct.py
  sdcm/microbenchmarking.py
  unit_tests/test_config.py
Labels: No Backport Needed, Ready for review

#1341 Fullscan - choose between select * and bypass cache
  sdcm/tester.py
Labels: Backport-3.1

#1366 Setting default nemesis interval to 5min
  defaults/test_default.yaml
Labels: No Backport Needed

#1368 Fix `wait_ami_available` code failing for scylla-cloud-run
  sdcm/tester.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1367 Destroy Gemini resources at the end of the test by default
  test-cases/gemini/gemini-1tb-10h.yaml
  test-cases/gemini/gemini-3h-with-nemesis.yaml
  test-cases/gemini/gemini-3h-with-nondisruptive-nemesis.yaml
  test-cases/gemini/gemini-basic-3h.yaml
Labels: No Backport Needed

#1372 Add availability to send email reports to all tests
  defaults/test_default.yaml
  sdcm/tester.py
Labels: Backport-2019.1, Backport-3.1, No Backport Needed, Ready for review

#1357 Adding processing the empty non system ks.cf list
  sdcm/nemesis.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1373 Fix client encrypt check when running cqlsh on loader node
  sdcm/cluster.py
Labels: Backport-2019.1, Backport-3.1

#1370 Disable networking nemesis on Gemini runs
  sdcm/nemesis.py
  test-cases/gemini/gemini-3h-with-nondisruptive-nemesis.yaml
Labels: Backport-3.1

#1336 Seed selection (task #1019)
  defaults/test_default.yaml
  docs/configuration_options.md
  internal_test_data/unknown_param_in_config.yaml
  sdcm/cluster.py
  sdcm/cluster_aws.py
  sdcm/cluster_libvirt.py
  sdcm/cluster_openstack.py
  sdcm/remote.py
  sdcm/sct_config.py
  sdcm/tester.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1374 Remove data_dir/ssl_conf/db.crt from index
  data_dir/ssl_conf/db.crt
Labels: No Backport Needed, Ready for review

#1381 Added log messages in sctool run for debugging
  sdcm/mgmt.py
Labels: Backport-2019.1, Backport-3.1

#1378 Adding to S3Storage object upload/download files with multiparts
  sdcm/utils/common.py
Labels: Ready for review

#1383 Fix all booleans defined as strings in config
  defaults/test_default.yaml
  internal_test_data/complex_test_case_with_version.yaml
  longevity_test.py
  performance_regression_test.py
  sdcm/fill_db_data.py
  sdcm/sct_config.py
  test-cases/features/corrupt-then-rebuild.yaml
  test-cases/features/hinted-handoff.yaml
  test-cases/features/refresh-30mins-120gb.yaml
  test-cases/features/system-sla-test.yaml
  test-cases/longevity/longevity-100GB-48h-cloud-CloudLimitedChaosMonkey-tls.yaml
  test-cases/longevity/longevity-200GB-48h-network-monkey.yaml
  test-cases/longevity/longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml
  test-cases/longevity/longevity-2TB-4days-authorization-and-tls-ssl-1dis-2nondis-nemesis.yaml
  test-cases/longevity/longevity-50GB-4days-authorization-and-tls-ssl.yaml
  test-cases/longevity/longevity-counters-4days-multidc.yaml
  test-cases/longevity/longevity-encryption-at-rest-200GB-6h.yaml
  test-cases/longevity/longevity-in-memory-36GB-4days.yaml
  test-cases/longevity/longevity-large-partition-4days.yaml
  test-cases/performance/perf-regression-latency-1TB.yaml
  test-cases/performance/perf-regression-latency-500gb-30min.yaml
  test-cases/performance/perf-regression-latency-in-memory.yaml
  test-cases/upgrades/rolling-upgrade.yaml
Labels: No Backport Needed, Ready for review

#1379 Add support for BYO on specific repo/branch
  vars/byoLongevityPipeline.groovy
Labels: No Backport Needed, Ready for review

#1386 Keep on fail monitor
  defaults/test_default.yaml
Labels: No Backport Needed

#1384 improve email report for longevity test runs
  gemini_test.py
  longevity_test.py
  sdcm/results_longevity.html
  sdcm/send_email.py
  sdcm/tester.py
Labels: No Backport Needed, Ready for review

#1391 Minor fix of longevity html report template
  sdcm/results_longevity.html
Labels: No Backport Needed, Ready for review

#1394 Create new doc in ES with document_id as test-id
  sdcm/db_stats.py
  sdcm/tester.py
Labels: No Backport Needed

#1389 Add event that when journald suppress Scylla log messages
  sdcm/cluster.py
  unit_tests/test_cluster.py
  unit_tests/test_data/database_suppressed_messages.log
Labels: No Backport Needed, Ready for review

#1388 Unit tests for seed_selector feature
  sdcm/cluster.py
  unit_tests/test_data/scylla.yaml
  unit_tests/test_seed_selector.py
Labels: No Backport Needed, Ready to be Merged

#1392 Improving gemini result report
  gemini_test.py
  longevity_test.py
  sdcm/results_gemini.html
  sdcm/send_email.py
  sdcm/tester.py
  sdcm/utils/common.py
Labels: No Backport Needed, Ready for review

#1171 Add a command to patch es mapping of old branches
  utils/fix_es_mapping.py
Labels: No Backport Needed, Ready to be Merged

#1345 EaR: reduce cs threads to avoid Semaphore timedout
  test-cases/longevity/longevity-encryption-at-rest-200GB-6h.yaml
  tests/longevity-encryption-at-rest-200GB-6h.yaml
Labels: Backport-2019.1, Ready to be Merged

#1377 archive SCT logs to jenkins server
  vars/longevityPipeline.groovy
  vars/rollingUpgradePipeline.groovy
Labels: Backport-2019.1, Backport-3.1, Ready to be Merged

#1158 Support to configure Encryption at rest
  data_dir/encrypt_conf/system_key
  docs/configuration_options.md
  sdcm/cluster.py
  sdcm/cluster_aws.py
  sdcm/keystore.py
  sdcm/sct_config.py
  sdcm/tester.py
  sdcm/utils/common.py
  test-cases/longevity/longevity-encryption-at-rest-200GB-6h.yaml
  test-cases/longevity/longevity-in-memory-36GB-4days.yaml
Labels: Backport-2019.1, Ready to be Merged

#1376 fix of cleaning replacement node ip
  sdcm/cluster.py
  sdcm/cluster_aws.py
Labels: Backport-2019.1, Backport-3.1, Ready to be Merged

#1400 Fix for: the scylla_create_devices has been moved to the '/opt/scylladb' folder in the master branch
  sdcm/cluster_aws.py
Labels: Backport-2019.1, Backport-3.1, Ready to be Merged

#1398 Set public read access for uploaded resources
  sdcm/utils/common.py
Labels: No Backport Needed

#1395 Adding send email report stage
  sct.py
  sdcm/tester.py
  vars/longevityPipeline.groovy
Labels: No Backport Needed

#1361 Add support to fail test on thread failures
  longevity_in_memory_test.py
  longevity_large_partition_test.py
  sdcm/cluster.py
  sdcm/tester.py
  sdcm/utils/thread.py
Labels: No Backport Needed, Ready for review

#1405 Fix reflector unit test in seed selection (receive_files function should return status)
  unit_tests/test_seed_selector.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1401 Adding installation phantomjs to docker image
  docker/env/version
  install-prereqs.sh
  sdcm/logcollector.py
Labels: No Backport Needed, Ready to be Merged

#1311 convert EaR longevity to pipeline
  configurations/kmip-ear.yaml
  configurations/local-ear.yaml
  configurations/replicated-ear.yaml
  jenkins-pipelines/EaR-longevity-kmip-200gb-6h.jenkinsfile
  jenkins-pipelines/EaR-longevity-kmip-50gb-4d.jenkinsfile
  jenkins-pipelines/EaR-longevity-local-200gb-6h.jenkinsfile
  jenkins-pipelines/EaR-longevity-local-50gb-4d.jenkinsfile
  jenkins-pipelines/EaR-longevity-replicated-200gb-6h.jenkinsfile
  jenkins-pipelines/EaR-longevity-replicated-50gb-4d.jenkinsfile
  test-cases/longevity/longevity-encryption-at-rest-200GB-6h.yaml
  vars/longevityPipeline.groovy
Labels: Backport-2019.1, Ready to be Merged

#1274 Configure scale test as a pipeline job
  configurations/scale-180-200.yaml
  configurations/scale-450-500.yaml
  docs/configuration_options.md
  grow_cluster_test.py
  jenkins-pipelines/features-scale-180-200-cluster-test.jenkinsfile
  jenkins-pipelines/features-scale-450-500-cluster-test.jenkinsfile
  sdcm/cluster.py
  sdcm/remote.py
  sdcm/sct_config.py
  test-cases/features/scale-cluster.yaml
Labels: Backport-2019.1, Backport-3.1, Ready to be Merged

#1406 Refactor DummyRemote into once place
  unit_tests/dummy_remote.py
  unit_tests/test_cluster.py
  unit_tests/test_seed_selector.py
Labels: No Backport Needed, Ready for review

#1407 ClusterHealthValidator: use node.ip_address instead of node.private_ip_address
  sdcm/cluster.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1409 Fix the case of no tag on AMI
  sdcm/utils/common.py
Labels: No Backport Needed

#1403 Remove old document_id and related functionality
  sdcm/cluster.py
  sdcm/tester.py
Labels: No Backport Needed, Ready to be Merged

#1410 ignore error in reporting housekeeping uuid
  sdcm/cluster.py
Labels: No Backport Needed

#1411 verify data by fill_db_data.py during upgrade
  upgrade_test.py
Labels: Backport-3.1, Ready to be Merged

#1416 upgrade: get version from suffix of branch name
  vars/supportedUpgradeFromVersions.groovy
Labels: No Backport Needed

#1419 Fix issue with collecting logs if node is not available
  sdcm/logcollector.py
Labels: No Backport Needed, Ready for review, test-provision

#1418 Minor fixes for gemini send email functionality and email report
  gemini_test.py
  sct.py
  sdcm/cluster.py
  sdcm/results_gemini.html
  sdcm/tester.py
Labels: No Backport Needed, Ready to be Merged

#1424 Make sure we pass via `node_config_setup` when re-configuring scylla
  sdcm/cluster.py
  sdcm/cluster_aws.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1425 Fix missing default values in #1424
  sdcm/cluster.py
  sdcm/cluster_aws.py
Labels: Backport-2019.1, Backport-3.1, Ready to be Merged

#1426 Disable `nemesis_during_prepare` for multiple nemesis test
  test-cases/longevity/longevity-2TB-4days-authorization-and-tls-ssl-1dis-2nondis-nemesis.yaml
Labels: Backport-2019.1, Backport-3.1, Ready to be Merged

#1414 Introduce a way to dynamically skip a nemesis
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#1428 Disabled nemesis_during_prepare in 1TB 7 days
  test-cases/longevity/longevity-1TB-7days-authorization-and-tls-ssl.yaml
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1431 for 3.1: switch prepare of scylla monitor to python2
  sdcm/cluster.py
Labels: Backport-2019.1, Backport-3.0

#1430 Make sure we append scylla args only once
  sdcm/cluster.py
Labels: Backport-2019.1, Backport-3.1, Ready to be Merged

#1433 Adding support to search and collect data for terminated node #1404
  sdcm/logcollector.py
Labels: No Backport Needed, Ready to be Merged

#1432 Fix screenshot creation due to wrong time_start
  sdcm/cluster.py
Labels: No Backport Needed, Ready for review

#1434 After hitting admission control, the load is not killed
  admission_control_overload_test.py
Labels: Backport-2019.1, Backport-3.1, Ready to be Merged

#1397 Update builder eu-west names and ips
  sdcm/utils/common.py
Labels: No Backport Needed

#1439 Add more log filtering to enospc nemesis
  sdcm/nemesis.py
  unit_tests/test_events.py
Labels: Backport-2019.1, Backport-3.1, Ready to be Merged

#1441 Enlarge timeout in `RestartThenRepairNode` nemesis to 8 hours
  sdcm/nemesis.py
Labels: Backport-2019.1, Backport-3.1, Ready to be Merged

#1436 Fix collection PrometheusSnapshot upon various exception
  sdcm/logcollector.py
Labels: No Backport Needed, Ready for review

#1437 Add support for hydra collect-logs correctly found monitor branch
  sdcm/cluster.py
Labels: Backport-2019.1, Ready for review
