Repository scylladb/scylla-cluster-tests, pull requests merged in 2019-06, with the labels that each got.

#1011 Fix ngrok to work when using `cluster_reuse: true`
  sdcm/cluster.py
  sdcm/tester.py
Labels: No Backport Needed

#1015 Fix issue with show empty avg aio metrics in regression report
  sdcm/microbenchmarking.py
Labels: No Backport Needed

#1017 Fix bash escaping in rollingUpgradePipeline.groovy
  vars/rollingUpgradePipeline.groovy
Labels: Backport-3.1

#1022 Fix the best result for new metrica
  sdcm/microbenchmarking.py
Labels: Backport-3.1

#1014 Add explicit gemini version to email report
  gemini_test.py
  sdcm/cluster.py
  sdcm/tester.py
Labels: No Backport Needed

#1012 Fix PR configuration check in Jenkinsfile
  Jenkinsfile
Labels: No Backport Needed

#1018 Fix `params.get()` calls in upgrade_test calling with old avocado arg…
  upgrade_test.py
Labels: Backport-3.1

#1023 Fix the debug output of gemini version which cause Exception
  sdcm/cluster.py
Labels: Backport-3.1

#1024 Fix `append_scylla_args` to support debian/ubuntu
  sdcm/cluster.py
Labels: Backport-3.1

#1025 Add support for selecting distro for loader
  defaults/test_default.yaml
  sdcm/sct_config.py
  unit_tests/test_config.py
Labels: Backport-3.1

#1019 Add `nodetool upgradesstables` to upgrade_test.py
  jenkins-pipelines/rolling-upgrade-ubuntu16.04.jenkinsfile
  jenkins-pipelines/rolling-upgrade-ubuntu18.04.jenkinsfile
  upgrade_test.py
  vars/rollingUpgradePipeline.groovy
  vars/supportedUpgradeFromVersions.groovy
Labels: Backport-3.1

#1028 Limit user_prefix to 32 characters
  sdcm/sct_config.py
  unit_tests/test_config.py
Labels: Backport-3.1

#1013 Added version decorator
  sct.py
  sdcm/utils.py
  unit_tests/test_utils_version.py
Labels: No Backport Needed

#1026 Adding dynamic gemini nemesis list build
  sdcm/nemesis.py
Labels: No Backport Needed

#1035 add virtualenv files and direnv files to .gitignore
  .gitignore
Labels: No Backport Needed

#1039 Remove the node name from map field
  sdcm/db_stats.py
Labels: Backport-3.1

#1027 Add to report only errors messages
  gemini_test.py
  sdcm/results_analyze.py
  sdcm/results_gemini.html
Labels: No Backport Needed

#1038 Adding jenkins pipeline for in memory longevity
  Jenkinsfile
  jenkins-pipelines/longevity-in-memory-36gb-4d.jenkinsfile
  test-cases/longevity/longevity-in-memory-36GB-4days.yaml
Labels: No Backport Needed

#1044 longevity: don't use upper letter in keyspace name
  longevity_test.py
Labels: Backport-2019.1, Backport-3.1

#1050 Fix debian/ubuntu upgrade command to be noninteractive
  sdcm/cluster.py
Labels: Backport-3.1

#1051 Fixing current running nemesis when decomissioning a node
  sdcm/nemesis.py
Labels: Backport-2019.1, Backport-3.1

#1053 Set current node where disrupt method is run
  sdcm/nemesis.py
Labels: Backport-2019.1, Backport-3.1

#1034 change default monitor branch to 2.4
  defaults/test_default.yaml
  sdcm/cluster.py
Labels: Backport-3.1

#1048 Make sure debuginfo is installed
  sdcm/cluster.py
  sdcm/cluster_aws.py
Labels: Backport-3.1

#1054 Run in thread and log into job.log scylla-manager log
  sdcm/cluster.py
Labels: Backport-3.1

#1052 hydra.sh: fix nested escape character problem
  docker/env/hydra.sh
Labels: No Backport Needed

#1058 Enlarge the 3h longevity pipeline timeout
  jenkins-pipelines/longevity-10gb-3h.jenkinsfile
Labels: Backport-3.1

#1057 Handle failure in annotate to grafana (Fixes #960)
  sdcm/sct_events.py
  sdcm/tester.py
Labels: Backport-3.1

#1060 Fix unicode handling in saving annotation to file (fixes #971)
  sdcm/cluster.py
Labels: Backport-3.1

#1062 Upgrade PyYAML==5.1 and awscli==1.16.180
  docker/env/version
  performance_regression_test.py
  requirements-python.txt
  sdcm/cluster_aws.py
Labels: No Backport Needed

#1055 Fix upgrade_test `node.search_database_log()`
  sdcm/cluster.py
  unit_tests/test_cluster.py
  unit_tests/test_data/database.log
  upgrade_test.py
Labels: Backport-3.1

#1065 Remove duplicate code for GeminiChaosMonkey
  sdcm/nemesis.py
Labels: Backport-3.1

#1067 Disable backtrace decoding by default
  defaults/test_default.yaml
  sdcm/cluster.py
  sdcm/sct_config.py
  sdcm/tester.py
Labels: Backport-3.1

#1066 Refactor: moving cqlsh and nodetool calls to run from BaseNode objects
  jenkins-pipelines/longevity-1tb-7days-1Dis-2NonDis-Nemesises.jenkinsfile
  longevity_test.py
  refresh_test.py
  sdcm/cluster.py
  sdcm/cluster_aws.py
  sdcm/cluster_baremetal.py
  sdcm/cluster_gce.py
  sdcm/cluster_libvirt.py
  sdcm/cluster_openstack.py
  sdcm/docker.py
  sdcm/nemesis.py
  sdcm/stress_thread.py
  sdcm/tester.py
  snitch_test.py
  sstable_corrupt.py
  test-cases/longevity/longevity-1TB-7days-authorization-and-tls-ssl-1dis-2nondis-nemesis.yaml
  unit_tests/test_cluster.py
  upgrade_test.py
Labels: Backport-3.1

#1072 Fixing FullScanThread
  sdcm/cluster.py
  sdcm/nemesis.py
Labels: No Backport Needed

#1071 Remove a few more Avocado leftovers
  refresh_test.py
  sdcm/fill_db_data.py
Labels: No Backport Needed

#1070 Fix `hydra run-test` to have test failures in output.log
  sct.py
  sdcm/fill_db_data.py
Labels: No Backport Needed

#1059 Fail gracefully in when loader is missing
  sdcm/cluster.py
Labels: Backport-3.1

#1033 Check `nodetool upgradesstables` works after all nodes upgraded
  sdcm/cluster.py
  upgrade_test.py
Labels: Backport-3.1

#1068 Add fallback to storing monitoring data dir instead of prometheus snapshot
  sdcm/cluster.py
Labels: No Backport Needed

#1075 Fix longevity 200gb to not run nemesis on prepare
  test-cases/longevity/longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml
Labels: Backport-3.1

#1076 Fix copy'n'paste in longevity mv-si-4day pipeline
  jenkins-pipelines/longevity-mv-si-4days.jenkinsfile
Labels: Backport-3.1

#1077 Change large-partitions to use i3en instead of i3
  test-cases/longevity/longevity-large-partition-4days.yaml
Labels: Backport-3.1

#1083 Remove sct_log_formatter and fixes to run_nodetool/run_cqlsh
  data_dir/sct_log_formatter
  sdcm/cluster.py
  test-cases/longevity/longevity-1TB-7days-authorization-and-tls-ssl-1dis-2nondis-nemesis.yaml
Labels: Backport-3.1

#1085 increase timeouts of short longevities by 1 hour
  jenkins-pipelines/longevity-100gb-4h.jenkinsfile
  jenkins-pipelines/longevity-10gb-3h.jenkinsfile
Labels: Backport-3.1

#1084 Add space_node_threshold to test defaults
  defaults/test_default.yaml
  test-cases/longevity/longevity-multi-keyspaces.yaml
Labels: Backport-3.1

#1074 Fix Jenkinsfile to work on a branches
  Jenkinsfile
Labels: Backport-3.1

#1073 Adding database.log file to archive on S3
  sdcm/cluster.py
Labels: Backport-2019.1, Backport-3.1

#1069 in-memory: wrap ratio parameter by single quotes
  test-cases/longevity/longevity-in-memory-36GB-4days.yaml
  tests/longevity-in-memory-36GB-4days.yaml
Labels: Backport-2019.1
