Repository scylladb/scylla-cluster-tests, pull requests merged in 2019-02, with the labels that each got.

#771 Excluded 'TaskStatus.STARTING' from task progress check
  sdcm/mgmt.py
Labels: Backport-manager-v1.3.1

#807 update_db_binary: adapt relocated scylla binary
  sdcm/cluster.py
Labels: Backport-needed

#815 Fix boto3.resource missing region_name
  sdcm/ec2_client.py
Labels: Backport-2018.1, Backport-3.0, Backport-manager-v1.3.1
