Repository scylladb/scylla-cluster-tests, pull requests merged in 2019-07, with the labels that each got.

#1101 increase default monitor size due to memory issues during longevity
  defaults/aws_config.yaml
Labels: Backport-3.1

#1087 Make sure the correct debuginfo is installed
  sdcm/cluster.py
  sdcm/cluster_aws.py
Labels: Backport-3.1

#1113 removing as a temporary workaround
  test-cases/longevity/longevity-100gb-4h.yaml
  test-cases/longevity/longevity-10gb-3h.yaml
Labels: Backport-3.1

#1111 Enlarge timeout in `jenkins-pipelines/longevity-200gb-48h.jenkinsfile`
  jenkins-pipelines/longevity-200gb-48h.jenkinsfile
Labels: Backport-3.1

#1104 Add error processing of FullScan exception
  sdcm/cluster.py
  sdcm/sct_events.py
Labels: Backport-3.1

#1115 Fix: call to get_backtraces crashes TearDown when one of node is down
  sdcm/cluster.py
Labels: Backport-3.1

#1091 Fix a few place that was using public address by default
  refresh_test.py
  sdcm/cluster.py
  sdcm/db_stats.py
  sdcm/tester.py
Labels: Backport-3.1

#1107 Change `db_log_reader_thread()` and backtrace_thread()` to wait better
  sdcm/cluster.py
Labels: Backport-3.1

#1106 Filter db failure events in aws restart on i3/i2
  sdcm/cluster.py
  sdcm/cluster_aws.py
  sdcm/sct_events.py
  unit_tests/test_events.py
Labels: Backport-3.1

#1061 Add Scylla Cloud base longevity pipelines
  jenkins-pipelines/scylla-cloud-longevity-10gb-3h.jenkinsfile
  jenkins-pipelines/scylla-cloud-longevity-200gb-48h.jenkinsfile
  mgmt_cli_test.py
  sdcm/cluster.py
  sdcm/cluster_aws.py
  sdcm/nemesis.py
  sdcm/sct_config.py
  sdcm/tester.py
  vars/scyllaCloudLongevityPipeline.groovy
Labels: No Backport Needed

#1092 Adding a provision test for PRs
  Jenkinsfile
  test-cases/PR-provision-test.yaml
Labels: No Backport Needed, test-provision

#1119 remove RestartThenRepair nemesis from LimitedChaosMonkey list as it fail reads with CL=ONE while the data is gone
  sdcm/nemesis.py
Labels: Backport-3.1

#1042 Validate truncation entries during rolling upgrade test
  sdcm/fill_db_data.py
  sdcm/sct_config.py
  sdcm/tester.py
  upgrade_test.py
  vars/rollingUpgradePipeline.groovy
Labels: Backport-3.1, Ready for review

#1125 Change spot_termination notification period after aws termination time
  sdcm/cluster_aws.py
Labels: Backport-3.1

#1114 Add a proper `command_timeout` support to Remoter
  docker/env/version
  requirements-python.txt
  sdcm/remote.py
Labels: Backport-3.1

#1126 Changed scylla-manager default version to 1.4 (+2019.1)
  defaults/test_default.yaml
Labels: Backport-3.1

#1129 Rename monitoring repo to `scylla-monitoring`
  README.rst
  sdcm/cluster.py
  sdcm/utils.py
Labels: Backport-2019.1, Backport-3.0, Backport-3.1, perf-v6-backported

#1081 make sure reboot is really executed
  sdcm/cluster_aws.py
  sdcm/cluster_gce.py
Labels: Backport-2019.1, Backport-3.1

#1124 Adding new Nemesis - TopPartitions
  sdcm/nemesis.py
Labels: Backport-3.1

#1120 Gemini prometheus metricsv2
  data_dir/scylla-dash-per-server-nemesis.3.1.json
  data_dir/scylla-dash-per-server-nemesis.master.json
  gemini_test.py
  sdcm/cluster.py
Labels: Backport-3.1

#1088 adding unittest for microbenchmarking
  sdcm/microbenchmarking.py
  unit_tests/test_data/MBM/PFF_2_datasets/perf_fast_forward_output/large-partition-forwarding/large-part-ds1/no.1.json
  unit_tests/test_data/MBM/PFF_2_datasets/perf_fast_forward_output/large-partition-forwarding/large-part-ds1/yes.1.json
  unit_tests/test_data/MBM/PFF_2_datasets/perf_fast_forward_output/large-partition-forwarding/large-part-ds2/no.1.json
  unit_tests/test_data/MBM/PFF_2_datasets/perf_fast_forward_output/large-partition-forwarding/large-part-ds2/yes.1.json
  unit_tests/test_data/MBM/PFF_2_datasets/perf_fast_forward_output/small-partition-slicing/small-part-1/0-256.1.json
  unit_tests/test_data/MBM/PFF_2_datasets/perf_fast_forward_output/small-partition-slicing/small-part-1/500000-4096.1.json
  unit_tests/test_data/MBM/PFF_2_datasets/perf_fast_forward_output/small-partition-slicing/small-part/0-256.1.json
  unit_tests/test_data/MBM/PFF_2_datasets/perf_fast_forward_output/small-partition-slicing/small-part/500000-4096.1.json
  unit_tests/test_data/MBM/PFF_empty_dataset_folders/perf_fast_forward_output/large-partition-forwarding/large-part-ds1/.gitignore
  unit_tests/test_data/MBM/PFF_empty_dataset_folders/perf_fast_forward_output/small-partition-slicing/small-part/.gitignore
  unit_tests/test_data/MBM/PFF_empty_folder/perf_fast_forward_output/.gitignore
  unit_tests/test_data/MBM/PFF_empty_tests_folders/perf_fast_forward_output/large-partition-forwarding/.gitignore
  unit_tests/test_data/MBM/PFF_empty_tests_folders/perf_fast_forward_output/small-partition-slicing/.gitignore
  unit_tests/test_data/MBM/PFF_with_AVGAIO/perf_fast_forward_output/large-partition-forwarding/large-part-ds1/no.1.json
  unit_tests/test_data/MBM/PFF_with_AVGAIO/perf_fast_forward_output/large-partition-forwarding/large-part-ds1/yes.1.json
  unit_tests/test_data/MBM/PFF_with_AVGAIO/perf_fast_forward_output/small-partition-slicing/small-part/0-256.1.json
  unit_tests/test_data/MBM/PFF_with_AVGAIO/perf_fast_forward_output/small-partition-slicing/small-part/500000-4096.1.json
  unit_tests/test_data/MBM/PFF_with_AVGAIO/report_obj
  unit_tests/test_data/MBM/PFF_with_AVGAIO/result_obj
  unit_tests/test_data/MBM/PFF_with_new_metric/perf_fast_forward_output/large-partition-forwarding/large-part-ds1/no.1.json
  unit_tests/test_data/MBM/PFF_with_new_metric/perf_fast_forward_output/large-partition-forwarding/large-part-ds1/yes.1.json
  unit_tests/test_data/MBM/PFF_with_new_metric/perf_fast_forward_output/small-partition-slicing/small-part/0-1.1.json
  unit_tests/test_data/MBM/PFF_with_new_metric/perf_fast_forward_output/small-partition-slicing/small-part/500000-4096.1.json
  unit_tests/test_data/MBM/PFF_with_new_metric/result_obj
  unit_tests/test_data/MBM/PFF_without_AVGAIO/perf_fast_forward_output/large-partition-forwarding/large-part-ds1/no.1.json
  unit_tests/test_data/MBM/PFF_without_AVGAIO/perf_fast_forward_output/large-partition-forwarding/large-part-ds1/yes.1.json
  unit_tests/test_data/MBM/PFF_without_AVGAIO/perf_fast_forward_output/large-partition-slicing-single-key-reader/large-part-ds1/0-4096.1.json
  unit_tests/test_data/MBM/PFF_without_AVGAIO/perf_fast_forward_output/large-partition-slicing-single-key-reader/large-part-ds1/500000-1.1.json
  unit_tests/test_data/MBM/PFF_without_AVGAIO/report_obj
  unit_tests/test_data/MBM/PFF_without_AVGAIO/result_obj
  unit_tests/test_microbenchmarking.py
Labels: No Backport Needed

#1136 Fxing _resharding_status method
  sdcm/cluster.py
Labels: Backport-3.1

#1135 Fix cases of broken stalls line break events filtering
  sdcm/sct_events.py
  unit_tests/test_events.py
Labels: Backport-3.1

#1134 Catching exceptions during self.wait_ssh_up in spot termination thread
  sdcm/cluster_aws.py
Labels: No Backport Needed

#1122 BaseNode: avoid ssh connect when user isn't created
  sdcm/cluster_gce.py
Labels: Backport-2019.1, Backport-3.1

#1141 Fixing new_node.running_nemesis when exception happens
  sdcm/nemesis.py
Labels: Backport-3.1

#1102 node_setup/deb: disable apt daily services
  sdcm/cluster.py
Labels: Backport-2019.1, Backport-3.1

#1142 Remove Microbenchmark CI step, now part of unittest
  Jenkinsfile
Labels: No Backport Needed, Ready for review

#1143 Add node information to `CoreDumpEvent`
  sdcm/cluster.py
  sdcm/sct_events.py
  unit_tests/test_events.py
Labels: Backport-3.1, Ready for review

#1152 Printing scylla.yaml configuration that is goint to be set on DB node
  sdcm/cluster.py
Labels: Backport-3.1

#1137 Hydra containers are named with test_id
  docker/env/hydra.sh
  sdcm/cluster.py
  sdcm/cluster_aws.py
  sdcm/sct_config.py
  sdcm/tester.py
Labels: Backport-2019.1, Backport-3.1

#1144 New options to filter SctEvents by node
  sdcm/sct_events.py
  unit_tests/test_events.py
Labels: No Backport Needed, Ready for review

#1148 upgrade_test: only verify one sstable file by sstabledump to reduce test time
  upgrade_test.py
Labels: No Backport Needed

#1149 Revert "Change `db_log_reader_thread()` and backtrace_thread()` to wait better"
  sdcm/cluster.py
Labels: No Backport Needed

#1146 _try_split_coredump: assign file size limit in split cmdline
  sdcm/cluster.py
Labels: No Backport Needed

#1132 Recreate 'Node properties are null in system.peers in some cases (issue #4652)'
  data_dir/scylla-dash-per-server-nemesis.2018.1.json
  data_dir/scylla-dash-per-server-nemesis.2019.1.json
  data_dir/scylla-dash-per-server-nemesis.3.0.json
  data_dir/scylla-dash-per-server-nemesis.3.1.json
  data_dir/scylla-dash-per-server-nemesis.master.json
  sdcm/cluster.py
  sdcm/cluster_aws.py
  sdcm/nemesis.py
  sdcm/sct_events.py
  snitch_test.py
  test-cases/longevity/longevity-50GB-4days-authorization-and-tls-ssl.yaml
  upgrade_test.py
Labels: Backport-3.1, Ready for review

#1164 Fixing fullscan thread: thread shouldn't fail when timeout happened i…
  sdcm/cluster.py
Labels: Backport-3.1

#1099 Add longevity-counters-4days-multidc.yaml to `/test-cases`
  defaults/aws_config.yaml
  jenkins-pipelines/longevity-counters-4days-multidc.jenkinsfile
  sdcm/cluster.py
  sdcm/sct_config.py
  test-cases/longevity/longevity-counters-4days-multidc.yaml
  vars/getJenkinsLabels.groovy
  vars/longevityPipeline.groovy
  vars/perfRegressionParallelPipeline.groovy
Labels: Ready to be Merged

#1167 Fix Exception KeyError for Toppartition nemesis
  sdcm/nemesis.py
Labels: No Backport Needed

#1172 sct_config: wrongly appending region defaults ontop of user yaml
  internal_test_data/complex_test_case_with_version.yaml
  sdcm/sct_config.py
Labels: Backport-3.1, Ready for review

#1170 Fix issue #1151 Add large sct.log(more than 4GB) to zip archive
  sdcm/tester.py
Labels: Backport-3.1

#1128 Build list of Disruptive and NonDisruptive methods one time
  sdcm/nemesis.py
Labels: No Backport Needed

#1159 sdcm/cluster: ignore result if coredumpctl doesn't exist
  sdcm/cluster.py
Labels: No Backport Needed

#1176 Fix relative imports, broken cause of utils refactor
  sdcm/utils/common.py
Labels: Backport-3.1

#1180 Implemented list all/running resources and improved listing/cleaning …
  sct.py
  sdcm/cluster_aws.py
  sdcm/utils/common.py
  sdcm/utils/log.py
Labels: No Backport Needed

#1179 Change ClusterHealthValidatorEvent using
  sdcm/cluster.py
Labels: Backport-3.1, Ready to be Merged

#1183 Fix to use absolute paths to .yaml files
  sdcm/sct_config.py
Labels: No Backport Needed, Ready for review

#1178 Fixed the identification of an ERROR status
  sdcm/mgmt.py
Labels: Backport-2019.1, Backport-3.1

#1184 fix clean_instances_aws() to actully terminate instances
  sdcm/utils/common.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1177 Added a fix that deletes the automatic repair task
  sdcm/mgmt.py
  sdcm/nemesis.py
Labels: Backport-2019.1, Backport-3.1

#1186 Fix hydra grep for docker images
  docker/env/hydra.sh
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1166 Add support for selecting branch AMIs by tags
  sct.py
  sdcm/sct_config.py
  sdcm/utils/common.py
  unit_tests/test_config.py
Labels: Backport-2019.1, Backport-3.1, No Backport Needed, Ready to be Merged

#1188 Fix undefined variable in `node.check_nodes_status()`
  sdcm/cluster.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1138 Adding GeminiToolThread and same way as c-s stress is running
  gemini_test.py
  sdcm/cluster.py
  sdcm/gemini_thread.py
  sdcm/sct_events.py
  sdcm/tester.py
Labels: Backport-3.1, Ready for review

#1191 Fix truncate_entries() to exclude enterprise version
  sdcm/utils/version_utils.py
  unit_tests/test_version_utils.py
  upgrade_test.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1192 Fix import from utils.common
  sdcm/gemini_thread.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1198 Add `wait_for` ontop of call to `verify_logging_from_nodes()`
  sdcm/cluster.py
  sdcm/wait.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1140 longevity: add counter_write workload in prepare_write stage
  test-cases/longevity/longevity-1TB-7days-authorization-and-tls-ssl-1dis-2nondis-nemesis.yaml
  test-cases/longevity/longevity-1TB-7days-authorization-and-tls-ssl.yaml
  test-cases/longevity/longevity-50GB-4days-authorization-and-tls-ssl.yaml
  tests/longevity-1TB-7days-authorization-and-tls-ssl.yaml
  tests/longevity-1TB-7days.yaml
  tests/longevity-50GB-4days-authorization-and-tls-ssl.yaml
  tests/longevity-50GB-4days.yaml
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1197 Add print to log on test failures [fix #1181]
  sdcm/tester.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1187 MV backpressure test: profile and jenkins pipeline
  jenkins-pipelines/longevity-2mv-backpressure-4days.jenkinsfile
  test-cases/features/longevity-2mv-backpressure-4d.yaml
  tests/longevity-2mv-backpressure-4d.yaml
Labels: Backport-3.1, Ready for review

#1199 Enabled use_mgmt in parrallel nemesis run yaml
  test-cases/longevity/longevity-1TB-7days-authorization-and-tls-ssl-1dis-2nondis-nemesis.yaml
Labels: Ready to be Merged

#1201 Remove `get_node_database_errors()` from test tearDown
  sdcm/nemesis.py
  sdcm/sct_events.py
  sdcm/tester.py
  unit_tests/test_events.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1160 Send mail to siren team on failure of scylla-cloud run
  vars/scyllaCloudLongevityPipeline.groovy
Labels: No Backport Needed, Ready for review
