Repository scylladb/scylla-cluster-tests, pull requests merged in 2019-05, with the labels that each got.

#943 sct_config: Check for unsupportted environment variables
  sdcm/sct_config.py
Labels: No Backport Needed

#950 Fix start avocado if SCT_NEW_CONFIG env var was set
  sdcm/sct_config.py
Labels: No Backport Needed

#937 Terminate timeout when waiting for resharding finish
  sdcm/cluster.py
Labels: Backport-2019.1

#880 Add parallel running of nemesis
  sdcm/cluster.py
  sdcm/nemesis.py
  sdcm/sct_config.py
  sdcm/tester.py
  tests/sample.yaml
Labels: No Backport Needed

#917 Gemini integration
  gemini_test.py
  sdcm/cluster.py
  sdcm/sct_config.py
  sdcm/tester.py
  test-cases/gemini/gemini-basic-3h.yaml
  tests/gemini_test.yaml
Labels: Backport-2019.1

#961 Fix Setup.set_multi_region() wasn't called in old configuration
  sdcm/tester.py
Labels: Backport-2019.1

#962 Add timeout for verify_results() and get_results()
  sdcm/stress_thread.py
Labels: No Backport Needed

#931 Automatic decoding of Scylla Backtraces into Events
  sct.py
  sdcm/cluster.py
  sdcm/sct_config.py
  sdcm/sct_events.py
  unit_tests/__init__.py
  unit_tests/test_cluster.py
  unit_tests/test_config.py
  unit_tests/test_data/database.log
  unit_tests/test_events.py
Labels: No Backport Needed

#932 Added support for Ubuntu18
  sdcm/cluster.py
  sdcm/collectd.py
  sdcm/sct_config.py
  sdcm/utils.py
Labels: Backport-2019.1, Backport-3.0

#942 Select not-system keyspace and table for ModifyTable nemesis
  sdcm/cluster.py
  sdcm/nemesis.py
Labels: Backport-2019.1

#963 Calls to cql_connection_patient*(), session are being closed
  cql_test.py
  longevity_large_partition_test.py
  longevity_test.py
  performance_regression_test.py
  performance_regression_user_profiles_test.py
  sdcm/fill_db_data.py
  sdcm/nemesis.py
  sdcm/tester.py
  sdcm/utils.py
  snitch_test.py
Labels: No Backport Needed

#980 Fixing `monitor_install_path_base` to be a @property
  sdcm/cluster.py
Labels: No Backport Needed

#966 Move CassandraStressExporter() gauges to be global
  sdcm/loader.py
Labels: No Backport Needed

#984 Manager v1.4 - added missing commits of 1.4 fixes
  mgmt_cli_test.py
  sdcm/mgmt.py
  tests/manager-regression-multiDC-set-distro.yaml
Labels: Backport-manager-v1.4

#989 [BACKPORT] Manager v1.3.1 additions
  mgmt_cli_test.py
  sdcm/cluster.py
  sdcm/mgmt.py
  tests/manager-regression-multiDC-set-distro.yaml
Labels: No Backport Needed

#944 enhance workloads in upgrade test
  data_dir/complex_schema.yaml
  docs/configuration_options.md
  sdcm/sct_config.py
  tests/rolling-upgrade-gce.yaml
  upgrade_test.py
Labels: Backport-2019.1

#985 Improving average and total stats calculation
  sdcm/db_stats.py
  sdcm/results_analyze.py
  sdcm/tester.py
Labels: Backport-2019.1

#994 Improving printout when _instance_wait_safe fails
  sdcm/cluster_aws.py
Labels: Backport-2019.1

#991 Improve the nemesis termination
  sdcm/cluster.py
  sdcm/nemesis.py
  sdcm/tester.py
Labels: No Backport Needed

#974 Adding .github PR and issues templates
  .github/issue_template.md
  .github/pull_request_template.md
Labels: No Backport Needed

#995 Add new config settings to configure number of oracle test nodes
  sdcm/sct_config.py
  sdcm/tester.py
  test-cases/gemini/gemini-basic-3h.yaml
  tests/gemini_test.yaml
Labels: No Backport Needed

#990 Fix js script for created shared snapshots of grafana dashboards
  data_dir/share_snapshot.js
Labels: No Backport Needed

#993 Address Security Alerts in our requirements*.txt files
  docker/env/version
  requirements-python.txt
Labels: No Backport Needed

#1000 Installing Gemini tool anyway
  sdcm/cluster.py
Labels: No Backport Needed

#992 Fix possible issue with wrong attribute by invoke lib
  sdcm/remote.py
Labels: No Backport Needed

#1003 Fix CmdExecTimeout object
  sdcm/remote.py
Labels: No Backport Needed

#1004 Remove the use of name binding from ngrok
  sdcm/cluster.py
Labels: No Backport Needed

#1001 Replace tracking of aio with avg aio
  sdcm/microbenchmarking.py
  sdcm/results_microbenchmark.html
Labels: Backport-2019.1
