Repository scylladb/scylla-cluster-tests, pull requests merged in 2019-11, with the labels that each got.

#1444 Disable send email if testrun is executed by job/pipeline
  sdcm/tester.py
Labels: No Backport Needed

#1443 Delete ES doc-id from longevity email report
  longevity_test.py
  sdcm/cluster.py
  sdcm/results_longevity.html
  sdcm/send_email.py
Labels: No Backport Needed, Ready for review

#1393 Fix remote connection stuck on ssh_up stage
  sdcm/remote.py
Labels: No Backport Needed, Ready for review

#1451 Fix test_13_scylla_version_ami_branch() to use older ami
  unit_tests/test_config.py
Labels: No Backport Needed

#1202 MV backpressure yaml changes
  data_dir/scylla-dash-per-server-nemesis.3.1.json
  jenkins-pipelines/features-2mv-backpressure-4days.jenkinsfile
  test-cases/features/2mv-backpressure-4d.yaml
Labels: Backport-3.1, Backport-3.2, Ready for review

#1435 Support IPv6 by SCT
  jenkins-pipelines/longevity-10gb-3h-ipv6.jenkinsfile
  longevity_test.py
  refresh_test.py
  sdcm/cluster.py
  sdcm/cluster_aws.py
  sdcm/cluster_gce.py
  sdcm/db_stats.py
  sdcm/remote.py
  sdcm/sct_config.py
  sdcm/tester.py
  vars/longevityPipeline.groovy
Labels: Backport-3.2, Ready for review

#1371 Port SCT to python3
  .pre-commit-config.yaml
  docker/env/Dockerfile
  docker/env/version
  grow_cluster_test.py
  longevity_test.py
  mgmt_cli_test.py
  performance_regression_test.py
  pylintrc
  requirements-python.txt
  sct.py
  sdcm/cluster.py
  sdcm/cluster_aws.py
  sdcm/cluster_baremetal.py
  sdcm/cluster_gce.py
  sdcm/collectd.py
  sdcm/db_stats.py
  sdcm/docker.py
  sdcm/ec2_client.py
  sdcm/es.py
  sdcm/fill_db_data.py
  sdcm/gemini_thread.py
  sdcm/keystore.py
  sdcm/logcollector.py
  sdcm/mgmt.py
  sdcm/microbenchmarking.py
  sdcm/nemesis.py
  sdcm/prometheus.py
  sdcm/remote.py
  sdcm/results_analyze.py
  sdcm/results_microbenchmark.html
  sdcm/sct_config.py
  sdcm/sct_events.py
  sdcm/send_email.py
  sdcm/stress_thread.py
  sdcm/tester.py
  sdcm/utils/alternator.py
  sdcm/utils/cloud_monitor/cloud_monitor.py
  sdcm/utils/cloud_monitor/report.py
  sdcm/utils/common.py
  sdcm/utils/py3_backports.py
  sdcm/ycsb_thread.py
  sstable_corrupt.py
  test_lib/sla.py
  unit_tests/dummy_remote.py
  unit_tests/test_cluster.py
  unit_tests/test_config.py
  unit_tests/test_events.py
  unit_tests/test_get_non_system_ks_cf_list.py
  unit_tests/test_manual.py
  unit_tests/test_microbenchmarking.py
  unit_tests/test_seed_selector.py
  unit_tests/test_utils_common.py
  unit_tests/test_utils_version.py
  unit_tests/test_version_utils.py
  unit_tests/test_wait.py
  upgrade_test.py
Labels: No Backport Needed, Ready to be Merged

#1452 Fix pipeline post_behavior parameters
  jenkins-pipelines/longevity-5000-tables.jenkinsfile
  vars/byoLongevityPipeline.groovy
  vars/longevityPipeline.groovy
  vars/perfRegressionParallelPipeline.groovy
  vars/rollingUpgradePipeline.groovy
  vars/scyllaCloudLongevityPipeline.groovy
Labels: Backport-3.2, Ready to be Merged

#1454 Remove as much of the disable=no-memeber as possible
  longevity_test.py
  performance_regression_test.py
  sdcm/cluster.py
  sdcm/fill_db_data.py
  sdcm/keystore.py
  sdcm/tester.py
Labels: No Backport Needed, Ready for review

#1455 Disable email report since it sent as separate stage in Jenkins pipeline
  defaults/test_default.yaml
Labels: Backport-3.1, Backport-3.2, Ready for review

#1457 terminate_and_replace_node: fix problem in cleaning replace_address parameter
  sdcm/cluster.py
  sdcm/cluster_aws.py
Labels: Backport-2019.1, Backport-3.2

#1458 add abort-on-internal-error flag to our test defaults, to detect corruptions faster
  defaults/test_default.yaml
Labels: Backport-3.2

#1461 Fix all DbEventsFilter to use a specific node
  sdcm/cluster_aws.py
  sdcm/nemesis.py
Labels: Backport-2019.1, Backport-3.1, Backport-3.2, Ready for review

#1464 Python3 fixes
  sdcm/cluster_gce.py
  sdcm/results_performance.html
  sdcm/tester.py
  sla_per_user_system_test.py
Labels: Ready for review

#1463 Fix byo pipeline - byo shouldn't be using`pipelineParams`
  vars/byoLongevityPipeline.groovy
Labels: Backport-3.2

#1459 Changed loader type to c4.2xlarge in 50gb
  test-cases/longevity/longevity-50GB-4days-authorization-and-tls-ssl.yaml
Labels: Backport-2019.1, Backport-3.2

#1474 Get AWS keys from Jenkins in CI
  vars/byoLongevityPipeline.groovy
  vars/longevityPipeline.groovy
  vars/perfRegressionParallelPipeline.groovy
  vars/rollingUpgradePipeline.groovy
  vars/scyllaCloudLongevityPipeline.groovy
Labels: Backport-2019.1, Backport-3.1, Backport-3.2, Ready for review

#1476 Add AWS keys to Jenkinsfile
  Jenkinsfile
Labels: Backport-2019.1, Backport-3.1, Backport-3.2, Ready for review

#1442 Add support for promproxy
  sdcm/cluster.py
  sdcm/sct_config.py
Labels: No Backport Needed, Ready for review

#1471 Fix for send_email if char could n't be encoded to ascii
  sdcm/send_email.py
Labels: Backport-3.2

#1385 Feature: GCE add fix reuse cluster feature
  sdcm/cluster.py
  sdcm/cluster_aws.py
  sdcm/cluster_gce.py
Labels: Backport-3.1, Backport-3.2, Ready for review

#1480 Adding a precommit check for AWS Credentials and Private Keys
  .pre-commit-config.yaml
Labels: No Backport Needed, Ready for review

#1453 Add support to raise critical events on thread failures
  longevity_in_memory_test.py
  longevity_large_partition_test.py
  sdcm/cluster.py
  sdcm/sct_events.py
  sdcm/tester.py
  sdcm/utils/thread.py
  unit_tests/test_events.py
Labels: No Backport Needed, Ready for review

#1481 Fix multi-region / public support
  sdcm/cluster.py
Labels: Backport-3.2, Ready for review

#1479 nemesis: _modify_table_property: debug cqlsh statement
  sdcm/nemesis.py
Labels: Backport-2019.1, Backport-3.2

#1486 Fix aws cred to be pass down in parallel pipelines
  vars/perfRegressionParallelPipeline.groovy
  vars/rollingUpgradePipeline.groovy
Labels: Backport-2019.1, Backport-3.1, Backport-3.2, Ready for review

#1468 Added retrying to stop_scylla_server
  sdcm/cluster.py
Labels: No Backport Needed

#1475 Fix issue with mising dashboards for new scylla versions
  sdcm/logcollector.py
Labels: Backport-3.1, Backport-3.2
