Repository scylladb/scylla-cluster-tests, pull requests merged in 2019-08, with the labels that each got.

#1207 MBM: Fix wrong reporting upon metric is 0
  sdcm/microbenchmarking.py
  unit_tests/test_data/MBM/PFF_with_AVGAIO_0/perf_fast_forward_output/large-partition-forwarding/large-part-ds1/no.1.json
  unit_tests/test_data/MBM/PFF_with_AVGAIO_0/perf_fast_forward_output/large-partition-forwarding/large-part-ds1/yes.1.json
  unit_tests/test_data/MBM/PFF_with_AVGAIO_0/perf_fast_forward_output/small-partition-slicing/small-part/0-256.1.json
  unit_tests/test_data/MBM/PFF_with_AVGAIO_0/perf_fast_forward_output/small-partition-slicing/small-part/500000-4096.1.json
  unit_tests/test_microbenchmarking.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1165 Add support for using reverse tunnel for rsyslog
  sdcm/auto_ssh.py
  sdcm/cluster.py
  sdcm/cluster_baremetal.py
  sdcm/tester.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1205 Improve cluster health check
  sdcm/cluster.py
  sdcm/sct_events.py
Labels: Backport-2019.1, Backport-3.1, Ready to be Merged

#1204 Added automatic copy c-s user profile to run_stress_thread
  longevity_test.py
  sdcm/stress_thread.py
Labels: Backport-2019.1, Backport-3.1, Ready to be Merged

#1173 Fix non seed nodes list for update db pkg/binary
  sdcm/cluster.py
Labels: Backport-2019.1, Backport-3.1, Ready to be Merged

#968 Two system tests for feature 'SLA per user'
  jenkins-pipelines/features-sla-read-throughput-1to5-ratio.jenkinsfile
  jenkins-pipelines/features-sla-read-throughput-vs-latency-cache-and-disk.jenkinsfile
  jenkins-pipelines/features-sla-read-throughput-vs-latency-cache-only.jenkinsfile
  jenkins-pipelines/features-sla-read-throughput-vs-latency-disk-only.jenkinsfile
  sdcm/cluster.py
  sdcm/db_stats.py
  sdcm/tester.py
  sla_per_user_system_test.py
  test-cases/features/system-sla-test.yaml
  test_lib/__init__.py
  test_lib/sla.py
Labels: Backport-2019.1, Ready to be Merged

#1206 Filter schema failure known issues in upgrade_test
  unit_tests/test_events.py
  upgrade_test.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1210 Automatically remove autossh container after exit
  sdcm/auto_ssh.py
Labels: Backport-2019.1, Backport-3.1

#1100 upgrade_test: increase schema error factor
  upgrade_test.py
Labels: Backport-2019.1

#1212 URGENT: server encryption: extend period of validity for db.crt
  data_dir/ssl_conf/db.crt
  data_dir/ssl_conf/example/cadb.srl
  data_dir/ssl_conf/example/db.crt
Labels: Backport-2019.1, Backport-3.1

#1213 Prevent failure in case selected logs_transport ssh
  sdcm/cluster.py
Labels: Backport-3.1

#1214 db_stats - create_test_stats check flag before starting
  sdcm/db_stats.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1215 Support rsyslog for reuse_cluster
  README.rst
  sdcm/cluster.py
  sdcm/cluster_aws.py
  sdcm/cluster_baremetal.py
  sdcm/db_stats.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1218 Refactor the test case linting into it's own bash script
  Jenkinsfile
  utils/lint_test_cases.sh
Labels: No Backport Needed, Ready for review

#1217 Switch back to formal versions of `invoke` and `fabric`
  docker/env/version
  requirements-python.txt
  sdcm/remote.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1220 Increase cloud longevity pipeline timeout
  jenkins-pipelines/scylla-cloud-longevity-200gb-48h.jenkinsfile
Labels: No Backport Needed

#1219 Implemented Cloud Monitor
  sct.py
  sdcm/utils/cloud_monitor/__init__.py
  sdcm/utils/cloud_monitor/cloud_monitor.py
  sdcm/utils/cloud_monitor/report.py
  sdcm/utils/cloud_monitor/templates/base.html
  sdcm/utils/cloud_monitor/templates/cloud_resources.html
  sdcm/utils/cloud_monitor/templates/per_user.html
  sdcm/utils/cloud_monitor/templates/per_user_summary.html
  sdcm/utils/common.py
Labels: No Backport Needed

#1216 Determine hinted handoff state in absolute way: enabled/disabled
  docs/configuration_options.md
  sdcm/cluster.py
  sdcm/cluster_aws.py
  sdcm/cluster_libvirt.py
  sdcm/cluster_openstack.py
  sdcm/sct_config.py
  test-cases/features/hinted-handoff.yaml
  tests/hinted-handoff.yaml
  tests/sample.yaml
Labels: Backport-3.1, Ready to be Merged

#1221 Increased truncate nemesis timoeout
  sdcm/nemesis.py
Labels: Backport-2019.1, Backport-3.1

#1203 changed get_startup_script to run also on SSH
  sdcm/cluster.py
  sdcm/cluster_aws.py
Labels: Backport-2019.1, Backport-3.1, Ready to be Merged

#1232 Fixed a type on startup script cluster.py
  sdcm/cluster.py
Labels: Backport-2019.1, Backport-3.1

#1226 Adding functionality to show running instances per user
  sct.py
Labels: No Backport Needed

#1233 Fixed the ManagerCluster's delete_task function
  sdcm/mgmt.py
Labels: Backport-2019.1, Backport-3.1

#1235 Fix NodeType for AWS
  sdcm/cluster_aws.py
  sdcm/cluster_baremetal.py
Labels: Backport-2019.1, Backport-3.1

#1241 workaround: Install the python36 version of PyYAML
  sdcm/cluster.py
Labels: No Backport Needed

#1239 Added debug flags to Janus Graph test
  janus_graph_test.py
Labels: Backport-2018.1, Backport-2019.1, Backport-3.0, Backport-3.1

#1229 Fix Full scan to be using the python driver
  sdcm/cluster.py
  sdcm/sct_events.py
  sdcm/tester.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1242 Fix get_non_system_ks_cf_list function
  sdcm/cluster.py
  sdcm/nemesis.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1246 Fix some log print in AWSNode class
  sdcm/cluster_aws.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1245 GCE: fix yum error and report_uuid issue in setup stage
  sdcm/cluster.py
Labels: Backport-2019.1, Backport-3.0, Backport-3.1

#1248 Move get_non_system_ks_cf_list function to utils/common and add unit tests
  sdcm/cluster.py
  sdcm/nemesis.py
  sdcm/tester.py
  sdcm/utils/common.py
  unit_tests/test_get_non_system_ks_cf_list.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1234 Fix unit-tests for microbenchmarking
  unit_tests/test_microbenchmarking.py
Labels: No Backport Needed, Ready for review

#1250 backport PR #1245 (GCE fix) to branch-3.0
  sdcm/cluster.py
Labels: No Backport Needed

#1247 Make sure we ignore all the errors in abort repair nemesis
  sdcm/nemesis.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1231 Added keyspace_name optional parameter to create_table()
  longevity_test.py
  sdcm/tester.py
Labels: Backport-2019.1, Ready for review

#1254 Fix refresh nemesis: prepare test ks/table if it doesn't exist
  sdcm/nemesis.py
  sdcm/utils/common.py
Labels: Backport-3.1, Ready for review

#1240 Remove files for repair test: change file name template for deletition
  data_dir/break_scylla.sh
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1258 Fix variable name in _prepare_test_table function
  sdcm/nemesis.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1260 Remove autossh container at the and of the run (instead of just killi…
  sdcm/auto_ssh.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1264 Remove coredump splitting logic
  sdcm/cluster.py
  sdcm/sct_events.py
  unit_tests/test_events.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1267 Lower the load on cloud longevity to 100GB
  jenkins-pipelines/scylla-cloud-longevity-100gb-48h.jenkinsfile
  test-cases/longevity/longevity-100GB-48h-cloud-CloudLimitedChaosMonkey-tls.yaml
Labels: No Backport Needed, Ready for review

#1268 If MV does not exists don't return empty result from get_non_system_ks_cf_list
  sdcm/utils/common.py
  unit_tests/test_get_non_system_ks_cf_list.py
Labels: Backport-2019.1, Backport-3.1, Ready for review

#1263 fix uploading of job log (db/loader/monitor)
  sdcm/tester.py
Labels: Backport-2019.1, Backport-3.1

#1273 extend test duration of rolling upgrade to 180 mins
  test-cases/upgrades/rolling-upgrade.yaml
  tests/rolling-upgrade-gce.yaml
Labels: Backport-2019.1, Backport-3.1, Ready to be Merged
