Repository scylladb/scylla-cluster-tests, pull requests merged in 2020-08, with the labels that each got.

#2266 fix (refresh nemesis): load sstable files to all db nodes by refresh
  sdcm/nemesis.py
Labels: Backport-2020.1, Backport-4.0, Backport-4.1

#2444 fix(sdcm/cluster.py): stop using new_session
  sdcm/cluster.py
Labels: Backport-2020.1, Ready for review

#2465 fix(perf_test pipeline): fix old builder leftover
  vars/perfRegressionParallelPipeline.groovy
Labels: No Backport Needed

#2466 fix(getjenkinslabels): on master, moved to use new builders
  vars/getJenkinsLabels.groovy
Labels: No Backport Needed

#2405 fix(run_user_stress_in_batches): start nemesis thread after stress
  longevity_test.py
Labels: Backport-2019.1, Backport-2020.1, Backport-4.1, Backport-4.2, Ready for review

#2454 fix(cdcrepl_pipeline): Use correct functions in cdcrepl pipeline
  vars/cdcReplicationPipeline.groovy
Labels: No Backport Needed, Ready for review

#2478 fix(sdcm/remote/remote_base.py): fix it for case when ~ is present
  sdcm/remote/remote_base.py
Labels: No Backport Needed, Ready for review

#2469 feature(sct-runner): increase root disk size to 35 GB
  sdcm/sct_runner.py
  sdcm/tester.py
  sdcm/utils/common.py
Labels: No Backport Needed

#2474 fix(traffic_control): Install traffic control on AMAZON2 image
  sdcm/cluster_aws.py
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#2461 improvement(cluster): filter out unknown args from append_scylla_args
  sdcm/cluster.py
  sdcm/utils/scylla_args.py
  unit_tests/test_utils_scylla_args.py
Labels: No Backport Needed, Ready for review

#2440 feature(defaults/aws_config): increase root disk size of aws instance
  defaults/aws_config.yaml
Labels: Backport-4.2, Ready for review

#2464 fix(wait for schema agreement): wait for schema agreement on all nodes after schema change
  sdcm/cluster.py
  sdcm/nemesis.py
  sdcm/tester.py
  sdcm/utils/health_checker.py
Labels: Backport-2020.1, Backport-4.1, Backport-4.2, Ready for review

#2475 fix(system.peers): print all columns from system.peers table
  sdcm/utils/health_checker.py
Labels: Backport-2020.1, Backport-4.1, Backport-4.2, Ready for review

#2485 refactor(sct_events.py): Crating object for group common DB events
  cdc_replication_test.py
  mgmt_cli_test.py
  performance_regression_alternator_test.py
  performance_regression_lwt_test.py
  sdcm/group_common_events.py
  sdcm/nemesis.py
  sdcm/sct_events.py
  sdcm/utils/alternator/api.py
  upgrade_test.py
Labels: No Backport Needed

#2483 fix(alternator_api): Add configured region to getting resource
  sdcm/utils/alternator/api.py
Labels: Backport-4.2

#2488 fix(sdcm/remote/libssh2_client/__init__.py): make it show stderr
  sdcm/remote/libssh2_client/__init__.py
Labels: No Backport Needed

#2480 fix(sdcm/nemesis): Make nemesis calculate relaible replication factor
  sdcm/nemesis.py
  sdcm/tester.py
Labels: No Backport Needed, Ready for review

#2481 fix(sdcm/nemesis): fix refreshmonkeys failure if there is no target table
  sdcm/nemesis.py
Labels: Backport-2020.1, Backport-4.1, Backport-4.2, Ready for review

#2470 add running nodes to aborted email
  sct.py
  sdcm/report_templates/results_aborted.html
  sdcm/report_templates/results_base.html
  sdcm/send_email.py
Labels: No Backport Needed, Ready for review

#2489 improvement(rolling_upgrade): set server_encrypt to true
  test-cases/upgrades/rolling-upgrade.yaml
Labels: Backport-2020.1, Backport-4.2

#2492 fix(sdcm/remote/remote_base.py): fix context generation
  sdcm/remote/remote_base.py
  unit_tests/test_remoter.py
Labels: No Backport Needed, Ready for review

#2486 fix(parse_toppartition): Search pattern in output instead of match
  sdcm/nemesis.py
Labels: Backport-4.1, Backport-4.2, Ready for review

#2495 fix(sdcm/group_common_events.py): fix ExitStack usage
  sdcm/group_common_events.py
Labels: No Backport Needed, Ready for review

#2453 fix(sdcm/): Get rid of search_system_log
  sdcm/cluster.py
  sdcm/nemesis.py
  sdcm/utils/file.py
  unit_tests/test_cluster.py
  unit_tests/test_decode_backtrace.py
  upgrade_test.py
Labels: No Backport Needed, Ready for review

#2479 fix(manager): Changed the method that waits for the manager to start
  sdcm/cluster.py
Labels: Backport-2020.1, Backport-4.2, Backport-manager-v2.1

#2472 feature(manager-upgrade): Added a summary email
  mgmt_upgrade_test.py
  sdcm/report_templates/results_manager_upgrade.html
  sdcm/send_email.py
Labels: Backport-manager-v2.1

#2491 fix(epel install): enable amazon2-extras repo of epel
  sdcm/cluster.py
  sdcm/collectd.py
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#2496 fix(get_non_system_ks_cf_list): Return list instead of set
  sdcm/cluster.py
Labels: Backport-4.2, Ready for review, Urgent

#2501 improvement(artifacts): rename instance_provision jobs parameter to provision_type
  jenkins-pipelines/artifacts-amazon2.jenkinsfile
  jenkins-pipelines/artifacts-ami.jenkinsfile
  jenkins-pipelines/artifacts-centos7.jenkinsfile
  jenkins-pipelines/artifacts-centos8.jenkinsfile
  jenkins-pipelines/artifacts-debian10.jenkinsfile
  jenkins-pipelines/artifacts-debian9.jenkinsfile
  jenkins-pipelines/artifacts-oel76.jenkinsfile
  jenkins-pipelines/artifacts-ubuntu1604.jenkinsfile
  jenkins-pipelines/artifacts-ubuntu1804.jenkinsfile
  vars/artifactsPipeline.groovy
Labels: No Backport Needed, Ready for review

#2448 improvement(gemini_report): inherit report from base_report with atta…
  sdcm/report_templates/results_cdcreplication.html
  sdcm/report_templates/results_gemini.html
  sdcm/report_templates/results_longevity.html
  sdcm/report_templates/results_nemesis_stats.html
  sdcm/send_email.py
Labels: Backport-4.2, Ready for review

#2497 fix(upgrade test): restore scylla.yaml after rollback
  upgrade_test.py
Labels: No Backport Needed, Ready for review

#2502 improvement(nemesis.py): Added raise_event_on_failure to Nemesis.run
  sdcm/nemesis.py
Labels: Backport-2020.1, Backport-4.1, Backport-4.2

#2504 fix(sdcm/remote/libssh2_client/__init__.py): make it ipv6 complaint
  sdcm/remote/libssh2_client/__init__.py
  unit_tests/test_remoter.py
Labels: Backport-2020.1, Backport-4.2, Ready for review

#2511 fix(config): name gce_network env variable correctly
  docs/configuration_options.md
  sdcm/sct_config.py
Labels: Backport-2020.1, Backport-4.0, Backport-4.1, Backport-4.2, Ready for review

#2514 fix(should_keep_alive): use correct substring to match node type
  sdcm/cluster.py
Labels: Backport-2020.1, Backport-4.1, Backport-4.2, Ready for review

#2517 test(not stop_test_on_stress_failure): not stop_test_on_stress_failure in large partition 200k
  test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml
Labels: Backport-2020.1, Backport-4.2, Ready for review

#2516 improvement(clean_resources): remove --config-file, add --post-behavior and --dry-run options
  Jenkinsfile
  docs/new-hydra-commands.md
  sct.py
  sdcm/utils/common.py
  vars/artifactsPipeline.groovy
  vars/managerPipeline.groovy
  vars/operatorPipeline.groovy
  vars/perfRegressionParallelPipeline.groovy
  vars/rollingUpgradePipeline.groovy
  vars/runCleanupResource.groovy
Labels: No Backport Needed, Ready for review

#2518 fix(sct_config.py): Removing "authenticator_user" and "authenticator_…
  sdcm/sct_config.py
Labels: No Backport Needed

#2513 fix(delete by partition nemesis): change exception when missed max_partitions_in_test_table parameter
  sdcm/nemesis.py
  test-cases/PR-provision-test.yaml
Labels: Backport-2020.1, Backport-4.1, Backport-4.2, Ready for review

#2521 improvement(remoter): add 'sudo()' and 'run_shell_script()' methods
  sdcm/remote/base.py
  unit_tests/test_remoter.py
Labels: No Backport Needed, Ready for review

#2498 fix(cdc_repl_test): Use oracle cluster for cql connection
  cdc_replication_test.py
Labels: No Backport Needed, Ready for review

#2522 refactor(config_setup): improve append_scylla_args handling
  sdcm/cluster.py
Labels: No Backport Needed, Ready for review

#2510 fix(flackyretrypolicy): Fix multiple values for msg argument
  sdcm/cluster.py
Labels: Backport-4.2

#2523 fix(health cluster validator): fix source data for schema validation
  sdcm/utils/health_checker.py
Labels: Backport-2020.1, Backport-4.1, Backport-4.2, Ready for review

#2526 test(scylla bench threads): increase sleep between scylla-bench threads
  sdcm/cluster.py
Labels: Backport-2020.1, Backport-4.2, Ready for review

#2525 fix(_add_init_new_node): set running_nemesis to none if enableautocom…
  sdcm/nemesis.py
Labels: Backport-4.2, Ready for review

#2527 fix(alternator/api.py): Fixing region_name for Cloud run
  sdcm/utils/alternator/api.py
Labels: Backport-2020.1, Backport-4.2

#2507 fix(reporting): Add backend and region to the email report
  artifacts_test.py
  mgmt_cli_test.py
  mgmt_upgrade_test.py
  sdcm/report_templates/results_base.html
  sdcm/report_templates/results_manager.html
  sdcm/report_templates/results_manager_upgrade.html
  sdcm/send_email.py
  sdcm/tester.py
Labels: No Backport Needed, Ready for review

#2529 improvement(cluster): don't install net-tools, file, and wget packages to DB nodes
  docker/scylla-sct/Dockerfile
  sdcm/cluster.py
  sdcm/cluster_k8s.py
  sdcm/utils/version_utils.py
Labels: No Backport Needed, Ready for review

#2531 fix(alternator/api.py): Creating Alternator resources with "None" region name
  sdcm/utils/alternator/api.py
Labels: Backport-2020.1, Backport-4.2

#2535 Fix latency perf jobs
  sdcm/cluster.py
  sdcm/sct_config.py
  sdcm/utils/distro.py
Labels: No Backport Needed

#2533 fix(get_non_system_ks_cf_list): Add missing column to cql query
  sdcm/cluster.py
Labels: Backport-4.2, Ready for review

#2539 fix(cluster.py): Fixing cql_connection function
  sdcm/cluster.py
Labels: Backport-4.2, Ready for review

#2467 fix(sdcm/coredump): Move out coredump code and make it's shutdown better
  sdcm/cluster.py
  sdcm/cluster_aws.py
  sdcm/cluster_baremetal.py
  sdcm/cluster_gce.py
  sdcm/coredump.py
  sdcm/prometheus.py
  sdcm/tester.py
  unit_tests/test_decode_backtrace.py
  unit_tests/test_prometheus.py
Labels: No Backport Needed, Ready for review

#2487 fix(sdcm/cluster.py): Make reboot more stable
  sdcm/cluster.py
  sdcm/remote/remote_base.py
Labels: Backport-2020.1, Backport-4.2, Ready for review

#2536 fix(disableautocompaction): remove from add_node
  sdcm/nemesis.py
Labels: Backport-2020.1, Backport-4.2

#2545 fix(scyllakill): waiting for db to be down before
  sdcm/nemesis.py
Labels: Backport-4.2

#2544 fix(sdcm/remote/remote_libssh_cmd_runner.py): stop running keep-alive thread to reduce possibility of hitting segmentation fault
  sdcm/remote/libssh2_client/__init__.py
  sdcm/remote/remote_libssh_cmd_runner.py
Labels: Backport-2020.1, Backport-4.2, Ready for review

#2537 fix(ssl_files_location): get location on demand
  sdcm/nemesis.py
Labels: No Backport Needed

#2509 fix(sdcm/utils/file.py): make read_lines_filtered iteration repitable
  sdcm/utils/file.py
Labels: No Backport Needed, Ready for review

#2524 refactor(cluster): improve scylla.yaml patching
  sdcm/cluster.py
  sdcm/nemesis.py
  sdcm/remote/remote_file.py
  sdcm/tester.py
  unit_tests/test_remoter.py
Labels: No Backport Needed, Ready for review

#2547 improvement(result_analyze): Added email_subject_postfix to regression check
  sdcm/results_analyze/__init__.py
  sdcm/tester.py
Labels: No Backport Needed

#2551 fix(nemesis): set current disruption for MemoryStress Monkey
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#2552 fix(nemesis.py): Disabling TerminateAndRemoveNodeMonkey nemesis for Siren cloud
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#2557 improvement(CommitLint): allow case insensitive scope
  commitlint.config.js
Labels: No Backport Needed

#2564 fix(disrupt_kill_scylla): wait for schema agreement after disrupt_kill_scylla
  sdcm/nemesis.py
Labels: Backport-2020.1, Backport-4.1, Backport-4.2, Ready for review

#2567 fix(rolling-upgrade): Removing internode_compression 'all' from upgrades
  jenkins-pipelines/rolling-upgrade-centos8.jenkinsfile
  jenkins-pipelines/rolling-upgrade-ubuntu18.04.jenkinsfile
Labels: Backport-4.2

#2566 fix(instance_type): using c5 type instead of c4
  internal_test_data/multi_region_dc_test_case.yaml
  sdcm/cluster_aws.py
  test-cases/cdc/cdc-15m-replication-gemini.yaml
  test-cases/cdc/cdc-15m-replication-postimage.yaml
  test-cases/cdc/cdc-15m-replication-preimage.yaml
  test-cases/cdc/cdc-15m-replication.yaml
  test-cases/features/dns-cluster-5min.yaml
  test-cases/features/enospc-30mins.yaml
  test-cases/features/ics_space_amplification_test.yaml
  test-cases/load/admission_control_overload_test.yaml
  test-cases/longevity/longevity-2TB-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis.yaml
  test-cases/longevity/longevity-50GB-4days-authorization-and-tls-ssl.yaml
  test-cases/manager/manager-regression-ipv6.yaml
  test-cases/manager/manager-regression-multiDC-set-distro.yaml
  test-cases/performance/perf-regression-alternator-latency-500gb-30min.yaml
  test-cases/performance/perf-regression-alternator.100threads.30M-keys.yaml
  test-cases/performance/perf-regression-latency-1TB.yaml
  test-cases/performance/perf-regression-latency-250gb-with-nemesis.yaml
  test-cases/performance/perf-regression-latency-500gb-30min.yaml
  test-cases/performance/perf-regression-latency-lwt-big.yaml
  test-cases/performance/perf-regression-latency-lwt-small.yaml
  test-cases/performance/perf-regression-throughput-cdc-mixed-poll-batching.yaml
  test-cases/performance/perf-regression-throughput-lwt-big.yaml
  test-cases/performance/perf-regression-throughput-lwt-small.yaml
  test-cases/performance/perf-regression-write-latency-cdc.yaml
  test-cases/performance/perf-regression-write-throughput-cdc.yaml
  test-cases/performance/perf-regression.100threads.30M-keys.yaml
  test-cases/performance/perf-row-level-repair-1TB.yaml
  test-cases/upgrades/manager-upgrade.yaml
Labels: Backport-2020.1, Backport-4.2

#2568 fix(cdc_replication_test): autopep8 issues
  cdc_replication_test.py
Labels: No Backport Needed

#2565 add(unitests/test_coredump): add coredump tests
  sdcm/coredump.py
  unit_tests/lib/data_pickle.py
  unit_tests/lib/mock_remoter.py
  unit_tests/lib/remoter_recorder.py
  unit_tests/test_coredump.py
  unit_tests/test_data/test_coredump/fail_get_list_test_remoter.json
  unit_tests/test_data/test_coredump/fail_get_list_test_results.json
  unit_tests/test_data/test_coredump/fail_upload_test_remoter.json
  unit_tests/test_data/test_coredump/fail_upload_test_results.json
  unit_tests/test_data/test_coredump/success_test_remoter.json
  unit_tests/test_data/test_coredump/success_test_results.json
Labels: No Backport Needed, Ready for review

#2550 improvement(operator): grow cluster by changing spec
  defaults/k8s_gce_minikube_config.yaml
  docs/configuration_options.md
  sdcm/cluster.py
  sdcm/cluster_docker.py
  sdcm/cluster_gce.py
  sdcm/cluster_k8s.py
  sdcm/k8s_configs/cluster.yaml
  sdcm/nemesis.py
  sdcm/remote/base.py
  sdcm/remote/kubernetes_cmd_runner.py
  sdcm/sct_config.py
  sdcm/tester.py
  sdcm/utils/k8s.py
  sdcm/utils/remote_logger.py
Labels: No Backport Needed, Ready for review

#2560 fix(killscylla): wait_db_down has too large wait
  sdcm/cluster.py
  sdcm/nemesis.py
Labels: Backport-4.2, Ready for review

#2554 fix(runSctTest): export SCT_UPDATE_DB_PACKAGES
  vars/runSctTest.groovy
Labels: No Backport Needed, Ready for review
