Repository scylladb/scylla-cluster-tests, pull requests merged in 2020-11, with the labels that each got.

#2816 fix(lwt tests): scylla-qa-loader-ami-lwt-v5 image was reloaded to eu-west-1
  test-cases/longevity/longevity-lwt-1loader-3h.yaml
  test-cases/longevity/longevity-lwt-24h-multidc.yaml
  test-cases/longevity/longevity-lwt-500G-3d.yaml
  test-cases/longevity/longevity-lwt-basic-24h-1dis-2nondis.yaml
  test-cases/longevity/longevity-lwt-basic-24h.yaml
  test-cases/longevity/longevity-lwt-basic-3h.yaml
  test-cases/performance/perf-regression-latency-lwt-big.yaml
  test-cases/performance/perf-regression-latency-lwt-small.yaml
  test-cases/performance/perf-regression-throughput-lwt-big.yaml
  test-cases/performance/perf-regression-throughput-lwt-small.yaml
Labels: Ready for review

#2817 fix(aws_config): set aws_root_disk_size_db to 30
  defaults/aws_config.yaml
Labels: No Backport Needed, Ready for review

#2800 fix(scyllakillmonkey): reduce severity of event
  sdcm/nemesis.py
  sdcm/tester.py
Labels: Backport-4.3

#2818 refactor(rolling-upgrade): Changed the base version to 4.2
  jenkins-pipelines/rolling-upgrade-centos7.jenkinsfile
  jenkins-pipelines/rolling-upgrade-centos8.jenkinsfile
  jenkins-pipelines/rolling-upgrade-debian10.jenkinsfile
  jenkins-pipelines/rolling-upgrade-debian9.jenkinsfile
  jenkins-pipelines/rolling-upgrade-ubuntu16.04.jenkinsfile
  jenkins-pipelines/rolling-upgrade-ubuntu18.04.jenkinsfile
Labels: Backport-4.3

#2813 improvement(install scylla-bench): support scylla-bench when running test in docker
  sdcm/cluster.py
  sdcm/cluster_docker.py
Labels: Ready for review

#2812 feature(scylla-bench authentication): add username and password to scylla-bench command
  sdcm/sct_config.py
  sdcm/tester.py
Labels: Backport-2020.1, Backport-4.2, Backport-4.3, Ready for review

#2821 improvement(operator): bump operator version to v0.3.0
  defaults/k8s_gce_minikube_config.yaml
  defaults/k8s_gke_config.yaml
  sdcm/k8s_configs/operator.yaml
Labels: No Backport Needed, Ready for review

#2825 fix(minikube upgrade test): set correct path to yaml
  jenkins-pipelines/upgrade-scylla-k8s-minikube.jenkinsfile
Labels: No Backport Needed, Ready for review

#2822 fix(mgmt_cli_test): compare 2019 as a number
  mgmt_cli_test.py
Labels: Backport-2019.1, Backport-2020.1, Backport-4.1, Backport-4.2, Backport-4.3, Ready for review

#2826 fix(operator): switch to Scylla 4.2.0
  defaults/k8s_gce_minikube_config.yaml
  defaults/k8s_gke_config.yaml
  vars/operatorPipeline.groovy
Labels: No Backport Needed, Ready for review

#2829 fix(nemesis.py): Disabling TruncateMonkeyLargePartition nemesis
  sdcm/nemesis.py
Labels: No Backport Needed

#2832 fix(fill_db_data.py): Changing "caching" value to dict
  sdcm/fill_db_data.py
Labels: Backport-4.3, Ready for review

#2824 fix(rolling-upgrade): Added a wait for the jmx to start
  upgrade_test.py
Labels: Backport-2020.1, Backport-4.3

#2835 fix(k8s-gke): wait for clusters readiness
  sdcm/cluster_k8s/__init__.py
  sdcm/cluster_k8s/gke.py
Labels: No Backport Needed, Ready for review

#2827 improvement(docker): add the name to a Container str
  sdcm/utils/common.py
  sdcm/utils/docker_utils.py
Labels: No Backport Needed, Ready for review

#2833 fix(config_test): make it pass + refactor of get_branched_repo()
  sdcm/utils/common.py
  unit_tests/test_config.py
Labels: Backport-2020.1, Backport-4.2, Backport-4.3, Ready for review

#2838 fix(sct_config): don't use scylla_repo_loader for AWS
  sdcm/sct_config.py
  unit_tests/test_config.py
Labels: Backport-2020.1, Backport-4.2, Backport-4.3, Ready for review

#2834 fix(1tb-longevity): Added use_legacy_cluster_init flag to the config
  defaults/test_default.yaml
  test-cases/cdc/cdc-15m-replication-gemini.yaml
  test-cases/cdc/cdc-15m-replication-postimage.yaml
  test-cases/cdc/cdc-15m-replication-preimage.yaml
  test-cases/cdc/cdc-15m-replication.yaml
  test-cases/cdc/cdc-replication-longevity.yaml
  test-cases/features/scale-cluster.yaml
  test-cases/longevity/longevity-100gb-4h.yaml
  test-cases/longevity/longevity-5000-tables.yaml
  test-cases/upgrades/rolling-upgrade.yaml
Labels: Backport-4.3

#2839 fix(cluster_aws): moved var-lib-scylla.mount away after restart
  sdcm/cluster_aws.py
Labels: Backport-4.3

#2840 fix(gce failing spot): GCE failing during setup of spot instances
  sdcm/cluster_gce.py
Labels: No Backport Needed, Ready for review

#2830 feature(k8s-gke): put loaders into GKE cluster
  defaults/k8s_gke_config.yaml
  docs/configuration_options.md
  sdcm/cluster.py
  sdcm/cluster_k8s/__init__.py
  sdcm/cluster_k8s/gke.py
  sdcm/cluster_k8s/iptables.py
  sdcm/k8s_configs/gke-loaders.yaml
  sdcm/sct_config.py
  sdcm/tester.py
Labels: No Backport Needed, Ready for review

#2796 feature(scylla-bench refactor): refactor usage of scylla-bench
  data_dir/scylla-dash-per-server-nemesis.master.json
  longevity_test.py
  sdcm/cluster.py
  sdcm/loader.py
  sdcm/sct_events.py
  sdcm/scylla_bench_thread.py
  sdcm/stress_thread.py
  sdcm/tester.py
  sdcm/utils/common.py
Labels: No Backport Needed, Ready for review

#2846 fix(_read_system_log_and_publish_events): stop matching json-encoded logs to the patterns
  sdcm/cluster.py
Labels: No Backport Needed, Ready for review

#2848 fix(upgrade_test.py): Fixing "test_generic_cluster_upgrade"
  upgrade_test.py
Labels: No Backport Needed

#2849 fix(EventsAnalyzer): don't stop test on cassandra-stress/scylla-bench…
  sdcm/sct_events_analyzer.py
Labels: Backport-4.3, Ready for review

#2837 fix(set_target_node): allow to set target node in specific dc
  sdcm/nemesis.py
Labels: Backport-4.3

#2841 fix(docker): workaround for scylladb/scylla#7560
  docker/scylla-sct/Dockerfile
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed, Ready for review

#2847 fix(show-monitor): monitor missing dashboards on master
  sdcm/cluster.py
  unit_tests/test_cluster.py
Labels: No Backport Needed, Ready for review

#2856 improvement(cluster): wait for Scylla Machine Image setup to be done
  sdcm/cluster.py
  sdcm/cluster_aws.py
  sdcm/cluster_gce.py
Labels: No Backport Needed

#2860 fix(operator): bump default Scylla version to 4.2.1
  defaults/k8s_gce_minikube_config.yaml
  defaults/k8s_gke_config.yaml
Labels: No Backport Needed, Ready for review

#2865 fix(bump manager version): manager 2.2 was released
  defaults/test_default.yaml
  internal_test_data/complex_test_case_with_version.yaml
  test-cases/performance/perf-regression-latency-250gb-with-nemesis.yaml
Labels: Backport-4.3

#2845 fix(sct_config): Update of the help markdown
  docs/configuration_options.md
  sdcm/sct_config.py
Labels: No Backport Needed, Ready for review

#2873 feature(tests): add support for Ubuntu 20.04 LTS
  docs/artifacts_test.md
  jenkins-pipelines/artifacts-ubuntu2004.jenkinsfile
  jenkins-pipelines/rolling-upgrade-ubuntu20.04.jenkinsfile
  sct.py
  sdcm/cluster.py
  sdcm/cluster_gce.py
  sdcm/collectd.py
  sdcm/utils/distro.py
  test-cases/artifacts/ubuntu2004.yaml
  unit_tests/test_utils_distro.py
Labels: Backport-4.3, Ready for review

#2843 fix(get_grafana_annotations): make the limit much larger
  sdcm/cluster.py
Labels: Backport-4.3, Ready for review

#2876 fix(sct-runner): workaround for OOM issue #2859
  sdcm/sct_runner.py
Labels: Backport-4.3

#2864 fix(check_regression_multi_baseline): don't raise exception when no test found
  sdcm/results_analyze/__init__.py
Labels: Ready for review

#2862 feature(nemesis): new manager nemesis that backs up specific kespaces
  sdcm/nemesis.py
Labels: No Backport Needed

#2836 test(cdc-400gb-3d): New cdc job 3d 400gb dataset
  data_dir/cdc_profile_400gb.yaml
  data_dir/cdc_profile_400gb_postimage.yaml
  data_dir/cdc_profile_400gb_preimage.yaml
  data_dir/cdc_profile_400gb_preimage_postimage.yaml
  jenkins-pipelines/longevity-cdc-3d-400gb.jenkinsfile
  test-cases/longevity/longevity-cdc-3d-400gb.yaml
Labels: Backport-4.3, Ready for review

#2872 fix(logcollector): make GKE logs collected
  sdcm/logcollector.py
  sdcm/tester.py
  sdcm/utils/common.py
Labels: No Backport Needed, Ready for review

#2871 improvement(k8s): add event logger thread
  sdcm/cluster_k8s/__init__.py
  sdcm/utils/remote_logger.py
Labels: No Backport Needed, Ready for review

#2863 fix(check_regression_multi_baseline): don't raise exception when no test found
  sdcm/results_analyze/__init__.py
Labels: No Backport Needed, Ready for review

#2879 fix(amazon2 check): not check cluster name during amazon2 artifact test
  artifacts_test.py
Labels: Ready for review

#2886 fix(upgrade_test): ALLOW FILTERING isn't a must anymore in some queries
  sdcm/fill_db_data.py
Labels: No Backport Needed, Ready for review

#2889 improvement(operator): switch to nightly builds
  defaults/k8s_gce_minikube_config.yaml
  defaults/k8s_gke_config.yaml
  sdcm/cluster_k8s/__init__.py
  sdcm/k8s_configs/cluster-gke.yaml
  sdcm/k8s_configs/cluster-minikube.yaml
  sdcm/k8s_configs/operator.yaml
Labels: No Backport Needed, Ready for review

#2869 fix(nemesis.py): Fixing 'disrupt_hot_reloading_internode_certificate'
  sdcm/nemesis.py
Labels: Backport-4.3, Ready for review

#2894 fix(operator_monitoring.py): operator_pod_status can be None
  sdcm/cluster_k8s/operator_monitoring.py
Labels: No Backport Needed, Ready for review

#2895 fix(longevity-cdc-100-gb-4-h.yaml): Reduction stress duration
  test-cases/longevity/longevity-cdc-100gb-4h.yaml
Labels: Backport-4.3

#2893 fix(cluster_k8s): increase scylla readiness timeout
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed, Ready for review

#2896 fix(wait_for_pods_readiness): make it actually respect nodes count
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed, Ready for review

#2880 fix(multidc test): configure remoter with new public IP after reboot
  sdcm/cluster.py
Labels: Backport-4.3, Ready for review

#2899 fix(get_peers_info): cover case when run_cqlsh returns malformed output
  sdcm/cluster.py
Labels: No Backport Needed, Ready for review

#2898 fix(kubernetes_cmd_runner.py): rebase it from RemoteCmdRunnerBase to fix retrying issue
  sdcm/remote/kubernetes_cmd_runner.py
Labels: No Backport Needed, Ready for review

#2891 fix(StopWaitStartMonkey): on k8s it should not start scylla, but wait till s-o bring it up
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#2890 K8S: Rate limiter
  sdcm/cluster_k8s/__init__.py
  sdcm/cluster_k8s/gke.py
  sdcm/remote/kubernetes_cmd_runner.py
  sdcm/utils/k8s.py
  unit_tests/test_remoter.py
Labels: No Backport Needed, Ready for review

#2853 fix(remoter_logger): fix kubernetes logger to prevent old and new log mixing on restart
  sdcm/utils/remote_logger.py
Labels: No Backport Needed, Ready for review

#2877 fix(vars/getJobTimeouts.groovy): Fix timeouts
  vars/getJobTimeouts.groovy
Labels: Backport-4.3, Ready for review

#2810 fix(disrupt_terminate_and_replace_node): make it valid for gke
  sdcm/cluster.py
  sdcm/cluster_gce.py
  sdcm/cluster_k8s/__init__.py
  sdcm/cluster_k8s/gke.py
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#2902 fix(minikube): initialize api rate limiter
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed, Ready for review

#2905 fix(test_remoter): stop running long running tests
  unit_tests/test_remoter.py
Labels: No Backport Needed, Ready for review

#2914 test(200gb_48h): timeout too close to the stress size
  test-cases/longevity/longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml
Labels: Backport-4.3

#2878 fix(upgrade_test): use strict pattern for idx_token error
  upgrade_test.py
Labels: Backport-2020.1, Backport-4.2, Backport-4.3, Ready for review

#2901 fix(scylla-bench): Add iteration parameter to guarantees the load will run during all test
  test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml
  test-cases/longevity/longevity-large-partition-8h.yaml
Labels: Backport-2020.1, Backport-4.3, Ready for review

#2912 fix(rollout_restart): Make it wait till rollout is completed
  sdcm/cluster_k8s/__init__.py
  sdcm/utils/k8s.py
Labels: No Backport Needed, Ready for review

#2903 fix(update_scylla_config): Make it flush changes before feeding yaml file to kubectl
  sdcm/cluster_k8s/__init__.py
  sdcm/utils/k8s.py
Labels: No Backport Needed, Ready for review

#2906 fix(sdcm/utils/k8s.py): make _k8s_core_v1_api cached on KubernetesCluster
  sdcm/cluster_k8s/__init__.py
  sdcm/remote/kubernetes_cmd_runner.py
  sdcm/utils/k8s.py
Labels: Ready for review, Ready to be Merged

#2910 fix(sdcm/cluster_k8s/__init__.py): Make ip_address properties cached
  sdcm/cluster.py
  sdcm/cluster_aws.py
  sdcm/cluster_baremetal.py
  sdcm/cluster_docker.py
  sdcm/cluster_gce.py
  sdcm/cluster_k8s/__init__.py
  unit_tests/test_cluster.py
  unit_tests/test_seed_selector.py
Labels: No Backport Needed, Ready for review

#2870 fix(cluster_init): Add recommended cluster initialization with bootst…
  defaults/test_default.yaml
  docs/configuration_options.md
  sdcm/cluster.py
  sdcm/cluster_aws.py
  sdcm/cluster_gce.py
  sdcm/sct_config.py
  sdcm/tester.py
  test-cases/performance/perf-regression.100threads.30M-keys.yaml
  vars/perfRegressionParallelPipeline.groovy
Labels: Backport-perf-v8, Ready for review

#2907 Introduce CategoricalMonkey
  sdcm/nemesis.py
  unit_tests/test_nemesis.py
Labels: Backport-4.3

#2913 test(refresh_test): remove the test since it is implemented as Nemesis
  refresh_test.py
Labels: No Backport Needed

#2823 improvement(remove default from get method): Remove 'default' parameter from params.get() method
  cdc_replication_test.py
  defaults/aws_config.yaml
  defaults/gce_config.yaml
  defaults/test_default.yaml
  gemini_test.py
  grow_cluster_test.py
  longevity_large_partition_test.py
  longevity_test.py
  mgmt_cli_test.py
  mgmt_upgrade_test.py
  performance_regression_alternator_test.py
  performance_regression_row_level_repair_test.py
  performance_regression_test.py
  performance_regression_user_profiles_test.py
  sdcm/cluster.py
  sdcm/cluster_aws.py
  sdcm/cluster_gce.py
  sdcm/db_stats.py
  sdcm/gemini_thread.py
  sdcm/logcollector.py
  sdcm/nemesis.py
  sdcm/sct_config.py
  sdcm/tester.py
  sdcm/utils/common.py
  sdcm/utils/data_validator.py
  test-cases/longevity/longevity-5000-tables.yaml
  test-cases/longevity/longevity-multi-keyspaces.yaml
  unit_tests/test_config.py
  upgrade_test.py
Labels: Ready for review

#2921 fix(autossh): pin down to jnovack/autossh:1.2.2
  sdcm/utils/auto_ssh.py
Labels: Backport-2020.1, Backport-4.2, Backport-4.3, Ready for review, Urgent

#2923 fix(scylla_encryption_options): fix condition in create_table
  sdcm/tester.py
Labels: No Backport Needed, Ready for review

#2911 GKE: Fix rate limiter to work on urllib urlopen
  docker/env/version
  requirements-python.txt
  sdcm/cluster_k8s/__init__.py
  sdcm/cluster_k8s/gke.py
  sdcm/cluster_k8s/operator_monitoring.py
  sdcm/remote/kubernetes_cmd_runner.py
  sdcm/utils/k8s.py
  sdcm/utils/remote_logger.py
  unit_tests/test_remoter.py
Labels: No Backport Needed, Ready for review

#2917 fix(cluster_k8s): make kubectl config local
  sdcm/cluster_k8s/gke.py
  sdcm/tester.py
  sdcm/utils/common.py
  sdcm/utils/gce_utils.py
  sdcm/utils/k8s.py
Labels: No Backport Needed, Ready for review

#2934 fix(operator.yaml): add readiness check
  sdcm/k8s_configs/operator.yaml
Labels: No Backport Needed, Ready for review

#2933 fix(check_schema_version): cover case when node is absent in gossip_info
  sdcm/utils/health_checker.py
Labels: No Backport Needed, Ready for review

#2932 fix(get_peers_info): fix it to match only peers records
  sdcm/cluster.py
Labels: No Backport Needed, Ready for review

#2931 fix(logcollector): make loader-set pick up inactive nodes logs
  sdcm/logcollector.py
Labels: No Backport Needed, Ready for review

#2936 fix(raid-daemonset.yaml): make it deploy raid same way we do that in scylla_raid_setup
  sdcm/k8s_configs/raid-daemonset.yaml
Labels: No Backport Needed, Ready for review

#2937 fix(terminate_node): set last node as target for kubernetes case
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review
