Repository scylladb/scylla-cluster-tests, pull requests merged in 2020-01, with the labels that each got.

#1647 Fix IPv6 usage in URLs
  docker/env/version
  longevity_test.py
  refresh_test.py
  requirements-python.txt
  sdcm/cluster.py
  sdcm/db_stats.py
  sdcm/utils/common.py
Labels: Backport-2019.1, Backport-3.2, Ready to be Merged

#1648 Parameter for Cluster health check disabling/enabling
  defaults/test_default.yaml
  sdcm/cluster.py
  sdcm/sct_config.py
  test-cases/features/scale-cluster.yaml
  test-cases/longevity/longevity-5000-tables.yaml
Labels: Backport-2019.1, Backport-3.2

#1653 Search file for destroy just in table folder, not sub folders
  sdcm/nemesis.py
Labels: Backport-2019.1, Backport-3.2

#1656 Fix cassandra-stress commands calls
  sdcm/stress_thread.py
Labels: No Backport Needed, Urgent

#1659 Removed workaround code after ICS support for CS is added in enterprise-tools-java
  ics_space_amplification_test.py
  jenkins-pipelines/longevity-ics-toggle-strategy-500gb-24h.jenkinsfile
  longevity_ics_test.py
  test-cases/longevity/longevity-ics-toggle-strategy-500gb-24h.yaml
Labels: Backport-2019.1, Ready to be Merged

#1654 Added to existing test new compression usage (zstd)
  sdcm/nemesis.py
  test-cases/longevity/longevity-1TB-7days-authorization-and-tls-ssl.yaml
  test-cases/longevity/longevity-50GB-4days-authorization-and-tls-ssl.yaml
Labels: Backport-3.2, Ready for review

#1646 Config IPv6 as persistent
  sdcm/cluster_aws.py
Labels: Backport-2019.1, Backport-3.2, Ready for review

#1660 Update the configuration_options.md
  README.rst
  docs/configuration_options.md
  sct.py
Labels: No Backport Needed

#1629 Refactor rolloing-upgrade-test
  upgrade_test.py
Labels: No Backport Needed

#1662 Run IPv6 persistent script for IPv6 test only
  sdcm/cluster_aws.py
Labels: Backport-2019.1, Backport-3.2, Ready for review

#1655 Add support using scylla-cloud-image
  sdcm/cluster.py
  sdcm/cluster_aws.py
  sdcm/logcollector.py
Labels: No Backport Needed

#1641 Added RUNTIME_ERROR filter to AWSNode.restart
  sdcm/cluster_aws.py
Labels: Backport-2019.1, Backport-3.2, Ready to be Merged

#1663 Fixing DeepCode issues
  sdcm/cluster_aws.py
  sdcm/gemini_thread.py
  sdcm/sct_events.py
  sdcm/utils/common.py
Labels: No Backport Needed, Ready for review

#1664 Produce event on exception that comes from SetUp
  sdcm/sct_events.py
  sdcm/tester.py
Labels: No Backport Needed, Ready for review

#1667 Fix python3 F-string code
  sdcm/cluster_aws.py
Labels: Backport-2019.1, Backport-3.2, Urgent

#1649 Add email size validation
  sdcm/send_email.py
Labels: No Backport Needed, Ready for review

#1661 Fix to make AddDropColumn nemesis to ignore scylla-bench tables
  sdcm/nemesis.py
  test_lib/cql_types.py
Labels: No Backport Needed

#1670 Replace the current version tagging of resources
  sdcm/cluster.py
  sdcm/tester.py
Labels: Backport-2019.1, Backport-3.0, Backport-3.1, Backport-3.2, Ready to be Merged

#1652 Extend and enhance networking nemesis
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#1675 sdcm/cluster: deb: add new sign key
  sdcm/cluster.py
Labels: Backport-3.2, Ready for review

#1678 Default for instance_type_monitor changed to t3.large
  test-cases/manager/manager-regression-multiDC-set-distro.yaml
Labels: No Backport Needed, Ready for review, Ready to be Merged

#1676 sct_event: TestFrameworkEvent was casing Circular reference
  sdcm/sct_events.py
  sdcm/tester.py
  unit_tests/test_events.py
Labels: No Backport Needed

#1671 Add test-provision-gce
  Jenkinsfile
  sdcm/cluster_gce.py
  test-cases/PR-provision-test.yaml
  vars/pullRequestContainsLabels.groovy
  vars/pullRequestSetResult.groovy
Labels: Ready for review

#1674 Get screenshot and snapshot using selenium and remotewebdriver
  .pre-commit-config.yaml
  defaults/test_default.yaml
  docker/env/version
  install-prereqs.sh
  requirements-python.txt
  sdcm/auto_ssh.py
  sdcm/cluster.py
  sdcm/logcollector.py
  sdcm/utils/remotewebbrowser.py
Labels: No Backport Needed

#1620 Alert manager listener
  sdcm/cluster.py
  sdcm/prometheus.py
  sdcm/sct_events.py
  sdcm/tester.py
  unit_tests/test_data/test_prometheus/test_alert_manager_listener_artificial_run.yaml
  unit_tests/test_data/test_prometheus/test_alert_manager_listener_real_run.json
  unit_tests/test_prometheus.py
Labels: No Backport Needed, Ready for review

#1669 Enable backtrace decoding by default
  defaults/test_default.yaml
Labels: No Backport Needed

#1668 Wait for target node to be UN before waiting for hints in ValidateHintedHandoffShortDowntime
  sdcm/cluster.py
  sdcm/docker.py
  sdcm/nemesis.py
Labels: Backport-2019.1, Backport-3.2

#1687 Add daemon-reload to rollback procedure for all distros
  upgrade_test.py
Labels: Backport-2018.1, Backport-2019.1, Backport-3.0, Backport-3.1, Backport-3.2

#1690 for-3.2: fix event filter in upgrade test
  sdcm/cluster.py
  sdcm/nemesis.py
  upgrade_test.py
Labels: No Backport Needed, Urgent

#1691 upgrade: fix wait_for_sstable_upgrade
  upgrade_test.py
Labels: No Backport Needed, Ready for review, Urgent

#1686 Fix timeout on set_hostname
  sdcm/cluster_aws.py
Labels: Backport-2019.1, Backport-3.2, Ready for review

#1699 fix set_hostname: Remove single quotes from command
  sdcm/cluster_aws.py
Labels: Ready for review

#1701 fix set_hostname: Add workaround to rsyslogd problem
  sdcm/cluster_aws.py
Labels: Ready for review, Urgent

#1698 Revert part of "archive SCT logs to jenkins server (#1377)"
  vars/rollingUpgradePipeline.groovy
Labels: Backport-2019.1, Backport-3.2, Ready for review

#1697 Fix issue #1696 for correct filtering and clearing db-nodes
  sdcm/utils/common.py
Labels: Backport-2019.1, Backport-3.2

#1703 Fix rolling upgrade stage email_send failing
  vars/rollingUpgradePipeline.groovy
Labels: Backport-3.2

#1695 stop_task_threads: fix deadlock in stopping decoding thread
  sdcm/cluster.py
  sdcm/cluster_aws.py
Labels: No Backport Needed, Ready for review

#1692 Reduce severity unknown verb
  sdcm/cluster.py
Labels: Backport-2019.1, Backport-3.2, Ready for review

#1704 Fix set_hostname function
  sdcm/cluster_aws.py
Labels: Ready for review, Urgent

#1688 Remove fallback logic from AddDropColumn
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#1694 rollingUpgrade: make email_recipients configurable from jenkins
  vars/byoLongevityPipeline.groovy
  vars/longevityPipeline.groovy
  vars/rollingUpgradePipeline.groovy
Labels: No Backport Needed

#1702 Adding short email report for Upgrade tests
  sct.py
  sdcm/results_upgrade.html
  sdcm/send_email.py
  upgrade_test.py
Labels: Backport-2019.1, Backport-3.2

#1700 Fixing pullRequestContainsLabels.groovy for case when no PR associated
  Jenkinsfile
  vars/pullRequestContainsLabels.groovy
Labels: Ready for review

#1253 Added performance_regression_row_level_repair_test.py and its utils
  jenkins-pipelines/perf-row-level-repair.jenkinsfile
  longevity_large_partition_test.py
  performance_regression_row_level_repair_test.py
  sdcm/cluster.py
  sdcm/db_stats.py
  sdcm/results_analyze.py
  sdcm/tester.py
  sdcm/utils/common.py
  test-cases/performance/perf-row-level-repair-1TB.yaml
  test_lib/scylla_bench_tools.py
Labels: Backport-3.1, Ready to be Merged

#1705 Fix pullRequestContainsLabels for case when no PR associated #2
  Jenkinsfile
  vars/pullRequestContainsLabels.groovy
Labels: No Backport Needed, Ready for review

#1710 Set destroy as a default post behaviour for Cloud Longevity tests
  test-cases/longevity/longevity-100GB-48h-cloud-CloudLimitedChaosMonkey-tls.yaml
Labels: No Backport Needed

#1711 Changed SIRENADA_CLUSTER_KEEP to 50 hours to limit the time instances…
  vars/scyllaCloudLongevityPipeline.groovy
Labels: No Backport Needed

#1658 upgrade_test: check reload systemd config
  upgrade_test.py
Labels: Backport-3.2

#1683 sct_events: cleanup of log levels
  gemini_test.py
  longevity_test.py
  sdcm/cluster.py
  sdcm/logcollector.py
  sdcm/results_gemini.html
  sdcm/results_longevity.html
  sdcm/sct_events.py
  unit_tests/test_events.py
Labels: No Backport Needed, Ready for review

#1708 Fix error during hydra collect-log for monitoring
  sdcm/cluster.py
  sdcm/logcollector.py
Labels: No Backport Needed

#1712 Move aws_extra_network_interface to baseNode
  docs/configuration_options.md
  sdcm/cluster.py
  sdcm/cluster_aws.py
  sdcm/docker.py
  sdcm/nemesis.py
  sdcm/sct_config.py
  test-cases/longevity/longevity-200GB-48h-network-monkey.yaml
Labels: No Backport Needed, Ready for review

#1715 Improved the fix that fixes an sctool output string
  sdcm/mgmt.py
Labels: Backport-3.3

#1714 Move remotecmdrunner out of class initialization to __init__
  unit_tests/test_manual.py
Labels: No Backport Needed, Ready for review

#1709 Adding gemini log files to logcollector
  sdcm/cluster.py
  sdcm/gemini_thread.py
  sdcm/logcollector.py
Labels: No Backport Needed

#1716 perf-regression-user-profiles.yaml: fix wrong path to user profiles
  test-cases/performance/perf-regression-user-profiles.yaml
Labels: No Backport Needed

#1684 Added pipeline for Ubuntu 16 and 18
  jenkins-pipelines/manager/centos-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/ubuntu16-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/ubuntu18-manager-sanity.jenkinsfile
  sdcm/cluster.py
  sdcm/mgmt.py
  sdcm/sct_config.py
  sdcm/tester.py
  test-cases/longevity/longevity-2TB-4days-authorization-and-tls-ssl-1dis-2nondis-nemesis.yaml
  test-cases/manager/manager-regression-multiDC-set-distro.yaml
  vars/longevityPipeline.groovy
Labels: No Backport Needed, Ready for review

#1720 Fixing broken longevity pipeline
  vars/longevityPipeline.groovy
Labels: No Backport Needed, Urgent

#1719 rolling-upgrade: update base version to 3.2
  jenkins-pipelines/rolling-upgrade-centos7.jenkinsfile
  jenkins-pipelines/rolling-upgrade-debian9.jenkinsfile
  jenkins-pipelines/rolling-upgrade-ubuntu16.04.jenkinsfile
  jenkins-pipelines/rolling-upgrade-ubuntu18.04.jenkinsfile
Labels: No Backport Needed, Ready for review

#1721 Remove post from Jenkins file
  Jenkinsfile
  sdcm/cluster.py
Labels: No Backport Needed, test-provision

#1722 Fixed Centos job
  test-cases/manager/manager-regression-multiDC-set-distro.yaml
Labels: No Backport Needed

#1713 Move is_up into retry cycle
  sdcm/remote.py
Labels: No Backport Needed, Ready for review

#1565 Large partition new flow
  data_dir/scylla-dash-per-server-nemesis.2019.1.json
  data_dir/scylla-dash-per-server-nemesis.3.1.json
  data_dir/scylla-dash-per-server-nemesis.3.2.json
  data_dir/scylla-dash-per-server-nemesis.master.json
  jenkins-pipelines/longevity-large-partition-200k-pks-4days.jenkinsfile
  longevity_test.py
  sdcm/cluster.py
  sdcm/sct_events.py
  sdcm/tester.py
  test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml
  unit_tests/test_events.py
Labels: Backport-2019.1, Ready for review

#1724 start_scylla_server: adjust wait_db_up timeout to 500 seconds
  sdcm/cluster.py
  sdcm/docker.py
  upgrade_test.py
Labels: Backport-2019.1, Backport-3.2, Ready for review

#1728 Removed default scylla_mgmt_agent_repo from manager-regression config
  test-cases/manager/manager-regression-multiDC-set-distro.yaml
Labels: No Backport Needed

#1731 Removed one more time wrong scylla_mgmt_agent_repo
  jenkins-pipelines/manager/ubuntu16-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/ubuntu18-manager-sanity.jenkinsfile
Labels: Backport-manager

#1735 Added a flag named store_perf_results
  defaults/test_default.yaml
  sdcm/db_stats.py
  sdcm/sct_config.py
  test-cases/performance/perf-regression-2mv.yaml
  test-cases/performance/perf-regression-latency-1TB.yaml
  test-cases/performance/perf-regression-latency-500gb-30min.yaml
  test-cases/performance/perf-regression-latency-in-memory.yaml
  test-cases/performance/perf-regression-user-profiles.yaml
  test-cases/performance/perf-regression.100threads.30M-keys.yaml
  test-cases/performance/perf-row-level-repair-1TB.yaml
Labels: Backport-2019.1, Backport-3.3, Ready to be Merged

#1727 Remove scylla debug files from builders after decode backtraces finished
  sdcm/cluster.py
  unit_tests/test_decode_backtrace.py
Labels: Backport-3.3

#1738 Fix issue #1733: missing key events_summary for jinja template
  sdcm/send_email.py
Labels: Backport-3.3, Ready for review

#1732 Add tc(iproute) to hydra
  docker/env/version
  install-prereqs.sh
Labels: Backport-2019.1, Backport-3.2, Backport-3.3, Ready for review

#1737 debian9-sanity for manager
  jenkins-pipelines/manager/debian9-manager-sanity.jenkinsfile
  sdcm/cluster.py
  sdcm/cluster_aws.py
Labels: Backport-manager, Ready to be Merged

#1739 Added subtest steps to manager sanity
  mgmt_cli_test.py
Labels: Backport-manager

#1729 Replace 'hinted_handoff_disabled' param to 'hinted_handoff' in 2mv-backpressure-4d.yaml
  test-cases/features/2mv-backpressure-4d.yaml
Labels: Backport-2019.1, Backport-3.2, Backport-3.3, Ready for review

#1723 Added gemini command with ics
  jenkins-pipelines/gemini-3h-ics-nondisruptive-nemesis.jenkinsfile
  jenkins-pipelines/gemini-3h-ics.jenkinsfile
  test-cases/gemini/gemini-3h-ics-with-nondisruptive-nemesis.yaml
  test-cases/gemini/gemini-basic-3h-ics.yaml
Labels: Backport-2019.1, Ready for review

#1736 [branch-2019.1] Large partition new flow
  data_dir/scylla-dash-per-server-nemesis.2019.1.json
  jenkins-pipelines/longevity-large-partition-200k-pks-4days.jenkinsfile
  longevity_test.py
  sdcm/cluster.py
  sdcm/sct_events.py
  sdcm/tester.py
  test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml
  unit_tests/test_events.py
Labels: No Backport Needed

#1742 Fix issue #1741
  sdcm/cluster.py
Labels: Backport-manager, Ready to be Merged, Urgent

#1744 Fix failing test_parallelobject.py
  unit_tests/test_parallelobject.py
Labels: No Backport Needed

#1693 Fix failing tests
  sdcm/sct_events.py
  sdcm/utils/common.py
  unit_tests/test_events.py
  unit_tests/test_manual.py
Labels: No Backport Needed

#1746 Fixed manager ubuntu16-sanity
  sdcm/cluster.py
Labels: Backport-manager

#1747 Fix container name when run multiDC test with IPv6
  sdcm/auto_ssh.py
Labels: Backport-2019.1, Backport-3.2, Backport-3.3, Ready to be Merged

#1745 Changed code to support ipv6 on manager sanity
  jenkins-pipelines/manager/centos-manager-sanity-ipv6.jenkinsfile
  mgmt_cli_test.py
  sdcm/mgmt.py
  test-cases/manager/manager-regression-ipv6.yaml
Labels: Backport-manager, Ready to be Merged

#1752 Remove duplicated string '-autossh' from container name
  sdcm/auto_ssh.py
Labels: Ready for review

#1750 [branch-2019.1] Fix container name when run multiDC test with IPv6
  sdcm/auto_ssh.py
Labels: Ready for review

#1753 feature(alternator): make dashboards support alternator
  data_dir/scylla-dash-per-server-nemesis.master.json
  jenkins-pipelines/longevity-alternator-3h.jenkinsfile
  sdcm/cluster.py
  sdcm/logcollector.py
Labels: No Backport Needed, Ready for review

#1718 feat(pre-commit-hook): adding commitlint support
  .pre-commit-config.yaml
  Jenkinsfile
  README.rst
  commitlint.config.js
  install-prereqs.sh
Labels: No Backport Needed

#1740 Add new_session to remoter
  sdcm/cluster.py
  sdcm/remote.py
Labels: No Backport Needed, Ready for review

#1749 Hide StartupTestEvent from logs
  sdcm/sct_events.py
Labels: No Backport Needed

#1758 feature(cloud_monitor): separating QA instances from others
  sdcm/keystore.py
  sdcm/utils/cloud_monitor/cloud_monitor.py
  sdcm/utils/cloud_monitor/report.py
  sdcm/utils/cloud_monitor/templates/cloud_resources.html
  sdcm/utils/cloud_monitor/templates/per_user_summary.html
Labels: No Backport Needed, Ready for review

#1751 [branch-3.2] Fix container name when run multiDC test with IPv6
  sdcm/auto_ssh.py
Labels: Ready for review

#1759 fix(gemini oracle db ami): ami id from wrong region
  test-cases/gemini/gemini-basic-3h.yaml
Labels: Backport-3.3
