Repository scylladb/scylla-cluster-tests, pull requests merged in 2020-10, with the labels that each got.

#2740 fix(rolling upgrade): increase test_duration to 250m
  test-cases/upgrades/rolling-upgrade.yaml
Labels: No Backport Needed, Ready for review

#2738 fix(hydra): clean know hosts when running on SCT Runner
  docker/env/hydra.sh
Labels: Backport-4.2

#2742 fix(vars/perfRegressionParallelPipeline.groovy): fix provision_type to on_demand
  vars/perfRegressionParallelPipeline.groovy
Labels: No Backport Needed, Ready for review

#2749 fix(perf-regression-latency-30min.jenkinsfile): increase timeout
  jenkins-pipelines/perf-regression-latency-30min.jenkinsfile
Labels: No Backport Needed, Ready for review

#2750 Fix longevity lwt timeout
  test-cases/longevity/longevity-lwt-basic-3h.yaml
Labels: No Backport Needed, Ready for review

#2757 fix(sdcm/cluster.py): fix reference before assigment in get_grafana_screenshot_and_snapshot
  sdcm/cluster.py
Labels: No Backport Needed, Ready for review

#2758 fix(wait_for_init): Reverting the change to control wait for db_up
  sdcm/cluster.py
  sdcm/cluster_aws.py
  sdcm/cluster_baremetal.py
  sdcm/cluster_docker.py
  sdcm/nemesis.py
Labels: Backport-4.2, Urgent

#2729 test(upgrade_test.py): implement kubernetes scylla upgrade test
  jenkins-pipelines/upgrade-scylla-k8s-minikube.jenkinsfile
  sdcm/cluster.py
  sdcm/cluster_k8s/__init__.py
  sdcm/fill_db_data.py
  sdcm/utils/version_utils.py
  test-cases/scylla-operator/kubernetes-scylla-upgrade.yaml
  upgrade_test.py
Labels: No Backport Needed, Ready for review

#2754 improvement(cluster_k8s): limited support for append_scylla_yaml
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed, Ready for review

#2753 refactor(remote): get rid of unconventional ternary operators
  sdcm/cluster.py
  sdcm/cluster_k8s/__init__.py
  sdcm/remote/__init__.py
  sdcm/remote/base.py
  sdcm/remote/remote_file.py
  unit_tests/test_remoter.py
Labels: No Backport Needed, Ready for review

#2760 fix(operator): remove default operator version from jobs
  vars/byoOperatorPipeline.groovy
  vars/operatorPipeline.groovy
Labels: No Backport Needed, Ready for review

#2762 fix(req python packages): update python packages for awscli and boto3
  docker/env/version
  requirements-python.txt
Labels: New Hydra Version

#2731 Make nemesis restartable
  corrupt_then_rebuild_test.py
  destroy_data_then_repair_test.py
  grow_cluster_test.py
  longevity_lwt_test.py
  mgmt_cli_test.py
  sdcm/cluster.py
  sdcm/nemesis.py
Labels: No Backport Needed

#2763 fix(stop_scylla_server): Added workaround for stop scylla server
  sdcm/cluster.py
  sdcm/nemesis.py
Labels: Backport-4.2, Ready for review

#2768 fix(loaders): fix c-s issue with ssl certificates
  defaults/aws_config.yaml
Labels: No Backport Needed, Ready for review

#2764 feature(monitoring): switch to branch-3.5
  defaults/test_default.yaml
Labels: Backport-manager-v2.2

#2771 fix(is_streaming_started): timeout to wait streaming started increased
  sdcm/nemesis.py
Labels: Backport-4.2, Ready for review

#2774 improvement(increase fd limit): Increase limit of open FDs on SCT runners
  sdcm/sct_runner.py
Labels: Backport-4.2, Ready for review

#2638 feature(remote_file): add ability to preserve permissions and ownership
  sdcm/remote/remote_file.py
  unit_tests/test_remoter.py
Labels: No Backport Needed

#2773 fix(scylla_setup): pass '--setup-nic-and-disks' to scylla_setup
  sdcm/cluster.py
Labels: Backport-2020.1, Backport-4.1, Backport-4.2

#2752 improvement(config_setup): set FinalKillSignal to SIGABRT
  sdcm/cluster.py
  sdcm/utils/version_utils.py
Labels: No Backport Needed, Ready for review

#2769 refactor(runSctTest): simplify 'params.x is null or empty string' case
  vars/artifactsPipeline.groovy
  vars/cdcReplicationPipeline.groovy
  vars/managerPipeline.groovy
  vars/perfRegressionParallelPipeline.groovy
  vars/rollingUpgradePipeline.groovy
  vars/runSctTest.groovy
Labels: No Backport Needed, Ready for review

#2751 fix(longevity-alternator-3h.yaml): Add timeout to ycsb
  test-cases/longevity/longevity-alternator-3h.yaml
Labels: No Backport Needed, Ready for review

#2778 fix(artifacts): remove redundant closing parenthesis in .groovy
  vars/artifactsPipeline.groovy
Labels: No Backport Needed, Ready for review, Urgent

#2772 fix(5000 tables test): increase nemesis interval
  test-cases/longevity/longevity-5000-tables.yaml
Labels: Backport-4.2

#2784 fix(nemesis): to recognize gke as kubernetes
  sdcm/nemesis.py
Labels: Backport-2020.1, Ready for review

#2786 fix(operator): make user_prefix shorter for GKE
  test-cases/scylla-operator/kubernetes-scylla-upgrade-gke.yaml
  test-cases/scylla-operator/kubernetes-scylla-upgrade-minikube.yaml
  test-cases/scylla-operator/longevity-scylla-operator-3h-gke.yaml
  test-cases/scylla-operator/longevity-scylla-operator-3h-minikube.yaml
Labels: No Backport Needed, Ready for review

#2788 fix(cluster_k8s): increase waiting timeout
  sdcm/cluster_k8s/__init__.py
Labels: Backport-2020.1, Ready for review

#2789 fix(hydra): bump paramiko version to 2.7.2
  docker/env/version
  requirements-python.txt
Labels: New Hydra Version, No Backport Needed

#2791 improvement(operator): bump cert-manager version to 1.0.3
  defaults/k8s_gce_minikube_config.yaml
  defaults/k8s_gke_config.yaml
  sdcm/k8s_configs/operator.yaml
Labels: No Backport Needed, Ready for review

#2792 effecient YCSB requires explicitly stating connections number
  test-cases/longevity/longevity-ycsb-a-10M.yaml
  test-cases/longevity/longevity-ycsb-a-1B.yaml
  test-cases/longevity/longevity-ycsb-a-1M.yaml
Labels: No Backport Needed

#2794 fix(get_branched_ami): split by first colon only
  sct.py
  sdcm/utils/common.py
Labels: Backport-2020.1, Backport-4.1, Backport-4.2, Ready for review

#2783 test(manager): tests for intensity and parallel repair options
  jenkins-pipelines/manager/centos-manager-repair-intensity-multiple-repaired-nodes.jenkinsfile
  jenkins-pipelines/manager/centos-manager-repair-intensity-single-repaired-nodes.jenkinsfile
  mgmt_cli_test.py
  sdcm/mgmt.py
  test-cases/manager/manager-repair-intensity-multiple-repaired-nodes.yaml
  test-cases/manager/manager-repair-intensity-single-repaired-nodes.yaml
Labels: Backport-manager-v2.2

#2801 fix(nemesis): does not recognize gke as kubernetes
  sdcm/nemesis.py
  unit_tests/test_nemesis.py
Labels: No Backport Needed, Ready for review

#2803 fix(manager): turned the throttle value into int
  mgmt_cli_test.py
Labels: Backport-manager-v2.2

#2795 fix(prepare_region): Added Prometheus Alert Manager port
  sdcm/utils/prepare_region.py
Labels: No Backport Needed

#2797 fix(kubernetes_cmd_runner): make it threadsafe
  sdcm/remote/kubernetes_cmd_runner.py
  unit_tests/test_remoter.py
Labels: No Backport Needed, Ready for review

#2782 fix(ssh2-python): replace ssh2-python
  docker/env/version
  requirements-python.txt
Labels: No Backport Needed, Ready for review

#2802 fix(grafana_snapsho): fix dom selector for monitoring 3.5
  sdcm/logcollector.py
Labels: No Backport Needed, Ready for review

#2733 [branch-4.2] fix(coredump thread): Coredump thread should not retry forever on exception
  sdcm/cluster.py
  unit_tests/dummy_remote.py
  unit_tests/test_decode_backtrace.py
Labels: Backport-2020.1, Ready for review

#2804 improvement(unit_tests): speed up update_db_packages tests
  sdcm/utils/common.py
  unit_tests/test_utils_common.py
Labels: No Backport Needed, Ready for review

#2809 fix(disrupt_nodetool_enospc): fix to work on kubernetes, except minikube
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#2806 fix(disrupt_nodetool_decommission): Make it work on kubernetes all the times
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#2811 fix(disrupt_nodetool_enospc): raise UnsupportedNemesis instead of logging
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#2814 fix(artifact_tests): set gce_image_db
  test-cases/artifacts/centos7.yaml
  test-cases/artifacts/centos8.yaml
  test-cases/artifacts/debian10.yaml
  test-cases/artifacts/debian9.yaml
  test-cases/artifacts/rhel7.yaml
  test-cases/artifacts/rhel8.yaml
  test-cases/artifacts/ubuntu1604.yaml
  test-cases/artifacts/ubuntu1804.yaml
Labels: No Backport Needed, Ready for review
