Repository scylladb/scylla-cluster-tests, pull requests merged in 2020-03, with the labels that each got.

#1881 fix(sct_events): race condition in EventsDevice
  sdcm/sct_events.py
Labels: Backport-2019.1, Backport-3.2, Backport-3.3, Ready for review

#1869 test(private repo): migrate private repo tests from scylla-artifact-tests
  .pre-commit-config.yaml
  docker/env/version
  docs/artifacts_test.md
  jenkins-pipelines/private-repo.jenkinsfile
  private_repo_test.py
  requirements-python.txt
  sct.py
  sdcm/keystore.py
  sdcm/results_private_repo.html
  sdcm/sct_config.py
  sdcm/send_email.py
  sdcm/tester.py
  sdcm/utils/housekeeping.py
  test-cases/private-repo/private-repo.yaml
Labels: No Backport Needed, Ready for review

#1885 [branch-3.3] improvement(artifacts test): improve email report
  artifacts_test.py
  sdcm/results_artifacts.html
  sdcm/send_email.py
Labels: Ready for review

#1887 fix(artifacts test): provide default region_name for OEL test
  jenkins-pipelines/artifacts-oel76.jenkinsfile
  vars/artifactsPipeline.groovy
Labels: Backport-3.3, Ready for review

#1855 fix(sdcm/docker.py): fix docker and non-docker teardown proceedure
  Jenkinsfile
  defaults/docker_config.yaml
  sdcm/cluster.py
  sdcm/cluster_docker.py
  sdcm/logcollector.py
  sdcm/remote.py
  sdcm/sct_config.py
  sdcm/stress_thread.py
  sdcm/tester.py
  sdcm/utils/docker.py
  test-cases/PR-provision-test-docker.yaml
  test-cases/PR-provision-test.yaml
  unit_tests/dummy_remote.py
Labels: No Backport Needed

#1884 fix(artifact-test): disable changing rf of system_auth
  sdcm/sct_config.py
  sdcm/tester.py
  test-cases/artifacts/ami.yaml
  test-cases/artifacts/centos7.yaml
  test-cases/artifacts/centos8.yaml
  test-cases/artifacts/debian10.yaml
  test-cases/artifacts/debian9.yaml
  test-cases/artifacts/docker.yaml
  test-cases/artifacts/oel76.yaml
  test-cases/artifacts/rhel7.yaml
  test-cases/artifacts/rhel8.yaml
  test-cases/artifacts/ubuntu1604.yaml
  test-cases/artifacts/ubuntu1804.yaml
Labels: Backport-3.3, Ready for review

#1890 fix(artifacts test): increase timeout for OEL job
  jenkins-pipelines/artifacts-oel76.jenkinsfile
Labels: Backport-3.3, Ready for review

#1836 improvement(perfreport): Adding data with comparision for latest commit
  sdcm/results_analyze.py
  sdcm/results_performance.html
Labels: Backport-3.3, Ready for review

#1894 feature(ndbench): adding a test case and a pipeline
  jenkins-pipelines/longevity-ndbench-100gb-4h.jenkinsfile
  sdcm/ndbench_thread.py
  test-cases/longevity/longevity-ndbench-100gb-4h.yaml
  unit_tests/test_ndbench_thread.py
Labels: No Backport Needed, Ready for review

#1891 fix(results_analyze): few fixes for baseline based analyzer
  sdcm/results_analyze.py
  sdcm/results_performance_baseline.html
Labels: No Backport Needed, Ready for review

#1896 improvement(test-result): support subtests
  sdcm/tester.py
  unit_tests/test_events.py
Labels: Backport-3.3

#1899 fix(performance_subtype): Minor fixes for performance test with sub_type
  sdcm/results_analyze.py
  sdcm/results_base.html
  sdcm/results_performance_baseline.html
Labels: No Backport Needed

#1861 feature(hydra): push/pull docker images from dockerhub
  README.rst
  docker/env/build_n_push.sh
  docker/env/hydra.sh
Labels: No Backport Needed, Ready for review

#1898 refactor(email): generalize getting email data
  artifacts_test.py
  gemini_test.py
  longevity_test.py
  private_repo_test.py
  sdcm/send_email.py
  sdcm/tester.py
  upgrade_test.py
Labels: No Backport Needed, Ready for review

#1848 fix(scylla issue #5624): db,view: fix checking for secondary index special columns
  sdcm/fill_db_data.py
  sdcm/sct_events.py
  upgrade_test.py
Labels: Backport-3.2, Backport-3.3, Ready for review

#1888 feature(event_analyzer): stopping the test on critical event
  docs/sct-events.md
  sdcm/cluster.py
  sdcm/ndbench_thread.py
  sdcm/sct_events.py
  sdcm/sct_events_analyzer.py
  sdcm/stress_thread.py
  sdcm/tester.py
  sdcm/utils/common.py
  sdcm/ycsb_thread.py
  unit_tests/test_events.py
  unit_tests/test_ycsb_thread.py
Labels: No Backport Needed, Ready for review

#1906 fix(longevity-200gb-48h-network-monkey.yaml): decrease stress duration
  test-cases/longevity/longevity-200GB-48h-network-monkey.yaml
Labels: Backport-3.3

#1901 improvement(aws_config.yaml): change loader type, disk and swap size
  defaults/aws_config.yaml
  docs/configuration_options.md
  sdcm/sct_config.py
  sdcm/tester.py
  test-cases/longevity/longevity-1TB-7days-authorization-and-tls-ssl.yaml
Labels: Backport-3.3

#1904 fix(longevity reporting): add last N events
  sdcm/results_longevity.html
  sdcm/sct_config.py
  sdcm/sct_events.py
  sdcm/send_email.py
  sdcm/tester.py
Labels: No Backport Needed, Ready for review

#1911 fix(artifacts test): make docker job run on master branch
  docs/artifacts_test.md
  sdcm/sct_config.py
  unit_tests/test_config.py
Labels: No Backport Needed, Ready for review

#1916 Fix issue with having more than 5 events
  sdcm/send_email.py
Labels: No Backport Needed, Ready for review

#1909 fix(events-severity): classify ClusterHealthValidatorEvent, CoreDumpE…
  sdcm/sct_events.py
Labels: No Backport Needed

#1834 test(cdc longevity): add longevity test for cdc
  data_dir/cdc_profile.yaml
  data_dir/cdc_profile_preimage.yaml
  jenkins-pipelines/longevity-cdc-4h.jenkinsfile
  test-cases/longevity/longevity-cdc-100gb-4h.yaml
Labels: Backport-3.3, Ready for review

#1913 fix(driver_version): Increase cassandra python version
  docker/env/version
  requirements-python.txt
Labels: No Backport Needed, Ready for review

#1918 fix(docker): check for aio_max_nr after SSH is up
  sdcm/cluster_docker.py
Labels: No Backport Needed, Ready for review

#1917 improvement(build-n-push): added more verbosity and docker login
  README.rst
  docker/env/build_n_push.sh
Labels: No Backport Needed

#1912 improvement(run_nodetool): Add timeout and coredump generation
  sdcm/cluster.py
  sdcm/nemesis.py
  upgrade_test.py
Labels: Backport-3.3, Ready for review

#1920 fix(drain nemesis): remove check_cluster_health() call
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#1921 improvement(dashboards): add WARNING filter
  data_dir/scylla-dash-per-server-nemesis.2.3.json
  data_dir/scylla-dash-per-server-nemesis.2018.1.json
  data_dir/scylla-dash-per-server-nemesis.2019.1.json
  data_dir/scylla-dash-per-server-nemesis.3.0.json
  data_dir/scylla-dash-per-server-nemesis.3.1.json
  data_dir/scylla-dash-per-server-nemesis.3.2.json
  data_dir/scylla-dash-per-server-nemesis.3.3.json
  data_dir/scylla-dash-per-server-nemesis.master.json
Labels: Backport-2.3, Backport-2018.1, Backport-2019.1, Backport-3.0, Backport-3.1, Backport-3.2, Backport-3.3, Ready for review

#1922 feature(test_defaults): advance monitor_branch to use branch-3.2
  defaults/test_default.yaml
Labels: Backport-3.3

#1926 fix(loader ami for lwt test): copy dedicated loader AMI to other regions
  test-cases/longevity/longevity-lwt-basic-3h.yaml
Labels: No Backport Needed, Ready for review

#1927 fix(loader ami for lwt test): dedicated loader ami for us-west-2
  test-cases/longevity/longevity-lwt-basic-3h.yaml
Labels: No Backport Needed, Ready for review

#1919 fix(parallel nemesis): disable cluster_health_check
  test-cases/longevity/longevity-2TB-4days-authorization-and-tls-ssl-1dis-2nondis-nemesis.yaml
Labels: Backport-2019.1, Backport-3.2, Backport-3.3, Ready for review

#1924 Fix(nemesis): Change Networking nemesis to be 'Disruptive' as they sh…
  sdcm/nemesis.py
Labels: Backport-3.3

#1929 improvement(manager backup): restore procedure changes
  mgmt_cli_test.py
  sdcm/mgmt.py
Labels: No Backport Needed

#1933 fix(support region_data in test yaml): add possibilty to change any of region_data values for one test
  sdcm/sct_config.py
  test-cases/longevity/longevity-lwt-basic-3h.yaml
Labels: No Backport Needed, Urgent

#1910 fix(large-collections): limit list items number
  data_dir/large_collections.yaml
  test-cases/longevity/longevity-large-collections-12h.yaml
Labels: Backport-3.3, Ready for review

#1936 improvement(test_default): Extend scylla_args with new flag enable-sstable-key-validation
  defaults/test_default.yaml
Labels: Backport-2019.1, Backport-3.3

#1938 fix(sct_config): Adding append_scylla_setup_args to config
  docs/configuration_options.md
  sdcm/sct_config.py
Labels: Backport-3.3, Ready for review, Urgent

#1932 fix(hydra): bump invoke and docker-py versions
  docker/env/version
  requirements-python.txt
Labels: No Backport Needed, Ready for review

#1940 test(longevity-5000-tables): Add ChaosMonkey as nemesis to longevity …
  test-cases/longevity/longevity-5000-tables.yaml
Labels: No Backport Needed

#1930 fix(docker): add retry to check_aio_max_nr()
  sdcm/remote.py
Labels: No Backport Needed, Ready for review

#1931 fix(tester.py): move failure logic based on events to one place
  sdcm/tester.py
Labels: No Backport Needed

#1945 test(ycsb unittest): disable flaky docker based integration test
  unit_tests/test_ycsb_thread.py
Labels: No Backport Needed, Ready for review

#1944 fix(hydra): downgrade invoke version to 1.3.1
  docker/env/version
  requirements-python.txt
Labels: No Backport Needed, Ready for review

#1947 fix(cqlsh run): increase connect-timeout for cqlsh command
  sdcm/cluster.py
Labels: Backport-2019.1, Backport-3.1, Backport-3.2, Backport-3.3, Ready for review

#1928 Fix issue with multiline erros and move last n reports to base report class
  sdcm/report_templates/results_artifacts.html
  sdcm/report_templates/results_base.html
  sdcm/report_templates/results_base_custom.html
  sdcm/report_templates/results_gemini.html
  sdcm/report_templates/results_longevity.html
  sdcm/report_templates/results_microbenchmark.html
  sdcm/report_templates/results_performance.html
  sdcm/report_templates/results_performance_baseline.html
  sdcm/report_templates/results_private_repo.html
  sdcm/report_templates/results_upgrade.html
  sdcm/results_analyze.py
  sdcm/results_artifacts.html
  sdcm/results_private_repo.html
  sdcm/results_upgrade.html
  sdcm/sct_events.py
  sdcm/send_email.py
  sdcm/tester.py
  unit_tests/test_data/test_send_email/LongevityEmailReporter/big_report.zip
  unit_tests/test_events.py
Labels: No Backport Needed, Ready for review

#1949 fix(manager agent installation): changed installation
  sdcm/cluster.py
  sdcm/tester.py
Labels: Backport-3.3

#1946 feature(cluster_aws): read user_data_format_version from AMI tags
  sdcm/cluster_aws.py
Labels: No Backport Needed, Ready for review

#1954 fix(tester_setup): Return loader init to Setup
  sdcm/tester.py
Labels: Backport-3.3, Urgent

#1955 fix(mgr backup workaround): because of mermaid issue #1794
  sdcm/mgmt.py
Labels: Backport-3.3

#1950 fix(gemini_config): Fix gemini command to decrease false positives
  test-cases/gemini/gemini-1tb-10h.yaml
  test-cases/gemini/gemini-3h-ics-with-nondisruptive-nemesis.yaml
  test-cases/gemini/gemini-3h-with-nemesis.yaml
  test-cases/gemini/gemini-3h-with-nondisruptive-nemesis.yaml
  test-cases/gemini/gemini-basic-3h-ics.yaml
  test-cases/gemini/gemini-basic-3h.yaml
Labels: Backport-3.2, Backport-3.3, Ready for review

#1952 fix(config_setup): stop using regex to replace variables in scylla.yml
  sdcm/cluster.py
Labels: No Backport Needed

#1953 fix(mgr_cli_test): load must finish before other mgr actions
  mgmt_cli_test.py
Labels: Backport-4.0, Backport-manager

#1951 fix(scylla-bench): make sure output is saved to log
  sdcm/cluster.py
  sdcm/ndbench_thread.py
  sdcm/stress_thread.py
  sdcm/utils/thread.py
  sdcm/ycsb_thread.py
Labels: No Backport Needed

#1941 fix(gemini_version): Fix gemini version for email report
  gemini_test.py
  sdcm/cluster.py
  sdcm/utils/version_utils.py
Labels: Backport-3.3, Backport-4.0, Ready for review

#1964 fix(backup nemesis timeout): increasing backup timeout
  sdcm/nemesis.py
Labels: Backport-3.3, Backport-4.0, Backport-manager

#1963 fix(config_setup): listen_address wrongly configured in multi-dc
  sdcm/cluster.py
Labels: Backport-4.0, Backport-manager

#1958 improvement(remoter): making socket time out retriable
  sdcm/remote.py
Labels: Backport-3.2, Backport-3.3, Backport-4.0, Backport-manager

#1962 fix(nemesis_interval): Init nemesis interval in one place
  gemini_test.py
  grow_cluster_test.py
  longevity_test.py
  sdcm/cluster.py
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#1942 fix(logcollector): Change log levels for messages
  sdcm/logcollector.py
Labels: Backport-3.3

#1967 fix(sdcm/send_email.py): Increasing event message body limit
  sdcm/send_email.py
Labels: No Backport Needed, Ready for review

#1969 fix(artifacts pipeline): remove disableConcurrentBuilds()
  vars/artifactsPipeline.groovy
Labels: Backport-4.0, Ready for review

#1973 fix(gemini-10h): Changed the timeout of gemini-10h
  jenkins-pipelines/gemini-1tb-10h.jenkinsfile
Labels: No Backport Needed

#1957 feature(build_branch_jobs): script to build all the pipeline jobs in …
  README.rst
  docker/env/build_n_push.sh
  docker/env/hydra.sh
  docker/env/version
  requirements-python.txt
  sct.py
  utils/build_system/create_test_release_jobs.py
  utils/build_system/folder-template.xml
  utils/build_system/template.xml
Labels: No Backport Needed

#1974 fix(create-test-release-jobs): fix command to not use underscores
  README.rst
  sct.py
Labels: No Backport Needed, Ready for review

#1477 introduced StreamingError nemesis
  sdcm/nemesis.py
Labels: Backport-2019.1, Backport-3.2, Backport-3.3, Backport-4.0

#1975 fix(semaphore timed out severity): change severity of semaphore_timed_out event to WARNING
  sdcm/cluster.py
Labels: Backport-4.0

#1965 fix(backup nemesis timeout): increasing backup timeout
  sdcm/nemesis.py
Labels: No Backport Needed

#1937 improvement(longevity_test): configurable sstable size
  defaults/test_default.yaml
  longevity_test.py
  sdcm/sct_config.py
  sdcm/tester.py
  test-cases/longevity/longevity-100gb-4h.yaml
Labels: Backport-2019.1

#1976 fix(database_error_events): change CQL_SERVER_CONN_SYSTEM_ERROR to BR…
  sdcm/cluster.py
Labels: Backport-3.3, Backport-4.0, Ready for review

#1981 fix(backup nemesis): adjust to changes in original commit
  sdcm/mgmt.py
  sdcm/nemesis.py
Labels: No Backport Needed

#1988 fix(docker artifacts): running supervisorctl as root
  sdcm/cluster_docker.py
Labels: Backport-3.3, Backport-4.0
