Repository scylladb/scylla-cluster-tests, pull requests merged in 2020-09, with the labels that each got.

#2553 fix(tester.py): Disabling set_system_auth_rf function for Siren cloud
  sdcm/tester.py
Labels: No Backport Needed

#2575 Enable stop start
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#2577 revert(instance_type): revert #2566 for the performance cases
  test-cases/performance/perf-regression-alternator-latency-500gb-30min.yaml
  test-cases/performance/perf-regression-alternator.100threads.30M-keys.yaml
  test-cases/performance/perf-regression-latency-1TB.yaml
  test-cases/performance/perf-regression-latency-250gb-with-nemesis.yaml
  test-cases/performance/perf-regression-latency-500gb-30min.yaml
  test-cases/performance/perf-regression-latency-lwt-big.yaml
  test-cases/performance/perf-regression-latency-lwt-small.yaml
  test-cases/performance/perf-regression-throughput-cdc-mixed-poll-batching.yaml
  test-cases/performance/perf-regression-throughput-lwt-big.yaml
  test-cases/performance/perf-regression-throughput-lwt-small.yaml
  test-cases/performance/perf-regression-write-latency-cdc.yaml
  test-cases/performance/perf-regression-write-throughput-cdc.yaml
  test-cases/performance/perf-regression.100threads.30M-keys.yaml
  test-cases/performance/perf-row-level-repair-1TB.yaml
Labels: Backport-2020.1, Backport-4.2, Ready for review

#2583 fix(sdcm/nemesis.py): enable DrainerMonkey for kube
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#2585 improvement(cluster): add retry for distro property
  sdcm/cluster.py
Labels: No Backport Needed, Ready for review

#2578 fix(sdcm/nemesis.py): enable StopWaitStartMonkey
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#2576 Set multi-dc jobs to use server encryption (internode_encryption)
  test-cases/longevity/longevity-counters-multidc.yaml
  test-cases/longevity/longevity-lwt-24h-multidc.yaml
Labels: Backport-4.2

#2584 fix(sdcm/nemesis): enable CorruptThenRepairMonkey for kube
  sdcm/cluster.py
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#2593 fix(manager): changed the default manager in manager tests to 2.1
  jenkins-pipelines/manager/debian9-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu16-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu18-manager-upgrade.jenkinsfile
  test-cases/upgrades/manager-upgrade.yaml
Labels: No Backport Needed

#2599 fix(sdcm/nemesis): enable ModifyTableMonkey for kube
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#2596 fix(sdcm/nemesis): enable TruncateLargeParititionMonkey and TruncateMonkey for kube
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#2598 manager pipeline: set default value for SCT jobs
  jenkins-pipelines/manager-backup.jenkinsfile
  jenkins-pipelines/manager/centos-manager-sanity-ipv6.jenkinsfile
  jenkins-pipelines/manager/centos-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/debian9-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/debian9-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu16-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/ubuntu16-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu18-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/ubuntu18-manager-upgrade.jenkinsfile
  vars/managerPipeline.groovy
Labels: No Backport Needed

#2601 feature(scylla-bench): support not stopping a test when the tool failed
  sdcm/cluster.py
  sdcm/tester.py
Labels: Backport-2020.1, Backport-4.2

#2603 fix(whitespaces): manager pipeline: set default value for SCT job
  jenkins-pipelines/manager/centos-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/debian9-manager-upgrade.jenkinsfile
Labels: No Backport Needed

#2604 fix(manager): missing comma in ubuntu18-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/ubuntu18-manager-sanity.jenkinsfile
Labels: No Backport Needed

#2606 fix(is_manager_agent_up): ipv6 support
  sdcm/cluster.py
Labels: Backport-manager-v2.2, Ready for review

#2609 refactor(manger-upgrade): add defaults targets repos
  jenkins-pipelines/manager/centos-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/debian9-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu16-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu18-manager-upgrade.jenkinsfile
  vars/managerPipeline.groovy
Labels: No Backport Needed, Ready for review

#2610 Enable AbortRepairMonkey for kube
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#2595 improvement(GeminiLogEvent): parse logs using json.loads() instead of regex
  sdcm/gemini_thread.py
  sdcm/sct_events.py
Labels: No Backport Needed, Ready for review

#2607 refactor(ycsb-install): remove ycsb installation from docker
  sdcm/cluster.py
Labels: No Backport Needed

#2546 fix(recognize resharding): recognize resharding in case it was finished before Scylla init completed
  sdcm/cluster.py
Labels: Backport-4.2, Ready for review

#2588 fix(sdcm/nemesis.py): enable ScyllaKillMonkey and MajorCompactionMonkey for kube
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#2613 test(enable nemesis for kubernetes): Enable nemesises for kubernetes
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#2600 fix(sdcm/nemesis): enable AddDropColumnMonkey for kube
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#2597 fix(sdcm/nemesis): enable DeleteByPartitionsMonkey and DeleteByRowsRangeMonkey for kube
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#2589 fix(sdcm/nemesis.py): enable NoCorruptRepairMonkey for kube
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#2592 fix(sdcm/nemesis.py): enable NodeToolCleanupMonkey for kube
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#2587 fix(sdcm/nemesis.py): enable CorruptThenRebuildMonkey for kude
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#2494 Improve timeout handling
  sct.py
  sdcm/sct_config.py
  sdcm/sct_events.py
  sdcm/sct_events_analyzer.py
  sdcm/tester.py
  test-cases/PR-provision-test-docker.yaml
  test-cases/PR-provision-test.yaml
  test-cases/load/admission_control_overload_test.yaml
  test-cases/longevity/longevity-10gb-3h.yaml
  unit_tests/test_cluster.py
  unit_tests/test_decode_backtrace.py
  unit_tests/test_events.py
  vars/getJobTimeouts.groovy
  vars/longevityPipeline.groovy
Labels: No Backport Needed, Ready for review, test-provision-gce

#2616 fix(sdcm/nemesis): enable NodeRestartWithResharding for kube
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#2590 feature(sdcm.utils.common): `find_scylla_repo()` for branch version
  sdcm/sct_config.py
  sdcm/utils/common.py
  unit_tests/test_config.py
Labels: No Backport Needed

#2617 fix(manager-timeouts): manager test-cases missing `test_duration`
  jenkins-pipelines/manager-backup.jenkinsfile
  jenkins-pipelines/manager-sanity.jenkinsfile
  test-cases/manager/manager-regression-ipv6.yaml
  test-cases/manager/manager-regression-multiDC-set-distro.yaml
  test-cases/upgrades/manager-upgrade.yaml
Labels: Backport-manager-v2.2, Ready for review

#2615 improvement(logcollector): check archives before transfers
  sdcm/cluster.py
  sdcm/logcollector.py
  sdcm/tester.py
Labels: No Backport Needed, Ready for review

#2619 fix(replacement node with public): replacement node procedure fix when ip_ssh_connections is public
  sdcm/cluster_aws.py
Labels: No Backport Needed

#2602 fix(sdcm/nemesis): enable ToggleTableIcsMonkey for kube
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#2628 fix(operator-pipeline): fix timeout
  jenkins-pipelines/longevity-scylla-operator-3h.jenkinsfile
Labels: No Backport Needed, Ready for review

#2625 fix(sdcm/nemesis): enable HardRebootNodeMonkey for kube
  sdcm/cluster.py
  sdcm/cluster_k8s.py
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#2629 Fix operator loggging
  sdcm/cluster_k8s.py
  sdcm/utils/remote_logger.py
Labels: No Backport Needed, Ready for review

#2630 fix(nemesis): fix disrupt_nodetool_refresh failing when chaosmonkey invokes it
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#2620 feature(snapshot multiple tables): extend disrupt_snapshot_operations nemesis
  sdcm/cluster.py
  sdcm/nemesis.py
Labels: Backport-4.2, Ready for review

#2631 fix(test_duration_alternator): Fix test duration for alternator tests
  jenkins-pipelines/longevity-alternator-200gb-48h.jenkinsfile
  jenkins-pipelines/longevity-alternator-3h-multidc.jenkinsfile
  test-cases/longevity/longevity-alternator-200GB-48h.yaml
  test-cases/longevity/longevity-alternator-3h-multidc.yaml
Labels: Backport-4.2, Ready for review

#2626 fix(cdc_repl_tests): Fix test timeouts for cdc replication tests
  jenkins-pipelines/feature-cdc-replication-gemini-postimage.jenkinsfile
  jenkins-pipelines/feature-cdc-replication-gemini-preimage.jenkinsfile
  jenkins-pipelines/feature-cdc-replication-gemini.jenkinsfile
  jenkins-pipelines/feature-cdc-replication-longevity.jenkinsfile
  test-cases/cdc/cdc-15m-replication-gemini.yaml
  test-cases/cdc/cdc-15m-replication-postimage.yaml
  test-cases/cdc/cdc-15m-replication-preimage.yaml
Labels: No Backport Needed, Ready for review

#2633 fix(logcollector): support of ipv6 in grafana urls
  sdcm/logcollector.py
Labels: Backport-manager-v2.2, Ready for review

#2632 fix(manager): Got rid of port check in wait_manager_up
  sdcm/cluster.py
Labels: Backport-2020.1, Backport-4.2, Backport-manager-v2.1, Backport-manager-v2.2, Ready for review

#2622 improvement(email report): include more detailed Scylla version
  artifacts_test.py
  cdc_replication_test.py
  gemini_test.py
  longevity_test.py
  mgmt_cli_test.py
  mgmt_upgrade_test.py
  sdcm/cluster.py
  sdcm/send_email.py
  sdcm/tester.py
  unit_tests/test_cluster.py
  upgrade_test.py
Labels: Backport-4.2, Ready for review

#2643 fix(longevity_5000_tables): Enable sequentially init cluster
  test-cases/longevity/longevity-5000-tables.yaml
Labels: Backport-4.2, Ready for review

#2644 fix(manager-timeouts): manager gce test-case missing `test_duration`
  test-cases/manager/manager-regression-gce.yaml
Labels: Backport-manager-v2.2, Ready for review

#2640 fix(nemesis): nemesis running nodetool status on a dead node
  sdcm/nemesis.py
Labels: No Backport Needed

#2612 fix(sdcm/nemesis): enable EnospcMonkey on kube
  sdcm/cluster.py
  sdcm/utils/common.py
Labels: No Backport Needed, Ready for review

#2652 fix(manager): rectified a few incorrect repo paths
  jenkins-pipelines/manager/debian9-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/debian9-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu16-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/ubuntu16-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu18-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/ubuntu18-manager-upgrade.jenkinsfile
Labels: No Backport Needed

#2639 fix(manager): Removed host and token ranges flags
  sdcm/mgmt.py
Labels: Backport-manager-v2.2

#2650 test(manager-upgrade): Rerunning repairs that use legacy flags
  mgmt_upgrade_test.py
  sdcm/mgmt.py
Labels: Backport-manager-v2.2

#2654 fix(manger-upgrade-pipelines): update to start upgrades from manager-2.1
  jenkins-pipelines/manager/ubuntu16-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu18-manager-upgrade.jenkinsfile
Labels: No Backport Needed, Ready for review

#2648 fix(ToggleICS): catching the wrong UnexpectedExit
  sdcm/nemesis.py
Labels: Backport-2020.1, Backport-4.2, Ready for review

#2641 fix(DockerClient): support ipv6 when passing base_url
  sdcm/utils/common.py
  sdcm/utils/remotewebbrowser.py
Labels: Backport-manager-v2.2, Ready for review

#2655 fix(manager-pipeline): typo in ubuntu18-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu18-manager-upgrade.jenkinsfile
Labels: No Backport Needed, Ready for review

#2657 fix(alternator email recipients): remove alternator@scylladb.com from tests email recipients list
  jenkins-pipelines/longevity-alternator-200gb-48h.jenkinsfile
  jenkins-pipelines/longevity-alternator-3h-multidc.jenkinsfile
  jenkins-pipelines/longevity-alternator-3h.jenkinsfile
  jenkins-pipelines/perf-regression-alternator-latency-30min.jenkinsfile
  jenkins-pipelines/perf-regression-alternator-throughput-30min.jenkinsfile
Labels: Backport-2020.1, Backport-4.1, Backport-4.2, Ready for review

#2660 fix(longevity): enlarged the test_duration of some longevities
  test-cases/longevity/longevity-10gb-3h.yaml
  test-cases/longevity/longevity-lwt-basic-3h.yaml
  test-cases/upgrades/rolling-upgrade.yaml
Labels: No Backport Needed

#2646 feature(ManagementBackup): support backup to google storage
  sdcm/nemesis.py
Labels: Backport-manager-v2.2

#2662 fix(stress in operator test): decrease threads in the operator test
  test-cases/scylla-operator/longevity-scylla-operator-3h.yaml
Labels: No Backport Needed, Ready for review

#2663 fix(wait for node up): wait for the target node up after reboot
  sdcm/nemesis.py
Labels: Backport-2020.1, Backport-4.2, Ready for review

#2656 refactor(manager_pipeline): add sct-runner support
  vars/copyLogsFromSctRunner.groovy
  vars/managerPipeline.groovy
Labels: Backport-manager-v2.2, Ready for review

#2668 fix(operator job scylla version): Set 'latest' as default Scylla version for operator job
  vars/operatorPipeline.groovy
Labels: No Backport Needed, Ready for review

#2666 fix(sdcm/cluseter): fix retrying logic
  sdcm/cluster.py
Labels: Backport-4.2, Ready for review

#2653 fix(sdcm/tester): expose threads and processes alive at the end of the teardown
  sdcm/tester.py
Labels: No Backport Needed, Ready for review

#2658 fix(DockerClient): support ipv6 when passing base_url with port
  sdcm/utils/common.py
  sdcm/utils/remotewebbrowser.py
Labels: Backport-manager-v2.2, Ready for review

#2669 fix(runscttest.grovy): Fix if condition for updatedbpackages
  vars/runSctTest.groovy
Labels: Backport-4.2, Ready for review

#2667 fix(sct_runner): overwrite connect_timeout, 60s wasn't enough
  sct.py
  sdcm/sct_runner.py
Labels: Backport-4.2, Backport-manager-v2.2

#2649 improvement(add validation): Improve snapshot nemesis - add snapshot validation
  sdcm/nemesis.py
  sdcm/utils/common.py
Labels: No Backport Needed, Ready for review

#2672 fix(alternator-3h-multidc-yaml): remove c-s commands
  test-cases/longevity/longevity-alternator-3h-multidc.yaml
Labels: Backport-2020.1, Backport-4.2

#2665 feature(get_scylla_version): output scylla full version
  sdcm/cluster.py
Labels: No Backport Needed

#2674 fix(clean_scylla_data): don't delete the data directory
  sdcm/cluster.py
Labels: Ready for review

#2670 fix(large_collection_12h): Change instance type to i3en
  test-cases/longevity/longevity-large-collections-12h.yaml
Labels: Backport-4.2, Ready for review

#2680 fix(longevity-alternator-3h.yaml): set correct timeout
  test-cases/longevity/longevity-alternator-3h.yaml
Labels: No Backport Needed

#2682 fix(counter_multidc): remove encryption config params
  test-cases/longevity/longevity-counters-multidc.yaml
Labels: Backport-4.2, Ready for review

#2684 fix(sdcm/cluster_k8s): add enabling ip_forwarding at minikube setup
  sdcm/cluster_k8s.py
Labels: No Backport Needed, Ready for review

#2671 improvement(operator): bump version to 0.2.4
  defaults/k8s_gce_minikube_config.yaml
Labels: No Backport Needed, Ready for review

#2659 fix(test_lwt_3d): Set test duration 3 days for lwt-500g-3d
  test-cases/longevity/longevity-lwt-500G-3d.yaml
Labels: Backport-4.2

#2538 fix(improve spot request): Improve spot duration request time calculation
  defaults/aws_config.yaml
  sdcm/cluster_aws.py
  sdcm/ec2_client.py
  sdcm/sct_config.py
  sdcm/utils/common.py
  vars/byoLongevityPipeline.groovy
  vars/longevityPipeline.groovy
  vars/managerPipeline.groovy
  vars/runSctTest.groovy
Labels: Backport-2020.1, Backport-4.1, Backport-4.2

#2586 fix(version_utils.py): Enabled get Scylla version from private repo
  sdcm/utils/version_utils.py
Labels: Ready for review

#2686 fix(scylla_args): workaround for doubled scylla options
  sdcm/utils/scylla_args.py
Labels: No Backport Needed, Ready for review

#2681 improvement(mgmt_upgrade_test.py): Test backup force param removal on 2.2 upgrade
  mgmt_upgrade_test.py
  sdcm/mgmt.py
Labels: Backport-manager-v2.2

#2693 improvement(logcollector): check arhives before transfers
  sdcm/cluster.py
  sdcm/logcollector.py
  sdcm/tester.py
Labels: No Backport Needed, Ready for review

#2699 fix(manager-restore): pindown awscli version
  mgmt_cli_test.py
Labels: Backport-manager-v2.2, Ready for review

#2695 fix(alternator email failure): check if cluster object was created
  sdcm/tester.py
Labels: Backport-2020.1, Backport-4.2, Ready for review

#2694 fix(clean_sct_runners): fixing issue #2661 incorrect cleaning logic
  sdcm/utils/common.py
Labels: Backport-4.2, Urgent

#2703 Revert "fix(rolling-upgrade): Removing internode_compression 'all' from upgrades"
  jenkins-pipelines/rolling-upgrade-centos8.jenkinsfile
  jenkins-pipelines/rolling-upgrade-ubuntu18.04.jenkinsfile
Labels: Backport-4.2

#2708 fix(get gemini version): email creation fails if loaders were not created
  gemini_test.py
Labels: Backport-2020.1, Backport-4.2, Ready for review

#2704 fix(remove spot_low_price): remove hard coded using of spot_low_price provision
  defaults/test_default.yaml
  test-cases/PR-provision-test.yaml
  test-cases/artifacts/amazon2.yaml
  test-cases/artifacts/ami.yaml
  test-cases/artifacts/oel76.yaml
Labels: Backport-2020.1, Backport-4.1, Backport-4.2, Ready for review

#2709 fix(sdcm/tester.py): fix to not show if only main thread here
  sdcm/tester.py
Labels: No Backport Needed, Ready for review

#2696 fix(sdcm/cluster_k8s): implement scylla operator monitoring
  sdcm/cluster_k8s/__init__.py
  sdcm/cluster_k8s/operator_monitoring.py
Labels: No Backport Needed, Ready for review

#2690 fix(sdcm/cluster_k8s): freeze helm version
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed, Ready for review

#2698 fix(gemini-1tb-10h): tune test_duration to meaningfull value
  test-cases/gemini/gemini-1tb-10h.yaml
Labels: No Backport Needed, Ready for review

#2710 fix(runSctTest): assign update_db_packages conditionally
  vars/runSctTest.groovy
Labels: No Backport Needed, Ready for review

#2692 fix(scrub nemesis): switch to use nodetool scrub from API
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#2712 improvement(nemesis): join ..GrowShrink.. nemeses
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#2711 fix(scylla version for k8s): not check scylla version parameter
  sdcm/sct_config.py
Labels: No Backport Needed

#2689 fix(manager): deleting automatic repair when adding cluster by default
  sdcm/cluster.py
  sdcm/mgmt.py
Labels: Backport-manager-v2.2

#2687 feature(resharding before uploading): nodetool refresh - check resharding before uploading
  sdcm/nemesis.py
Labels: Backport-4.2, Ready for review

#2717 fix(manager): fixed wait_for_uploading_stage
  sdcm/mgmt.py
Labels: Backport-manager-v2.2

#2715 fix(wait node up and normal): wait when node setup is completed
  sdcm/cluster.py
Labels: Backport-2020.1, Backport-4.2

#2702 improvement(health_checker): add a retry to health validator
  sdcm/cluster.py
  sdcm/cluster_docker.py
  sdcm/sct_events.py
  sdcm/utils/health_checker.py
  unit_tests/test_utils_health_checker.py
Labels: No Backport Needed, Ready for review

#2722 fix(add verification node): set verification node when call wait_for_nodes_up_and_normal
  sdcm/cluster.py
Labels: Backport-2020.1, Backport-4.2, Ready for review, Urgent

#2723 fix(k8s defaul scylla_version): set default scylla_version to 4.1.7
  vars/operatorPipeline.groovy
Labels: No Backport Needed, Ready for review

#2719 fix(defaults/aws_config.yaml): set default loader to v12 with java-11 on board
  defaults/aws_config.yaml
Labels: Backport-2020.1, Backport-4.2, Ready for review

#2726 fix(network exception): add missed network exceptions
  sdcm/remote/__init__.py
Labels: Backport-2020.1, Backport-4.2, Ready for review

#2720 fix(sdcm/cluster.py): enable coredump collecting on loaders
  sdcm/cluster.py
Labels: No Backport Needed, Ready for review

#2728 fix(partition range validation): fix mistake in partition_range validation
  sdcm/sct_config.py
Labels: Backport-2020.1, Backport-4.2, Ready for review

#2701 fix(one line backtraces): handle correctly one line backtraces
  sdcm/cluster.py
  unit_tests/test_cluster.py
  unit_tests/test_data/system_one_line_backtrace.log
Labels: No Backport Needed, Ready for review

#2721 feature(email_reports): include direct links for the logs
  sct.py
  sdcm/report_templates/results_base.html
  sdcm/send_email.py
Labels: No Backport Needed, Ready for review

#2716 fix(k8s scylla_repo_loader): not search scylla_repo for loader
  sdcm/sct_config.py
  unit_tests/test_config.py
Labels: No Backport Needed

#2734 fix(vars/runSctTest.groovy): jenkins throws operation not supported
  vars/runSctTest.groovy
Labels: No Backport Needed, Ready for review

#2735 fix(check_schema_agreement_in_gossip_and_peers): check for None gossip and peers info
  sdcm/utils/health_checker.py
Labels: No Backport Needed, Ready for review

#2736 improvement(resharding nemesis): throw event in the resharding Nemesis instead of logging error in the log
  sdcm/cluster.py
Labels: Backport-2020.1, Backport-4.2, Ready for review

#2739 fix(test-cases/longevity/longevity-100gb-4h.yaml): set test_duration to 6 hours
  test-cases/longevity/longevity-100gb-4h.yaml
Labels: No Backport Needed, Ready for review
