Repository scylladb/scylla-cluster-tests, pull requests merged in 2020-05, with the labels that each got.

#2105 fix(manager): changed the column name the get_cluster searches for
  sdcm/mgmt.py
Labels: Backport-manager-v2.0, Backport-manager-v2.1

#2104 improvement(manager install): change default prometheus
  sdcm/cluster.py
  sdcm/sct_config.py
Labels: Backport-4.0, Backport-manager-v2.0, Backport-manager-v2.1

#2013 fix(sdcm/nemesis.py): ToggleTableICS: use command of alter materialized view for MV table
  sdcm/nemesis.py
Labels: Backport-2019.1, Backport-4.0, Ready for review

#2112 fix(resharding nemesis): Decrease nodetool compactionstats calls from 5sec to 1min to avoid the noise
  sdcm/cluster.py
Labels: Backport-2019.1, Backport-3.2, Backport-3.3, Backport-4.0, Ready for review

#2110 fix(create session): add 'verbose' parameter to ScyllaCQLSession
  sdcm/tester.py
  sdcm/utils/common.py
Labels: Backport-4.0, Ready for review

#2102 feature(data validation): add data validation to LWT longevity. 500Gb LWT longevity test
  data_dir/c-s_lwt_big_data.yaml
  jenkins-pipelines/longevity-lwt-500G-3d.jenkinsfile
  longevity_lwt_test.py
  sdcm/cluster.py
  sdcm/nemesis.py
  sdcm/tester.py
  sdcm/utils/common.py
  sdcm/utils/data_validator.py
  sdcm/utils/decorators.py
  test-cases/longevity/longevity-lwt-500G-3d.yaml
Labels: Backport-4.0, Ready for review

#2111 fix(nemesis): Rename config parameter for GrowShrinkCluster
  defaults/test_default.yaml
  docs/configuration_options.md
  sdcm/nemesis.py
  sdcm/sct_config.py
Labels: Backport-4.0

#2116 fix(sct_events): EventsFilter broke all Events subscribers
  sdcm/sct_events.py
  unit_tests/test_events.py
Labels: Backport-4.0, Ready for review, Urgent

#2120 fix(manager): changed get_cluster to accept empty cluster list table
  sdcm/mgmt.py
Labels: Backport-4.0, Backport-manager-v2.0, Backport-manager-v2.1

#2121 fix(fill_db_data): sleep before creating index
  sdcm/fill_db_data.py
Labels: Backport-4.0, Ready for review

#2122 fix(common function): Add retrying decorator to get_non_system_ks_cf_list function
  sdcm/utils/common.py
Labels: Backport-2019.1, Backport-3.3, Backport-4.0, Ready for review

#2128 fix(ycsb_thread): remove exception logging on uninit metrics
  sdcm/ycsb_thread.py
Labels: Backport-4.0, Ready for review

#2065 test(longevity): new lwt longevity with parallel nemesis
  jenkins-pipelines/longevity-lwt-24h-1dis-2nondis.jenkinsfile
  test-cases/longevity/longevity-lwt-basic-24h-1dis-2nondis.yaml
Labels: Backport-4.0, Ready for review

#2126 feature(boto3): add mypy_boto3 for s3, ec2, dynamodb
  .pre-commit-config.yaml
  docker/env/version
  requirements-python.txt
  sdcm/cluster_aws.py
  sdcm/ec2_client.py
  sdcm/utils/alternator.py
  sdcm/utils/common.py
Labels: No Backport Needed, Ready for review

#2132 fix(spot fleet): spot fleet couldn't be built
  sdcm/ec2_client.py
Labels: Backport-3.3, Backport-4.0, Backport-4.1, Ready for review

#1797 perf(performance_regression_lwt_test.py): Add performance tests for lwt
  data_dir/cs_lwt_perf_big.yaml
  data_dir/cs_lwt_perf_small.yaml
  docs/configuration_options.md
  jenkins-pipelines/perf-regression-latency-lwt-big.jenkinsfile
  jenkins-pipelines/perf-regression-latency-lwt-small.jenkinsfile
  jenkins-pipelines/perf-regression-throughput-lwt-big.jenkinsfile
  jenkins-pipelines/perf-regression-throughput-lwt-small.jenkinsfile
  performance_regression_lwt_test.py
  performance_regression_test.py
  sdcm/cluster.py
  sdcm/db_stats.py
  sdcm/report_templates/results_base_custom.html
  sdcm/report_templates/results_base_new.html
  sdcm/report_templates/results_performance_multi_baseline.html
  sdcm/report_templates/results_performance_multi_baseline_single_metric.html
  sdcm/results_analyze/__init__.py
  sdcm/results_analyze/base.py
  sdcm/results_analyze/metrics.py
  sdcm/results_analyze/test.py
  sdcm/sct_config.py
  sdcm/sct_events.py
  sdcm/tester.py
  sdcm/utils/es_queries.py
  test-cases/performance/perf-regression-latency-lwt-big.yaml
  test-cases/performance/perf-regression-latency-lwt-small.yaml
  test-cases/performance/perf-regression-throughput-lwt-big.yaml
  test-cases/performance/perf-regression-throughput-lwt-small.yaml
  test_lib/utils.py
  unit_tests/test_lib_utils.py
  vars/byoLongevityPipeline.groovy
Labels: No Backport Needed, Ready for review

#2140 feature(cloud-monitor): added pricing
  sdcm/ec2_client.py
  sdcm/utils/cloud_monitor/cloud_monitor.py
  sdcm/utils/cloud_monitor/common.py
  sdcm/utils/cloud_monitor/report.py
  sdcm/utils/cloud_monitor/templates/per_user.html
  sdcm/utils/cloud_monitor/templates/per_user_summary.html
  sdcm/utils/fromisoformat.py
  sdcm/utils/pricing.py
Labels: No Backport Needed

#2142 fix(manager): fixed test_client_encryption by using fail-fast option
  mgmt_cli_test.py
  sdcm/mgmt.py
Labels: Backport-manager-v2.1

#2130 fix(create_test_release_jobs): sct_base_dir wasn't configured correctly
  README.rst
  utils/build_system/create_test_release_jobs.py
Labels: No Backport Needed

#2052 feature(longevity): add lwt longevity of multiple datacenters
  data_dir/c-s_lwt_big_data_multidc.yaml
  jenkins-pipelines/longevity-lwt-24h-multidc.jenkinsfile
  test-cases/longevity/longevity-lwt-24h-multidc.yaml
Labels: Backport-4.0, Backport-4.1, Ready for review

#2148 fix(fill_db_data): sleep after creating type
  sdcm/fill_db_data.py
Labels: Backport-3.3, Backport-4.0, Backport-4.1, Ready for review, Urgent

#2147 fix(jenkins-pipelines/perf-regression-*): Switch to perfRegressionParallelPipeline
  jenkins-pipelines/perf-regression-latency-lwt-big.jenkinsfile
  jenkins-pipelines/perf-regression-latency-lwt-small.jenkinsfile
  jenkins-pipelines/perf-regression-throughput-lwt-big.jenkinsfile
  jenkins-pipelines/perf-regression-throughput-lwt-small.jenkinsfile
Labels: No Backport Needed, Ready for review

#2150 fix(run_stress_thread): support to identify cs cmdline starts with JVM_OPTION
  sdcm/tester.py
Labels: Backport-4.1, Ready for review

#2144 fix(nemesis): disable unstable streaming err nemesises
  sdcm/nemesis.py
Labels: Backport-4.1, Ready for review

#2119 fix(grow_shrink_nemesis): Fix GrowShrinkClusterNemesis for parallel run
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#2153 fix(hints_sending_in_progress): is failing with "No results from Prom…
  sdcm/tester.py
Labels: Backport-4.0, Backport-4.1, Ready for review

#2152 feature(cloud-monitor): added static IPs information to the report
  sdcm/utils/cloud_monitor/cloud_monitor.py
  sdcm/utils/cloud_monitor/common.py
  sdcm/utils/cloud_monitor/report.py
  sdcm/utils/cloud_monitor/resources/__init__.py
  sdcm/utils/cloud_monitor/resources/instances.py
  sdcm/utils/cloud_monitor/resources/static_ips.py
  sdcm/utils/cloud_monitor/templates/cloud_resources.html
  sdcm/utils/cloud_monitor/templates/per_user.html
  sdcm/utils/common.py
Labels: No Backport Needed

#2136 fix(validate_hh_short_downtime): don't run ValidateHintedHandoffShortDowntime nemesis if hinted_handoff is disabled
  sdcm/nemesis.py
Labels: Backport-2019.1, Backport-4.0, Ready for review

#2138 fix(defaults/aws_config.yaml): Update loader AMI with new scylla-java-tools
  defaults/aws_config.yaml
Labels: No Backport Needed, Ready for review

#2145 fix(sdcm/send_email.py): Send email even if no email data found
  sct.py
  sdcm/send_email.py
Labels: No Backport Needed, Ready for review

#2146 improvement(tagging): tag hydra container with TestId and RunByUser
  docker/env/hydra.sh
  sdcm/cluster.py
  sdcm/logcollector.py
  sdcm/tester.py
  sdcm/utils/common.py
  sdcm/utils/get_username.py
Labels: Backport-4.0, Backport-4.1, Ready for review

#2139 fix(sdcm/nemesis.py): Enable add drop column nemesis for c-s tables
  sdcm/nemesis.py
  sdcm/stress_thread.py
Labels: No Backport Needed, Ready for review

#2135 fix(sdcm/*): Improve teardown
  sdcm/sct_events.py
  sdcm/tester.py
  sdcm/utils/common.py
  unit_tests/test_events.py
Labels: No Backport Needed, Ready for review

#2155 fix(break_streaming_task_and_rebuild): added wait_db_up after reboot
  sdcm/nemesis.py
Labels: Backport-4.0, Backport-4.1

#2156 fix(abort_repair nemesis): fix pattern of active_repair API result
  sdcm/nemesis.py
Labels: Backport-2019.1, Backport-4.0, Backport-4.1, Ready for review

#2131 fix(mv backpressure): change nemesis and add MV backpressure panel
  data_dir/scylla-dash-per-server-nemesis.4.0.json
  data_dir/scylla-dash-per-server-nemesis.master.json
  test-cases/features/2mv-backpressure-4d.yaml
Labels: Backport-4.0, Ready for review

#2129 Refactor counters longevities
  jenkins-pipelines/longevity-counters-3h.jenkinsfile
  jenkins-pipelines/longevity-counters-multidc.jenkinsfile
  longevity_test.py
  sdcm/sct_config.py
  test-cases/longevity/longevity-counters-3h.yaml
  test-cases/longevity/longevity-counters-4days-multidc.yaml
  test-cases/longevity/longevity-counters-multidc.yaml
Labels: Backport-4.0

#2101 feature(lightweight transaction): decrease threads amount to get lower load
  test-cases/longevity/longevity-lwt-1loader-3h.yaml
  test-cases/longevity/longevity-lwt-basic-24h.yaml
  test-cases/longevity/longevity-lwt-basic-3h.yaml
Labels: Backport-4.0, Ready for review

#2166 fix(sdcm/tester.py): Fix test status calculation for email
  sdcm/tester.py
Labels: Backport-4.1, Ready for review

#2159 fix(rolling-upgrade): Removed the use of rows_only from the test
  sdcm/fill_db_data.py
Labels: Backport-4.0

#1779 test(new test): Performance tests for CDC
  jenkins-pipelines/perf-regression-cdc-write-60min.jenkinsfile
  jenkins-pipelines/perf-regression-cdc-write-latency-60min.jenkinsfile
  performance_regression_cdc_test.py
  sdcm/db_stats.py
  sdcm/results_analyze/__init__.py
  sdcm/utils/common.py
  sdcm/utils/es_queries.py
  test-cases/performance/perf-regression-write-cdc.yaml
  test-cases/performance/perf-regression-write-latency-cdc.yaml
Labels: No Backport Needed, Ready for review

#2167 fix(sdcm/stress_thread.py): Fix logic of adding errors option
  sdcm/stress_thread.py
Labels: Backport-4.1, Ready for review

#2169 fix(run_stress_thread_bench): local variable 'result' referenced before assignment
  sdcm/cluster.py
Labels: Backport-2019.1, Backport-4.0, Backport-4.1, Ready for review

#2172 feature(stop_test_on_failure): don't fail the test if slave cassandra-stress thread failed
  sdcm/nemesis.py
  sdcm/stress_thread.py
  sdcm/tester.py
Labels: Backport-4.0, Backport-4.1, Ready for review

#2173 improvement(paramiko-logging): set paramiko log level to critical in …
  sct.py
Labels: No Backport Needed

#2171 refactor(sstable_corrupt): Removing sstable_corrupt.py
  sstable_corrupt.py
Labels: No Backport Needed

#2174 fix(artifacts-ami): increase timeout of ami-test
  jenkins-pipelines/artifacts-ami.jenkinsfile
Labels: Backport-4.1, Ready for review

#2176 fix(docker): filter out current container from the list of containers
  sdcm/utils/common.py
Labels: Backport-4.1, Ready for review

#2175 fix(sdcm/stress_thread.py): don't add skip-unsupported-columns if it is not supported
  sdcm/stress_thread.py
Labels: Backport-4.1, Ready for review

#2161 fix(manager): fixed the name of the root disk in the debian sanity
  jenkins-pipelines/manager/debian9-manager-sanity.jenkinsfile
  vars/managerPipeline.groovy
Labels: Backport-manager-v2.0, Backport-manager-v2.1

#2179 fix(sdcm/sct_events.py): Add log message on error while reading events file
  sdcm/sct_events.py
Labels: No Backport Needed, Ready for review

#2180 fix(download_scylla_repo): retry to download scylla repo
  sdcm/cluster.py
Labels: Backport-2019.1, Backport-4.0, Backport-4.1, Ready for review

#2184 fix(hydra): updated url for IUS repo
  docker/env/Dockerfile
Labels: Backport-perf-v8

#2186 fix(perf-regression-latency): Increase scylla-release-perf-regression…
  jenkins-pipelines/perf-regression-latency-1TB.jenkinsfile
Labels: Backport-perf-v8, Backport-perf-v9

#2182 fix(upgrade_test): generate random order before complex workload
  upgrade_test.py
Labels: Backport-4.1, Ready for review

#2177 fix(get_latest_gemini_version): Fix get latest version of gemini
  sdcm/utils/common.py
Labels: Backport-3.3, Backport-4.0, Backport-4.1, Ready for review, Urgent

#2151 Jenkins longevity abort callback
  sct.py
  vars/longevityPipeline.groovy
Labels: No Backport Needed, Ready for review

#2183 fix(sdcm/utils/docker.py): Rename to docker_utils.py to avoid module import confusion
  sdcm/cdclog_reader_thread.py
  sdcm/cluster.py
  sdcm/cluster_docker.py
  sdcm/localhost.py
  sdcm/logcollector.py
  sdcm/ndbench_thread.py
  sdcm/utils/auto_ssh.py
  sdcm/utils/docker_utils.py
  sdcm/utils/remotewebbrowser.py
  sdcm/ycsb_thread.py
  unit_tests/conftest.py
  unit_tests/test_utils_docker.py
  unit_tests/test_ycsb_thread.py
Labels: Backport-4.1, Ready for review

#2164 fix(large partition): increase scylla-bench and change scylla-bench event severity
  sdcm/cluster.py
  sdcm/sct_events.py
  test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml
Labels: Backport-4.0, Backport-4.1, Ready for review

#2194 fix(gemini): Change oracle version for gemini tests
  sdcm/cluster.py
  test-cases/gemini/gemini-1tb-10h.yaml
  test-cases/gemini/gemini-3h-with-nemesis.yaml
  test-cases/gemini/gemini-3h-with-nondisruptive-nemesis.yaml
  test-cases/gemini/gemini-basic-3h.yaml
Labels: Backport-4.0, Backport-4.1, Ready for review

#2181 fix(refresh nemesis): recreate snapshot without COMPACT STORAGE
  sdcm/nemesis.py
Labels: Backport-4.1, Ready for review

#2189 Separating manager yaml files
  configurations/manager/debian9.yaml
  configurations/manager/ubuntu16.yaml
  configurations/manager/ubuntu18.yaml
  jenkins-pipelines/manager/debian9-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/ubuntu16-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/ubuntu18-manager-sanity.jenkinsfile
  vars/managerPipeline.groovy
Labels: Backport-manager-v2.0, Backport-manager-v2.1

#2170 improvement(logging): put log to a file for hydra commands
  sct.py
  sdcm/cluster.py
Labels: Ready for review

#2199 refactor(thread): remove unnecessary module thread
  sdcm/cdclog_reader_thread.py
  sdcm/cluster.py
  sdcm/ndbench_thread.py
  sdcm/sct_events.py
  sdcm/sct_events_analyzer.py
  sdcm/stress_thread.py
  sdcm/utils/thread.py
  sdcm/ycsb_thread.py
Labels: No Backport Needed
