Repository scylladb/scylla-cluster-tests, pull requests merged in 2020-07, with the labels that each got.

#2310 fix(get_nodetool_status): function can't parse line when load is '?'
  sdcm/cluster.py
Labels: Backport-2020.1, Backport-4.0, Backport-4.1, Ready for review

#2309 fix(manager): Moved the backup configuration to node setup
  sdcm/cluster.py
  sdcm/mgmt.py
  sdcm/nemesis.py
Labels: Backport-2019.1, Backport-2020.1, Backport-4.0, Backport-4.1, Backport-manager-v2.1

#2315 fix(sdcm/tester.py): Fail test is critical or error event spotted
  sdcm/sct_events.py
  sdcm/tester.py
  unit_tests/test_events.py
Labels: Backport-2020.1, Backport-4.1, Ready for review

#2327 fix(jenkins_job): Fix typo in jenkins file extension
  jenkins-pipelines/longevity-large-collections-12h.jenkinsfile
Labels: Backport-4.1, Backport-4.2, Ready for review

#2332 fix(manager-installation): using correct paramter for GCE region
  sdcm/cluster.py
Labels: Urgent

#2212 Manager 2.1 tests p2
  mgmt_cli_test.py
  sdcm/mgmt.py
  sdcm/nemesis.py
  sdcm/utils/common.py
Labels: Backport-manager-v2.1

#2337 [BACKPORT] test(manager): test an sctool backup during enospc
  mgmt_cli_test.py
  sdcm/mgmt.py
  sdcm/nemesis.py
  sdcm/utils/common.py
Labels: No Backport Needed

#2318 fix(scylla install): drop external openjdk installation
  sdcm/cluster.py
Labels: Backport-2020.1, Backport-4.1, Ready for review

#2329 fix(test_cases_lint): assort fixes for the test_case linting
  grow_cluster_test.py
  jenkins-pipelines/ics-longevity-toggle-strategy-large-partitions-24h.jenkinsfile
  sct.py
  sdcm/sct_config.py
  test-cases/enterprise-features/ics/longevity/ics-longevity-toggle-strategy-large-partitions-24h.yaml
  test-cases/features/scale-cluster.yaml
  utils/lint_test_cases.sh
Labels: Backport-2020.1, Backport-4.2

#2276 fix(rsyslog): support the case of possible IP change in AWS
  sdcm/cluster.py
  sdcm/cluster_aws.py
Labels: Backport-2020.1, Backport-4.0, Backport-4.1

#2339 revert(backtrace-thread): ignore bash coredumps
  sdcm/cluster.py
Labels: Backport-2020.1, Backport-4.1, Backport-4.2, Ready for review

#2334 fix(sdcm/): Create tester tests, and improve final event
  sdcm/cluster.py
  sdcm/db_stats.py
  sdcm/sct_config.py
  sdcm/sct_events.py
  sdcm/send_email.py
  sdcm/tester.py
  sdcm/utils/log.py
  unit_tests/test_events.py
  unit_tests/test_microbenchmarking.py
  unit_tests/test_tester.py
Labels: Ready for review, Urgent, test-provision-docker

#2341 fix(nemesis.py): remove reboot nemesis from toggle ics Monkey
  sdcm/nemesis.py
Labels: Backport-2019.1, Backport-2020.1

#2342 fix(sdcm/nemesis.py): fix possible exeption if number of columns less than 2
  sdcm/nemesis.py
Labels: Backport-4.2, Ready for review

#2343 fix(sdcm/cluster.py): Fix to return [] if no packages are there
  artifacts_test.py
  sdcm/cluster.py
Labels: Backport-2020.1, Backport-4.1, Backport-4.2, Ready for review

#2344 fix(sdcm/tester.py): Make it show very last exception point
  sdcm/tester.py
Labels: No Backport Needed, Ready for review

#2336 fix(grafana_snapshot): Scrolldown grafana page before create live sna…
  sdcm/logcollector.py
Labels: Backport-4.0, Backport-4.1, Backport-4.2, Ready for review

#2330 fix(rolling upgrade): remove subtest and correct schema_load_error_num
  sdcm/fill_db_data.py
  upgrade_test.py
Labels: Backport-2019.1, Backport-2020.1, Backport-4.1, Backport-4.2, Ready for review

#2347 fix(manager-upgrade): Disabled ES result storage
  test-cases/upgrades/manager-upgrade.yaml
Labels: Backport-manager-v2.1

#2326 fix(cluster_init): Add recommended cluster initialization with bootst…
  defaults/test_default.yaml
  docs/configuration_options.md
  sdcm/cluster.py
  sdcm/sct_config.py
  sdcm/tester.py
Labels: Backport-4.0, Backport-4.1, Backport-4.2, Ready for review

#2349 fix(artifacts_test.py): make no raise if .node is not available on save_email_data
  artifacts_test.py
Labels: No Backport Needed, Ready for review

#2351 fix(sdcm/send_email.py): Add reporter for SlaPerUserTest
  sdcm/send_email.py
Labels: Backport-2020.1, Backport-4.2, Ready for review

#2354 fix(cluster): ignore absent scylla data files
  sdcm/cluster.py
Labels: No Backport Needed

#2356 fix(cluster): host parameter of add_cluster() should be an IP address
  sdcm/cluster.py
Labels: No Backport Needed

#2353 fix(sdcm/): Make event cycles been stopped gracefully, not loosing any event which is in progress.
  sdcm/prometheus.py
  sdcm/sct_events.py
  sdcm/sct_events_analyzer.py
  unit_tests/test_events.py
Labels: No Backport Needed, Ready for review

#2352 fix(sdcm/tester.py): don't log final event if test failed
  sdcm/tester.py
  unit_tests/test_tester.py
Labels: No Backport Needed, Ready for review

#2358 improvement(hydra): always update hydra image on a builder
  docker/env/hydra.sh
Labels: No Backport Needed, Ready for review

#2363 fix(scylla_setup): support multiple nvme devices
  sdcm/cluster.py
Labels: Backport-2019.1, Backport-2020.1, Backport-4.1, Backport-4.2, Ready for review

#2360 fix(jenkinsfile): set PR jobs timeout to 90 minutes
  Jenkinsfile
Labels: No Backport Needed, Ready for review

#2366 fix(detect_disks): Fix regexp pattern for matching the nvme disk name
  sdcm/cluster.py
Labels: Backport-4.1, Backport-4.2, Ready for review, Urgent

#2348 improvement(hydra): reduce size of the Hydra image
  docker/env/Dockerfile
  docker/env/version
Labels: No Backport Needed, Ready for review

#2368 fix(verify_no_drops_and_errors): fix error message
  sdcm/tester.py
Labels: Backport-2019.1, Backport-2020.1, Backport-4.1, Backport-4.2

#2362 fix(coredumps): ignore bash coredump
  sdcm/cluster.py
Labels: Backport-2020.1, Backport-4.1, Backport-4.2, Ready for review

#2369 fix(nemesis.py): don't use disableautocompaction if not supported
  sdcm/nemesis.py
Labels: No Backport Needed

#2364 fix(terminate_and_replace): wait for old node to be removed from ring
  sdcm/nemesis.py
Labels: Backport-2020.1, Ready for review

#2350 fix(ear cert place): cert on /tmp is bad as isn't persisted
  configurations/hytrust-kmip-ear.yaml
  configurations/kmip-ear.yaml
  sdcm/cluster.py
  test-cases/longevity/longevity-encryption-at-rest-200GB-6h.yaml
Labels: Backport-2020.1

#2375 fix(./upgrade_test.py): rename search_system_log to search_database_log
  upgrade_test.py
Labels: No Backport Needed, Ready for review

#2378 fix(streaming_err nemesis): only interrupt streaming task by reboot
  sdcm/nemesis.py
Labels: Backport-2020.1, Backport-4.1, Backport-4.2

#2380 fix(5000 tables test): use c5.4xlarge instance type for loader
  test-cases/longevity/longevity-5000-tables.yaml
Labels: Backport-2020.1, Backport-4.1, Backport-4.2, Ready for review, Urgent

#2382 fix(node_setup): Fix node setup to avoid stopping scylla image setup
  sdcm/cluster.py
Labels: Backport-4.2, Ready for review, Urgent

#2357 feature(nemesis): introducing Nemesis.add_disrupt_method
  sdcm/nemesis.py
  unit_tests/test_nemesis.py
Labels: No Backport Needed, Ready for review

#2385 fix(wait_for_init): add parameter that allow either run node.check_node_health or not
  sdcm/cluster.py
  sdcm/nemesis.py
Labels: Backport-2020.1, Backport-4.1, Backport-4.2, Ready for review

#2387 fix(wait_init): Fix passing arguments in wrapper to node_setup
  sdcm/cluster.py
Labels: Backport-4.1, Backport-4.2, Ready for review, Urgent

#2384 improvement(sct_investigate): New subcommand to monitor runnnig jobs …
  sct.py
  sdcm/utils/common.py
Labels: No Backport Needed

#2388 fix(hydra): bump Python version to 3.8.4
  docker/env/Dockerfile
  docker/env/version
Labels: No Backport Needed, Ready for review

#2381 test(nemesis.py): Adding kill Scylla monkey nemesis
  sdcm/nemesis.py
Labels: No Backport Needed

#2389 fix(pylint): disable arguments-differ for wait_for_init()
  sdcm/cluster_aws.py
Labels: Backport-2020.1, Backport-4.1, Backport-4.2, Ready for review

#2367 improvement(alternator.py): Creating new API functions
  performance_regression_alternator_test.py
  sdcm/cluster.py
  sdcm/nemesis.py
  sdcm/tester.py
  sdcm/utils/alternator.py
  sdcm/utils/alternator/__init__.py
  sdcm/utils/alternator/api.py
  sdcm/utils/alternator/consts.py
  sdcm/utils/alternator/enums.py
  sdcm/utils/alternator/schemas.py
  sdcm/ycsb_thread.py
  unit_tests/conftest.py
  unit_tests/test_ycsb_thread.py
Labels: No Backport Needed, Ready for review

#2359 fix(restart_then_repair_node): filter out no_such_column_family error during restart
  sdcm/nemesis.py
Labels: Backport-2019.1, Backport-2020.1, Backport-4.0, Backport-4.1, Backport-4.2, Ready for review

#2373 fix(lwt basic profile): decrease rows amount for data validator views
  data_dir/c-s_lwt_basic.yaml
  sdcm/utils/data_validator.py
Labels: Backport-2019.1, Backport-2020.1, Backport-4.1, Backport-4.2, Ready for review

#2333 fix(create_spot_instances): fix duration calculate in python 3
  sdcm/cluster_aws.py
Labels: Backport-2019.1, Backport-2020.1, Backport-4.0, Backport-4.1, Backport-4.2

#2394 fix(replicated-ear): config system_key
  configurations/replicated-ear.yaml
Labels: Backport-2019.1, Backport-2020.1, Ready for review, Urgent

#2399 CDC replication test: increase nemesis timeout
  cdc_replication_test.py
Labels: No Backport Needed

#2267 fix(sdcm/remote.py): Replace paramiko with libssh2
  .pre-commit-config.yaml
  defaults/test_default.yaml
  docker/env/Dockerfile
  docker/env/version
  docs/configuration_options.md
  requirements-python.txt
  sdcm/cluster.py
  sdcm/logcollector.py
  sdcm/remote.py
  sdcm/remote/__init__.py
  sdcm/remote/base.py
  sdcm/remote/libssh2_client/__init__.py
  sdcm/remote/libssh2_client/exceptions.py
  sdcm/remote/libssh2_client/result.py
  sdcm/remote/local_cmd_runner.py
  sdcm/remote/remote_base.py
  sdcm/remote/remote_cmd_runner.py
  sdcm/remote/remote_libssh_cmd_runner.py
  sdcm/sct_config.py
  sdcm/tester.py
  sdcm/utils/common.py
  sdcm/utils/remote_logger.py
  test-cases/features/scale-cluster.yaml
  test-cases/longevity/longevity-10gb-3h.yaml
  unit_tests/lib/test_profiler/lib2.py
  unit_tests/test_manual.py
  unit_tests/test_remoter.py
Labels: No Backport Needed, Ready for review

#2409 fix(cluster.py): during backport variable name changed
  sdcm/cluster.py
Labels: No Backport Needed, Urgent

#2407 fix(alternator): Adding node variable for all Alternator API funcs
  performance_regression_alternator_test.py
  sdcm/tester.py
  sdcm/utils/alternator/api.py
  unit_tests/test_ycsb_thread.py
Labels: No Backport Needed

#2411 fix(scylla_cloud_nemesis.yaml): delete this unneeded file
  configurations/scylla_cloud_nemesis.yaml
Labels: No Backport Needed

#2414 fix(remote): fix a typo in key_file arg
  sdcm/remote/remote_base.py
Labels: No Backport Needed, Ready for review, Urgent

#2403 feature(upgrade): enable internode_compression for part of upgrade test
  docs/configuration_options.md
  jenkins-pipelines/rolling-upgrade-centos8.jenkinsfile
  jenkins-pipelines/rolling-upgrade-ubuntu18.04.jenkinsfile
  sdcm/cluster.py
  sdcm/sct_config.py
  vars/rollingUpgradePipeline.groovy
Labels: No Backport Needed, Ready for review

#2377 feature(k8s-gce-minikube): Add a new backend
  .pre-commit-config.yaml
  defaults/k8s_gce_minikube_config.yaml
  docker/env/Dockerfile
  docker/env/version
  docs/configuration_options.md
  docs/kubernetes_backend.md
  install-prereqs.sh
  internal_test_data/simple_test_case.yaml
  jenkins-pipelines/k8s-simple-test.jenkinsfile
  requirements-python.txt
  sct.py
  sdcm/cluster.py
  sdcm/cluster_k8s.py
  sdcm/k8s_configs/cluster.yaml
  sdcm/k8s_configs/operator.yaml
  sdcm/remote/kubernetes_cmd_runner.py
  sdcm/sct_config.py
  sdcm/tester.py
  sdcm/utils/gce_utils.py
  sdcm/utils/k8s.py
  sdcm/utils/remote_logger.py
  vars/operatorPipeline.groovy
Labels: No Backport Needed

#2415 fix(refresh nemesis): remove unsupported file from snapshot
  sdcm/nemesis.py
Labels: Backport-2019.1

#2417 fix(hydra): change version to 0.75
  docker/env/version
Labels: No Backport Needed, Ready for review

#2421 fix(k8s-gce-minikube): update to Scylla Operator v0.2.3
  defaults/k8s_gce_minikube_config.yaml
  sdcm/cluster_k8s.py
  sdcm/k8s_configs/operator.yaml
  sdcm/tester.py
  sdcm/utils/k8s.py
  vars/operatorPipeline.groovy
Labels: No Backport Needed, Ready for review

#2416 fix(hydra): bump Python version to 3.8.5
  docker/env/Dockerfile
  docker/env/version
Labels: New Hydra Version, No Backport Needed, Ready for review

#2420 improvement(new loader ami): change default loaders
  data_dir/c-s_lwt_basic.yaml
  data_dir/c-s_lwt_big_data.yaml
  data_dir/c-s_lwt_big_data_multidc.yaml
  defaults/aws_config.yaml
  test-cases/longevity/longevity-lwt-1loader-3h.yaml
  test-cases/longevity/longevity-lwt-24h-multidc.yaml
  test-cases/longevity/longevity-lwt-500G-3d.yaml
  test-cases/longevity/longevity-lwt-basic-24h-1dis-2nondis.yaml
  test-cases/longevity/longevity-lwt-basic-24h.yaml
  test-cases/longevity/longevity-lwt-basic-3h.yaml
Labels: Backport-2020.1, Backport-4.2, Ready for review

#2424 fix(unit_tests/test_tester.py): add test on error event
  unit_tests/test_tester.py
Labels: No Backport Needed, Ready for review

#2427 fix(in memory test): shorten longevity-in-memory-36GB-4days test to 24h
  jenkins-pipelines/longevity-in-memory-36gb-4d.jenkinsfile
  test-cases/longevity/longevity-in-memory-36GB-4days.yaml
Labels: Backport-2020.1, Ready for review

#2428 fix(remote): logging levels
  sdcm/remote/base.py
  sdcm/remote/remote_base.py
Labels: No Backport Needed

#2422 fix(sdcm/): Make paramiko remoter threadsafe
  sdcm/remote/remote_base.py
  sdcm/remote/remote_cmd_runner.py
  sdcm/remote/remote_libssh_cmd_runner.py
Labels: No Backport Needed

#2419 fix(sdcm/send_email): Maximaze event number in the report
  sdcm/send_email.py
Labels: Backport-2020.1, Backport-4.2, Ready for review

#2408 refactor(requirements-travis.txt): Removing unless file
  requirements-travis.txt
Labels: No Backport Needed, Ready for review

#2429 fix(in memory test): rename longevity-in-memory-36GB-4days test to 1d
  jenkins-pipelines/longevity-in-memory-36gb-1d.jenkinsfile
  sct.py
  test-cases/longevity/longevity-in-memory-36GB-1day.yaml
Labels: Backport-2020.1, Ready for review

#2402 improvement(cdc_repl_jenkins): Switch cdc_repl pipeline to use longev…
  cdc_replication_test.py
  jenkins-pipelines/cdcReplicationPipeline.jenkinsfile
  jenkins-pipelines/feature-cdc-replication.jenkinsfile
  sdcm/report_templates/results_cdcreplication.html
  sdcm/send_email.py
  vars/cdcReplicationPipeline.groovy
Labels: No Backport Needed, Ready for review

#2412 fix(toppartition_nemesis): Fix incorrect output splitting for toppartition command
  sdcm/nemesis.py
Labels: Backport-4.1, Backport-4.2, Ready for review

#2433 fix(hydra): resolve issue with SCT-CONTAINER resolve
  docker/env/Dockerfile
  docker/env/version
Labels: New Hydra Version, No Backport Needed, Ready for review

#2436 fix(longevity-in-memory): fix "Multiple definition for property 'compaction' " error
  sdcm/tester.py
Labels: Backport-2020.1, Ready for review, Urgent

#2434 feature(scylla setup): enable swap setup for GCE instances
  sdcm/cluster.py
Labels: Backport-4.2, Ready for review

#2404 feature(nemesis): introduce MemoryStressMonkey
  sdcm/nemesis.py
Labels: Backport-4.2, Ready for review

#2442 fix(in memory cs): InMemoryCompactionStrategy is missed in the compaction strategy enum
  test_lib/compaction.py
Labels: Backport-2020.1, Ready for review, Urgent

#2443 fix(sdcm/remote/libssh2_client): Fix memory leaking on reconnect
  sdcm/remote/libssh2_client/__init__.py
  sdcm/remote/libssh2_client/session.py
Labels: Backport-2020.1, Ready for review

#2441 test(operator): 1h longevity with non-disruptive nemeses
  jenkins-pipelines/k8s-longevity-10gb-1h.jenkinsfile
  sdcm/cluster_k8s.py
  sdcm/remote/kubernetes_cmd_runner.py
  sdcm/tester.py
  test-cases/k8s/gce-minikube-longevity-10gb-1h.yaml
  utils/lint_test_cases.sh
Labels: Backport-2020.1, Ready for review

#2451 improvement(sct-runner-cleaner): improved logging
  sdcm/utils/common.py
Labels: No Backport Needed

#2450 fix(scylla_setup): only enable swap setup when it's supported
  sdcm/cluster.py
Labels: Backport-4.2, Ready for review

#2449 fix(lwt test): fix issue when lwt longevities consume all memory
  sdcm/tester.py
Labels: Backport-2020.1, Backport-4.1, Backport-4.2, Ready for review

#2438 fix(aborting on shard): add new database log event for aborting on shard
  sdcm/cluster.py
Labels: Backport-2020.1, Backport-4.1, Backport-4.2, Ready for review

#2455 fix(sct_config): aws-siren wasn't working since sct-runner changes
  sdcm/sct_config.py
  sdcm/tester.py
Labels: No Backport Needed, Urgent
