Repository scylladb/scylla-cluster-tests, pull requests merged in 2021-03, with the labels that each got.

#3275 fix(email-report): show correct GCE instance type in the email
  sdcm/tester.py
Labels: Backport-4.4

#3279 feature(k8s logs): Add k8s logs to the email report
  sdcm/utils/common.py
Labels: No Backport Needed, Ready for review

#3245 test(upgrade_test.py): adding paged query to complex
  sdcm/fill_db_data.py
  upgrade_test.py
Labels: Backport-4.3, Backport-4.4

#3274 fix(nemesis.py): fix backport PR-3253
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#3269 improvement(jepsen): allow multiple test commands
  defaults/test_default.yaml
  docs/configuration_options.md
  jepsen_test.py
  sdcm/report_templates/results_jepsen.html
  sdcm/sct_config.py
  vars/jepsenPipeline.groovy
Labels: No Backport Needed, Ready for review

#3284 fix(gce create instance): cover destroy gce instance failure in case preemption
  sdcm/cluster_gce.py
Labels: Backport-4.4, Ready for review

#3286 fix(loader ami v5): set scylla-qa-loader-ami-lwt-v5 for multiks test
  test-cases/longevity/longevity-multi-keyspaces.yaml
Labels: Backport-4.4, Ready for review

#3288 fix(fill_db_data.py): Fixing "Tom Bob" query result
  sdcm/fill_db_data.py
Labels: Ready for review

#3291 Fix DecommissionStreamingErr nemesis
  sdcm/nemesis.py
Labels: Backport-4.4, Ready for review

#3294 fix(ldap_toggle_config): the entries in LDAP were not
  sdcm/tester.py
Labels: Backport-2020.1

#3295 fix(ldap_toggle_config): the entries in LDAP were not
  sdcm/tester.py
Labels: No Backport Needed

#3303 fix(longevity-lwt-500G-3d): fix prepare stage
  test-cases/longevity/longevity-lwt-500G-3d.yaml
Labels: Backport-4.4, Ready for review

#3309 DataValidator - take unique MV names from user profile
  sdcm/utils/data_validator.py
Labels: Backport-4.4, Ready for review

#3310 refactor(manager): changed scylla version to 4.3
  jenkins-pipelines/manager/centos-manager-backup-gce.jenkinsfile
  jenkins-pipelines/manager/centos-manager-backup.jenkinsfile
  jenkins-pipelines/manager/centos-manager-repair-control.jenkinsfile
  jenkins-pipelines/manager/centos-manager-repair-intensity-multiple-repaired-nodes.jenkinsfile
  jenkins-pipelines/manager/centos-manager-repair-intensity-single-repaired-nodes.jenkinsfile
  jenkins-pipelines/manager/centos-manager-sanity-ipv6.jenkinsfile
  jenkins-pipelines/manager/centos-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/centos-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/debian9-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/debian9-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu16-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/ubuntu16-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu18-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/ubuntu18-manager-upgrade.jenkinsfile
Labels: No Backport Needed

#3311 fix(fill_db_data.py): paged query test did insert before table schema
  sdcm/fill_db_data.py
Labels: Backport-4.4

#3263 fix(ldap credentials): everything gets right credentials
  sdcm/cluster.py
  sdcm/tester.py
Labels: Backport-2020.1, Ready for review

#3312 fix(ldap credentials): everything gets right credentials
  sdcm/cluster.py
  sdcm/tester.py
Labels: No Backport Needed

#3304 fix(rollingOperatorUpgradePipeline.groovy): fix eks code to make pipeline succeeded
  jenkins-pipelines/upgrade-major-scylla-k8s-eks.jenkinsfile
  jenkins-pipelines/upgrade-scylla-k8s-eks.jenkinsfile
  sdcm/tester.py
  vars/rollingOperatorUpgradePipeline.groovy
Labels: No Backport Needed, Ready for review

#3314 fix(corrupt_then_scrub): set current disruption event
  sdcm/nemesis.py
  sdcm/scylla_bench_thread.py
Labels: Backport-4.4, Ready for review

#3306 fix(eks pipelines): Set default parameters
  jenkins-pipelines/longevity-scylla-operator-3h-eks-add-remove-rack.jenkinsfile
  jenkins-pipelines/longevity-scylla-operator-3h-eks-backup.jenkinsfile
  jenkins-pipelines/longevity-scylla-operator-3h-eks-cluster-rolling.jenkinsfile
  jenkins-pipelines/longevity-scylla-operator-3h-eks-grow-shrink.jenkinsfile
  jenkins-pipelines/longevity-scylla-operator-3h-eks-repair.jenkinsfile
  jenkins-pipelines/longevity-scylla-operator-3h-eks-replace.jenkinsfile
  jenkins-pipelines/longevity-scylla-operator-3h-eks-stop-start.jenkinsfile
  jenkins-pipelines/longevity-scylla-operator-3h-eks-terminate-decommission-add.jenkinsfile
  jenkins-pipelines/longevity-scylla-operator-3h-eks-terminate-recover.jenkinsfile
  jenkins-pipelines/longevity-scylla-operator-3h-eks-terminate-replace.jenkinsfile
  jenkins-pipelines/longevity-scylla-operator-3h-eks.jenkinsfile
  jenkins-pipelines/longevity-scylla-operator-basic-3h-eks.jenkinsfile
Labels: No Backport Needed, Ready for review

#3323 fix(k8s-gke): Fix deployment of minio storage for scylla-manager
  sdcm/tester.py
Labels: No Backport Needed

#3321 improvement(cdc_replication_test): update replicator
  cdc_replication_test.py
Labels: Backport-4.4, Ready for review

#3322 fix(longevity-2tb-48h): Fixing timeout issue and stress duration
  jenkins-pipelines/longevity-2tb-4days-1Dis-2NonDis-Nemesises.jenkinsfile
  test-cases/longevity/longevity-2TB-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis.yaml
Labels: Backport-4.4

#3324 refactor(manager): Changed post behavior to destroy
  jenkins-pipelines/manager/centos-manager-backup-gce-1tb.jenkinsfile
  jenkins-pipelines/manager/centos-manager-backup-gce.jenkinsfile
  jenkins-pipelines/manager/centos-manager-backup.jenkinsfile
  jenkins-pipelines/manager/centos-manager-repair-control.jenkinsfile
  jenkins-pipelines/manager/centos-manager-repair-intensity-multiple-repaired-nodes.jenkinsfile
  jenkins-pipelines/manager/centos-manager-repair-intensity-single-repaired-nodes.jenkinsfile
  jenkins-pipelines/manager/centos-manager-sanity-ipv6.jenkinsfile
  jenkins-pipelines/manager/centos-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/debian9-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/ubuntu16-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/ubuntu18-manager-sanity.jenkinsfile
Labels: Backport-manager-v2.3

#3329 fix(k8s-gke): reduce number of used k8s terminate methods
  sdcm/nemesis.py
Labels: No Backport Needed

#3330 fix(upgrade): Allow upgrade on versions older than 4.4
  sdcm/fill_db_data.py
Labels: No Backport Needed

#3334 fix(get_any_ks_cf_list): use PageFetcher.fetch_all instead session.execute
  sdcm/cluster.py
Labels: Backport-4.4, Ready for review

#3280 feature(asymmertic cluster): add support of asymmetric cluster
  defaults/test_default.yaml
  docs/configuration_options.md
  sdcm/cluster.py
  sdcm/nemesis.py
  sdcm/report_templates/results_base.html
  sdcm/report_templates/results_issue_template.html
  sdcm/report_templates/results_longevity.html
  sdcm/sct_config.py
  sdcm/send_email.py
  sdcm/tester.py
Labels: Ready for review

#3331 fix(gemini-1tb): Run test gemini 1tb with nemesis
  jenkins-pipelines/gemini-1tb-10h.jenkinsfile
  test-cases/gemini/gemini-1tb-10h.yaml
Labels: Backport-4.3, Backport-4.4, Ready for review

#3333 fix(fill_db_data.py): correct the support version with rc suffix
  sdcm/fill_db_data.py
Labels: No Backport Needed, Ready for review

#3338 fix(gce-ipv6-property): return empty string for IPv6 address in GCE
  sdcm/cluster_gce.py
Labels: No Backport Needed, Urgent

#3340 fix(nonroot user tests): get SMP from SCYLLA_ARGS
  sdcm/cluster.py
Labels: Ready for review

#3339 fix(test_update_db_packages_gce): remove dependency on the remote bucket contents
  unit_tests/test_utils_common.py
Labels: Backport-4.4

#3341 test(asymmetric cluster): Add new longevity-large-partition-asymmetric-cluster-3h test
  configurations/db-nodes-shards-random.yaml
  jenkins-pipelines/longevity-large-partition-asymmetric-cluster-3h.jenkinsfile
  test-cases/longevity/longevity-large-partition-3h.yaml
Labels: Ready for review

#3349 fix(save_email_data): no IPv6 address for Docker
  sdcm/cluster_docker.py
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed, Ready for review

#3342 test(12h with asymmetric cluster): Add new longevity-50gb-asymmetric-cluster-12h test
  jenkins-pipelines/longevity-50gb-asymmetric-cluster-12h.jenkinsfile
  test-cases/longevity/longevity-50GB-12h-verifier-LimitedMonkey-tls.yaml
Labels: No Backport Needed, Ready for review

#3344 fix(shrink cluster): transfer nemesis name in 'decommission' method
  sdcm/cluster.py
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#3345 fix(nodes list in email): not print nodes list in the email if more then 20 nodes
  sdcm/report_templates/results_issue_template.html
  sdcm/report_templates/results_longevity.html
Labels: No Backport Needed, Ready for review

#3347 fix(removenode_filter_issue): the repair running
  sdcm/nemesis.py
Labels: Backport-4.4

#3353 fix(kubernetes): fix usage of custom operator image
  sdcm/cluster_k8s/__init__.py
Labels: Backport-operator-1.1

#3359 fix(longevity-encryption-at-rest-200GB-6h.yaml): remove unstable KMIP config
  test-cases/longevity/longevity-encryption-at-rest-200GB-6h.yaml
Labels: Backport-2021.1, Ready for review
