Repository scylladb/scylla-cluster-tests, pull requests merged in 2021-07, with the labels that each got.

#3729 fix(k8s-eks): use K8S v1.20 instead of v1.19 in EKS
  defaults/k8s_eks_config.yaml
Labels: Backport-operator-1.3, Ready for review

#3735 [K8S] Do not make direct scylla statefulset updates
  sdcm/cluster_k8s/__init__.py
Labels: Ready for review

#3730 improvement(cloud-monitor): add procedure link to cloud resources email
  sdcm/utils/cloud_monitor/templates/base.html
Labels: No Backport Needed

#3737 fix(k8s-eks): use new namespaces for operator and manager
  sdcm/cluster_k8s/__init__.py
Labels: Ready for review

#3748 fix(gemini_cmd): Reduce gemini threads in test
  test-cases/gemini/gemini-1tb-10h.yaml
  test-cases/gemini/gemini-3h-cdc-postimage-write.yaml
  test-cases/gemini/gemini-3h-cdc-preimage-write.yaml
  test-cases/gemini/gemini-3h-cdc-write.yaml
  test-cases/gemini/gemini-3h-ics-cdc-with-nemesis.yaml
  test-cases/gemini/gemini-3h-ics-with-nondisruptive-nemesis.yaml
  test-cases/gemini/gemini-3h-with-nemesis.yaml
  test-cases/gemini/gemini-3h-with-nondisruptive-nemesis.yaml
  test-cases/gemini/gemini-8h-large-num-columns.yaml
  test-cases/gemini/gemini-basic-3h-ics.yaml
  test-cases/gemini/gemini-basic-3h.yaml
Labels: Backport-2021.1, Backport-4.5, Ready for review

#3745 fix(manager): changed default post behavior in all jobs to destroy
  jenkins-pipelines/manager/centos-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/debian10-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/debian9-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu16-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu18-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu20-manager-upgrade.jenkinsfile
Labels: Backport-manager-v2.4

#3758 fix(cfstat event): not publish NodetoolEvent when waiting for space_node_threshold
  sdcm/cluster.py
Labels: No Backport Needed, Ready for review

#3762 fix(eks-k8s): update image for node-setup daemonset
  sdcm/k8s_configs/eks/scylla-node-prepare.yaml
Labels: Ready for review

#3749 fix(gemini-1tb-10h): Change test duration to 10h
  test-cases/gemini/gemini-1tb-10h.yaml
Labels: Backport-2021.1, Backport-4.4, Backport-4.5, Ready for review

#3722 feature(fill_db_data): log every step in between updates
  sdcm/fill_db_data.py
Labels: No Backport Needed, Ready for review

#3763 feature(k8s-monitoring): store K8S monitoring config in local yaml files
  sdcm/cluster_k8s/__init__.py
  sdcm/k8s_configs/monitoring/scylla-manager-service-monitor.yaml
  sdcm/k8s_configs/monitoring/scylla-service-monitor.yaml
  sdcm/k8s_configs/monitoring/values.yaml
  sdcm/tester.py
Labels: No Backport Needed, Ready for review

#3742 feature(kubernetes): add operator upgrade test
  docs/configuration_options.md
  jenkins-pipelines/operator/upgrade/upgrade-operator-k8s-eks.jenkinsfile
  jenkins-pipelines/operator/upgrade/upgrade-operator-k8s-gke.jenkinsfile
  sdcm/cluster_k8s/__init__.py
  sdcm/sct_config.py
  sdcm/utils/k8s.py
  test-cases/scylla-operator/kubernetes-operator-upgrade.yaml
  test-cases/scylla-operator/kubernetes-scylla-upgrade.yaml
  upgrade_test.py
  vars/rollingOperatorUpgradePipeline.groovy
  vars/runSctTest.groovy
Labels: Ready for review

#3741 fix(README.rst): fix functional test docs
  README.rst
Labels: No Backport Needed, Ready for review

#3761 k8s-local-kind: kill old cluster if REUSE_CLUSTER is not set
  sdcm/cluster_k8s/__init__.py
  sdcm/cluster_k8s/mini_k8s.py
Labels: No Backport Needed, Ready for review

#3692 fix(check_regression): Limit number of events for perf email
  defaults/test_default.yaml
  docs/configuration_options.md
  sdcm/results_analyze/__init__.py
  sdcm/sct_config.py
  sdcm/tester.py
Labels: Backport-perf-v11, Ready for review

#3766 Fix k8s local reuse
  sdcm/cluster_k8s/mini_k8s.py
Labels: No Backport Needed, Ready for review

#3743 improvement(sct_events): add singleton ContinuousEventsRegistry
  sdcm/sct_events/base.py
  unit_tests/test_sct_events_continuous_events_registry.py
Labels: No Backport Needed, Ready for review

#3771 fix(kubernetes): make SCT support seedless scylla using operator
  sdcm/cluster_k8s/__init__.py
Labels: Ready for review

#3776 refactor(manager-upgrade): change base version to 2.4
  jenkins-pipelines/manager/centos-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/debian10-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/debian9-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu16-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu18-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu20-manager-upgrade.jenkinsfile
Labels: No Backport Needed

#3765 fix(disrupt_nodetool_refresh): make it wait for resharding log messages
  sdcm/nemesis.py
Labels: Backport-2021.1, Backport-4.4, Backport-4.5, Ready for review

#3781 fix(nodetool): prevent reporting event as error if it should be warning
  sdcm/cluster.py
Labels: No Backport Needed, Ready for review

#3775 fix(k8s-local*): fix kubectl proxy issue with reuse cluster
  sdcm/cluster_k8s/mini_k8s.py
  sdcm/utils/common.py
Labels: No Backport Needed, Ready for review

#3779 feature(k8s-functional-test): cover creation of invalid ScyllaClusters
  functional_tests/scylla_operator/test_functional.py
Labels: Ready for review

#3780 fix(k8s-minikube): install prerequisites correctly
  sdcm/cluster_k8s/mini_k8s.py
Labels: Ready for review

#3782 fix(test_listen_address): one error reported twice
  functional_tests/scylla_operator/test_functional.py
Labels: No Backport Needed, Ready for review

#3787 Polish functional tests
  functional_tests/scylla_operator/test_functional.py
Labels: No Backport Needed, Ready for review

#3784 improvement(kubernetes): use logLevel=4 for operator
  sdcm/cluster_k8s/__init__.py
Labels: Backport-operator-1.4, Ready for review

#3790 fix(longevity-5000-tables): increase timeout
  test-cases/longevity/longevity-5000-tables.yaml
Labels: Backport-4.5

#3755 feature(manager): sanities trigger upgrade and downstream jobs
  jenkins-pipelines/manager/centos-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/debian10-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/debian9-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/ubuntu16-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/ubuntu18-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/ubuntu20-manager-sanity.jenkinsfile
  vars/managerPipeline.groovy
Labels: Backport-manager-v2.4

#3700 fix(grow_shrink_cluster): Decommission nodes to initial cluster state
  sdcm/nemesis.py
Labels: Backport-4.5, Ready for review

#3795 fix(logcollector): remove collect_single_archive
  defaults/test_default.yaml
  docs/configuration_options.md
  sdcm/logcollector.py
  sdcm/sct_config.py
Labels: Backport-2021.1, Backport-4.5, Ready for review

#3797 Prometheus data not collected on branch-4.5
  sdcm/cluster.py
Labels: No Backport Needed, Ready for review

#3798 fix(sct.py): fix backport of e2b351d0dca
  sct.py
Labels: No Backport Needed, Ready for review

#3772 test(operator functional): new functional tests cover orphaned services issue
  functional_tests/scylla_operator/libs/helpers.py
  functional_tests/scylla_operator/test_functional.py
Labels: No Backport Needed

#3800 fix(distro): add support ubuntu 21.04
  sdcm/utils/distro.py
Labels: No Backport Needed, Ready for review

#3802 fix(conftet.py): fix cluster recover
  functional_tests/scylla_operator/conftest.py
Labels: No Backport Needed, Ready for review

#3803 fix(TokenUpdateThread): update token safely
  sdcm/utils/k8s.py
Labels: Backport-operator-1.4, Ready for review

#3804 fix(cluster_k8s): make iproute installation more stable
  sdcm/cluster_k8s/__init__.py
Labels: Backport-operator-1.4, Ready for review

#3808 fix(mini_k8s): make kind and minikube be persistent
  sdcm/cluster_k8s/mini_k8s.py
Labels: No Backport Needed, Ready for review

#3812 Fix gcloud
  sdcm/cluster_k8s/gke.py
  sdcm/utils/k8s.py
Labels: No Backport Needed, Ready for review

#3811 improvement(sct_events): jmx event
  defaults/severities.yaml
  sdcm/sct_events/database.py
Labels: No Backport Needed, Ready for review

#3820 feature(cloud_monitor): use CloudTrail to find an owner of the instance
  sdcm/utils/cloud_monitor/resources/instances.py
Labels: No Backport Needed

#3821 fix(hydra.sh): parse arguments properly
  docker/env/hydra.sh
Labels: No Backport Needed, Ready for review

#3825 fix(hydra.sh): add sct arguments
  docker/env/hydra.sh
Labels: No Backport Needed, Ready for review

#3823 improvement(cloud nemesis): a list for cloud_limited_chaos_monkey
  sdcm/nemesis.py
Labels: No Backport Needed

#3752 fix(multi_hard_reboot): add to global filters and cdc generation check
  sdcm/nemesis.py
  sdcm/sct_events/setup.py
Labels: Backport-4.5, Ready for review

#3826 refactor(TestConfig): convert to Singleton
  sdcm/sct_events/base.py
  sdcm/test_config.py
  sdcm/utils/metaclasses.py
Labels: No Backport Needed, Ready for review

#3828 fix(servernemesisdashboard): set new resolution
  sdcm/monitorstack/ui.py
Labels: No Backport Needed, Ready for review

#3773 improvement(update_db_binary): add support to ubuntu packages
  defaults/severities.yaml
  sdcm/cluster.py
Labels: No Backport Needed, Ready for review

#3706 feature(show_toppartition): Add check for new api of toppartition
  sdcm/nemesis.py
  sdcm/utils/toppartition_util.py
Labels: No Backport Needed, Ready for review

#3819 fix(mgmt/cli.py): Remove unneeded manager backup command stderr check
  sdcm/mgmt/cli.py
Labels: Ready for review

#3834 fix(BaseCluster): make property of test_config
  sdcm/cluster.py
Labels: No Backport Needed, Ready for review, test-provision-aws

#3832 improvement(ScyllaServerStatusEvent): catch service failures to start
  sdcm/sct_events/database.py
Labels: No Backport Needed
