Repository scylladb/scylla-cluster-tests, pull requests merged in 2021-02, with the labels that each got.

#3183 fix(k8s jenkins jobs): add +20 to testduration and +40 to pipeline timeout
  jenkins-pipelines/longevity-scylla-operator-3h-gke-add-remove-rack.jenkinsfile
  jenkins-pipelines/longevity-scylla-operator-3h-gke-backup.jenkinsfile
  jenkins-pipelines/longevity-scylla-operator-3h-gke-cluster-rolling.jenkinsfile
  jenkins-pipelines/longevity-scylla-operator-3h-gke-grow-shrink.jenkinsfile
  jenkins-pipelines/longevity-scylla-operator-3h-gke-repair.jenkinsfile
  jenkins-pipelines/longevity-scylla-operator-3h-gke-replace.jenkinsfile
  jenkins-pipelines/longevity-scylla-operator-3h-gke-stop-start.jenkinsfile
  jenkins-pipelines/longevity-scylla-operator-3h-gke-terminate-decommission-add.jenkinsfile
  jenkins-pipelines/longevity-scylla-operator-3h-gke-terminate-recover.jenkinsfile
  jenkins-pipelines/longevity-scylla-operator-3h-gke-terminate-replace.jenkinsfile
  jenkins-pipelines/longevity-scylla-operator-3h-gke.jenkinsfile
  jenkins-pipelines/longevity-scylla-operator-3h-minikube.jenkinsfile
  jenkins-pipelines/longevity-scylla-operator-basic-3h-gke.jenkinsfile
  test-cases/scylla-operator/longevity-scylla-operator-3h-gke-add-remove-rack.yaml
  test-cases/scylla-operator/longevity-scylla-operator-3h-gke-backup.yaml
  test-cases/scylla-operator/longevity-scylla-operator-3h-gke-cluster-rolling.yaml
  test-cases/scylla-operator/longevity-scylla-operator-3h-gke-grow-shrink.yaml
  test-cases/scylla-operator/longevity-scylla-operator-3h-gke-repair.yaml
  test-cases/scylla-operator/longevity-scylla-operator-3h-gke-replace.yaml
  test-cases/scylla-operator/longevity-scylla-operator-3h-gke-stop-start.yaml
  test-cases/scylla-operator/longevity-scylla-operator-3h-gke-terminate-decommission-add.yaml
  test-cases/scylla-operator/longevity-scylla-operator-3h-gke-terminate-recover.yaml
  test-cases/scylla-operator/longevity-scylla-operator-3h-gke-terminate-replace.yaml
  test-cases/scylla-operator/longevity-scylla-operator-3h-gke.yaml
  test-cases/scylla-operator/longevity-scylla-operator-3h-minikube.yaml
  test-cases/scylla-operator/longevity-scylla-operator-basic-3h-gke.yaml
Labels: No Backport Needed, Ready for review

#3194 fix(clean-resources): assign backend
  sct.py
  vars/artifactsPipeline.groovy
  vars/byoOperatorPipeline.groovy
  vars/operatorPipeline.groovy
  vars/rollingUpgradePipeline.groovy
Labels: Backport-4.4

#3196 fix(cluster_k8s): fix monitoring setup process to be inline with current s-o repo
  sdcm/cluster_k8s/__init__.py
  sdcm/tester.py
  sdcm/utils/common.py
Labels: No Backport Needed, Ready for review

#3197 fix(50gb-3days): fixed the value of the user_prefix
  test-cases/longevity/longevity-50GB-3days-authorization-and-tls-ssl.yaml
Labels: Backport-4.4

#3200 fix(check_kubernetes_monitoring_health): make it don't fail the test if it can't reach prometheus
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed, Ready for review

#3205 refactor(manager-upgrade): changed base version to 2.2
  jenkins-pipelines/manager/centos-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/debian9-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu16-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu18-manager-upgrade.jenkinsfile
Labels: No Backport Needed

#3202 fix(sct_config): remove `store_results_in_elasticsearch`
  defaults/test_default.yaml
  docs/configuration_options.md
  sdcm/sct_config.py
  sdcm/tester.py
  test-cases/artifacts/amazon2.yaml
  test-cases/artifacts/ami.yaml
  test-cases/artifacts/centos7.yaml
  test-cases/artifacts/centos8.yaml
  test-cases/artifacts/debian10.yaml
  test-cases/artifacts/debian9.yaml
  test-cases/artifacts/docker.yaml
  test-cases/artifacts/gce-image.yaml
  test-cases/artifacts/oel76.yaml
  test-cases/artifacts/oel81.yaml
  test-cases/artifacts/rhel7.yaml
  test-cases/artifacts/rhel8.yaml
  test-cases/artifacts/ubuntu1604.yaml
  test-cases/artifacts/ubuntu1804.yaml
  test-cases/artifacts/ubuntu2004.yaml
  test-cases/gemini/gemini-1tb-10h.yaml
  test-cases/gemini/gemini-3h-cdc-postimage-write.yaml
  test-cases/gemini/gemini-3h-cdc-preimage-write.yaml
  test-cases/gemini/gemini-3h-cdc-write.yaml
  test-cases/gemini/gemini-3h-ics-with-nondisruptive-nemesis.yaml
  test-cases/gemini/gemini-3h-with-nemesis.yaml
  test-cases/gemini/gemini-3h-with-nondisruptive-nemesis.yaml
  test-cases/gemini/gemini-8h-large-num-columns.yaml
  test-cases/gemini/gemini-basic-3h-ics.yaml
  test-cases/gemini/gemini-basic-3h.yaml
  test-cases/load/admission_control_overload_test.yaml
  test-cases/longevity/longevity-5000-tables.yaml
  test-cases/longevity/longevity-alternator-200GB-48h.yaml
  test-cases/longevity/longevity-alternator-3h-multidc.yaml
  test-cases/longevity/longevity-alternator-3h.yaml
  test-cases/longevity/longevity-alternator-streams-100gb-4h.yaml
  test-cases/longevity/longevity-multi-keyspaces.yaml
  test-cases/longevity/longevity-ycsb-a-100M.yaml
  test-cases/longevity/longevity-ycsb-a-10M.yaml
  test-cases/longevity/longevity-ycsb-a-1B.yaml
  test-cases/longevity/longevity-ycsb-a-1M.yaml
  test-cases/private-repo/private-repo.yaml
  test-cases/upgrades/manager-upgrade.yaml
  unit_tests/test_config.py
  unit_tests/test_tester.py
Labels: No Backport Needed

#3170 feature(hydra_kcl): Use alternator client load balancer
  sdcm/kcl_thread.py
  sdcm/ycsb_thread.py
Labels: No Backport Needed, Ready for review

#3209 fix(nemesis_toggle_cdc_feature): fix SyntaxWarning for assert
  sdcm/nemesis.py
Labels: Backport-4.4, Ready for review

#3211 fix(data validator): fix wrong assert syntax
  sdcm/utils/data_validator.py
Labels: Backport-4.3, Backport-4.4, Ready for review

#3210 fix(jepsen): increase default concurrency
  defaults/test_default.yaml
Labels: No Backport Needed, Ready for review

#3214 fix(scylla-stop-start-on-k8s): improrer commands were used
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed, Ready for review

#3213 improvement(db_stats): Store in ES output sysctl -a
  sdcm/cluster.py
  sdcm/db_stats.py
Labels: Backport-perf-v10, Backport-perf-v8, Ready for review

#3224 feature(jepsen): add hydra command to run web server with Jepsen results
  sct.py
  sdcm/report_templates/results_jepsen.html
  sdcm/utils/jepsen.py
Labels: No Backport Needed

#3229 improvement(.gitignore): ignore linux swap files (tmp of vim)
  .gitignore
Labels: No Backport Needed

#3225 fix(wait_for_init): Reverting the change to control wait for db_up
  sdcm/cluster.py
  sdcm/cluster_aws.py
  sdcm/cluster_baremetal.py
  sdcm/cluster_docker.py
  sdcm/nemesis.py
Labels: No Backport Needed

#3167 fix(CorruptThenScrubMonkey): fix and renable scrub nemesis
  sdcm/nemesis.py
  sdcm/sct_events/group_common_events.py
Labels: Backport-2020.1, Ready for review

#3222 fix(fullscan): pass credentials for cql connection
  sdcm/tester.py
Labels: Backport-4.4, Ready for review

#3193 fix(sct_runner.py): use larger disk for long longevity
  sdcm/sct_runner.py
Labels: Backport-4.4, Ready for review, Urgent

#3125 improvement(test_latency_with_nemesis): display events to email report
  sct.py
  sdcm/microbenchmarking.py
  sdcm/report_templates/results_base.html
  sdcm/report_templates/results_base_custom.html
  sdcm/report_templates/results_base_new.html
  sdcm/report_templates/results_gemini.html
  sdcm/report_templates/results_issue_template.html
  sdcm/report_templates/results_latency_during_ops.html
  sdcm/report_templates/results_microbenchmark.html
  sdcm/report_templates/results_performance.html
  sdcm/results_analyze/__init__.py
  sdcm/send_email.py
  sdcm/tester.py
Labels: Backport-perf-v10

#3227 fix(db_fill_data): Add timeout after simple table creation
  sdcm/fill_db_data.py
Labels: No Backport Needed, Ready for review

#3204 feature(siren): collect Siren Manager logs
  sdcm/logcollector.py
  sdcm/utils/common.py
Labels: No Backport Needed, Ready for review

#3230 test(nemesis.py): added nemesis that will toggle LDAP connection
  sdcm/nemesis.py
  sdcm/utils/docker_utils.py
Labels: Backport-2020.1

#3233 [branch-2020.1] test(nemesis.py): added nemesis that will toggle LDAP connection
  sdcm/nemesis.py
  sdcm/utils/docker_utils.py
Labels: No Backport Needed

#3099 fix(perf_query): Filter performance tests for last year
  sdcm/results_analyze/__init__.py
  sdcm/tester.py
  sdcm/utils/es_queries.py
Labels: Backport-perf-v10, Backport-perf-v8, Ready for review

#3206 fix(AddRemoveRackNemesis): switch it to use plain values
  sdcm/cluster_k8s/__init__.py
  sdcm/utils/common.py
Labels: No Backport Needed, Ready for review

#3228 improvement(artifacts test cases): enable fallback as 'on demand'
  test-cases/artifacts/amazon2.yaml
  test-cases/artifacts/ami.yaml
  test-cases/artifacts/centos7.yaml
  test-cases/artifacts/centos8.yaml
  test-cases/artifacts/debian10.yaml
  test-cases/artifacts/debian9.yaml
  test-cases/artifacts/gce-image.yaml
  test-cases/artifacts/oel76.yaml
  test-cases/artifacts/oel81.yaml
  test-cases/artifacts/rhel7.yaml
  test-cases/artifacts/rhel8.yaml
  test-cases/artifacts/ubuntu1604.yaml
  test-cases/artifacts/ubuntu1804.yaml
  test-cases/artifacts/ubuntu2004.yaml
Labels: No Backport Needed

#3237 fix(manager): Changed the order of the sanity tests
  mgmt_cli_test.py
Labels: No Backport Needed

#3236 feature(hydra_kcl): Adding time based checkpoints, and retries
  sdcm/kcl_thread.py
Labels: Backport-4.4, Ready for review

#3240 fix(sct_events.py): default filter warning from DB log
  sdcm/sct_events.py
Labels: No Backport Needed, Ready for review

#3246 fix(ycsb_thread): taskset is broken when using `stress_multiplier`
  sdcm/ycsb_thread.py
Labels: No Backport Needed, Ready for review

#3243 fix(dependencies): bump httplib2 and cryptography
  docker/env/version
  requirements.in
  requirements.txt
Labels: New Hydra Version, Ready for review

#3247 fix(cluster.py): Remove apt-get install deprecated option of --force-yes
  sdcm/cluster.py
Labels: Backport-4.4

#3244 feature(perf_report): Add events to all perf reports
  sdcm/report_templates/results_base_custom.html
  sdcm/report_templates/results_latency_during_ops.html
  sdcm/report_templates/results_performance.html
  sdcm/report_templates/results_performance_baseline.html
  sdcm/results_analyze/__init__.py
  sdcm/tester.py
Labels: Backport-perf-v10, Ready for review

#3217 feature(monitoring): add scylla_rsyslog_setup parameter
  defaults/test_default.yaml
  docs/configuration_options.md
  sdcm/cluster.py
  sdcm/sct_config.py
Labels: No Backport Needed, Ready for review

#3249 feature(rsyslog): enable scylla_rsyslog_setup for 200gb job
  test-cases/longevity/longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml
Labels: No Backport Needed, Ready for review

#3250 fix(cluster.py): Fixing remote typo error
  sdcm/cluster.py
Labels: No Backport Needed

#3248 improvement(send_email): add kernel version info
  sdcm/report_templates/results_base.html
  sdcm/report_templates/results_issue_template.html
  sdcm/send_email.py
  sdcm/tester.py
Labels: No Backport Needed

#3234 test(nemesis.py): add test that will toggle LDAP configuration
  sdcm/nemesis.py
  sdcm/tester.py
Labels: Backport-2020.1, Ready for review

#3253 test(nemesis.py): add test that will toggle LDAP configuration
  sdcm/nemesis.py
  sdcm/tester.py
Labels: No Backport Needed, Ready for review

#3255 fix(sdcm/cluster): rename random library to librandom
  sdcm/cluster.py
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed, Ready for review

#3258 fix(issue_template): don't print events and screenshots in the result_issue_template
  sdcm/report_templates/results_issue_template.html
Labels: No Backport Needed, Ready for review

#3259 feature(perf_report): Add events to all perf reports
  sdcm/report_templates/results_base_custom.html
  sdcm/report_templates/results_latency_during_ops.html
  sdcm/report_templates/results_performance.html
  sdcm/report_templates/results_performance_baseline.html
  sdcm/results_analyze/__init__.py
  sdcm/tester.py
Labels: Backport-perf-v10, Ready for review

#3252 feature(resetlocalschema): run 'resetlocalschema'
  sdcm/nemesis.py
Labels: Ready for review

#3266 fix(cluster.py): unsupported python3.9 feature
  sdcm/cluster.py
Labels: No Backport Needed, Urgent

#3261 test(ldap authorization): add new test
  jenkins-pipelines/feature-ldap-authorization-longevity-50gb-3days.jenkinsfile
Labels: Backport-2020.1, Ready for review

#3260 test(nemesis.py): add LDAP nemesis to limited chaos monkey
  sdcm/nemesis.py
Labels: Backport-2020.1, Ready for review

#3267 feature(perf_query): Use wide queries to get results from ES
  sdcm/results_analyze.py
  sdcm/tester.py
Labels: Backport-perf-v8, Ready for review

#3265 feature(private_repo_test): remove private repo test
  docs/artifacts_test.md
  jenkins-pipelines/private-repo.jenkinsfile
  private_repo_test.py
  sdcm/send_email.py
  test-cases/private-repo/private-repo.yaml
Labels: No Backport Needed

#3241 fix(sct_events.py): default filter warning from DB log
  sdcm/sct_events/setup.py
Labels: No Backport Needed, Ready for review

#3268 fix(upgrade cluster): Remove apt-get install deprecated option of --force-yes
  sdcm/cluster.py
  upgrade_test.py
Labels: Backport-4.4

#3271 fix(sdcm/sct_events.py): regex pattern missed .*
  sdcm/sct_events.py
Labels: No Backport Needed, Ready for review

#3272 fix(sdcm/sct_events.py): regex pattern missed .*
  sdcm/sct_events/setup.py
Labels: No Backport Needed, Ready for review

#3270 fix(restart_then_repair): filter out 'Can't find a column family with UUID' backtrace
  sdcm/nemesis.py
Labels: Backport-4.4, Ready for review
