Repository scylladb/scylla-cluster-tests, pull requests merged in 2021-05, with the labels that each got.

#3489 improvement(kubernetes): use latest versions for mgmt and mgmt-agent
  defaults/k8s_eks_config.yaml
  defaults/k8s_gce_minikube_config.yaml
  defaults/k8s_gke_config.yaml
Labels: Backport-operator-1.2

#3474 improvement(latency.py): improved the collect_latency
  sdcm/utils/latency.py
Labels: Backport-perf-v10, Ready for review, Ready to be Merged

#3488 fix(k8s-eks): add send_email step in rollingOperatorUpgradePipeline
  vars/rollingOperatorUpgradePipeline.groovy
Labels: Backport-operator-1.2

#3482 fix(ubuntu2004): switch to new unified source
  test-cases/artifacts/ubuntu2004.yaml
Labels: No Backport Needed, Ready for review

#3487 fix(k8s-eks): create SCT runner in rollingOperatorUpgradePipeline
  vars/rollingOperatorUpgradePipeline.groovy
Labels: Backport-operator-1.2

#3496 test(scylla-manager): set use_mgmt on test_default.yaml
  configurations/alternator/streams-with-nemesis.yaml
  defaults/test_default.yaml
  internal_test_data/complex_test_case_with_version.yaml
  internal_test_data/multi_region_dc_test_case.yaml
  test-cases/PR-provision-test.yaml
  test-cases/features/system-sla-test.yaml
  test-cases/longevity/longevity-100GB-48h-cloud-CloudLimitedChaosMonkey-tls.yaml
  test-cases/longevity/longevity-100gb-4h.yaml
  test-cases/longevity/longevity-1TB-7days-authorization-and-tls-ssl.yaml
  test-cases/longevity/longevity-200GB-48h-network-monkey.yaml
  test-cases/longevity/longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml
  test-cases/longevity/longevity-2TB-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis.yaml
  test-cases/longevity/longevity-50GB-12h-verifier-LimitedMonkey-tls.yaml
  test-cases/longevity/longevity-alternator-200GB-48h.yaml
  test-cases/longevity/longevity-alternator-3h-multidc.yaml
  test-cases/longevity/longevity-alternator-3h.yaml
  test-cases/longevity/longevity-counters-3h.yaml
  test-cases/longevity/longevity-counters-multidc.yaml
  test-cases/longevity/longevity-encryption-at-rest-200GB-6h.yaml
  test-cases/longevity/longevity-in-memory-36GB-1day.yaml
  test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml
  test-cases/longevity/longevity-large-partition-3h.yaml
  test-cases/longevity/longevity-large-partition-4days.yaml
  test-cases/longevity/longevity-large-partition-8h.yaml
  test-cases/longevity/longevity-multi-keyspaces.yaml
  test-cases/longevity/longevity-mv-si-4days.yaml
  test-cases/longevity/longevity-ndbench-100gb-4h.yaml
  test-cases/manager/manager-backup-1TB-gce.yaml
  test-cases/manager/manager-regression-gce.yaml
  test-cases/manager/manager-regression-ipv6.yaml
  test-cases/manager/manager-regression-multiDC-set-distro.yaml
  test-cases/manager/manager-repair-control.yaml
  test-cases/manager/manager-repair-intensity-multiple-repaired-nodes.yaml
  test-cases/manager/manager-repair-intensity-single-repaired-nodes.yaml
  test-cases/performance/perf-regression-latency-250gb-with-nemesis.yaml
  test-cases/scylla-operator/longevity-scylla-operator-3h-backup.yaml
  test-cases/scylla-operator/longevity-scylla-operator-3h-repair.yaml
  test-cases/scylla-operator/longevity-scylla-operator-3h.yaml
  test-cases/scylla-operator/longevity-scylla-operator-basic-3h.yaml
  test-cases/upgrades/manager-upgrade.yaml
Labels: Ready for review

#3497 fix(test_defaults scylla_mgmt_agent_repo): Changing default manager
  defaults/test_default.yaml
Labels: No Backport Needed

#3486 fix(kill_gemini_thread): Switch signal for kill gemini process
  sdcm/cluster.py
Labels: Backport-2021.1, Backport-4.5, Ready for review

#3481 fix(cdc.options): Fix assertion of cdc properties
  sdcm/utils/cdc/options.py
Labels: Backport-2021.1, Backport-4.4, Backport-4.5, Ready for review

#3469 Change loader for 5k tables test - newest loader doesn't work for this test
  test-cases/longevity/longevity-5000-tables.yaml
  test-cases/longevity/longevity-multi-keyspaces.yaml
Labels: Backport-2020.1, Backport-2021.1, Backport-4.3, Backport-4.4, Backport-4.5

#3499 fix(k8s-gke): disable basic auth for K8S
  sdcm/cluster_k8s/gke.py
Labels: Backport-operator-1.2

#3492 fix(port-availability-checks): make sure that ss binary is installed
  sdcm/cluster.py
Labels: Backport-operator-1.2

#3498 fix(get_scylla_versions): add to regex corner case
  sdcm/db_stats.py
Labels: Backport-4.5, Backport-perf-v10, Backport-perf-v8, Urgent

#3500 fix(asymmetric cluster): decrease c-s duration command from 540 min to 170min
  test-cases/longevity/longevity-large-partition-3h.yaml
Labels: Backport-2021.1, Ready for review

#3501 fix(k8s-eks): define 'backup_bucket_location' for manager tests
  defaults/k8s_eks_config.yaml
Labels: Backport-operator-1.2

#3505 improvement(keep_alive): set to 11 hours
  sdcm/cluster.py
Labels: Backport-2021.1

#3506 fix(scylla_rsyslog_setup): disable scylla_rsyslog_setup in branch-2021.1
  test-cases/longevity/longevity-50GB-12h-verifier-LimitedMonkey-tls.yaml
Labels: No Backport Needed, Ready for review

#3513 fix(node_setup): update repo cache for db nodes
  sdcm/cluster.py
Labels: Backport-2021.1, Ready for review

#3515 fix(amazon2 artifact): changed manager repo defaults
  jenkins-pipelines/artifacts-amazon2.jenkinsfile
Labels: No Backport Needed

#3516 fix(artifact debian10): changed scylla_mgmt_agent_repo
  jenkins-pipelines/artifacts-debian10.jenkinsfile
  jenkins-pipelines/nonroot-offline-install/artifacts-debian10.jenkinsfile
  test-cases/artifacts/debian10.yaml
Labels: No Backport Needed

#3519 fix(option parse): fix a typo in choise list of --dist-version
  sct.py
Labels: No Backport Needed, Ready for review

#3514 fix(disrupt_memory_stress): stress-ng install
  sdcm/nemesis.py
Labels: Backport-2021.1, Backport-4.5, Ready for review

#3520 fix(upgrade test): ignore "Can't find column family" err
  sdcm/sct_events/group_common_events.py
Labels: No Backport Needed, Ready for review

#3521 fix(mutation_write_exception): add warning for system.paxos timeout messages
  defaults/severities.yaml
  sdcm/sct_events/database.py
  unit_tests/test_sct_events_database.py
Labels: Backport-2021.1, Backport-4.5, Ready for review

#3531 fix(email): correct snapshot links according to name
  sdcm/report_templates/results_base.html
Labels: Backport-2021.1, Ready for review

#3527 fix(scylla-upgrade): make fill_db_data module use proper queries
  sdcm/fill_db_data.py
Labels: Backport-operator-1.2

#3507 fix(k8s-eks): gather monitoring set data correctly
  sdcm/logcollector.py
Labels: Backport-operator-1.2

#3526 fix(k8s-gke): use 10m timeout for minio pod readiness kubectl call
  sdcm/cluster_k8s/__init__.py
Labels: Backport-operator-1.2

#3523 fix(ipv6 config): ubuntu 20.04 network
  sdcm/cluster_aws.py
Labels: Backport-2021.1

#3533 fix(nodetool event): don't pusblish nodetool event when failure expected
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#3534 fix(local-ear config): moving secret key from /tmp to /etc/scylla/encrypt_conf/
  configurations/local-ear.yaml
Labels: Backport-2021.1, Ready for review

#3540 fix(kubernetes): define KUBECONFIG running cleanup resources
  sdcm/utils/common.py
Labels: Backport-operator-1.2

#3537 fix(k8s-gke): wait for minio app pod correctly
  sdcm/cluster_k8s/__init__.py
Labels: Backport-operator-1.2

#3539 improvement(kubernetes): use custom cache dir for kubectl
  sdcm/utils/k8s.py
Labels: Backport-operator-1.2

#3535 test(ldap with audit features): add new pipeline job
  jenkins-pipelines/feature-ldap-authorization-and-audit-longevity-100gb-4h.jenkinsfile
Labels: Backport-2021.1

#3447 feature(nemesis.py) New rolling internode communication configuration…
  sdcm/nemesis.py
Labels: Ready for review

#3544 fix(mgmt_agent_repo): url changed
  vars/perfRegressionParallelPipeline.groovy
Labels: No Backport Needed, Urgent

#3547 fix(logcollector): log warning using DirLog class on remote nodes
  sdcm/logcollector.py
Labels: Backport-operator-1.2

#3545 fix(mgmt_agent_repo): url changed
  defaults/test_default.yaml
Labels: No Backport Needed, Urgent

#3562 ci(artifactsPipeline): always export scylla_manager* params
  vars/artifactsPipeline.groovy
Labels: Ready for review, Urgent

#3556 fix(longevity-1tb-7days): Removing stress commands of compressed tables
  test-cases/longevity/longevity-1TB-7days-authorization-and-tls-ssl.yaml
Labels: Backport-4.5

#3567 refactor(longevity-50gb-3d): Remove stress commands of compressed tables
  test-cases/longevity/longevity-50GB-3days-authorization-and-tls-ssl.yaml
Labels: Backport-4.5

#3571 fix(offline install): disable scylla-manager for offline artifact-tests
  vars/artifactsPipeline.groovy
Labels: Backport-4.5, Ready for review

#3491 improvement(fullscan): Add CQL TIMEOUT parameter to full-scan query
  sdcm/tester.py
Labels: Backport-4.4, Backport-4.5

#3532 fix(TerminateAndRemoveNode): remove node from dead list
  sdcm/nemesis.py
Labels: Backport-2021.1, Backport-4.4, Backport-4.5, Ready for review, Ready to be Merged

#3549 improvement(results_latency_during_ops.html): color lines
  sdcm/report_templates/results_latency_during_ops.html
  sdcm/utils/latency.py
Labels: Backport-perf-v10, Ready for review

#3565 refactor(manager): Changed all manager repos to 2.3
  defaults/test_default.yaml
  test-cases/artifacts/amazon2.yaml
  test-cases/artifacts/ami.yaml
  test-cases/artifacts/centos7.yaml
  test-cases/artifacts/centos8.yaml
  test-cases/artifacts/debian10.yaml
  test-cases/artifacts/debian9.yaml
  test-cases/artifacts/docker.yaml
  test-cases/artifacts/gce-image.yaml
  test-cases/artifacts/oel76.yaml
  test-cases/artifacts/oel81.yaml
  test-cases/artifacts/rhel7.yaml
  test-cases/artifacts/rhel8.yaml
  test-cases/artifacts/ubuntu1604.yaml
  test-cases/artifacts/ubuntu1804.yaml
  test-cases/manager/manager-backup-1TB-gce.yaml
Labels: No Backport Needed

#3449 test(perf-test): new performance test with not 100% cached
  jenkins-pipelines/perf-regression-throughput-125gb.jenkinsfile
  performance_regression_test.py
  test-cases/performance/perf-regression-throughput-125gb.yaml
Labels: Backport-perf-v10, Ready for review

#3573 fix(results_analyze.get_events): Set correct variable type
  sdcm/results_analyze/__init__.py
Labels: Backport-perf-v10, Ready for review, Urgent

#3579 fix(rolling-upgrade): Disable usage of manager in rolling upgrades
  test-cases/upgrades/rolling-upgrade.yaml
Labels: Backport-4.5

#3577 fix(poweroff-event): filtering when terminate is run
  sdcm/cluster.py
  sdcm/nemesis.py
Labels: Backport-4.5

#3580 improvement(filters.py): Add extra parameters to printout for filters
  sdcm/sct_events/filters.py
Labels: No Backport Needed, Ready for review

#3585 fix(gemini-tests): Change gemini oracle cluster scylla version to 4.3.3
  test-cases/gemini/gemini-1tb-10h.yaml
  test-cases/gemini/gemini-3h-with-nemesis.yaml
  test-cases/gemini/gemini-basic-3h.yaml
Labels: Backport-4.5, Ready for review, Urgent

#3588 fix(performance): Disable use_mgmt for disk and cache
  test-cases/performance/perf-regression-throughput-125gb.yaml
Labels: Backport-perf-v11, Ready for review

#3589 fix(get_cluster_aws): disable use_mgmt for oracle cluster
  sdcm/tester.py
Labels: Backport-4.5, Ready for review, Urgent

#3590 improvement(k8s-eks): stop using ELB service
  sdcm/cluster_k8s/eks.py
Labels: Backport-operator-1.2

#3594 fix(mgmt-backup): use proper bucket on EKS backend
  defaults/k8s_eks_config.yaml
Labels: Backport-operator-1.2

#3570 fix(upgrade_test): copy to /etc/scylla dir require sudo
  upgrade_test.py
Labels: Backport-4.5, Ready for review

#3564 improvement(results_latency_during_ops.html): add legend to table result
  sdcm/report_templates/results_latency_during_ops.html
  sdcm/results_analyze/__init__.py
  sdcm/tester.py
Labels: Backport-perf-v10, Backport-perf-v11, Ready for review

#3587 fix(tester): make all threads daemonic by default
  sdcm/tester.py
  sdcm/utils/common.py
Labels: Ready for review

#3591 fix(generic-rolling-upgrade): Disabling the usage of manager
  test-cases/upgrades/generic-rolling-upgrade.yaml
Labels: Backport-4.5

#3557 Refactoring 1tb longevity
  jenkins-pipelines/ics-longevity-1tb-7days.jenkinsfile
  jenkins-pipelines/longevity-1tb-7days-gce.jenkinsfile
  jenkins-pipelines/longevity-1tb-7days.jenkinsfile
  test-cases/longevity/longevity-1TB-5days-authorization-and-tls-ssl.yaml
  test-cases/longevity/longevity-1TB-7days-authorization-and-tls-ssl.yaml
Labels: Backport-4.5

#3595 fix(node_setup): disable iptables service
  sdcm/cluster.py
Labels: Backport-4.5, Ready for review
