Repository scylladb/scylla-cluster-tests, pull requests merged in 2021-04, with the labels that each got.

#3336 fix(manager-upgrade): changing test order
  mgmt_upgrade_test.py
Labels: Backport-manager-v2.3

#3368 fix(getCloudProviderFromBackend): not fail with there no backend defined
  vars/getCloudProviderFromBackend.groovy
Labels: Backport-4.5

#3352 improvement(jepsen): add test count and run policy options
  defaults/test_default.yaml
  docs/configuration_options.md
  jepsen_test.py
  sdcm/sct_config.py
  test-cases/jepsen/jepsen.yaml
Labels: No Backport Needed, Ready for review

#3086 Backport: enable Internode compression for 2020.1
  jenkins-pipelines/rolling-upgrade-ami.jenkinsfile
  jenkins-pipelines/rolling-upgrade-centos7.jenkinsfile
Labels: Pending

#3372 fix(fill_db_data.py): correct the support version of enterprise
  sdcm/fill_db_data.py
Labels: Backport-2021.1, Ready for review

#3373 Upgrade backport 2021.1
  sdcm/fill_db_data.py
Labels: No Backport Needed, Ready for review

#3378 fix(upgrade): disable unsupported upgrade test
  jenkins-pipelines/rolling-upgrade-centos8.jenkinsfile
  jenkins-pipelines/rolling-upgrade-debian10.jenkinsfile
  jenkins-pipelines/rolling-upgrade-ubuntu20.04.jenkinsfile
Labels: No Backport Needed, Ready for review

#3375 fix(lwt longevity): filter out mutation errors on system.paxos
  longevity_lwt_test.py
Labels: Backport-2020.1, Backport-2021.1, Ready for review

#3381 fix(health_checker.py): increase retry sleep time
  sdcm/utils/health_checker.py
Labels: Backport-2021.1, No Backport Needed, Ready for review

#3380 fix(fill_db_data): null as condition
  sdcm/fill_db_data.py
Labels: No Backport Needed, Ready for review

#3386 improvement(scylla-bench): collect logs at the end of the test
  sdcm/logcollector.py
Labels: Backport-2021.1

#3387 fix(manager default): scylla now uses Focal Fossa as default
  defaults/test_default.yaml
Labels: Backport-perf-v10, Backport-perf-v8, Urgent

#3371 fix(data validator): Disable DataValidator for LWT test with parallel nemesis
  longevity_lwt_test.py
Labels: Backport-4.4, Backport-4.5, Ready for review

#3389 [branch-2020.1] fix(check_nodes_status): check if remove nodes list is None
  sdcm/utils/health_checker.py
Labels: Ready for review

#3390 [branch-2020.1] fix(lwt longevity): 'ignore_mutation_write_errors' function doesn't exist in 2020.1
  longevity_lwt_test.py
Labels: No Backport Needed, Ready for review

#3391 fix(coredump-monitoring-thread): ignore test coredumps generated by SMI
  sdcm/cluster.py
Labels: No Backport Needed

#3393 fix(node-setup): disable daily triggered services for Ubuntu
  sdcm/cluster.py
Labels: No Backport Needed

#3365 fix(kubernetes): update lib and k8s versions
  defaults/k8s_gke_config.yaml
  docker/env/version
  requirements.in
  requirements.txt
  sdcm/utils/gce_utils.py
Labels: Backport-operator-1.1

#3394 fix(parallel nemesis test): rename the pipeline
  jenkins-pipelines/longevity-2TB-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis.jenkinsfile
Labels: Backport-2021.1, Backport-4.5

#3401 branch-2021.1: fix boto3 import error
  sdcm/tester.py
Labels: No Backport Needed, Ready for review, Urgent

#3354 fix(kubernetes): fix terminate_decommission_add_node_kubernetes nemesis
  sdcm/cluster_k8s/__init__.py
  sdcm/nemesis.py
Labels: Backport-operator-1.1

#3366 refactor(kubernetes): squash set_target_node and set_last_node_as_target
  sdcm/nemesis.py
Labels: Backport-operator-1.1

#3405 fix(artifact-test): assign scylla_mgmt_agent_repo for different distros
  test-cases/artifacts/centos7.yaml
  test-cases/artifacts/centos8.yaml
  test-cases/artifacts/debian10.yaml
  test-cases/artifacts/debian9.yaml
  test-cases/artifacts/oel76.yaml
  test-cases/artifacts/oel81.yaml
  test-cases/artifacts/ubuntu1604.yaml
  test-cases/artifacts/ubuntu1804.yaml
  test-cases/artifacts/ubuntu2004.yaml
Labels: Backport-4.5, Ready for review, Urgent

#3399 Saslauthd fix: optionally prepare saslauthd and add support of Ubuntu
  sdcm/cluster.py
  sdcm/utils/common.py
Labels: No Backport Needed, Ready for review, Urgent

#3404 Apt daily services fix
  sdcm/cluster.py
Labels: No Backport Needed, Ready for review

#3403 fix(logcollector): Added dmesg output to collecting logs
  sdcm/logcollector.py
Labels: Backport-4.4, Backport-4.5, Ready for review

#3406 fix(disable_daily_triggered_services): fix typo in repo path
  test-cases/artifacts/debian10.yaml
  test-cases/artifacts/debian9.yaml
  test-cases/artifacts/ubuntu1604.yaml
  test-cases/artifacts/ubuntu1804.yaml
  test-cases/artifacts/ubuntu2004.yaml
Labels: Ready for review

#3407 fix(scylla-bench): log time inconsistency
  sdcm/sct_events/base.py
Labels: Ready for review

#3412 improvement(memory_stress): support stress-ng installation on Ubuntu
  sdcm/nemesis.py
Labels: Backport-4.5

#3414 fix(event log): use clear target_node in DisruptionEvent log
  sdcm/sct_events/nemesis.py
Labels: No Backport Needed, Ready for review

#3402 fix (unittest): workaround the fail in test_search_cdc_invalid_request_2021_1
  unit_tests/test_cluster.py
Labels: No Backport Needed, Ready for review

#3313 fix(configure_ldap): there is a race condition between
  sdcm/cluster.py
  sdcm/nemesis.py
  sdcm/utils/ldap.py
Labels: Backport-2020.1, Backport-2021.1

#3351 feature(grafana): wait grafana page loading by panels
  sct.py
  sdcm/cluster.py
  sdcm/logcollector.py
  sdcm/monitorstack/__init__.py
  sdcm/monitorstack/ui.py
  sdcm/utils/remotewebbrowser.py
Labels: Ready for review

#3417 improvement(large_collections.yaml): Added a static column to c-s user-profile
  data_dir/large_collections.yaml
Labels: Backport-2021.1, Backport-4.4

#3418 fix(artifact-test): assign scylla_mgmt_agent_repo for amazon2
  test-cases/artifacts/amazon2.yaml
Labels: Backport-4.5, Ready for review

#3419 fix(monitoring): Switch monitoring branch to 3.7
  defaults/test_default.yaml
Labels: Backport-2021.1, Backport-4.5, Ready for review

#3425 fix(mgmt agent repo): workaround to new base image
  jenkins-pipelines/perf-regression-latency-250gb-with-nemesis.jenkinsfile
  vars/perfRegressionParallelPipeline.groovy
Labels: No Backport Needed, Ready for review, Urgent

#3409 fix(EaR pipeline): correct the pipeline file name
  jenkins-pipelines/EaR-longevity-kmip-50gb-4d.jenkinsfile
  jenkins-pipelines/EaR-longevity-local-50gb-4d.jenkinsfile
  jenkins-pipelines/EaR-longevity-replicated-50gb-4d.jenkinsfile
  jenkins-pipelines/ics-longevity-50gb-4days.jenkinsfile
Labels: Backport-2021.1, Ready for review

#3423 fix(apt install lock): since moved to Ubuntu base image
  sdcm/cluster.py
Labels: Backport-4.5, Backport-perf-v10, Ready for review, Urgent

#3429 refactor(manager-tests): changed scylla_version from master:latest to 4.4
  jenkins-pipelines/manager/centos-manager-backup-gce.jenkinsfile
  jenkins-pipelines/manager/centos-manager-backup.jenkinsfile
  jenkins-pipelines/manager/centos-manager-repair-control.jenkinsfile
  jenkins-pipelines/manager/centos-manager-repair-intensity-multiple-repaired-nodes.jenkinsfile
  jenkins-pipelines/manager/centos-manager-repair-intensity-single-repaired-nodes.jenkinsfile
  jenkins-pipelines/manager/centos-manager-sanity-ipv6.jenkinsfile
  jenkins-pipelines/manager/centos-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/centos-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/debian10-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/debian10-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/debian9-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/debian9-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu16-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/ubuntu16-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu18-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/ubuntu18-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu20-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/ubuntu20-manager-upgrade.jenkinsfile
Labels: Backport-manager-v2.4

#3431 fix(k8s-eks): add aws_region option to basic k8s-eks job
  jenkins-pipelines/operator/eks/longevity-scylla-operator-basic-3h-eks.jenkinsfile
Labels: Backport-operator-1.1, Ready for review

#3420 fix(artifact oel81): fix user prefix
  test-cases/artifacts/oel81.yaml
Labels: Ready for review

#3436 fix(k8s-logs): fix k8s log collector
  sdcm/logcollector.py
Labels: Backport-operator-1.1, Ready for review

#3437 fix(mgmt agent repo): make the URL entry connect to the job
  jenkins-pipelines/perf-regression-latency-250gb-with-nemesis.jenkinsfile
  vars/perfRegressionParallelPipeline.groovy
Labels: No Backport Needed, Ready for review

#3438 fix(typo on pipeline): missed quotes in the pipeline params
  vars/perfRegressionParallelPipeline.groovy
Labels: No Backport Needed

#3428 fix(system_auth and ldap): possible race condition
  sdcm/tester.py
Labels: Backport-2020.1, Backport-2021.1

#3432 fix(system_auth and ldap): possible race condition
  sdcm/tester.py
Labels: No Backport Needed, Ready for review

#3435 fix(get_scylla_versions): inaccurate regex for scylla-server
  sdcm/db_stats.py
Labels: Backport-perf-v10, Backport-perf-v8

#3415 feature(sct event): add POWER_OFF event
  defaults/severities.yaml
  sdcm/cluster_aws.py
  sdcm/sct_events/database.py
  unit_tests/test_cluster.py
  unit_tests/test_data/power_off.log
  unit_tests/test_sct_events_database.py
Labels: No Backport Needed, Ready for review

#3433 fix(configure_ldap): there is a race condition between
  sdcm/cluster.py
  sdcm/nemesis.py
  sdcm/utils/ldap.py
Labels: No Backport Needed, Ready to be Merged

#3427 improvement(db-events): add event where scylla restarted due to timeout
  defaults/severities.yaml
  sdcm/sct_events/database.py
  unit_tests/test_sct_events_database.py
Labels: Ready for review

#3444 fix(email-report): fix calculation of scylla-version for email reports
  sdcm/cluster.py
Labels: Backport-operator-1.1, Ready for review

#3443 fix(email-report): Fix getting instance type for all the backends
  sdcm/tester.py
Labels: Backport-operator-1.1, Backport-operator-1.2, Ready for review

#3426 improvement(db-events): add scylla server stop event
  defaults/severities.yaml
  sdcm/sct_events/database.py
  unit_tests/test_sct_events_database.py
Labels: Ready for review

#3458 fix(disrupt_memory_stress): use is_rhel_like, is_ubuntu as properties
  sdcm/nemesis.py
Labels: No Backport Needed

#3445 fix(SaslauthdAuth): read config by remote_scylla_yaml helper
  sdcm/cluster.py
  sdcm/nemesis.py
Labels: Backport-2021.1, Ready for review

#3454 fix(k8s-gke): use existing k8s version
  defaults/k8s_gke_config.yaml
Labels: Backport-operator-1.1, Backport-operator-1.2

#3446 refactor(manager-upgrade): changed base manager version from 2.2 to 2.3
  jenkins-pipelines/manager/centos-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/debian10-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/debian9-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu16-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu18-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu20-manager-upgrade.jenkinsfile
Labels: Backport-manager-v2.4

#3460 improvement(perf with nemesis): rename function to have better report
  sdcm/nemesis.py
Labels: Backport-perf-v10, Ready for review

#3442 fix(convert s-b metrics): fix metric conversion to float
  sdcm/scylla_bench_thread.py
  sdcm/utils/common.py
  unit_tests/test_utils_common.py
Labels: Ready for review

#3466 fix(skip nemesis before running part of it): when no prepare_saslauthd
  sdcm/nemesis.py
Labels: Backport-2021.1

#3364 test(gemini-ics-cdc): New test gemini + cdc + ics
  gemini_test.py
  jenkins-pipelines/gemini-3h-ics-cdc-with-nemesis.jenkinsfile
  test-cases/gemini/gemini-3h-ics-cdc-with-nemesis.yaml
Labels: Backport-2021.1, Ready for review

#3451 ci(jenkins): use longevityPipeline instead of operatorPipeline
  jenkins-pipelines/k8s-longevity-10gb-1h.jenkinsfile
  jenkins-pipelines/operator/eks/longevity-scylla-operator-basic-3h-eks.jenkinsfile
  jenkins-pipelines/operator/gke/longevity-scylla-operator-3h-gke-add-remove-rack.jenkinsfile
  jenkins-pipelines/operator/gke/longevity-scylla-operator-3h-gke-backup.jenkinsfile
  jenkins-pipelines/operator/gke/longevity-scylla-operator-3h-gke-cluster-rolling.jenkinsfile
  jenkins-pipelines/operator/gke/longevity-scylla-operator-3h-gke-grow-shrink.jenkinsfile
  jenkins-pipelines/operator/gke/longevity-scylla-operator-3h-gke-repair.jenkinsfile
  jenkins-pipelines/operator/gke/longevity-scylla-operator-3h-gke-replace.jenkinsfile
  jenkins-pipelines/operator/gke/longevity-scylla-operator-3h-gke-stop-start.jenkinsfile
  jenkins-pipelines/operator/gke/longevity-scylla-operator-3h-gke-terminate-decommission-add.jenkinsfile
  jenkins-pipelines/operator/gke/longevity-scylla-operator-3h-gke-terminate-replace.jenkinsfile
  jenkins-pipelines/operator/gke/longevity-scylla-operator-3h-gke.jenkinsfile
  jenkins-pipelines/operator/gke/longevity-scylla-operator-basic-3h-gke.jenkinsfile
  jenkins-pipelines/operator/minikube/longevity-scylla-operator-3h-minikube.jenkinsfile
  vars/longevityPipeline.groovy
  vars/operatorPipeline.groovy
  vars/runSctTest.groovy
Labels: Backport-operator-1.2

#3307 fix(kubernetes): workaround wrong scheduling of scylla-manager
  sdcm/cluster_k8s/__init__.py
  sdcm/utils/k8s.py
Labels: Backport-operator-1.2

#3457 improvement(events): delete ScyllaOperatorRestartEvent event
  defaults/severities.yaml
  sdcm/cluster_k8s/__init__.py
  sdcm/cluster_k8s/operator_monitoring.py
  sdcm/sct_events/operator.py
  unit_tests/test_sct_events_operator.py
Labels: Backport-operator-1.2

#3455 ci(getJobTimeouts): increase timeout for cleanup
  vars/getJobTimeouts.groovy
Labels: Backport-operator-1.2

#3450 ci(k8s-gke): enable backtrace_decoding
  defaults/k8s_gke_config.yaml
Labels: Backport-operator-1.2

#3456 fix(kubernetes): Update ScyllaOperatorBasicOperationsMonkey
  sdcm/nemesis.py
Labels: Backport-operator-1.2

#3465 improvement(k8s-eks): enable K8S monitroing installation
  defaults/k8s_eks_config.yaml
  sdcm/tester.py
Labels: Backport-operator-1.2

#3471 fix(AMI loader): update both go and scylla-bench
  sdcm/cluster.py
Labels: Backport-2021.1, Ready for review

#3468 fix(upgrade_test/yum): downgrade package with strict pattern
  upgrade_test.py
Labels: Backport-2021.1, Ready for review

#3472 fix(manager): internal wait functions to throw error on timeout
  sdcm/mgmt/cli.py
Labels: Backport-manager-v2.3, Backport-manager-v2.4

#3464 fix(k8s-monitoring): use just one values file for Helm chart
  sdcm/cluster_k8s/__init__.py
  sdcm/utils/k8s.py
  unit_tests/test_utils_k8s.py
Labels: Backport-operator-1.2

#3473 fix(k8s-eks): bump scylla version for the EKS backend
  defaults/k8s_eks_config.yaml
Labels: Backport-operator-1.2

#3476 fix(k8s-eks): fix usage of aws runner for EKS
  vars/runCleanupResource.groovy
  vars/runCollectLogs.groovy
  vars/runSctTest.groovy
  vars/runSendEmail.groovy
Labels: Backport-operator-1.2

#3477 fix(k8s-eks): enable terminate and replace nemesis
  sdcm/nemesis.py
Labels: Backport-operator-1.2

#3478 fix(kubernetes): add node affinity rules for dns resolver pod
  sdcm/k8s_configs/dns-resolver-pod.yaml
Labels: Backport-operator-1.2

#3411 feature(nodetool event): add event for nodetool command
  defaults/severities.yaml
  performance_regression_lwt_test.py
  sdcm/cluster.py
  sdcm/nemesis.py
  sdcm/sct_events/nodetool.py
  unit_tests/test_sct_events_nodetool.py
Labels: No Backport Needed, Ready for review

#3479 fix(k8s-eks): delete K8S LB service if exists recreating scylla nodes
  sdcm/utils/k8s.py
Labels: Backport-operator-1.2

#3480 fix(upgrade_mgmt): skip interactive in upgrading scylla-manager
  sdcm/cluster.py
Labels: No Backport Needed, Ready for review

#3485 fix(k8s-eks): use latest scylla versions in upgrade CI jobs
  jenkins-pipelines/operator/upgrade/upgrade-major-scylla-k8s-eks.jenkinsfile
  jenkins-pipelines/operator/upgrade/upgrade-scylla-k8s-eks.jenkinsfile
Labels: Backport-operator-1.2
