Repository scylladb/scylla-cluster-tests, pull requests merged in 2021-01, with the labels that each got.

#3026 fix(upgrade_tests): wait until stress is starting
  sdcm/loader.py
  sdcm/tester.py
  upgrade_test.py
Labels: No Backport Needed, Ready for review

#3093 fix(scylla-operator-tests): increase test_duration to avoid test failures
  test-cases/scylla-operator/longevity-scylla-operator-3h-gke-add-remove-rack.yaml
  test-cases/scylla-operator/longevity-scylla-operator-3h-gke-cluster-rolling.yaml
  test-cases/scylla-operator/longevity-scylla-operator-3h-gke-grow-shrink.yaml
  test-cases/scylla-operator/longevity-scylla-operator-3h-gke-replace.yaml
  test-cases/scylla-operator/longevity-scylla-operator-3h-gke-stop-start.yaml
  test-cases/scylla-operator/longevity-scylla-operator-3h-gke-terminate-decommission-add.yaml
  test-cases/scylla-operator/longevity-scylla-operator-3h-gke-terminate-recover.yaml
  test-cases/scylla-operator/longevity-scylla-operator-3h-gke-terminate-replace.yaml
  test-cases/scylla-operator/longevity-scylla-operator-3h-gke.yaml
  test-cases/scylla-operator/longevity-scylla-operator-basic-3h-gke.yaml
Labels: No Backport Needed

#3094 fix(nemesis): unset node nemesis before getting list of nodes
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#3108 fix(versions): latest released to version under test
  jenkins-pipelines/rolling-upgrade-ami.jenkinsfile
  jenkins-pipelines/rolling-upgrade-centos7.jenkinsfile
  jenkins-pipelines/rolling-upgrade-debian9.jenkinsfile
  jenkins-pipelines/rolling-upgrade-ubuntu16.04.jenkinsfile
  jenkins-pipelines/rolling-upgrade-ubuntu18.04.jenkinsfile
Labels: No Backport Needed

#3050 feature(nemesis_publisher): report each nemesis result into elastic
  sdcm/db_stats.py
  sdcm/nemesis.py
  sdcm/nemesis_publisher.py
  utils/migrate_nemesis_data.py
Labels: No Backport Needed, Ready for review

#3106 feature(gce-siren): introducing a new backend
  sdcm/sct_config.py
  sdcm/tester.py
  sdcm/utils/common.py
Labels: No Backport Needed, Ready for review

#3100 fix(perf regression): add steady state info events
  sdcm/nemesis.py
Labels: Backport-perf-v10

#3101 fix(increase c-s time): perf-regression-latency-250gb-with-nemesis
  test-cases/performance/perf-regression-latency-250gb-with-nemesis.yaml
Labels: Backport-perf-v10

#3112 fix(scylla-operator jenkins): increase timeout
  jenkins-pipelines/longevity-scylla-operator-3h-gke-add-remove-rack.jenkinsfile
  jenkins-pipelines/longevity-scylla-operator-3h-gke-cluster-rolling.jenkinsfile
  jenkins-pipelines/longevity-scylla-operator-3h-gke-grow-shrink.jenkinsfile
  jenkins-pipelines/longevity-scylla-operator-3h-gke-replace.jenkinsfile
  jenkins-pipelines/longevity-scylla-operator-3h-gke-stop-start.jenkinsfile
  jenkins-pipelines/longevity-scylla-operator-3h-gke-terminate-decommission-add.jenkinsfile
  jenkins-pipelines/longevity-scylla-operator-3h-gke-terminate-recover.jenkinsfile
  jenkins-pipelines/longevity-scylla-operator-3h-gke-terminate-replace.jenkinsfile
  jenkins-pipelines/longevity-scylla-operator-3h-gke.jenkinsfile
  jenkins-pipelines/longevity-scylla-operator-3h-minikube.jenkinsfile
  jenkins-pipelines/longevity-scylla-operator-basic-3h-gke.jenkinsfile
Labels: No Backport Needed, Ready for review

#3124 fix(manager): Added 'Aborted' task status
  sdcm/mgmt.py
Labels: Backport-4.3, Backport-manager-v2.2

#3110 fix(perf latency with nemesis): fix mixed workload metrics
  sdcm/report_templates/results_latency_during_ops.html
  sdcm/utils/decorators.py
  sdcm/utils/latency.py
Labels: Backport-perf-v10, Ready for review

#3118 fix(ignore_ycsb_connection_refused): wrong regex caused evalutaion error
  sdcm/sct_events/filters.py
  sdcm/sct_events/group_common_events.py
Labels: No Backport Needed, Ready for review

#3116 fix(perfRegressionParallelPipeline): send no email from pipeline
  vars/perfRegressionParallelPipeline.groovy
Labels: Backport-perf-v10, Ready for review

#3117 fix(cluster_k8s): make scheme inline with current operator scheme
  sdcm/cluster_k8s/__init__.py
  sdcm/k8s_configs/cluster-gke.yaml
  sdcm/k8s_configs/cluster-minikube.yaml
  sdcm/k8s_configs/operator.yaml
  sdcm/k8s_configs/provisioner/values.yaml
Labels: No Backport Needed, Ready for review

#3109 fix(TerminateAndRemoveNodeMonkey): added event filter for repair errors
  sdcm/nemesis.py
Labels: Backport-4.3

#3130 fix(restart_then_repair_node): change event in filter
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#3129 fix(rebuild_streaming_err): filter 'Fail to send STREAM_MUTATION_DONE' warning when killing the rebuild
  sdcm/nemesis.py
Labels: Ready for review

#3123 fix(latency during ops): increase cs runtime
  test-cases/performance/perf-regression-latency-250gb-with-nemesis.yaml
Labels: Backport-perf-v10

#3079 fix(null query support,rolling upgrade test), scylla supports "WHERE k=null"
  sdcm/fill_db_data.py
Labels: No Backport Needed

#3090 feature(configurations): add audit.yaml
  configurations/audit.yaml
Labels: Backport-2020.1, Ready for review

#3126 fix(perf latency with nemesis): fix mixed workload metrics
  sdcm/report_templates/results_latency_during_ops.html
  sdcm/utils/decorators.py
  sdcm/utils/latency.py
Labels: No Backport Needed

#3132 fix(cluster): AWS or GCE runs with public connectivity and use_mgmt=true are failing
  sdcm/cluster.py
Labels: No Backport Needed, Ready for review

#3131 fix(TerminateAndRemoveNodeMonkey): added event filter for repair errors
  sdcm/nemesis.py
Labels: No Backport Needed

#3080 fix(gemini): Fix missing gemini command, screenshots in report
  gemini_test.py
  sdcm/gemini_thread.py
  sdcm/tester.py
Labels: Backport-4.3, Ready for review

#3138 fix(k8s_gke_config): update gke cluster version
  defaults/k8s_gke_config.yaml
Labels: No Backport Needed, Ready for review

#3136 fix(c-s_lwt_big_data_multidc): Adjust c-s_lwt_big_data_multidc.yaml to collect enough data for validation
  data_dir/c-s_lwt_big_data_multidc.yaml
Labels: Backport-4.3, Ready for review

#3137 fix(get_rate_limit_for_network_disruption): metric is not working
  sdcm/nemesis.py
Labels: Backport-4.3, Ready for review

#3144 fix(nemesis_publisher): remove dependcy from `store_results_in_elasti…
  sdcm/nemesis_publisher.py
Labels: Bug, Ready for review, Urgent

#3115 feature(monitoring): moving the new vesrion of scylla-monitoring
  defaults/test_default.yaml
Labels: No Backport Needed, Ready for review

#3145 fix(fill_db_data): don't run filter by NULL query for now
  sdcm/fill_db_data.py
Labels: No Backport Needed, Ready for review

#3107 Rolling upgrade ubuntu 18 with ldap enabled 2020.1
  jenkins-pipelines/rolling-upgrade-ubuntu18.04-ldap-authorization.jenkinsfile
Labels: Backport-2020.1

#3146 fix(SslHotReloadingNemesis): mask out 'error GnuTLS:-34, Base64 decoding error' error
  sdcm/nemesis.py
Labels: Backport-2020.1, Backport-4.3, Ready for review

#3152 fix(rolling upgrade pipeline): use new_scylla_repo from $params
  vars/rollingUpgradePipeline.groovy
Labels: Ready for review, Urgent

#2908 don't interpret Gemini's stderr as CRITICAL failure
  defaults/severities.yaml
  sdcm/gemini_thread.py
  sdcm/sct_events/base.py
  sdcm/sct_events/loaders.py
Labels: Backport-4.3, Ready for review

#3030 improvement(sct_config): resolve latest repo symlinks
  defaults/severities.yaml
  sdcm/sct_config.py
  sdcm/sct_events/base.py
  sdcm/sct_events/system.py
  sdcm/utils/version_utils.py
  unit_tests/test_config.py
  unit_tests/test_sct_events_system.py
Labels: No Backport Needed, Ready for review

#3031 fix(jepsen): switch to Jepsen Scylla upstream repo
  jepsen_test.py
  test-cases/jepsen/jepsen.yaml
Labels: No Backport Needed, Ready for review

#3160 fix(rolling upgrade file): fit it branch-2020.1
  jenkins-pipelines/rolling-upgrade-ubuntu18.04-ldap-authorization.jenkinsfile
  sdcm/tester.py
  sdcm/utils/ldap.py
  vars/rollingUpgradePipeline.groovy
Labels: No Backport Needed, Ready for review

#3163 fix(create_metrix_gauge): Revert renaming of c-s latency metric label
  sdcm/loader.py
Labels: Ready for review

#3165 fix(s3_paths): fix the paths to look from latest repo/list files
  sdcm/utils/common.py
  unit_tests/test_config.py
Labels: Backport-4.4, Ready for review

#3166 fix(rolling upgrade centos 7): make fit to branch-2020.1
  jenkins-pipelines/rolling-upgrade-centos7-ldap-authorization.jenkinsfile
Labels: No Backport Needed

#3155 fix(operator_monitoring): mask out some operator events to reduce severity
  defaults/severities.yaml
  sdcm/cluster_k8s/operator_monitoring.py
  sdcm/sct_events/base.py
  sdcm/sct_events/operator.py
  unit_tests/test_sct_events_base.py
  unit_tests/test_sct_events_operator.py
Labels: No Backport Needed, Ready for review

#3156 fix(latency): prometheus using public ip is failing
  sdcm/utils/latency.py
Labels: Backport-4.3, Backport-4.4, Backport-perf-v10

#3150 fix(cluster_k8s): make it wait till API is not operational first
  sdcm/cluster_k8s/__init__.py
  sdcm/cluster_k8s/gke.py
  sdcm/utils/k8s.py
Labels: No Backport Needed, Ready for review

#3024 improvement(tester): don't fail on ES errors
  defaults/severities.yaml
  sdcm/db_stats.py
  sdcm/sct_events/system.py
  unit_tests/test_sct_events_system.py
  unit_tests/test_tester.py
Labels: No Backport Needed, Ready for review

#3157 fix(1tb-longevity): Lowered number of threads in populate to 500
  test-cases/longevity/longevity-1TB-7days-authorization-and-tls-ssl.yaml
Labels: Backport-4.3, Backport-4.4

#3053 fix(gemini): don't warn for unparsable log messages
  sdcm/gemini_thread.py
  sdcm/sct_events/__init__.py
  sdcm/sct_events/base.py
Labels: No Backport Needed, Ready for review

#3171 fix(typo fix): duck typing typo
  sdcm/remote/remote_base.py
Labels: No Backport Needed, Urgent

#3172 fix(TerminateAndRemoveNodeMonkey): filter error on
  sdcm/nemesis.py
Labels: Backport-4.3, Backport-4.4

#3168 fix(wait_for_init): update db binary/package before node setup
  sdcm/cluster.py
Labels: No Backport Needed, Ready for review

#3076 fix(cluster_k8s): check if cert-manager is actually operational
  sdcm/cluster_k8s/__init__.py
  sdcm/k8s_configs/cert-manager-test.yaml
Labels: No Backport Needed, Ready for review

#3149 feature(cluster_k8s): deploy test monitoring in k8s
  defaults/k8s_gce_minikube_config.yaml
  defaults/k8s_gke_config.yaml
  defaults/severities.yaml
  defaults/test_default.yaml
  docs/configuration_options.md
  sdcm/cluster_k8s/__init__.py
  sdcm/cluster_k8s/gke.py
  sdcm/sct_config.py
  sdcm/sct_events/health.py
  sdcm/tester.py
  sdcm/utils/k8s.py
Labels: No Backport Needed, Ready for review

#3177 fix(scylla bench): run scylla-bench wuth correct ssh connection type
  sdcm/scylla_bench_thread.py
Labels: Backport-2020.1, Backport-4.3, Backport-4.4, Ready for review

#3178 Backport debug typo fix to 2020.1
  sdcm/remote/remote_base.py
Labels: No Backport Needed, Ready for review

#3180 fix(monitoring_prereqs): specifing python3.6 in installation
  sdcm/cluster.py
Labels: Backport-manager-v2.2

#3184 fix(remove_node_then_add_node): filter repair error for all normal nodes
  sdcm/nemesis.py
Labels: Backport-4.3, Backport-4.4, Ready for review

#3186 fix(validate partitions): not stop the test when cql command fails
  longevity_test.py
  sdcm/cluster.py
  sdcm/tester.py
Labels: Backport-4.3, Backport-4.4, Ready for review
