Repository scylladb/scylla-cluster-tests, pull requests merged in 2021-09, with the labels that each got.

#3923 improvement(local-k8s): run scylla with disabled developer mode
  sdcm/cluster_k8s/__init__.py
  sdcm/cluster_k8s/mini_k8s.py
Labels: No Backport Needed, Ready for review

#3921 feature(scylla operator): add event for catching pods wrong scheduling
  defaults/severities.yaml
  sdcm/cluster_k8s/__init__.py
  sdcm/cluster_k8s/eks.py
  sdcm/cluster_k8s/gke.py
  sdcm/sct_events/filters.py
  sdcm/sct_events/operator.py
  sdcm/utils/remote_logger.py
  unit_tests/test_sct_events_operator.py
Labels: No Backport Needed, Ready for review

#3930 fix(longevity-1tb): Decrease stress duration in order to meet timeout
  test-cases/longevity/longevity-1TB-5days-authorization-and-tls-ssl.yaml
Labels: Backport-4.5

#3926 fix(hydra.sh): allow to run hydra --help
  docker/env/hydra.sh
Labels: No Backport Needed, Ready for review

#3931 fix(disrupt_method_wrapper): Convert exception to str
  sdcm/nemesis.py
Labels: Ready for review, Backport-4.5

#3933 fix(node_setup): ignore status of iptables stop
  sdcm/cluster.py
Labels: Ready for review, Urgent, Backport-4.5

#3927 fix(kubernetes): place kube-system's deployments in default node pool
  sdcm/cluster_k8s/__init__.py
  sdcm/tester.py
Labels: No Backport Needed, Ready for review

#3929 fix(kubernetes): specify affinity rules for webhook-server pods
  sdcm/cluster_k8s/__init__.py
  sdcm/utils/k8s.py
Labels: No Backport Needed, Ready for review

#3928 improvement(k8s-gke): deploy 2 nodes in the default node pool
  sdcm/cluster_k8s/gke.py
  sdcm/tester.py
Labels: No Backport Needed, Ready for review

#3935 fix(mgmt.common.py): add OEL and Amazon2 defaults
  sdcm/mgmt/common.py
Labels: No Backport Needed, Ready for review

#3937 fix(k8s-functional-tests): correctly wait for the restored cluster state
  functional_tests/scylla_operator/conftest.py
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed, Ready for review

#3938 fix(k8s-functional-tests): correctly check orphaned operator resources
  functional_tests/scylla_operator/libs/helpers.py
  functional_tests/scylla_operator/test_functional.py
Labels: No Backport Needed, Ready for review

#3941 fix(sct_config.py): return back support for 2-digit versions
  sdcm/sct_config.py
Labels: No Backport Needed, Ready for review

#3940 improvement(run_pytest): allow to provide additional pytest params in CI
  docker/env/hydra.sh
  vars/longevityPipeline.groovy
  vars/runSctTest.groovy
Labels: No Backport Needed, Ready for review

#3939 fix(elasticsearch): handle elasticsearch connection exceptions
  sdcm/results_analyze/test.py
Labels: Ready for review, Backport-4.4, Backport-2021.1, Backport-4.5

#3943 ci(k8s-gke): fix region setting for the k8s-gke backend
  jenkins-pipelines/operator/upgrade/upgrade-major-scylla-k8s-gke.jenkinsfile
  jenkins-pipelines/operator/upgrade/upgrade-operator-k8s-gke.jenkinsfile
  jenkins-pipelines/operator/upgrade/upgrade-scylla-k8s-gke.jenkinsfile
  vars/rollingOperatorUpgradePipeline.groovy
Labels: Ready for review, Backport-operator-1.5

#3946 fix(k8s-functional-tests): refer to correct object with scylla namespace
  functional_tests/scylla_operator/libs/helpers.py
Labels: Ready for review, Backport-operator-1.5

#3952 fix(static_ips): display instance name if ip's name is empty
  sdcm/utils/cloud_monitor/resources/static_ips.py
Labels: No Backport Needed, Ready for review

#3932 feature(artifacts test): add test for web installer
  configurations/web_install.yaml
  defaults/test_default.yaml
  docker/env/hydra.sh
  jenkins-pipelines/artifacts-centos8-web.jenkinsfile
  jenkins-pipelines/artifacts-ubuntu2004-web.jenkinsfile
  sdcm/cluster.py
  sdcm/sct_config.py
  sdcm/utils/install.py
Labels: Ready for review

#3944 feature(pytest): add pytest-random-order plugin
  README.rst
  docker/env/version
  requirements.in
  requirements.txt
Labels: Ready for review, Backport-operator-1.5

#3953 fix(data validator): prevent creation tables with same name
  sdcm/utils/data_validator.py
Labels: Ready for review, Backport-4.5

#3956 fix(continuous event): __exit__ should not return
  sdcm/sct_events/continuous_event.py
Labels: No Backport Needed, Ready for review

#3961 Fix populate data parallel
  sdcm/tester.py
Labels: No Backport Needed, Ready for review

#3959 fix(common:get_branched_ami): filter out debug-image AMIs
  sdcm/utils/common.py
Labels: No Backport Needed

#3962 fix(typos): use correct info in some typo'ed log messages
  sdcm/sct_events/filters.py
  sdcm/tester.py
Labels: No Backport Needed, Ready for review

#3966 fix(longevity-lwt-parallel-24h.yaml): increase timeout
  test-cases/longevity/longevity-lwt-parallel-24h.yaml
Labels: Backport-4.5

#3947 fix(show_top_partition): disable new toppartition api
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#3968 feature(Jenkins): a job for show-monitor
  jenkins-pipelines/hydra-show-monitor.jenkinsfile
Labels: No Backport Needed, Ready for review

#3969 fix(pre-commit): excludes are regexps
  .pre-commit-config.yaml
Labels: Ready for review, Backport-4.4, Backport-2021.1, Backport-4.5, Backport-operator-1.5

#3945 feature(py-env-manager): add config for the 'tox' python env manager
  tox.ini
Labels: No Backport Needed, Ready for review

#3963 improvement(mgmt-agent-on-k8s): set dedicated resources explicitely
  sdcm/cluster_k8s/__init__.py
  sdcm/cluster_k8s/mini_k8s.py
Labels: No Backport Needed, Ready for review

#3964 improvement(k8s-local): cache images to speed up cluster creation
  sdcm/cluster_k8s/__init__.py
  sdcm/cluster_k8s/mini_k8s.py
Labels: No Backport Needed, Ready for review

#3965 test(k8s-functional): cover operator#718
  functional_tests/scylla_operator/libs/helpers.py
  functional_tests/scylla_operator/test_functional.py
Labels: Ready for review, Backport-operator-1.5

#3974 fix(list-gce-images-branch): filter out debug-images for GCP
  sdcm/utils/common.py
Labels: No Backport Needed, Ready for review

#3975 feature(nosqlbench): add documentation
  sdcm/nosql_thread.py
Labels: No Backport Needed, Ready for review

#3978 fix(artifacts pipeline): disable sct runner
  vars/artifactsPipeline.groovy
Labels: No Backport Needed

#3934 fix(siren backends): Adjust siren backens for sct cloud-provider option
  vars/getCloudProviderFromBackend.groovy
Labels: Ready for review

#3979 fix(perfRegressionParallelPipeline): remove cleanSCTRunners step
  vars/perfRegressionParallelPipeline.groovy
Labels: No Backport Needed, Ready for review

#3981 fix(kubernetes): suppress absence of seed nodes
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed, Ready for review

#3980 improvement(k8s-logs): gather also logs for previous containers in pods
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed, Ready for review

#3976 improvement(k8s-eks-perf): allow Scylla pods to get guaranteed CPU bind
  sdcm/cluster_k8s/eks.py
  sdcm/cluster_k8s/gke.py
  sdcm/k8s_configs/eks/scylla-node-prepare.yaml
Labels: No Backport Needed, Ready for review

#3977 improvement(functional): make webhook-server rollout test more stable
  functional_tests/scylla_operator/libs/helpers.py
  functional_tests/scylla_operator/test_functional.py
Labels: Ready for review, Backport-operator-1.5

#3982 feature(Jenkins): a job for show-jepsen-results
  jenkins-pipelines/hydra-show-jepsen-results.jenkinsfile
Labels: No Backport Needed, Ready for review

#3883 feature(cs_driver): Check is shared awarnes or not driver is used
  defaults/severities.yaml
  sdcm/db_stats.py
  sdcm/report_templates/results_base.html
  sdcm/sct_events/loaders.py
  sdcm/send_email.py
  sdcm/stress_thread.py
  sdcm/tester.py
  unit_tests/test_sct_events_loaders.py
Labels: Ready for review, Backport-4.5

#3955 fix(sct_config): fail fast when no available non-seed nodes for nemesis
  sdcm/sct_config.py
Labels: Ready for review
