Repository scylladb/scylla-cluster-tests, pull requests merged in 2021-11, with the labels that each got.

#4072 improvement(tox-venv-mgr): pass through 'HOME" env var needed by git
  tox.ini
Labels: No Backport Needed, Ready for review

#4066 fix(scylla_yaml): append_scylla_args parsing
  sdcm/provision/scylla_yaml/scylla_yaml.py
  unit_tests/test_data/scylla_yaml_update.yaml
  unit_tests/test_scylla_yaml.py
Labels: No Backport Needed, Ready for review

#4079 refactor(manager tests): manager tests use scylla 4.5 instead of 4.4
  jenkins-pipelines/manager/centos-manager-backup-200gb.jenkinsfile
  jenkins-pipelines/manager/centos-manager-backup-azure.jenkinsfile
  jenkins-pipelines/manager/centos-manager-backup-gce.jenkinsfile
  jenkins-pipelines/manager/centos-manager-backup.jenkinsfile
  jenkins-pipelines/manager/centos-manager-repair-control.jenkinsfile
  jenkins-pipelines/manager/centos-manager-repair-intensity-multiple-repaired-nodes.jenkinsfile
  jenkins-pipelines/manager/centos-manager-repair-intensity-single-repaired-nodes.jenkinsfile
  jenkins-pipelines/manager/centos-manager-sanity-ipv6.jenkinsfile
  jenkins-pipelines/manager/centos-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/centos-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/debian10-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/debian10-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/debian9-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/debian9-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu16-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/ubuntu16-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu18-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/ubuntu18-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu20-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/ubuntu20-manager-upgrade.jenkinsfile
Labels: No Backport Needed

#4078 fix(duplication): reuse walk_thru_data func in HelmValues.get method
  sdcm/utils/common.py
  sdcm/utils/k8s.py
Labels: No Backport Needed, Ready for review

#4081 fix(network monkey longevity): set ip_ssh_connections to public
  jenkins-pipelines/longevity-200gb-48h-network-monkey.jenkinsfile
Labels: Backport-4.5

#4082 fix(longevity-3h): increase test timeout
  test-cases/longevity/longevity-10gb-3h.yaml
Labels: Backport-4.5

#4084 fix(alternator-3h): increase test_duration by 60 minutes
  test-cases/longevity/longevity-alternator-3h.yaml
Labels: No Backport Needed, Ready for review

#4073 test(function): override scylla.yaml
  functional_tests/scylla_operator/conftest.py
  functional_tests/scylla_operator/test_functional.py
Labels: No Backport Needed

#4070 improvement(gke-cleanup): delete orphaned disks deleting GKE clusters
  sdcm/utils/common.py
Labels: No Backport Needed, Ready for review

#4086 improvement(Jenkins): add job for removing SCT runners
  jenkins-pipelines/hydra-clean-runner-instances.jenkinsfile
Labels: No Backport Needed, Ready for review

#4089 improvement(YCSB_docker): introduce version support scylla command
  docker/ycsb/Dockerfile
  docker/ycsb/image
  sdcm/utils/docker_remote.py
  sdcm/ycsb_thread.py
  unit_tests/test_ycsb_thread.py
Labels: No Backport Needed, Ready for review

#4093 refactor(manager): set scylla_version as master in the managerPipeline
  jenkins-pipelines/manager/centos-manager-backup-200gb.jenkinsfile
  jenkins-pipelines/manager/centos-manager-backup-azure.jenkinsfile
  jenkins-pipelines/manager/centos-manager-backup-gce.jenkinsfile
  jenkins-pipelines/manager/centos-manager-backup.jenkinsfile
  jenkins-pipelines/manager/centos-manager-repair-control.jenkinsfile
  jenkins-pipelines/manager/centos-manager-repair-intensity-multiple-repaired-nodes.jenkinsfile
  jenkins-pipelines/manager/centos-manager-repair-intensity-single-repaired-nodes.jenkinsfile
  jenkins-pipelines/manager/centos-manager-sanity-ipv6.jenkinsfile
  jenkins-pipelines/manager/centos-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/centos-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/debian10-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/debian10-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/debian9-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/debian9-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu16-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/ubuntu16-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu18-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/ubuntu18-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu20-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/ubuntu20-manager-upgrade.jenkinsfile
  vars/managerPipeline.groovy
Labels: No Backport Needed

#4095 fix(events): set debug level when more than 2 events found
  sdcm/prometheus.py
  sdcm/sct_events/database.py
Labels: No Backport Needed

#4097 fix(mgmt_cli_test): ubuntu fix
  mgmt_cli_test.py
Labels: No Backport Needed, Ready for review

#4101 improvement(email): add link to the job that recreate a monitor
  sdcm/report_templates/results_base.html
  sdcm/report_templates/results_base_new.html
  sdcm/report_templates/results_issue_template.html
  sdcm/report_templates/results_jepsen.html
  sdcm/send_email.py
  sdcm/tester.py
Labels: Ready for review, Backport-2021.1, Backport-4.5

#4090 improvement(nemesis): run resharding nemesis on K8S
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#4104 fix(provision): do not create test_id
  sdcm/sct_provision/common/layout.py
  sdcm/test_config.py
Labels: No Backport Needed, Ready for review

#4094 test(functional): validate pods dnsPolicy
  functional_tests/scylla_operator/test_functional.py
Labels: No Backport Needed, Ready for review

#4107 fix(show_alive_threads): make it safe
  sdcm/utils/threads_and_processes_alive.py
Labels: No Backport Needed, Ready for review

#4091 ci(perf-pipeline): use separate timeouts for different stages
  jenkins-pipelines/operator/performance/perf-regression-latency-eks.jenkinsfile
  jenkins-pipelines/operator/performance/perf-regression-throughput-eks.jenkinsfile
  vars/getJobTimeouts.groovy
  vars/perfRegressionParallelPipeline.groovy
Labels: Ready for review, Backport-perf-v8, Backport-perf-v10, Backport-perf-v11

#4077 improvement(nemesis.py): improve logs RebuildStreamingErr
  sdcm/nemesis.py
Labels: No Backport Needed

#4099 fix(manager_versions): changed master_latest deb urls to unified build
  defaults/manager_versions.yaml
Labels: No Backport Needed, Ready for review

#4110 fix(argus): make it be compatible with K8S backends
  sdcm/cluster.py
  sdcm/cluster_k8s/__init__.py
  sdcm/utils/docker_remote.py
Labels: No Backport Needed, Ready for review

#4106 Provision: localize provisioner plan and plan builder
  sdcm/provision/aws/provisioner.py
  sdcm/provision/common/provision_plan.py
  sdcm/provision/common/provision_plan_builder.py
  sdcm/provision/common/provisioner.py
  sdcm/sct_provision/aws/cluster.py
  sdcm/sct_provision/common/layout.py
Labels: No Backport Needed, Ready for review

#4108 Fix sct events panel
  data_dir/scylla-dash-per-server-nemesis.master.json
Labels: Ready for review, Backport-operator-1.5, Backport-manager-2.6

#4121 fix(pylint): remove the basis for the duplicate-code error
  sdcm/cluster_k8s/eks.py
Labels: No Backport Needed, Ready for review

#4120 fix(perf-pipeline): use post_behavior_k8s_cluster value from params
  vars/perfRegressionParallelPipeline.groovy
Labels: No Backport Needed, Ready for review

#4114 fix(longevity-pipeline): do not run provision resources stage on non-AWS
  vars/longevityPipeline.groovy
Labels: No Backport Needed, Ready for review

#4122 improvement(clean-runner-instances): add timeout to the pipeline job
  jenkins-pipelines/hydra-clean-runner-instances.jenkinsfile
Labels: No Backport Needed

#4124 Fix rolling upgrade
  sdcm/cluster.py
Labels: No Backport Needed, Ready for review

#4117 fix(test_timeout): make start_time to be in sync
  sdcm/tester.py
Labels: No Backport Needed, Ready for review

#4005 improvement(perf report): add `append_scylla_args` to email report
  sdcm/utils/es_queries.py
Labels: Ready for review, Ready to be Merged, Backport-perf-v10, Backport-perf-v11

#4028 fix(update_scylla_packages): ubuntu package
  sdcm/cluster.py
Labels: Backport-perf-v10, Backport-2021.1, Backport-4.5, Backport-perf-v11

#4123 improvement(kernel callstack event): add new event
  defaults/severities.yaml
  sdcm/sct_events/database.py
  unit_tests/test_cluster.py
  unit_tests/test_data/kernel_callstack.log
  unit_tests/test_sct_events_database.py
Labels: Ready for review, Ready to be Merged, Backport-perf-v10, Backport-perf-v11

#4134 fix(FullScanThread): Fix bad handling of 'random' option for fullscan
  sdcm/full_scan_thread.py
Labels: Backport-2021.1, Backport-4.5

#4116 fix(cdc-options): update supported values for preimage
  sdcm/utils/cdc/options.py
Labels: Backport-2021.1, Backport-4.5

#4138 fix(upgrade_test.py): Create Alternator tables once in all session
  sdcm/tester.py
Labels: Ready for review

#4140 fix(verify config): mandatory variables for siren tests
  sct.py
  sdcm/sct_config.py
  unit_tests/test_config.py
Labels: No Backport Needed

#4142 fix(ubuntu Dockerfile): wrong call to bashrc
  docker/scylla-sct/ubuntu/Dockerfile
Labels: Backport-4.6

#4143 fix(terminate_and_replace): changed to be able to replace a seed
  sdcm/nemesis.py
Labels: Backport-2021.1, Backport-4.5

#4144 fix(show-monitor): unset dashboard.id field for the restored dashboard
  sdcm/monitorstack/__init__.py
Labels: Ready for review

#3264 feature(housekeeping stats): add housekeeping stats test to artifact tests
  artifacts_test.py
  sdcm/cluster.py
  sdcm/cluster_docker.py
  sdcm/utils/housekeeping.py
  sdcm/utils/net.py
Labels: No Backport Needed, Ready for review

#4148 improvement(sct.py): move ArgusTestRun import to the func that uses it
  sct.py
Labels: No Backport Needed

#4152 fix(kernel callstack) remove from email attachment:
  sdcm/report_templates/results_reactor_stall_events_list.html
Labels: Backport-perf-v12

#4151 fix(monitorstack/ui): change xpath for panel searching
  sdcm/monitorstack/ui.py
Labels: Ready for review, Backport-4.6

#4139 revert(health_checker): removing removed_nodes_list check
  sdcm/utils/health_checker.py
  unit_tests/test_utils_health_checker.py
Labels: Backport-4.5

#4150 fix(longevity_test): Skip paxos error/warning messages (#8706)
  longevity_test.py
  sdcm/sct_events/group_common_events.py
Labels: Ready for review, Backport-4.4

#4132 feature(operator): Add possibility to configure K8S perf tuning
  defaults/k8s_gke_config.yaml
  defaults/test_default.yaml
  docs/configuration_options.md
  jenkins-pipelines/operator/performance/perf-regression-latency-eks.jenkinsfile
  jenkins-pipelines/operator/performance/perf-regression-throughput-eks.jenkinsfile
  sdcm/cluster_k8s/__init__.py
  sdcm/cluster_k8s/eks.py
  sdcm/cluster_k8s/gke.py
  sdcm/cluster_k8s/mini_k8s.py
  sdcm/k8s_configs/eks/scylla-node-prepare.yaml
  sdcm/k8s_configs/loaders.yaml
  sdcm/k8s_configs/node-config-crd.yaml
  sdcm/sct_config.py
  sdcm/utils/k8s.py
  vars/perfRegressionParallelPipeline.groovy
Labels: No Backport Needed, Ready for review

#4118 fix(tester.py): ignore cdc stream errors
  upgrade_test.py
Labels: No Backport Needed, Ready for review

#4160 fix(k8s): skip logging configuration
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed, Ready for review

#4158 fix(artifact test): nonroot install not support housekeeping
  artifacts_test.py
  sdcm/cluster.py
Labels: No Backport Needed, Ready for review

#4162 fix(event): not raise exception when begin event not found
  sdcm/sct_events/database.py
Labels: Ready for review, Backport-4.6

#4149 fix(dashboard): Use $test_name template for grafana dashboard
  data_dir/scylla-dash-per-server-nemesis.master.json
Labels: Ready for review, Urgent, test-provision-aws

#4157 fix(manager suspension tests): make sure to resume after suspending
  mgmt_cli_test.py
  sdcm/mgmt/cli.py
Labels: Backport-manager-2.6

#4156 fix(rolling upgrade): add another base version
  jenkins-pipelines/rolling-upgrade-alternator.jenkinsfile
  jenkins-pipelines/rolling-upgrade-ami.jenkinsfile
  jenkins-pipelines/rolling-upgrade-centos7.jenkinsfile
  jenkins-pipelines/rolling-upgrade-centos8.jenkinsfile
  jenkins-pipelines/rolling-upgrade-debian10.jenkinsfile
  jenkins-pipelines/rolling-upgrade-debian9.jenkinsfile
  jenkins-pipelines/rolling-upgrade-ubuntu16.04.jenkinsfile
  jenkins-pipelines/rolling-upgrade-ubuntu18.04.jenkinsfile
  jenkins-pipelines/rolling-upgrade-ubuntu20.04.jenkinsfile
  jenkins-pipelines/rolling-upgrade-with-null-inserts.jenkinsfile
Labels: No Backport Needed

#4168 fix(argus): make it work offline
  sdcm/argus_test_run.py
Labels: No Backport Needed, Ready for review

#4103 feature(hydra): AWS Mock integration
  docker/env/hydra.sh
  sct.py
  sdcm/sct_runner.py
  sdcm/utils/docker_utils.py
  utils/mocks/__init__.py
  utils/mocks/aws_mock.py
Labels: No Backport Needed, Ready for review, Ready to be Merged

#4171 fix(cluster_aws): remove unsed code
  sdcm/cluster_aws.py
Labels: No Backport Needed, Ready for review

#4169 fix(k8s-functional): disable logging configuration as redundant
  sdcm/cluster.py
  sdcm/cluster_k8s/mini_k8s.py
Labels: Ready for review, Backport-operator-1.6

#4166 fix(install_cassandra_harry): Change from Amos fork to official
  sdcm/cluster.py
Labels: Backport-4.6

#4175 feature(cloud-monitor): last 7 days report for non qa users
  sct.py
  sdcm/send_email.py
  sdcm/utils/cloud_monitor/cloud_monitor.py
  sdcm/utils/cloud_monitor/report.py
Labels: No Backport Needed
