Repository scylladb/scylla-cluster-tests, pull requests merged in 2022-09, with the labels that each got.

#5208 fix(dashboard): scheduler runtime query
  data_dir/scylla-dash-per-server-nemesis.2021.1.json
Labels: Ready for review, Backport-2021.1

#5210 fix(azure): backport list images for Azure
  sdcm/provision/azure/utils.py
  sdcm/utils/version_utils.py
Labels: No Backport Needed

#5209 fix(azure): backport list images for Azure
  sdcm/provision/azure/utils.py
  sdcm/utils/version_utils.py
Labels: No Backport Needed

#5218 fix(docker-stress): make sure params is passed
  sdcm/tester.py
  sdcm/ycsb_thread.py
Labels: No Backport Needed

#5219 fix(artifacts_docker): remove unnecessary param
  test-cases/artifacts/docker.yaml
Labels: Backport-5.1, Backport-2022.2

#5215 improvement(EKS,GKE): use more recent K8S and cert manager versions
  defaults/k8s_eks_config.yaml
  defaults/k8s_gke_config.yaml
Labels: No Backport Needed

#5220 fix(gemini_thread): enable docker host networking
  sdcm/gemini_thread.py
Labels: Backport-5.1, Backport-2022.2

#5227 feature(scylla-bench): move to using `scylla-bench==v0.1.9`
  defaults/test_default.yaml
  docker/scylla-bench/README.md
Labels: No Backport Needed

#5226 fix(SCTDashboard): increase screenshot size
  sdcm/monitorstack/ui.py
Labels: Ready for review, Backport-5.0, Backport-2022.2

#5223 fix(docker/scylla-sct/ubuntu/Dockerfile): Add support for ubuntu22.04
  docker/scylla-sct/ubuntu/Dockerfile
Labels: No Backport Needed, test-provision-docker

#5221 feature(ycsb): [dynamodb] add support for TTL
  defaults/test_default.yaml
  docker/ycsb/Dockerfile
  docker/ycsb/image
Labels: No Backport Needed

#5241 fix(upgrade_test): Create s-b keyspace before run stress
  sdcm/fill_db_data.py
Labels: Ready for review

#5244 fix(batched_tests): convert node list into comma separated list
  longevity_test.py
Labels: Backport-2022.2

#5252 fix(scylla_monitoring_start): remove depricated single dash prom flag
  sdcm/cluster.py
Labels: No Backport Needed, Ready for review, test-provision-docker

#5231 test(unittest): data validator
  sdcm/utils/data_validator.py
  unit_tests/conftest.py
  unit_tests/test_data/test_data_validator/lwt-basic-3h.yaml
  unit_tests/test_data/test_data_validator/no-validation-views-lwt-basic-3h.yaml
  unit_tests/test_utils_data_validator.py
Labels: Ready for review

#5235 fix(longevity): adjust assymetric 12h test
  jenkins-pipelines/longevity-150gb-asymmetric-cluster-12h.jenkinsfile
  test-cases/longevity/longevity-150GB-12h-autorization-LimitedMonkey.yaml
Labels: Backport-5.1, Backport-2022.2

#5205 test(longevity): add sla basic longevity test
  defaults/test_default.yaml
  jenkins-pipelines/longevity-sla-100gb-4h.jenkinsfile
  longevity_sla_test.py
  sdcm/sct_config.py
  test-cases/longevity/longevity-sla-100gb-4h.yaml
  test_lib/sla.py
Labels: Ready for review, Backport-2021.1, Backport-2022.1, Backport-2022.2

#5255 fix(ycsb): upload image that has python2 installed
  defaults/test_default.yaml
Labels: Backport-5.1

#5257 fix(artifacts): workaround - increase timeout
  jenkins-pipelines/artifacts-amazon2-arm.jenkinsfile
  jenkins-pipelines/artifacts-centos7.jenkinsfile
  jenkins-pipelines/artifacts-centos8-arm.jenkinsfile
  jenkins-pipelines/artifacts-centos8-selinux.jenkinsfile
  jenkins-pipelines/artifacts-centos8-web.jenkinsfile
  jenkins-pipelines/artifacts-centos8.jenkinsfile
  jenkins-pipelines/artifacts-debian10-arm.jenkinsfile
  jenkins-pipelines/artifacts-debian10.jenkinsfile
  jenkins-pipelines/artifacts-debian11.jenkinsfile
  jenkins-pipelines/artifacts-docker.jenkinsfile
  jenkins-pipelines/artifacts-rocky8.jenkinsfile
  jenkins-pipelines/artifacts-ubuntu1804.jenkinsfile
  jenkins-pipelines/artifacts-ubuntu2004-arm.jenkinsfile
  jenkins-pipelines/artifacts-ubuntu2004-web.jenkinsfile
  jenkins-pipelines/artifacts-ubuntu2004.jenkinsfile
  jenkins-pipelines/artifacts-ubuntu2204-arm.jenkinsfile
  jenkins-pipelines/artifacts-ubuntu2204-web.jenkinsfile
  jenkins-pipelines/nonroot-offline-install/artifacts-centos8.jenkinsfile
  jenkins-pipelines/nonroot-offline-install/artifacts-debian10.jenkinsfile
  jenkins-pipelines/nonroot-offline-install/artifacts-debian11.jenkinsfile
  jenkins-pipelines/nonroot-offline-install/artifacts-rocky8.jenkinsfile
  jenkins-pipelines/nonroot-offline-install/artifacts-ubuntu1804.jenkinsfile
  jenkins-pipelines/nonroot-offline-install/artifacts-ubuntu2004.jenkinsfile
  jenkins-pipelines/nonroot-offline-install/artifacts-ubuntu2204.jenkinsfile
Labels: No Backport Needed

#5258 fix(tls-ssl-1dis-2nondis-nemesis longevity): pre create schema
  test-cases/longevity/longevity-2TB-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis.yaml
Labels: No Backport Needed

#5239 feature(uda): add User Defined Aggregations support
  sdcm/utils/uda.py
  sdcm/utils/udas/my_avg.yaml
  sdcm/utils/udas/my_counter.yaml
  sdcm/utils/udf.py
  sdcm/utils/udf_scripts/lua_div.yaml
  sdcm/utils/udf_scripts/lua_simple_return.yaml
  sdcm/utils/udf_scripts/lua_var_length_counter_accumulator.yaml
  unit_tests/test_uda.py
  unit_tests/test_udf.py
Labels: No Backport Needed

#5240 feature(issue-template): add relocatable pkg url to report and argus
  sdcm/report_templates/results_base.html
  sdcm/report_templates/results_base_custom.html
  sdcm/report_templates/results_issue_template.html
  sdcm/send_email.py
  sdcm/tester.py
  sdcm/utils/version_utils.py
Labels: No Backport Needed

#5266 fix(kill_stress_thread): remove scylla-bench/gemini kills
  sdcm/cluster.py
Labels: Backport-5.1, Backport-2022.2

#5267 improvement(longevity-large-partition-8h): use retries for scylla-bench
  test-cases/longevity/longevity-large-partition-8h.yaml
Labels: No Backport Needed

#5275 fix(scylla-bench): switch to v0.1.11
  defaults/test_default.yaml
Labels: No Backport Needed

#5274 fix(hydra-show-monitor): add call to `hydra attach-test-sg`
  jenkins-pipelines/hydra-show-monitor.jenkinsfile
  sct_ssh.py
Labels: No Backport Needed

#5277 feature(ycsb): [Dynamodb] add support for updating TTL
  defaults/test_default.yaml
  docker/ycsb/image
Labels: No Backport Needed

#5273 feature(artifacts): verify cqlsh is working
  artifacts_test.py
Labels: No Backport Needed

#5276 fix(alternator): cover more places with ignore_ycsb_connection_refused
  sdcm/nemesis.py
Labels: No Backport Needed

#5272 fix(schema-agreement): print proper error messages
  sdcm/cluster.py
  sdcm/utils/health_checker.py
  unit_tests/test_utils_health_checker.py
Labels: No Backport Needed

#5283 fix(sct_config): remove `scylla_bench_version` configuration option
  defaults/test_default.yaml
  docs/configuration_options.md
  sdcm/sct_config.py
  test-cases/longevity/longevity-counters-multidc.yaml
  test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml
  test-cases/longevity/longevity-large-partition-4days.yaml
  test-cases/longevity/longevity-twcs-48h.yaml
Labels: Backport-5.1, Backport-2022.2

#5279 fix(ycsb): fix ttl to be sent as number, and not as string
  defaults/test_default.yaml
  docker/ycsb/Dockerfile
  docker/ycsb/README.md
Labels: No Backport Needed

#5286 fix(longevity-network): change default to `ip_ssh_connections: public`
  jenkins-pipelines/longevity-200gb-48h-network-monkey.jenkinsfile
Labels: Backport-5.1, Backport-2022.2

#5288 fix(create_session): remove redundant debug message
  sdcm/cluster.py
Labels: Ready for review

#5289 fix(artifacts_test): install python2.7 for older ubuntu distros
  sdcm/cluster.py
Labels: No Backport Needed

#5290 fix(longevity-50GB-3days-authorization...): Adjust instance type
  test-cases/longevity/longevity-50GB-3days-authorization-and-tls-ssl.yaml
Labels: No Backport Needed

#5296 fix(nemesis): remove version control from nemesis
  sdcm/nemesis.py
Labels: No Backport Needed

#5295 fix(nemesis): skip enospc nemesis
  sdcm/nemesis.py
Labels: No Backport Needed

#5287 fix(functional): wait for system.log file exists on every node
  functional_tests/scylla_operator/conftest.py
  sdcm/cluster.py
  sdcm/cluster_k8s/__init__.py
Labels: Ready for review

#5300 Revert "fix(artifacts): workaround - increase timeout"
  jenkins-pipelines/artifacts-amazon2-arm.jenkinsfile
  jenkins-pipelines/artifacts-centos7.jenkinsfile
  jenkins-pipelines/artifacts-centos8-arm.jenkinsfile
  jenkins-pipelines/artifacts-centos8-selinux.jenkinsfile
  jenkins-pipelines/artifacts-centos8-web.jenkinsfile
  jenkins-pipelines/artifacts-centos8.jenkinsfile
  jenkins-pipelines/artifacts-debian10-arm.jenkinsfile
  jenkins-pipelines/artifacts-debian10.jenkinsfile
  jenkins-pipelines/artifacts-debian11.jenkinsfile
  jenkins-pipelines/artifacts-docker.jenkinsfile
  jenkins-pipelines/artifacts-rocky8.jenkinsfile
  jenkins-pipelines/artifacts-ubuntu1804.jenkinsfile
  jenkins-pipelines/artifacts-ubuntu2004-arm.jenkinsfile
  jenkins-pipelines/artifacts-ubuntu2004-web.jenkinsfile
  jenkins-pipelines/artifacts-ubuntu2004.jenkinsfile
  jenkins-pipelines/artifacts-ubuntu2204-arm.jenkinsfile
  jenkins-pipelines/artifacts-ubuntu2204-web.jenkinsfile
  jenkins-pipelines/nonroot-offline-install/artifacts-centos8.jenkinsfile
  jenkins-pipelines/nonroot-offline-install/artifacts-debian10.jenkinsfile
  jenkins-pipelines/nonroot-offline-install/artifacts-debian11.jenkinsfile
  jenkins-pipelines/nonroot-offline-install/artifacts-rocky8.jenkinsfile
  jenkins-pipelines/nonroot-offline-install/artifacts-ubuntu1804.jenkinsfile
  jenkins-pipelines/nonroot-offline-install/artifacts-ubuntu2004.jenkinsfile
  jenkins-pipelines/nonroot-offline-install/artifacts-ubuntu2204.jenkinsfile
Labels: No Backport Needed

#5297 fix(disrupt_hot_reloading_internode_certificate): boost reload timeout
  sdcm/nemesis.py
Labels: No Backport Needed

#5246 fix(azure): unset az for basic longevity job
  Jenkinsfile
  jenkins-pipelines/artifacts-azure-image.jenkinsfile
  jenkins-pipelines/longevity-10gb-3h-azure.jenkinsfile
  sdcm/provision/azure/ip_provider.py
  sdcm/provision/azure/virtual_machine_provider.py
  sdcm/provision/azure/virtual_network_provider.py
Labels: No Backport Needed

#5305 fix(nemesis): prevent pre-commit failure with 'Unreachable code' error
  sdcm/nemesis.py
Labels: Ready for review

#5307 fix(_prepare_test_table): execute single c-s thread
  sdcm/nemesis.py
Labels: Ready for review, Backport-5.1, Backport-2022.2

#5311 fix(run_nodetool): fix coredump on timeout
  sdcm/cluster.py
  sdcm/remote/libssh2_client/__init__.py
Labels: Backport-5.1, Backport-2022.2

#5302 fix(nemesis): add_remove_dc keyspace cleanup
  sdcm/nemesis.py
  sdcm/tester.py
Labels: Backport-5.1, Backport-2022.2

#5317 fix(argus_test_run): Don't use argus for local runs with docker
  sdcm/argus_test_run.py
Labels: Ready for review

#5320 fix(workaround): reactor stall threshold increase
  test-cases/performance/perf-regression-latency-1TB.yaml
  test-cases/performance/perf-regression-latency-500gb-30min.yaml
  test-cases/performance/perf-regression-user-profiles.yaml
Labels: Backport-perf-v8, Backport-perf-v10, Backport-perf-v12

#5321 fix(gce): strip image url
  sdcm/tester.py
Labels: No Backport Needed

#5284 improvement(data validator): improve investigation ability
  defaults/severities.yaml
  sdcm/logcollector.py
  sdcm/utils/data_validator.py
Labels: Ready for review, Backport-2022.1

#5316 fix(drain): fix timeout for nodetool drain command
  sdcm/nemesis.py
  upgrade_test.py
Labels: Backport-5.1, Backport-2022.2

#5325 fix(data validator): list of unique view names with same elements order
  sdcm/utils/data_validator.py
Labels: Ready for review, Backport-4.6, Backport-5.0, Backport-2022.1, Backport-5.1, Backport-2022.2

#5315 feature(cluster.py): support new directory structure of unified package
  sdcm/cluster.py
Labels: No Backport Needed

#5309 fix(dashboard): add SLA scheduler runtime panel
  data_dir/scylla-dash-per-server-nemesis.master.json
Labels: No Backport Needed, Ready for review

#5324 test(5000-tables): change seed for 5000 tables test
  test-cases/scale/longevity-5000-tables.yaml
Labels: Backport-5.1, Backport-2022.2

#5327 fix(start_and_interrupt_rebuild_streaming): Increased timeout to 400
  sdcm/nemesis.py
Labels: Backport-2022.1, Backport-5.1, Backport-2022.2
