Repository scylladb/scylla-cluster-tests, pull requests merged in 2022-06, with the labels that each got.

#4845 fix(event): print scylla-bench event stress_cmd
  sdcm/scylla_bench_thread.py
Labels: Backport-5.0, Backport-2022.1

#4831 fix(spot_failure_fallback): catch all ClientError
  sdcm/cluster_aws.py
Labels: Backport-4.5, Backport-4.6, Backport-5.0, Backport-2022.1

#4846 fix(azure): fix missing params attribute in AzureCLuster
  sdcm/cluster_azure.py
Labels: No Backport Needed

#4851 fix(autossh): fix bind mount on hosts with selinux
  sdcm/utils/auto_ssh.py
Labels: No Backport Needed

#4852 fix(syslog-ng): fix bind mount on hosts with selinux
  sdcm/utils/syslogng.py
Labels: No Backport Needed

#4830 fix(ipv6_workaround_script): find the network device
  sdcm/provision/aws/utils.py
Labels: No Backport Needed

#4853 fix(sdcm/argus_test_run.py): Only split regions property if it's str
  sdcm/argus_test_run.py
Labels: Backport-5.0, Backport-2022.1

#4842 feature(backport-script): added a script that helps to backport commits
  utils/backport.sh
Labels: No Backport Needed

#4764 Add ubuntu22 artifacts test
  configurations/arm/ubuntu2204.yaml
  jenkins-pipelines/artifacts-ubuntu2204-arm.jenkinsfile
  jenkins-pipelines/artifacts-ubuntu2204-web.jenkinsfile
  jenkins-pipelines/artifacts-ubuntu2204.jenkinsfile
  sdcm/utils/distro.py
  test-cases/artifacts/ubuntu2204.yaml
  unit_tests/test_utils_distro.py
Labels: Backport-5.0, Backport-2022.1

#4854 feature(run-test): make sure we don't select multiple test methods
  sct.py
Labels: No Backport Needed

#4860 feature(cloud-init): add cloud-init user-data for gce
  sdcm/cluster_gce.py
Labels: Backport-5.0, Backport-2022.1

#4869 fix(db_events): change regex for UNKNOWN_VERB
  sdcm/sct_events/database.py
Labels: No Backport Needed

#4873 fix(rolling-upgrade): add oss base version for 2022.1 test
  unit_tests/test_base_version.py
  utils/get_supported_scylla_base_versions.py
Labels: Backport-5.0, Backport-2022.1

#4871 fix(coredump): change the upload url to use https
  sdcm/coredump.py
  unit_tests/test_data/test_coredump/filebased/fail_upload_test_remoter.json
  unit_tests/test_data/test_coredump/filebased/success_test_remoter.json
  unit_tests/test_data/test_coredump/systemd/exceptions_limit_not_reached_test_remoter.json
  unit_tests/test_data/test_coredump/systemd/exceptions_limit_reached_test_remoter.json
  unit_tests/test_data/test_coredump/systemd/fail_upload_test_remoter.json
  unit_tests/test_data/test_coredump/systemd/success_test_remoter.json
Labels: Bug, Backport-2021.1, Backport-4.5, Backport-4.6, Backport-perf-v12, Backport-5.0, Backport-manager-3.0, Backport-perf-v13, Backport-2022.1

#4823 fix(ics goal test): Fix invalid user prefix characters
  test-cases/features/ics_space_amplification_goal_test.yaml
Labels: Backport-2022.1

#4876 fix(sct_config): make sure siren is handled correctly
  sdcm/sct_config.py
  unit_tests/test_config.py
Labels: No Backport Needed

#4879 fix(kill_cs_thread): Use different commands to kill c-s threads
  sdcm/cluster.py
Labels: Ready for review, Urgent, Backport-perf-v12, Backport-perf-v13

#4885 fix(cql_ip_address): change to be @cached_property
  sdcm/cluster.py
Labels: Ready for review, Backport-5.0, Backport-2022.1

#4826 fix(resharding): recognize resharding during restart
  sdcm/cluster.py
Labels: Backport-5.0, Backport-2022.1

#4886 fix(destroy_data_and_restart_scylla): two small fixes
  sdcm/cluster.py
  sdcm/nemesis.py
Labels: Backport-5.0, Backport-2022.1

#4884 fix(rollingOperatorUpgradePipeline): better handle platform upgrade
  vars/rollingOperatorUpgradePipeline.groovy
Labels: No Backport Needed

#4855 fix(aws_region) Enable DNS hostnames
  sdcm/utils/aws_region.py
Labels: No Backport Needed

#4891 fix(test_default): Add default value for gce_pd_standard_disk_size_db
  defaults/test_default.yaml
Labels: Backport-5.0, Backport-2022.1

#4862 fix(k8s): make sure we have an event for the test outcome
  functional_tests/scylla_operator/conftest.py
  functional_tests/scylla_operator/libs/auxiliary.py
Labels: Backport-5.0, Backport-2022.1

#4896 feature(manager-3.0): Switch default to scylla manager-3.0
  defaults/manager_versions.yaml
  defaults/test_default.yaml
Labels: Ready for review, Urgent, Backport-perf-v12

#4899 fix(manager task arguments): Restricted split with maxsplit
  sdcm/mgmt/cli.py
Labels: No Backport Needed

#4903 test(artifacts): add nonroot offline for ubuntu 22
  jenkins-pipelines/nonroot-offline-install/artifacts-ubuntu2204.jenkinsfile
Labels: Backport-5.0, Backport-2022.1

#4905 improvement(k8s): make 'append_scylla_args' option work in K8S
  defaults/k8s_eks_config.yaml
  defaults/k8s_gke_config.yaml
  defaults/k8s_local_kind_config.yaml
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed, Ready for review

#4776 fix(time synchronization check): Added full service print
  artifacts_test.py
Labels: Backport-5.0, Backport-2022.1

#4548 test(manager 3.0): Added test for on-resume-start-tasks flag
  mgmt_cli_test.py
  sdcm/mgmt/cli.py
  sdcm/mgmt/common.py
Labels: Backport-manager-3.0

#4792 fix(artifact_test): Skip timesync test on offline installation scenarios
  artifacts_test.py
Labels: Backport-5.0, Backport-2022.1

#4904 improvement(k8s): use mgmt 3.0.0 in K8S
  defaults/k8s_eks_config.yaml
  defaults/k8s_gke_config.yaml
  defaults/k8s_local_kind_config.yaml
  functional_tests/scylla_operator/test_functional.py
  test-cases/scylla-operator/functional.yaml
Labels: No Backport Needed, Ready for review

#4863 improvement(k8s-local): use static local volume provisioner
  defaults/k8s_local_kind_config.yaml
  sdcm/cluster_k8s/__init__.py
  sdcm/cluster_k8s/mini_k8s.py
  sdcm/k8s_configs/provisioner/values.yaml
  sdcm/tester.py
Labels: No Backport Needed, Ready for review

#4911 feature(longevity-with-raft): New regular longevities with raft enabled
  jenkins-pipelines/raft/longevity-100gb-4h-with-raft.jenkinsfile
  jenkins-pipelines/raft/longevity-50gb-3days-raft.jenkinsfile
  jenkins-pipelines/raft/longevity-cdc-8h-multi-dc-topology-changes-raft.jenkinsfile
  jenkins-pipelines/raft/longevity-lwt-parallel-schema-changes-with-disruptive-24h-raft.jenkinsfile
Labels: No Backport Needed, Ready for review

#4910 feature(argus): Update to 0.8.0
  docker/env/version
  requirements.in
  sdcm/tester.py
Labels: Backport-5.0, Backport-2022.1

#4901 fix(cassandra stress): disabling client encryption for cloud runs
  sdcm/tester.py
Labels: No Backport Needed

#4918 fix(k8s): make append_scylla_args not break multi-tenant setup
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed, Ready for review

#4917 fix(nemesis): clear all snapshots after scrub
  sdcm/nemesis.py
Labels: Ready for review, Backport-5.0, Backport-2022.1

#4921 fix(error): ignore view update gate_closed_exception during reboot
  sdcm/nemesis.py
  sdcm/sct_events/group_common_events.py
Labels: Ready for review, Backport-5.0, Backport-2022.1

#4916 test(artifact test): added amazon linux 2 arm artifact test
  configurations/arm/amazon2.yaml
  jenkins-pipelines/artifacts-amazon2-arm.jenkinsfile
Labels: Backport-5.0, Backport-2022.1

#4919 fix(remote_file): if content wasn't changed, don't copy back the file
  sdcm/remote/remote_file.py
  unit_tests/test_remoter.py
Labels: No Backport Needed

#4924 fix(common.py): add ubuntu 22 to `get_distro_name`
  sdcm/mgmt/common.py
Labels: Backport-5.0, Backport-2022.1

#4929 fix(k8s): refresh ip addresses on hard/soft reboot
  sdcm/cluster_k8s/__init__.py
  sdcm/nemesis.py
Labels: Backport-5.0, Backport-2022.1

#4927 fix(decommission_streaming_err): run rebuild on a new node
  sdcm/nemesis.py
Labels: Ready for review, Backport-5.0, Backport-2022.1

#4931 feature(k8s_nemesis): move to use SisyphusMonkey for longvity
  configurations/operator/1tb-7days-no-tls.yaml
  configurations/operator/200GB-no-tls.yaml
  configurations/operator/50GB-no-tls.yaml
  configurations/operator/cdc-3d-400gb.yaml
  configurations/operator/large-collections-12h.yaml
  configurations/operator/large-partition-200k-pks-4days.yaml
  configurations/operator/lwt-basic-24h.yaml
  configurations/operator/twcs-basic-48h.yaml
  sdcm/nemesis.py
  test-cases/scylla-operator/longevity-scylla-operator-3h.yaml
  test-cases/scylla-operator/longevity-scylla-operator-basic-12h.yaml
Labels: No Backport Needed

#4940 fix(nemesis): ignore STREAM_MUTATION_FRAGMENTS during decommission
  sdcm/nemesis.py
  sdcm/sct_events/group_common_events.py
Labels: Backport-5.0, Backport-2022.1

#4944 fix(get_gossip_info): implement `_refresh_instance_state` for AWSNode
  sdcm/cluster_aws.py
Labels: No Backport Needed, Bug

#4943 fix(sla deviation): change deviation percent
  sla_per_user_system_test.py
Labels: Ready for review, Backport-5.0, Backport-2022.1

#4942 fix(flush_and_reshard_on_k8s): identify the scylla pod base on it's name
  sdcm/nemesis.py
Labels: No Backport Needed

#4934 fix(arm artifact tests): Enabled manager agent installation
  jenkins-pipelines/artifacts-amazon2-arm.jenkinsfile
  jenkins-pipelines/artifacts-centos8-arm.jenkinsfile
  jenkins-pipelines/artifacts-debian10-arm.jenkinsfile
  jenkins-pipelines/artifacts-ubuntu2004-arm.jenkinsfile
  jenkins-pipelines/artifacts-ubuntu2204-arm.jenkinsfile
Labels: Backport-5.0, Backport-2022.1

#4947 test(stop-upgrade): disable stop upgrade compaction test
  stop_compaction_test.py
Labels: Backport-5.0, Backport-2022.1

#4958 fix(unit-tests): update AMI ids in the tests
  .pre-commit-config.yaml
  sdcm/utils/common.py
  unit_tests/test_config.py
  unit_tests/test_utils_common.py
Labels: No Backport Needed, Ready for review

#4955 fix(RebuildStreamingErr): ingore STREAM_MUTATION_FRAGMENTS errors
  sdcm/nemesis.py
  sdcm/sct_events/group_common_events.py
Labels: Backport-5.0, Backport-2022.1

#4957 fix(database event): reduce severity ScyllaHelpErrorEvent
  defaults/severities.yaml
  sdcm/sct_events/database.py
Labels: Backport-5.0, Backport-2022.1

#4956 fix(group_common_events): don't use LogEvent in SeverityChangerFilter
  sdcm/sct_events/group_common_events.py
Labels: Bug, Backport-2021.1, Backport-4.6, Backport-5.0, Backport-2022.1

#4953 fix(nemesis): avoid retrying after interrupt
  sdcm/cluster.py
  sdcm/nemesis.py
Labels: Ready for review, Backport-5.0, Backport-2022.1

#4967 fix(group_common_events.py): delete unused import making pylint be happy
  sdcm/sct_events/group_common_events.py
Labels: No Backport Needed
