Repository scylladb/scylla-cluster-tests, pull requests merged in 2022-03, with the labels that each got.

#4476 fix(cluster.py): fix is_apt_lock_free method
  sdcm/cluster.py
Labels: Ready for review, Backport-perf-v10, Bug, Backport-2021.1, Backport-4.5, Backport-manager-v2.4, Backport-perf-v11, Backport-operator-1.3, Backport-operator-1.4, Backport-manager-v2.5, Backport-operator-1.5, Backport-manager-2.6, Backport-4.6, Backport-perf-v12, Backport-operator-1.6, Backport-5.0, Backport-manager-3.0

#4466 refactor(manager): Rewritten the manager code to use the new 3.0 cli
  mgmt_cli_test.py
  mgmt_upgrade_test.py
  sdcm/cluster.py
  sdcm/mgmt/cli.py
  sdcm/mgmt/common.py
  sdcm/mgmt/operator.py
Labels: Backport-manager

#4495 refactor(manager upgrade): changed base version to 2.6
  jenkins-pipelines/manager/centos-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/debian10-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/debian9-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu16-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu18-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu20-manager-upgrade.jenkinsfile
Labels: Backport-manager-3.0

#4499 fix(artifact timesync check): skip the test for docker runs
  artifacts_test.py
Labels: Backport-4.6

#4498 refactor(artifact-arm): set manager 2.6 agent installation for arm tests
  configurations/arm/centos8.yaml
  configurations/arm/debian10.yaml
  configurations/arm/ubuntu2004.yaml
  jenkins-pipelines/artifacts-centos8-arm.jenkinsfile
  jenkins-pipelines/artifacts-debian10-arm.jenkinsfile
  jenkins-pipelines/artifacts-ubuntu2004-arm.jenkinsfile
  vars/artifactsPipeline.groovy
Labels: No Backport Needed

#4494 fix(cloud_longevity): collect cloud manager logs for AWS cluster
  sdcm/logcollector.py
  sdcm/tester.py
Labels: No Backport Needed, Ready for review

#4500 fix(filter_rc_only_version): last 2 base version don't have release
  unit_tests/test_base_version.py
  utils/get_supported_scylla_base_versions.py
Labels: No Backport Needed

#4504 fix(getJobTimeouts): +20min to collect logs timeout
  vars/getJobTimeouts.groovy
Labels: No Backport Needed, Ready for review

#4508 fix(cloud manager): collect manager logs
  sdcm/logcollector.py
  sdcm/sct_config.py
Labels: No Backport Needed, Ready for review

#4513 fix(logcollector): not need cloud manager id for log collection on GCE
  sdcm/logcollector.py
Labels: No Backport Needed, Ready for review

#4482 fix(disrupt_delete_by_rows_range): Fix choose_partitions_for_delete
  sdcm/nemesis.py
Labels: Backport-4.6

#4473 improvement(sdcm.argus_test_run): Parse JOB_NAME instead of branch names
  sdcm/argus_test_run.py
  sdcm/tester.py
Labels: Backport-5.0

#4517 fix(manager sanity): removed unnecessary suspend command
  mgmt_cli_test.py
Labels: Backport-manager-3.0

#4515 fix(nemesis): fix verification in disrupt terminate and replace node
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#4510 fix(housekeeping): gether scylla-houskeeping log
  sdcm/logcollector.py
  sdcm/utils/remote_logger.py
Labels: Ready for review, Backport-4.6

#4512 test(artifact): validate housekeeping service
  artifacts_test.py
  defaults/severities.yaml
  sdcm/cluster.py
  sdcm/cluster_docker.py
  sdcm/sct_events/database.py
Labels: Ready for review

#4505 fix(filter_rc_only_version): don't filter on master branch
  unit_tests/test_base_version.py
  utils/get_supported_scylla_base_versions.py
Labels: No Backport Needed

#4521 fix(argus): Update argus to 0.6.2
  docker/env/version
  requirements.in
Labels: Backport-5.0

#4526 fix(jepsen test): change owner of jepsen-scylla folder
  jepsen_test.py
  sdcm/utils/git.py
Labels: No Backport Needed, Ready for review

#4525 fix(check_regression_with_subtest_baseline): use use_wide_query=True
  sdcm/results_analyze/__init__.py
Labels: Backport-perf-v13

#4529 fix(cassandra-harry): clone repo as non-root user
  sdcm/cluster.py
Labels: No Backport Needed, Ready for review

#4531 improvement(cloud longevity): change get manager for both backends
  sdcm/logcollector.py
Labels: No Backport Needed, Ready for review

#4530 refactor(get-user-keyspaces): remove duplication
  sdcm/cluster.py
  sdcm/nemesis.py
Labels: No Backport Needed

#4533 fix(dababase_log_event): New disk error event
  defaults/severities.yaml
  sdcm/sct_events/database.py
  unit_tests/test_sct_events_database.py
Labels: Ready for review, Backport-5.0

#4535 fix(events): disable compaction and repair events
  sdcm/sct_events/database.py
  unit_tests/test_sct_events_continuous_events_registry.py
Labels: Ready for review, Backport-4.6, Backport-5.0

#4536 fix(alternator-pref): move to us-east-1
  jenkins-pipelines/perf-regression-alternator-latency-30min.jenkinsfile
  jenkins-pipelines/perf-regression-alternator-throughput-30min.jenkinsfile
  test-cases/performance/perf-regression-alternator-latency-500gb-30min.yaml
  test-cases/performance/perf-regression-alternator.100threads.30M-keys.yaml
Labels: Backport-perf-v13

#4541 fix(azure-image-test): use public ssh connection
  jenkins-pipelines/artifacts-azure-image.jenkinsfile
Labels: Backport-5.0

#4542 fix(break_streaming_task_and_rebuild): wait for JMX server to be up
  sdcm/nemesis.py
Labels: Backport-4.6

#4544 fix(alternator-200GB-48h): add time limit to the main stress cmds
  test-cases/longevity/longevity-alternator-200GB-48h.yaml
Labels: Backport-5.0

#4543 fix(disrupt_no_corrupt_repair): remove timeout from thread result
  sdcm/nemesis.py
Labels: Backport-5.0

#4522 fix(backtrace_decoding): decoding wasn't done
  sdcm/cluster.py
  sdcm/sct_events/database.py
  unit_tests/test_decode_backtrace.py
Labels: Backport-perf-v10, Backport-perf-v11, Backport-4.6, Backport-perf-v12, Backport-5.0, Backport-perf-v13

#4559 fix(sdcm.monitorstack): tolerate absence of some dashboard
  sdcm/logcollector.py
  sdcm/monitorstack/__init__.py
Labels: Ready for review, Backport-5.0

#4560 fix(managerPipeline): fetched the value of manager_version
  vars/managerPipeline.groovy
Labels: Backport-manager-3.0

#4557 fix(monitoring_download): revert to master dashboard if not available
  sdcm/monitorstack/__init__.py
Labels: Backport-5.0
