Repository scylladb/scylla-cluster-tests, pull requests merged in 2022-11, with the labels that each got.

#5376 fix(k8s): do not call `docker pull` command in stress thread class
  sdcm/scylla_bench_thread.py
  sdcm/stress_thread.py
Labels: No Backport Needed, Ready for review

#5375 fix(k8s-gke): skip flush and reshard nemesis due to the bug
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#5351 feature(event-handler): collect data for schema mismatch investigation
  defaults/severities.yaml
  sdcm/sct_events/event_handler.py
  sdcm/sct_events/events_processes.py
  sdcm/sct_events/handlers/__init__.py
  sdcm/sct_events/handlers/schema_disagreement.py
  sdcm/sct_events/loaders.py
  sdcm/sct_events/setup.py
  sdcm/tester.py
  sdcm/utils/common.py
  sdcm/utils/s3_remote_uploader.py
  sdcm/utils/sstable/s3_uploader.py
  unit_tests/test_sct_events_events_handler.py
  unit_tests/test_sct_events_loaders.py
Labels: No Backport Needed

#5382 fix(rolling-upgrade): add missing linux_distro param
  sct.py
Labels: Backport-5.1, Backport-2022.2

#5385 feature(show monitor): support multi-tenant configuration
  sct.py
  sdcm/monitorstack/__init__.py
Labels: test-provision-aws, test-provision-docker

#5389 fix(duplicate): remove unused `create_cql_ks_and_table`
  unit_tests/test_scylla_bench_thread.py
Labels: No Backport Needed

#5392 fix(add_remove_dc): skip nemesis for multi dc scenario
  sdcm/nemesis.py
Labels: Backport-5.1, Backport-2022.2

#5391 fix(nemesis): ignore connection refused error on restart_with_resharding
  sdcm/nemesis.py
Labels: Backport-5.1, Backport-2022.2

#5397 fix(pylint): remove duplicate-code check
  pylintrc
Labels: Backport-5.0, Backport-2022.1, Backport-5.1, Backport-2022.2

#5396 fix(ignore_stream_mutation_fragments): filter mutation write error
  sdcm/sct_events/group_common_events.py
Labels: Ready for review, Backport-2022.1, Backport-5.1, Backport-2022.2

#5400 fix(multi-keyspaces): remove loader ami overrides
  test-cases/longevity/longevity-multi-keyspaces.yaml
Labels: Backport-5.1, Backport-2022.2

#5401 Revert "test(upgrade): add OS package upgrade for AMI test"
  upgrade_test.py
Labels: Backport-5.0, Backport-2022.1, Backport-5.1, Backport-2022.2

#5407 improvement(k8s-local): cache docker images only on fresh setups
  sdcm/cluster_k8s/mini_k8s.py
Labels: No Backport Needed, Ready for review

#5394 fix(requirements.in): update to `ssh2-python==1.0.0`
  docker/env/version
  requirements.in
  requirements.txt
Labels: No Backport Needed, test-provision-aws, test-provision-gce, test-provision-docker, New Hydra Version

#5416 fix(k8s-eks): make i4i instance types be supported for the Scylla nodes
  sdcm/k8s_configs/eks/scylla-node-prepare.yaml
Labels: No Backport Needed, Ready for review

#5417 fix(get_relocatable_pkg_url): skip get reloc_pkg if version is none
  sdcm/tester.py
  sdcm/utils/version_utils.py
Labels: Backport-5.0, Backport-2022.1, Backport-5.1, Backport-2022.2

#5414 fix(longevity-multi-keyspaces-60h): enlarge the db root disk size
  test-cases/longevity/longevity-multi-keyspaces.yaml
Labels: Backport-5.1, Backport-2022.2

#5411 fix(test_default): Switch oracle db version for gemini
  defaults/test_default.yaml
  unit_tests/test_config.py
  unit_tests/test_data/test_scylla_yaml_builders/PR-provision-test.yaml
  unit_tests/test_scylla_yaml_builders.py
Labels: Ready for review, Backport-2022.1, Backport-5.1, Backport-2022.2

#5420 fix(cluster.py): Generate a scylla core dump according to boolean flag
  defaults/severities.yaml
  sdcm/cluster.py
  sdcm/sct_events/system.py
Labels: Backport-5.1, Backport-2022.2

#5425 fix(nemesis.py): Shadowing of a node variable
  sdcm/nemesis.py
Labels: No Backport Needed

#5426 fix(cluster.py): Increase timeout of node init to 8 hours
  sdcm/cluster.py
Labels: Backport-5.1, Backport-2022.2

#5427 fix(sct-cleanup): add CreatedBy tag to security groups
  sdcm/utils/aws_region.py
Labels: Backport-5.1, Backport-2022.2

#5424 fix(sct_events/setup.py): Filter LDAP connection resets
  sdcm/sct_events/setup.py
Labels: Backport-5.0, Backport-2022.1, Backport-5.1, Backport-2022.2

#5421 test(upgrade): run upgrade test with SLA
  configurations/rolling-upgrade-with-sla.yaml
  jenkins-pipelines/rolling-upgrade-with-sla.jenkinsfile
  longevity_sla_test.py
  sdcm/utils/loader_utils.py
  test_lib/sla.py
  upgrade_test.py
Labels: Ready for review, Backport-2022.1, Backport-5.1, Backport-2022.2

#5432 feature(sct-runner): new test configuration for instance/disk
  defaults/k8s_local_kind_aws_config.yaml
  defaults/k8s_local_kind_gce_config.yaml
  sct.py
  sdcm/sct_config.py
  test-cases/longevity/longevity-multi-keyspaces.yaml
  vars/createSctRunner.groovy
Labels: Backport-5.1, Backport-2022.2

#5434 fix(cluster.py): properly parse cpuset node info
  sdcm/cluster.py
  unit_tests/test_cluster.py
Labels: No Backport Needed, Ready for review

#4655 feature(nemesis): Change TWCS unit size and check reshaping
  sdcm/cluster.py
  sdcm/nemesis.py
Labels: Ready for review

#5435 improvement(k8s-multitenancy): process all monitors in parallel
  sdcm/tester.py
Labels: No Backport Needed, Ready for review

#5436 fix(docker): fix `reuse_cluster` to find instance
  sdcm/cluster_docker.py
  sdcm/utils/docker_utils.py
  unit_tests/test_utils_docker.py
Labels: No Backport Needed

#5441 fix(k8s-kind): setup calico CNI plug-in first
  sdcm/cluster_k8s/mini_k8s.py
  sdcm/k8s_configs/cni-calico.yaml
Labels: No Backport Needed, test-provision-k8s-local-kind-aws

#5437 fix(dynamic-loader): create new pods on `reuse_cluster`
  sdcm/remote/kubernetes_cmd_runner.py
Labels: No Backport Needed

#5446 fix(multitanent): `stop_resources when` `setUp` fails
  sdcm/utils/operator/multitenant_common.py
Labels: No Backport Needed

#5445 fix(upgrade): remove enable_authorization_after_upgrade parameter
  defaults/test_default.yaml
  docs/configuration_options.md
  sdcm/sct_config.py
  test-cases/scylla-operator/kubernetes-scylla-upgrade.yaml
  test-cases/upgrades/generic-rolling-upgrade.yaml
  test-cases/upgrades/multi-dc-rolling-upgrade.yaml
  test-cases/upgrades/rolling-upgrade.yaml
  unit_tests/test_data/test_scylla_yaml_builders/rolling-upgrade.yaml
  upgrade_test.py
Labels: Backport-5.1, Backport-2022.2

#5422 fix(disrupt_no_corrupt_repair): wait for schema agreement
  sdcm/nemesis.py
Labels: Backport-5.1, Backport-2022.2

#5461 fix(k8s-ingress): remove wrong configuration options
  sdcm/k8s_configs/ingress-controller/10_haproxy-kubernetes-ingress.configmap.yaml
Labels: No Backport Needed

#5460 fix(rolling_upgrade): add azure region name param to getJenkinsLabels
  vars/rollingUpgradePipeline.groovy
Labels: Backport-5.1, Backport-2022.2

#5454 fix(loaders): disable retry on main loader run commands
  sdcm/cassandra_harry_thread.py
  sdcm/cdclog_reader_thread.py
  sdcm/gemini_thread.py
  sdcm/kcl_thread.py
  sdcm/ndbench_thread.py
  sdcm/scylla_bench_thread.py
  sdcm/stress_thread.py
  sdcm/ycsb_thread.py
Labels: No Backport Needed, test-integration

#5453 fix(5000-tables): enlarge the runner root disk to 120Gb
  test-cases/scale/longevity-5000-tables.yaml
Labels: Backport-2022.1, Backport-5.1

#5471 fix(aws-ami): skip arm AMI when listing AMIs
  sdcm/utils/common.py
Labels: No Backport Needed

#5475 Fix fullscan queries
  sdcm/scan_operation_thread.py
Labels: Backport-5.1, Backport-2022.2

#5481 fix(perf-with-nemesis): Support ubuntu 22.04
  defaults/manager_versions.yaml
  sdcm/cluster.py
  sdcm/mgmt/common.py
  sdcm/provision/common/utils.py
  sdcm/utils/distro.py
  test-cases/performance/perf-regression-latency-1TB.yaml
  test-cases/performance/perf-regression-latency-250gb-with-nemesis.yaml
  test-cases/performance/perf-regression.100threads.30M-keys.yaml
Labels: No Backport Needed, Ready for review, Urgent

#5482 fix(argus): Switch to Argus version that works `AddressTranslator`
  docker/env/version
  requirements.in
  requirements.txt
  sdcm/keystore.py
  unit_tests/test_argus.py
Labels: No Backport Needed

#5484 fix(get_docker_image_by_version): make it more roubst to errors
  sdcm/utils/version_utils.py
  unit_tests/test_version_utils.py
Labels: No Backport Needed

#5456 Fix resharding nemesis for k8s
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#5487 fix(lwt-datavalidator): wrong query for `copy_table_as`
  sdcm/tester.py
Labels: No Backport Needed

#5488 fix(perf_jobs): move to correct email recipient
  test-cases/performance/perf-regression-latency-500gb-30min.yaml
  test-cases/performance/perf-regression.100threads.30M-keys.yaml
Labels: No Backport Needed

#5463 test(upgrade): run upgrade test with SLA [branch 2022.2]
  configurations/rolling-upgrade-with-sla.yaml
  jenkins-pipelines/rolling-upgrade-with-sla.jenkinsfile
  longevity_sla_test.py
  test_lib/sla.py
  upgrade_test.py
Labels: Ready for review

#5490 fix(es_queries): Use explicit job name instead of wc
  sdcm/utils/es_queries.py
Labels: Ready for review, Backport-perf-v8, Backport-perf-v12

#5492 fix(cordump_thread): get coredumpctl output in json format
  sdcm/coredump.py
  unit_tests/test_coredump.py
  unit_tests/test_data/test_coredump/systemd/success_test_systemd_248_remoter.json
  unit_tests/test_data/test_coredump/systemd/success_test_systemd_248_results.json
Labels: Backport-perf-v8, Backport-perf-v12

#5497 improvement(monitor_branch): Switch monitor to branch-4.1
  defaults/test_default.yaml
Labels: test-provision-aws, test-provision-docker

#5491 fix(es_queries): Use explicit job name instead of wc
  sdcm/results_analyze.py
Labels: No Backport Needed, Ready for review

#5507 fix(install_bench_tool): Install git on db instances
  sdcm/utils/benchmarks.py
Labels: No Backport Needed, Ready for review
