Repository scylladb/scylla-cluster-tests, pull requests merged in 2022-07, with the labels that each got.

#4959 fix(sla test): change expected shares ratio to 3.5
  sla_per_user_system_test.py
Labels: Ready for review, Backport-2022.1

#4966 fix(nemesis): increase timeout in 'disrupt_decommission_streaming_err'
  sdcm/nemesis.py
Labels: Backport-5.0, Backport-2022.1

#4965 fix(nemesis): increase timeout in the 'disrupt_repair_streaming_err'
  sdcm/nemesis.py
Labels: Backport-5.0, Backport-2022.1

#4970 fix(aws_config): re-created loader v9
  defaults/aws_config.yaml
Labels: No Backport Needed

#4969 fix(aws_config): re-created loader v16
  defaults/aws_config.yaml
Labels: No Backport Needed

#4972 fix(backup nemesis): deleting all backup tasks before nemesis run
  sdcm/nemesis.py
Labels: Backport-5.0, Backport-2022.1

#4909 fix(scylla_bench_thread): add all available node to command
  sdcm/scylla_bench_thread.py
Labels: No Backport Needed

#4961 test(manager): added manager tests that use enterprise ami
  jenkins-pipelines/manager/enterprise-ami-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/enterprise-ami-manager-upgrade.jenkinsfile
Labels: No Backport Needed

#4990 fix(install_scylla): adding workaround to JDK
  sdcm/cluster.py
Labels: No Backport Needed

#4991 fix(gce): fix warning flood in GCE tests about ipv6
  sdcm/cluster_gce.py
Labels: Backport-5.0, Backport-2022.1

#4989 fix(get_email_data): add trackbacks to log in case of failure
  longevity_test.py
Labels: No Backport Needed

#4985 fix(GrowShrinkClusterNemesis): use `k8s_n_scylla_pods_per_cluster`
  sdcm/nemesis.py
Labels: No Backport Needed

#4986 fix(SnapshotOperations): filter out SI/MV tables
  sdcm/nemesis.py
Labels: Backport-5.0, Backport-2022.1

#4982 feature(nemesis): parametrize nemesis cycles count
  performance_regression_test.py
  sdcm/cluster.py
  sdcm/nemesis.py
Labels: Backport-perf-v12, Backport-perf-v13

#4992 fix(mini_k8s): `start_k8s_software()` was creating extra db node
  sdcm/cluster_k8s/mini_k8s.py
Labels: No Backport Needed

#4979 feature(gce-log-monitor): error events for GCE hostError
  sdcm/cluster.py
  sdcm/cluster_aws.py
  sdcm/cluster_gce.py
  sdcm/gce_log_monitor.py
  sdcm/sct_events/gce_events.py
  sdcm/tester.py
  sdcm/utils/gce_utils.py
  unit_tests/test_gce_log_monitor.py
Labels: No Backport Needed

#4996 feature(azure): support list-resources command
  sct.py
  sdcm/provision/azure/provisioner.py
Labels: No Backport Needed

#5002 fix(k8s-multitenant): run 7+ DB cluster really in parallel
  performance_regression_operator_multi_tenant_test.py
  sdcm/tester.py
Labels: No Backport Needed

#5004 fix(k8s-multitenant): make Scylla pods be sched only on different nodes
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed

#5006 improvement(k8s): run fstrim command with retry
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed

#5009 fix(k8s-multitenant): use non-unique values for storing test names
  performance_regression_operator_multi_tenant_test.py
Labels: No Backport Needed

#5015 fix(nemesis): ignore ycsb `Connection refused` on terminating a node
  sdcm/nemesis.py
Labels: No Backport Needed

#5008 feature(Azure): support Azure in SCT provision test
  Jenkinsfile
  vars/getJenkinsLabels.groovy
  vars/runCleanupResource.groovy
  vars/runCollectLogs.groovy
Labels: No Backport Needed, test-provision-azure

#4988 fix(upgrade-test): fix recover backup config files
  upgrade_test.py
Labels: Backport-5.0, Backport-2022.1

#5017 fix(upgrade-test): Fix new version in mail and argus
  upgrade_test.py
Labels: No Backport Needed

#5000 improvement(TaskStatus): Added SKIPPED task status
  sdcm/mgmt/common.py
Labels: No Backport Needed

#5021 fix(log_reader): off by one error when saving offset in log file
  sdcm/db_log_reader.py
  unit_tests/test_cluster.py
Labels: No Backport Needed

#5027 fix(cluster.py): replaced fstring with format
  sdcm/cluster.py
Labels: Backport-2019.1

#5029 fix(cluster.py): Remove command of yum makecache
  sdcm/cluster.py
Labels: Backport-5.0, Backport-2022.1

#5032 fix(cluster.py): skipping scylla bench installation
  sdcm/cluster.py
Labels: Backport-2019.1

#5033 fix(Full-Partition-Scan): Increase scan interval
  test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml
  test-cases/longevity/longevity-large-partition-3h.yaml
  test-cases/longevity/longevity-large-partition-4days.yaml
  test-cases/longevity/longevity-large-partition-8h.yaml
Labels: No Backport Needed

#5022 feature(spot-termination): Support SpotTerminationEvent on Azure
  sdcm/cluster_azure.py
Labels: No Backport Needed

#5019 refactor(rolling_upgrade): machine image as base for ubuntu 20.04
  jenkins-pipelines/rolling-upgrade-ubuntu20.04.jenkinsfile
  vars/rollingUpgradePipeline.groovy
Labels: Backport-5.0, Backport-2022.1

#5044 fix(jdk issue): adding case where artifacts starts from AMI
  sdcm/cluster.py
  sdcm/fill_db_data.py
  upgrade_test.py
Labels: No Backport Needed

#5055 fix(upgrade): fix base version for 2022.1
  unit_tests/test_base_version.py
  utils/get_supported_scylla_base_versions.py
Labels: Backport-5.0, Backport-2022.1

#5054 fix(rollingUpgrade): gce_image_db use_preinstalled_scylla can be null
  vars/rollingUpgradePipeline.groovy
Labels: Backport-5.0, Backport-2022.1

#5010 improvement(perf during ops): increase load for i3en test
  configurations/aws/i3en_2xlarge.yaml
Labels: Backport-perf-v12

#5049 fix(SSHScyllaSystemdLogger): install python3 to remove if needed
  sdcm/cluster.py
  sdcm/utils/remote_logger.py
Labels: Backport-5.0, Backport-2022.1

#5053 refactor(azure config): Changed backup backend to azure instead of s3
  defaults/azure_config.yaml
Labels: No Backport Needed, Ready to be Merged

#5038 feature(azure): add creation time to rg and vm's
  sct.py
  sdcm/provision/azure/provisioner.py
  sdcm/provision/azure/resource_group_provider.py
  sdcm/provision/azure/virtual_machine_provider.py
  sdcm/provision/provisioner.py
  unit_tests/lib/fake_provisioner.py
  unit_tests/provisioner/test_provisioner.py
Labels: No Backport Needed

#5047 feature(azure): use new Ls generation instance for 10gb test
  test-cases/longevity/longevity-10gb-3h.yaml
Labels: No Backport Needed

#5059 fix(version_utils): make semver transformation function be safer
  sdcm/utils/version_utils.py
Labels: No Backport Needed

#5061 fix(_run_stress_in_batches): treat stress_cmd as a list or a string
  longevity_test.py
Labels: No Backport Needed

#4968 improvement(operator): pre-create data for functional tests
  docs/configuration_options.md
  functional_tests/scylla_operator/conftest.py
  sdcm/cluster_k8s/__init__.py
  sdcm/sct_config.py
  sdcm/utils/common.py
  sdcm/utils/sstable/load_utils.py
  test-cases/scylla-operator/functional.yaml
Labels: Ready for review

#5067 fix(rolling upgrade): ignored all 'abort requested' messages
  sdcm/sct_events/group_common_events.py
  upgrade_test.py
Labels: No Backport Needed

#5078 fix(k8s): refresh IP addresses after flush and reshard nemesis
  sdcm/nemesis.py
Labels: No Backport Needed

#5076 fix(k8s): pick up really latest operator helm chart
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed

#5077 fix(k8s): always set proper number of CPUs for Scylla pods
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed

#5065 fix(get_specific_tag_of_docker_image): tag doesn't have images anymore
  sdcm/utils/version_utils.py
Labels: No Backport Needed

#5073 improvement(manager tests): using scylla 5.0 instead of 4.6
  vars/managerPipeline.groovy
Labels: Backport-manager-3.0
