Repository scylladb/scylla-cluster-tests, pull requests merged in 2022-04, with the labels that each got.

#4576 fix(test_base_version.py): bump enterprise version
  unit_tests/test_base_version.py
Labels: No Backport Needed

#4575 fix(managerPipeline.groovy): added missing curly bracket
  vars/managerPipeline.groovy
Labels: Backport-manager-3.0

#4395 fix(perf with nemesis): reduce email size
  sdcm/report_templates/results_latency_during_ops.html
  sdcm/report_templates/results_latency_during_ops_short.html
  sdcm/report_templates/results_reactor_stall_events_list.html
  sdcm/results_analyze/__init__.py
Labels: Ready to be Merged, Backport-perf-v12, Backport-perf-v13

#4572 fix(email): send email when cloud cluster is not created
  sdcm/logcollector.py
  sdcm/sct_config.py
Labels: No Backport Needed, Ready for review

#4565 fix(aws_user_data): make sure logs_transport is being passed
  sdcm/sct_provision/aws/user_data.py
Labels: Bug, Backport-4.6, Backport-5.0, Backport-2022.1

#4571 improvement(artifacts_test.py): Verify docker image locale settings
  artifacts_test.py
Labels: Backport-5.0, Backport-2022.1

#4558 fix(gce-reboot): fix hard_reboot method for gce
  sdcm/cluster_gce.py
Labels: Backport-5.0, Backport-2022.1

#4578 fix(housekeeping): workaround for the issue w/ Azure builder
  sdcm/utils/housekeeping.py
Labels: No Backport Needed, Ready for review

#4582 fix(cluster.py): modify PATH for monitoring start
  sdcm/cluster.py
Labels: Ready for review, Backport-4.6, Backport-5.0, Backport-2022.1

#4583 fix(email data): do not collect data if cluster was not created
  longevity_test.py
Labels: No Backport Needed, Ready for review

#4549 fix(manager jobs): Removed unnecessary timeout param in pipeline files
  jenkins-pipelines/manager/centos-manager-backup-200gb.jenkinsfile
  jenkins-pipelines/manager/centos-manager-backup-azure.jenkinsfile
  jenkins-pipelines/manager/centos-manager-backup-gce-1tb.jenkinsfile
  jenkins-pipelines/manager/centos-manager-backup-gce.jenkinsfile
  jenkins-pipelines/manager/centos-manager-backup.jenkinsfile
  jenkins-pipelines/manager/centos-manager-repair-control.jenkinsfile
  jenkins-pipelines/manager/centos-manager-repair-intensity-multiple-repaired-nodes.jenkinsfile
  jenkins-pipelines/manager/centos-manager-repair-intensity-single-repaired-nodes.jenkinsfile
  jenkins-pipelines/manager/centos-manager-sanity-ipv6.jenkinsfile
  jenkins-pipelines/manager/centos-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/centos-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/debian10-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/debian10-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/debian9-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/debian9-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu16-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/ubuntu16-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu18-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/ubuntu18-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu20-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/ubuntu20-manager-upgrade.jenkinsfile
Labels: Backport-manager-3.0

#4584 fix(ManagerTask.arguments): switched to using progress_string function
  sdcm/mgmt/cli.py
Labels: Backport-manager-3.0

#4592 fix(database.py): lower event severity
  defaults/severities.yaml
  sdcm/sct_events/database.py
Labels: Backport-5.0, Backport-2022.1

#4591 fix(pylint): remove code duplication
  sdcm/cluster_aws.py
  sdcm/cluster_gce.py
  sdcm/cluster_k8s/eks.py
  sdcm/cluster_k8s/gke.py
  sdcm/wait.py
Labels: No Backport Needed, Ready for review

#4590 refactor(manager): Moved scylla version to 4.6
  jenkins-pipelines/manager/centos-manager-backup-gce.jenkinsfile
  vars/managerPipeline.groovy
Labels: Backport-manager-3.0

#4596 fix(fill_db_data): version was set wrong for min_version
  sdcm/fill_db_data.py
Labels: Backport-5.0, Backport-2022.1

#4601 fix(rollingUpgradePipeline): make backported commit work
  vars/rollingUpgradePipeline.groovy
Labels: No Backport Needed

#4600 feature(raft_config): Add config file for raft experimental
  configurations/raft/enable_raft_experimental.yaml
Labels: Ready for review, Backport-5.0, Backport-2022.1

#4607 fix(monitoring): bump monitoring version to 3.11
  defaults/test_default.yaml
Labels: Ready for review, Backport-5.0, Backport-2022.1

#4554 fix(cleanup-resources): azure clean by user
  sdcm/provision/azure/provisioner.py
  sdcm/utils/common.py
Labels: Backport-5.0, Backport-2022.1

#4594 fix(sdcm.nemesis): redefinition in disrupt_multiple_hard_reboot_node
  sdcm/nemesis.py
Labels: Ready for review, Backport-4.6, Backport-5.0, Backport-2022.1

#4587 fix(loader): fix missing ICS in c-s
  defaults/aws_config.yaml
  docs/new_loader_ami.md
Labels: Backport-5.0, Backport-2022.1

#4615 feature(argus): Argus 0.7.0 update
  docker/env/version
  requirements.in
  sdcm/argus_test_run.py
Labels: Backport-5.0, Backport-2022.1

#4620 fix(rolling-upgrade): Set a fixed gemini_seed for rolling-upgrades
  test-cases/upgrades/rolling-upgrade.yaml
Labels: Backport-4.5, Backport-4.6, Backport-5.0, Backport-2022.1

#4617 fix(runner): name of SCT runners that are use to restore monitoring
  docker/env/hydra.sh
  jenkins-pipelines/hydra-show-monitor.jenkinsfile
  sct.py
  sdcm/sct_runner.py
Labels: No Backport Needed, Ready for review

#4624 fix(cluster_docker.py): Implement region property
  sdcm/cluster_docker.py
Labels: Backport-5.0, Backport-2022.1

#4561 test(range tombstones): Add a new nemesis: DeleteOverlappingRowRangesMonkey
  sdcm/nemesis.py
Labels: Backport-4.6, Backport-5.0

#4630 fix(alternator_perf): extend throughput test test duration
  test-cases/performance/perf-regression-alternator.100threads.30M-keys.yaml
Labels: Backport-perf-v13

#4619 improvement(kuber): run scylla node prepare just once for a K8S cluster
  sdcm/cluster_k8s/__init__.py
  sdcm/cluster_k8s/eks.py
  sdcm/cluster_k8s/gke.py
  sdcm/tester.py
Labels: No Backport Needed

#4618 improvement(kuber): support creation of multiple K8S PVs on a local disk
  sdcm/cluster_k8s/__init__.py
  sdcm/k8s_configs/eks/scylla-node-prepare.yaml
  sdcm/k8s_configs/gke/scylla-node-prepare.yaml
  sdcm/k8s_configs/provisioner/templates/provisioner.yaml
  sdcm/k8s_configs/provisioner/values.yaml
Labels: No Backport Needed

#4568 fix(perf-test): stop after one nemesis cycle
  performance_regression_test.py
  sdcm/cluster.py
  test-cases/performance/perf-regression-latency-250gb-with-nemesis.yaml
Labels: Backport-perf-v12, Backport-perf-v13

#4603 Rolling upgrade base version discovery - add logging and faster pipeline exit
  sct.py
  unit_tests/test_base_version.py
  utils/get_supported_scylla_base_versions.py
  vars/rollingUpgradePipeline.groovy
  vars/supportedUpgradeFromVersions.groovy
Labels: Backport-2021.1, Backport-4.5, Backport-4.6, Backport-5.0, Backport-2022.1

#4633 fix(COMPACTION_STOPPED): change order of event in list
  sdcm/sct_events/database.py
  unit_tests/test_cluster.py
  unit_tests/test_data/compaction_stopped_exception.log
Labels: Backport-5.0, Backport-2022.1

#4634 fix(MemoryStressMonkey): install snap
  sdcm/nemesis.py
Labels: No Backport Needed

#4627 improvement(monitoring): support K8S multi-tenant case
  sdcm/cluster.py
  sdcm/cluster_k8s/eks.py
  sdcm/cluster_k8s/gke.py
Labels: No Backport Needed, Ready for review

#4635 improvement(k8s-net): use VPC-wide pod IPs for network connections
  sdcm/cluster.py
  sdcm/cluster_k8s/__init__.py
  sdcm/cluster_k8s/eks.py
  sdcm/cluster_k8s/gke.py
  sdcm/cluster_k8s/iptables.py
  sdcm/tester.py
Labels: No Backport Needed, Ready for review

#4637 Cleanup code in the sdcm/cluster.py module
  sdcm/cluster.py
Labels: No Backport Needed, Ready for review

#4638 fix(compaction.py): Added DateTieredCompactionStrategy to list
  test_lib/compaction.py
Labels: Backport-5.0, Backport-2022.1

#4640 fix(sct.py): `list_ami_branch` more resilient
  sct.py
Labels: No Backport Needed

#4639 fix(longevity-2tb job): `user_prefix` was wrong
  test-cases/longevity/longevity-2TB-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis.yaml
Labels: Backport-5.0, Backport-2022.1

#4643 improvement(sdcm.argus_test_run): Azure resources config support
  sdcm/argus_test_run.py
Labels: Backport-5.0, Backport-2022.1

#4644 improvement(argus): Download argus from pypi
  requirements.in
Labels: No Backport Needed

#4647 fix(cdc-8h-multi-dc): set correct config yaml file
  jenkins-pipelines/longevity-cdc-8h-multi-dc-large-cluster.jenkinsfile
Labels: Ready for review, Backport-5.0, Backport-2022.1

#4468 improvement(reversed queries): Added reversed queries data validation
  sdcm/scan_operation_thread.py
  test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml
  test-cases/longevity/longevity-large-partition-3h.yaml
  test-cases/longevity/longevity-large-partition-4days.yaml
  test-cases/longevity/longevity-large-partition-8h.yaml
Labels: Backport-4.6, Backport-5.0, Backport-2022.1

#4651 refactor(unit_tests): remove duplicated code for DummyNode
  unit_tests/test_cluster.py
  unit_tests/test_decode_backtrace.py
  unit_tests/test_utils_common.py
Labels: No Backport Needed

#4654 fix(scylla_yaml): add missed EaR options
  sdcm/provision/scylla_yaml/scylla_yaml.py
  unit_tests/test_scylla_yaml.py
Labels: Backport-5.0, Backport-2022.1

#4653 fix(4628): handle connection errors in `get_my_public_ip()`
  sdcm/utils/net.py
Labels: Backport-5.0, Backport-2022.1

#4645 fix(cloud_monitor): cast str for GCE instance state
  sdcm/utils/cloud_monitor/resources/instances.py
Labels: No Backport Needed

#4658 fix(gemini): use proper user for the oracle node
  test-cases/gemini/gemini-3h-ics-cdc-with-nemesis.yaml
Labels: Backport-5.0, Backport-2022.1

#4642 fix(nemesis): not start nodetool rebuild if another rebuild runs
  sdcm/nemesis.py
Labels: Ready for review, Backport-5.0, Backport-2022.1

#4593 test(nodetool-stop): test nodetool stop for ICS
  jenkins-pipelines/features-nodetool-stop-compaction-ics.jenkinsfile
  stop_compaction_test.py
  test-cases/features/stop-compaction-ics.yaml
Labels: Ready to be Merged, Backport-5.0, Backport-2022.1
