Repository scylladb/scylla-cluster-tests, pull requests merged in 2022-08, with the labels that each got.

#5057 improvement(latency during ops): report colors
  sdcm/report_templates/results_latency_during_ops_short.html
  sdcm/utils/latency.py
Labels: Ready for review, Ready to be Merged, Backport-perf-v12

#5071 feature(gce_project): switch the default project for gce
  sdcm/keystore.py
  vars/getJenkinsLabels.groovy
Labels: No Backport Needed

#5070 feature(cloud_monitor): add support for showing multiple projects
  sdcm/utils/cloud_monitor/resources/__init__.py
  sdcm/utils/cloud_monitor/resources/instances.py
  sdcm/utils/cloud_monitor/templates/per_qa_user.html
  sdcm/utils/cloud_monitor/templates/per_user.html
Labels: No Backport Needed

#5052 fix(azure-list-images): fix scylla master latest images list
  sdcm/provision/azure/utils.py
  sdcm/utils/version_utils.py
  unit_tests/provisioner/fake_azure_service.py
  unit_tests/provisioner/test_azure_get_scylla_images.py
  unit_tests/provisioner/test_data/SCYLLA-IMAGES/azure_images_list.json
  unit_tests/test_version_utils.py
Labels: No Backport Needed

#5081 Revert "fix(install_scylla): adding workaround to JDK"
  sdcm/cluster.py
Labels: No Backport Needed

#5075 fix(disrupt_multiple_hard_reboot_node): waiting for cdc success messages
  sdcm/nemesis.py
Labels: No Backport Needed

#5087 fix(unit-tests): add 2022.1 to base versions
  unit_tests/test_base_version.py
  unit_tests/test_config.py
Labels: No Backport Needed

#5089 fix(cluster_aws): added missing import
  sdcm/cluster_aws.py
Labels: No Backport Needed

#5091 fix(load utils): untar snapshot
  sdcm/utils/common.py
  sdcm/utils/sstable/load_utils.py
Labels: No Backport Needed

#5088 fix(manager-sanity): stop using public networking
  jenkins-pipelines/manager/debian11-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/enterprise-ami-manager-sanity.jenkinsfile
Labels: No Backport Needed

#5099 fix(k8s): run reconfigure_scylla_monitoring in flush and reshard nemesis
  sdcm/nemesis.py
Labels: No Backport Needed

#5100 improvement(k8s): disable k8s monitoring as redundant
  defaults/k8s_eks_config.yaml
  defaults/k8s_gke_config.yaml
Labels: No Backport Needed

#5097 fix(k8s): use proper number of loaders in K8S with single DB cluster
  defaults/k8s_eks_config.yaml
  defaults/k8s_gke_config.yaml
  defaults/k8s_local_kind_config.yaml
Labels: No Backport Needed

#5098 fix(k8s): make cql_ip_address not be cached forever
  sdcm/cluster.py
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed

#5102 fix(grafana_sct_dashboard): clear default list flags
  data_dir/scylla-dash-per-server-nemesis.master.json
Labels: Backport-perf-v12, Backport-5.0, Backport-2022.1

#5090 fix(loader_user_data): bring back user-data for loader nodes
  sdcm/cluster_aws.py
Labels: No Backport Needed

#5013 ci(k8s): add jobs to run K8S multi-tenant tests with 2, 7 and 14 clients
  configurations/operator/perf-regression-latency-and-throughput-multitenant-14-clients.yaml
  configurations/operator/perf-regression-latency-and-throughput-multitenant-2-clients.yaml
  configurations/operator/perf-regression-latency-and-throughput-multitenant-7-clients.yaml
  configurations/operator/perf-regression-latency-multitenant-14-clients.yaml
  configurations/operator/perf-regression-latency-multitenant-2-clients.yaml
  configurations/operator/perf-regression-latency-multitenant-7-clients.yaml
  jenkins-pipelines/operator/performance/perf-regression-latency-and-throughput-eks-multitenant-14-clients.jenkinsfile
  jenkins-pipelines/operator/performance/perf-regression-latency-and-throughput-eks-multitenant-2-clients.jenkinsfile
  jenkins-pipelines/operator/performance/perf-regression-latency-and-throughput-eks-multitenant-7-clients.jenkinsfile
  jenkins-pipelines/operator/performance/perf-regression-latency-eks-multitenant-14-clients.jenkinsfile
  jenkins-pipelines/operator/performance/perf-regression-latency-eks-multitenant-2-clients.jenkinsfile
  jenkins-pipelines/operator/performance/perf-regression-latency-eks-multitenant-7-clients.jenkinsfile
  test-cases/performance/perf-regression-latency-k8s-multitenant.yaml
Labels: No Backport Needed

#5103 fix(nemesis): skip 'disrupt_restart_with_resharding' nemesis for K8S
  sdcm/nemesis.py
Labels: No Backport Needed

#5101 feature(cluster): consume scylla key by gpg instead of apt-key
  sdcm/cluster.py
Labels: No Backport Needed

#4997 refactor(list-images): consolidate image listing
  sct.py
  sdcm/utils/common.py
Labels: No Backport Needed

#5108 fix(aws_config): re-created loader v16
  defaults/aws_config.yaml
Labels: No Backport Needed, Urgent, Bug

#5112 fix(longevity-cdc-100gb-4h): rename to fix typo
  jenkins-pipelines/longevity-cdc-100gb-4h.jenkinsfile
Labels: No Backport Needed

#5117 improvement(sdcm.tester): Generate scylla-server package in offline test
  sdcm/tester.py
Labels: Backport-5.0, Backport-2022.1, Backport-5.1

#5121 fix(unit_test): bump current enterprise version to 2022.2
  unit_tests/test_base_version.py
Labels: Backport-5.0, Backport-2022.1, Backport-5.1

#5096 fix(ParallelObject): log a full tracebacks on failures
  sdcm/utils/common.py
Labels: No Backport Needed

#5104 fix(k8s-functional): make prefill_cluster not run when we reuse cluster
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed

#5086 improvement(nemesis): add wrapper to disrupt method during init
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#5116 refactor(manager upgrade): bump base manager version to 3.0
  jenkins-pipelines/manager/centos-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/debian10-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/enterprise-ami-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu18-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu20-manager-upgrade.jenkinsfile
Labels: No Backport Needed

#5115 test(functional): add rolling change internode compression test
  functional_tests/scylla_operator/test_functional.py
Labels: No Backport Needed, Ready for review

#5131 fix(sdcm/tester.py): Fix test stoppage on shard reporting failure
  sdcm/cluster.py
Labels: Backport-5.0, Backport-2022.1, Backport-5.1

#5014 Adjust SCT runner lifespans based on test failure and collect_logs status
  sct.py
  sct_ssh.py
  sdcm/sct_runner.py
Labels: No Backport Needed

#5129 fix(k8s-upgrade): provision 4 K8S Scylla nodes
  test-cases/scylla-operator/kubernetes-operator-upgrade.yaml
  test-cases/scylla-operator/kubernetes-platform-upgrade.yaml
Labels: No Backport Needed

#5139 fix(gke): use non-deprecated config option for the logging
  sdcm/cluster_k8s/gke.py
Labels: No Backport Needed

#5134 fix(k8s nemeses): update nodes' IPs after node recreation
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#5141 improvement(eks): bump vpc-cni version
  defaults/k8s_eks_config.yaml
Labels: No Backport Needed

#5142 fix(sct_runner): reduce error to warning for no runners
  sdcm/sct_runner.py
Labels: No Backport Needed

#5144 Revert "fix(syslog-ng): add support for multi-line logs"
  sdcm/provision/common/utils.py
  sdcm/utils/syslogng.py
Labels: No Backport Needed

#5132 fix(db_stats.py): Reorganize Prometheus query methods
  ics_space_amplification_goal_test.py
  sdcm/db_stats.py
Labels: No Backport Needed

#5143 fix(gke): make longevity CI jobs work
  sdcm/tester.py
  vars/runCleanupResource.groovy
  vars/runCollectLogs.groovy
  vars/runSctTest.groovy
Labels: No Backport Needed

#5152 fix(gce): make cleanup work correctly
  sdcm/utils/common.py
Labels: No Backport Needed

#5153 improvement(k8s): fail fast if latest tag not translated to specific one
  sdcm/sct_config.py
  sdcm/utils/version_utils.py
Labels: No Backport Needed

#5094 test(mulitenant longevity): add new longevity test
  jenkins-pipelines/operator/eks/longevity-scylla-operator-3h-mulitenant-eks.jenkinsfile
  longevity_operator_multi_tenant_test.py
  sdcm/tester.py
  sdcm/utils/operator/miltitenant_common.py
  test-cases/scylla-operator/longevity-scylla-operator-3h-multitenant.yaml
  unit_tests/test_config.py
  unit_tests/test_data/test_config/multitenant/same_stress_cmd_for_all_tenants.yaml
  unit_tests/test_data/test_config/multitenant/unique_stress_cmd_per_tenant.yaml
Labels: No Backport Needed

#5158 fix(gemini): pin gemini version to the stable one
  test-cases/gemini/gemini-3h-with-nemesis.yaml
Labels: No Backport Needed

#5128 Split stress tools latencies panels
  data_dir/scylla-dash-per-server-nemesis.master.json
Labels: Ready for review, Backport-perf-v12

#5165 fix(list-images): make enterprise version work without prefixing
  sdcm/utils/common.py
Labels: No Backport Needed

#5166 Revert "fix(HACK): remove nemeis from harry case"
  test-cases/longevity/longevity-harry-2h.yaml
Labels: No Backport Needed

#5156 test(manager): Added ubuntu 22 sanity and upgrade test scenarios
  configurations/manager/ubuntu22.yaml
  jenkins-pipelines/manager/ubuntu22-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/ubuntu22-manager-upgrade.jenkinsfile
  sdcm/mgmt/cli.py
Labels: No Backport Needed

#5175 fix(longevity-10gb-3h): switch AWS instance type to `i4i.2xlarge`
  test-cases/longevity/longevity-10gb-3h.yaml
Labels: No Backport Needed

#5127 feature(docker-based-loaders): adding the design
  docs/docker-loaders.md
Labels: No Backport Needed

#5093 improvement(collect kallsyms): Collect Seastar kallsyms on boot
  sdcm/cluster.py
  sdcm/logcollector.py
  sdcm/nemesis.py
  sdcm/utils/common.py
Labels: Backport-perf-v12

#5182 improvement(nemesis): print traceback in log
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#5184 fix(version_utils): improve regexp for architecture part
  sdcm/utils/version_utils.py
Labels: Ready for review

#5177 feature(azure): handle availability zone
  sdcm/cluster.py
  sdcm/cluster_azure.py
  sdcm/provision/azure/ip_provider.py
  sdcm/provision/azure/provisioner.py
  sdcm/provision/azure/resource_group_provider.py
  sdcm/provision/azure/virtual_machine_provider.py
  sdcm/provision/azure/virtual_network_provider.py
  sdcm/provision/provisioner.py
  sdcm/sct_provision/instances_provider.py
  sdcm/sct_provision/region_definition_builder.py
  sdcm/sct_runner.py
  sdcm/tester.py
  unit_tests/lib/fake_provisioner.py
  unit_tests/lib/fake_resources.py
  unit_tests/provisioner/conftest.py
  unit_tests/provisioner/test_azure_region_definition_builder.py
  unit_tests/provisioner/test_provision_sct_resources.py
  unit_tests/provisioner/test_provisioner.py
  unit_tests/test_cluster.py
Labels: No Backport Needed

#5188 improvement(reactor stall): reduce detector and tolerable
  defaults/test_default.yaml
  sdcm/sct_events/database.py
Labels: No Backport Needed

#5181 fix(nemesis): revert using wrapped_disruptive_methods list
  sdcm/nemesis.py
Labels: Ready for review, Backport-2022.2

#5192 feature(github-actions): add auto assign action
  .github/auto_assign.yml
  .github/workflows/auto_assign.yaml
Labels: No Backport Needed

#5195 feature(github-actions): add auto assign action
  .github/workflows/auto_assign.yaml
Labels: No Backport Needed

#5197 feature(github-actions): switch to different actions for auto assign
  .github/auto_assign.yml
  .github/workflows/auto_assign.yaml
Labels: No Backport Needed

#5199 fix(azure): fix list instances when missing az
  sdcm/sct_runner.py
Labels: No Backport Needed

#5178 feature(udf): udf class, loader, scripts and unit tests
  sdcm/utils/udf.py
  sdcm/utils/udf_scripts/lua_var_length_counter.yaml
  sdcm/utils/udf_scripts/xwasm_fib.yaml
  sdcm/utils/udf_scripts/xwasm_plus.yaml
  unit_tests/test_udf.py
Labels: No Backport Needed

#5123 improvement(availability zone): Fallback availability zones in AWS instance provisioning
  defaults/test_default.yaml
  sdcm/sct_config.py
  sdcm/tester.py
  sdcm/utils/aws_utils.py
  test-cases/artifacts/ami.yaml
Labels: Backport-5.1

#5154 fix(get_specific_tag_of_docker_image): get tag from build info
  sdcm/utils/version_utils.py
  unit_tests/test_version_utils.py
Labels: No Backport Needed

#5191 improvement(upgrade base_version): remove deprecated and add lastest of
  jenkins-pipelines/rolling-upgrade-alternator.jenkinsfile
  jenkins-pipelines/rolling-upgrade-ami.jenkinsfile
  jenkins-pipelines/rolling-upgrade-centos7-ldap-authorization.jenkinsfile
  jenkins-pipelines/rolling-upgrade-centos7.jenkinsfile
  jenkins-pipelines/rolling-upgrade-debian10.jenkinsfile
  jenkins-pipelines/rolling-upgrade-debian9.jenkinsfile
  jenkins-pipelines/rolling-upgrade-ubuntu16.04.jenkinsfile
  jenkins-pipelines/rolling-upgrade-ubuntu18.04-ldap-authorization.jenkinsfile
  jenkins-pipelines/rolling-upgrade-ubuntu18.04.jenkinsfile
  jenkins-pipelines/rolling-upgrade-ubuntu20.04.jenkinsfile
  jenkins-pipelines/rolling-upgrade-with-null-inserts.jenkinsfile
Labels: No Backport Needed

#5176 feature(docker_backend): support running docker based loaders
  docker/scylla-sct/ubuntu/Dockerfile
  sdcm/cluster_docker.py
  sdcm/utils/docker_remote.py
  sdcm/utils/remotewebbrowser.py
Labels: No Backport Needed, test-provision-docker

#5204 fix(github-actions): switch to use `pull_request_target`
  .github/workflows/auto_assign.yaml
Labels: No Backport Needed

#5122 feature(log_collector): collect malformed sstables
  defaults/severities.yaml
  sdcm/logcollector.py
  sdcm/sct_events/database.py
  sdcm/utils/common.py
  sdcm/utils/s3_remote_uploader.py
Labels: No Backport Needed

#5207 fix(sct_runner): add force option
  sct.py
  sdcm/sct_runner.py
Labels: No Backport Needed

#5206 fix(upgrade test): extend the time to ignore cdc error
  sdcm/sct_events/group_common_events.py
  unit_tests/test_cluster.py
  upgrade_test.py
Labels: No Backport Needed

#5203 feature(k8s-local-kind): bump kind version
  defaults/k8s_local_kind_config.yaml
  test-cases/scylla-operator/functional.yaml
Labels: No Backport Needed
