Repository scylladb/scylla-cluster-tests, pull requests merged in 2022-12, with the labels that each got.

#5514 fix(disrupt_nodetool_enospc): re-enable enospc nemesis
  sdcm/nemesis.py
Labels: Backport-5.0, Backport-2022.1, Backport-5.1, Backport-2022.2

#5511 fix(cassandra-stress): make sure docker image is pull upfront
  sdcm/stress/base.py
  sdcm/stress_thread.py
  sdcm/utils/docker_remote.py
Labels: No Backport Needed, test-provision-aws

#5520 fix(performance): run perf test on Ubuntu22
  test-cases/performance/perf-regression-latency-500gb-30min.yaml
Labels: No Backport Needed

#5510 fix(perfsearch): new pipeline parameter cs commands
  vars/perfSearchBestConfigParallelPipeline.groovy
Labels: No Backport Needed, Ready for review

#5531 fix(get_cfstats): enlarge timeouts for EBS case
  sdcm/cluster.py
Labels: No Backport Needed, serverless, scylla-operator

#5532 fix(scylla_start_server): move `verify_up_timeout` default into property
  sdcm/cluster.py
  sdcm/cluster_docker.py
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed, serverless, scylla-operator

#5539 Revert "improvement(artifacts_test.py): Verify docker image locale se…
  artifacts_test.py
Labels: No Backport Needed

#5541 feature(raft): new jobs with raft enabled
  configurations/scale/scale-40-60.yaml
  jenkins-pipelines/raft/gemini-8h-large-num-columns.jenkinsfile
  jenkins-pipelines/raft/jepsen-with-raft.jenkinsfile
  jenkins-pipelines/raft/longevity-150gb-asymmetric-cluster-12h.jenkinsfile
  jenkins-pipelines/raft/longevity-1tb-7days.jenkinsfile
  jenkins-pipelines/raft/longevity-200gb-48h-network-monkey.jenkinsfile
  jenkins-pipelines/raft/longevity-2TB-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis.jenkinsfile
  jenkins-pipelines/raft/longevity-5000-tables.jenkinsfile
  jenkins-pipelines/raft/longevity-50gb-asymmetric-cluster-12h.jenkinsfile
  jenkins-pipelines/raft/longevity-alternator-200gb-48h.jenkinsfile
  jenkins-pipelines/raft/longevity-cdc-3d-400gb.jenkinsfile
  jenkins-pipelines/raft/longevity-counters-6h-multidc.jenkinsfile
  jenkins-pipelines/raft/longevity-large-collections-12h.jenkinsfile
  jenkins-pipelines/raft/longevity-large-partition-200k-pks-4days.jenkinsfile
  jenkins-pipelines/raft/longevity-large-partition-4days.jenkinsfile
  jenkins-pipelines/raft/longevity-large-partition-8h.jenkinsfile
  jenkins-pipelines/raft/longevity-lwt-24h-1dis-2nondis.jenkinsfile
  jenkins-pipelines/raft/longevity-lwt-24h-multidc.jenkinsfile
  jenkins-pipelines/raft/longevity-lwt-500G-3d.jenkinsfile
  jenkins-pipelines/raft/longevity-multi-keyspaces-60h.jenkinsfile
  jenkins-pipelines/raft/longevity-mv-si-4days.jenkinsfile
  jenkins-pipelines/raft/longevity-twcs-48h.jenkinsfile
  jenkins-pipelines/raft/scale-40-60-cluster-test.jenkinsfile
  test-cases/jepsen/jepsen_with_raft.yaml
Labels: No Backport Needed, Ready for review

#5548 fix(k8s): make dynamic loader 'send_files' work correctly
  sdcm/remote/kubernetes_cmd_runner.py
Labels: No Backport Needed, Ready for review, serverless, scylla-operator

#5552 fix(cluster.py): use networkctl to start an interface if possible
  sdcm/cluster.py
Labels: No Backport Needed, Ready for review

#5549 fix(k8s-dynamic-loader): stop assuming src/dest filename is identical
  sdcm/remote/kubernetes_cmd_runner.py
Labels: No Backport Needed, scylla-operator

#5557 feature(cassandra-stress): add option for enabling debug
  data_dir/logback-tools-debug.xml
  docs/configuration_options.md
  sdcm/sct_config.py
  sdcm/stress_thread.py
  unit_tests/test_cassandra_stress_thread.py
Labels: No Backport Needed

#5559 fix(longevity): descrease stress duration in longevity-lwt-500G-3d-test
  test-cases/longevity/longevity-lwt-500G-3d.yaml
Labels: Ready for review, Backport-2022.1, Backport-5.1, Backport-2022.2

#5556 fix(logcollector): change order of collection
  sdcm/logcollector.py
Labels: No Backport Needed, test-provision-aws, test-provision-docker

#5540 fix(nemesis.py): fail nemesis if non-empty table not found
  sdcm/cluster.py
  sdcm/nemesis.py
Labels: Backport-5.1, Backport-2022.2

#5537 feature(decommission): add timeout to cluster.decommission
  defaults/severities.yaml
  sdcm/cluster.py
  sdcm/cluster_k8s/__init__.py
  sdcm/nemesis.py
  sdcm/sct_events/system.py
  unit_tests/test_events.py
Labels: No Backport Needed

#5563 fix(scale-cluster): Setting backtrace_decoding to false for scale test
  test-cases/scale/scale-cluster.yaml
Labels: No Backport Needed

#5570 fix(gce_datacenter): set its type to str_or_list_or_eval
  sdcm/sct_config.py
Labels: No Backport Needed

#5571 fix(unittests): switch away from delete old AMIs
  unit_tests/test_config.py
Labels: No Backport Needed

#5569 feature(k8s-cloud-bundle): enable for multi tenant test
  test-cases/scylla-operator/longevity-scylla-operator-3h-multitenant.yaml
Labels: No Backport Needed

#5561 refactor(get_peers_info): switch to use python-driver
  sdcm/cluster.py
  sdcm/utils/health_checker.py
  unit_tests/test_utils_health_checker.py
Labels: No Backport Needed

#5573 fix(gce manager backup): updated the bucket name
  defaults/gce_config.yaml
  test-cases/manager/manager-backup-1TB-gce.yaml
  test-cases/manager/manager-regression-multiDC-gce.yaml
Labels: No Backport Needed

#5457 ci(k8s): add new K8S longevity multitenant job with 14 clients
  jenkins-pipelines/operator/eks/longevity-scylla-operator-12h-multitenant-eks.jenkinsfile
  sdcm/logcollector.py
  test-cases/scylla-operator/longevity-scylla-operator-12h-multitenant-14-clients.yaml
Labels: No Backport Needed, Ready for review, serverless, scylla-operator

#5576 fix(loader): typo in java-8 installation
  sdcm/cluster.py
Labels: No Backport Needed

#5581 fix(setup): stabilise docker installation
  install-hydra.sh
  install-prereqs.sh
  sdcm/cluster.py
Labels: No Backport Needed

#5583 fix(setup): stabilise download repo file
  sdcm/cluster.py
Labels: No Backport Needed

#5584 fix(scylla-bench): Use newest version [2022.1]
  defaults/test_default.yaml
Labels: Backport-2021.1

#5587 fix(hydra): use properly built image with actual requirements
  docker/env/version
  requirements.in
  requirements.txt
Labels: Ready for review, Urgent, serverless, scylla-operator

#5591 fix(k8s): make CSHDRFileLogger context manager be compatible with K8S
  sdcm/utils/remote_logger.py
Labels: Ready for review, serverless, scylla-operator

#5582 fix(aws_instance_profile): split profiles per node type
  defaults/aws_config.yaml
  defaults/azure_config.yaml
  sdcm/cluster_aws.py
  sdcm/sct_config.py
  sdcm/sct_provision/aws/instance_parameters_builder.py
  test-cases/manager/manager-regression-ipv6.yaml
  test-cases/manager/manager-regression-multiDC-set-distro.yaml
  test-cases/upgrades/manager-upgrade.yaml
Labels: Backport-5.0, Backport-2022.1, Backport-5.1, Backport-2022.2

#5589 fix(longevity-4h): optimized test stability and cost
  jenkins-pipelines/longevity-100gb-4h.jenkinsfile
  test-cases/longevity/longevity-100gb-4h.yaml
Labels: No Backport Needed

#5575 feature(gcp): adding local-ssd-latency project
  docs/gcp_create_new_project.md
  sdcm/utils/gce_utils.py
Labels: No Backport Needed

#5505 test(compaction_limit): added new feature test
  jenkins-pipelines/features-compaction-throughput-limit.jenkinsfile
  per_partition_limit_test.py
  sdcm/cluster.py
  test-cases/features/compaction-throughput-limit.yaml
  throughput_limit_test.py
Labels: Backport-5.1, Backport-2022.2

#5595 fix(lodaer-install): fix the symbolic link to java
  sdcm/cluster.py
Labels: No Backport Needed

#5578 fix(k8s-functional): use --cloudconf on cqlsh only from scylla 5.2.0
  sdcm/cluster.py
Labels: No Backport Needed, test-provision-k8s-local-kind-aws, serverless, scylla-operator

#5596 fix(sct_config): make .get(None) work
  sdcm/sct_config.py
  unit_tests/test_config.py
Labels: Backport-5.1, Backport-2022.2

#5600 fix(gemini): Update Oracle version
  test-cases/gemini/gemini-3h-with-nemesis.yaml
Labels: No Backport Needed

#5601 fix(stress_thread): disable CSHDRLogger when not needed
  sdcm/stress_thread.py
Labels: No Backport Needed

#5597 fix(nemesis): make UnsupportedNemesis skip to the next nemesis
  sdcm/nemesis.py
Labels: Backport-5.1, Backport-2022.2

#5606 refactor(get_any_ks_cf_list): stop fetching data from system tables
  sdcm/cluster.py
  unit_tests/test_cluster.py
Labels: No Backport Needed, test-integration

#5612 fix(show-monitor): support multi-tenant cluster
  sdcm/monitorstack/__init__.py
Labels: Ready for review, test-provision-aws, test-provision-docker

#5609 fix(test_operator_managed_tls): add WhiteList when connecting to cluster
  functional_tests/scylla_operator/test_functional.py
Labels: test-provision-k8s-local-kind-aws, serverless, scylla-operator

#5611 fix(docker-loader): fix ipv6 support
  sdcm/stress_thread.py
Labels: No Backport Needed, test-integration
