Repository scylladb/scylla-cluster-tests, pull requests merged in 2022-10, with the labels that each got.

#5330 fix(k8s-multitenancy): properly calculate number of tenants
  configurations/operator/perf-regression-latency-and-throughput-multitenant-14-clients.yaml
  configurations/operator/perf-regression-latency-and-throughput-multitenant-2-clients.yaml
  configurations/operator/perf-regression-latency-and-throughput-multitenant-7-clients.yaml
  configurations/operator/perf-regression-latency-multitenant-14-clients.yaml
  configurations/operator/perf-regression-latency-multitenant-2-clients.yaml
  configurations/operator/perf-regression-latency-multitenant-7-clients.yaml
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed, Ready for review

#5328 fix(azure): fix running without setting az
  defaults/azure_config.yaml
  vars/createSctRunner.groovy
  vars/provisionResources.groovy
Labels: No Backport Needed

#5332 fix(k8s_loader): make docker base loader work
  sdcm/k8s_configs/loaders/sts.yaml
Labels: No Backport Needed

#4912 fix(nemesis): move wrapping code from __new__ to __init__
  sdcm/nemesis.py
  unit_tests/test_nemesis.py
Labels: No Backport Needed, test-provision-aws, test-provision-docker

#5339 fix(k8s-sts-loaders): add missing 'path' parameter
  sdcm/k8s_configs/loaders/sts.yaml
Labels: No Backport Needed

#5333 fix(longevity-twcs-48h): add timeout to s-b commands
  test-cases/longevity/longevity-twcs-48h.yaml
Labels: No Backport Needed

#5341 fix(nemesis.py): make lint happy
  sdcm/nemesis.py
Labels: No Backport Needed

#5343 fix(severity.yaml): change reactor stall severity
  defaults/severities.yaml
Labels: Backport-5.0, Backport-2022.1, Backport-5.1, Backport-2022.2

#5338 fix(severity.yaml): change nosqlbench severity
  defaults/severities.yaml
Labels: No Backport Needed, Ready to be Merged

#5350 fix(nemesis): wait for db_up in start_and_interrupt_rebuild_streaming()
  sdcm/nemesis.py
Labels: Backport-5.0, Backport-2022.1, Backport-5.1, Backport-2022.2

#5322 fix(sdcm/tester.py): Check if version_str is non-empty
  sdcm/tester.py
Labels: Backport-5.0, Backport-2022.1, Backport-5.1, Backport-2022.2

#5308 fix(gemini_thread): Increase request and connect timeouts for gemini
  sdcm/gemini_thread.py
Labels: Ready for review, Backport-2022.1, Backport-5.1, Backport-2022.2

#5359 fix(gemini_thread): correctly build gemini comand with oracle
  sdcm/gemini_thread.py
Labels: Ready for review, Backport-5.1, Backport-2022.2

#5323 test(nemesis): remove service level while load
  longevity_sla_test.py
  sdcm/nemesis.py
  test-cases/longevity/longevity-sla-100gb-4h.yaml
  test_lib/sla.py
Labels: Ready for review, Backport-2021.1, Backport-2022.1, Backport-2022.2

#5304 fix(schema-agreement): print proper error messages. v2
  sdcm/cluster.py
  sdcm/utils/health_checker.py
  unit_tests/test_utils_health_checker.py
Labels: Ready for review, Backport-5.0, Backport-2022.1, Backport-5.1, Backport-2022.2

#5364 improvement(k8s-functional): increase resharding wait time to 10m
  functional_tests/scylla_operator/libs/helpers.py
Labels: No Backport Needed, Ready for review

#5366 improvement(k8s-gke): use taint for Scylla K8S nodes
  sdcm/cluster_k8s/__init__.py
  sdcm/cluster_k8s/gke.py
  sdcm/k8s_configs/static-local-volume-provisioner.yaml
  sdcm/tester.py
Labels: No Backport Needed

#5362 fix(k8s): make scylla-bench work using dynamic K8S loader pods
  sdcm/remote/kubernetes_cmd_runner.py
  sdcm/scylla_bench_thread.py
Labels: No Backport Needed, Ready for review

#5363 improvement(k8s-functional): run mgmt tests before K8S node drain ones
  functional_tests/scylla_operator/test_functional.py
Labels: No Backport Needed, Ready for review

#5353 fix(scylla-bench): fix s-b delay for first run
  defaults/test_default.yaml
  sdcm/cassandra_harry_thread.py
  sdcm/cdclog_reader_thread.py
  sdcm/gemini_thread.py
  sdcm/kcl_thread.py
  sdcm/ndbench_thread.py
  sdcm/nosql_thread.py
  sdcm/scylla_bench_thread.py
  sdcm/stress_thread.py
  sdcm/utils/docker_remote.py
  sdcm/ycsb_thread.py
  unit_tests/test_config.py
Labels: Backport-5.1, Backport-2022.2

#5360 Azure rolling upgrade 5.1
  configurations/azure/azure_rolling_upgrade.yaml
  jenkins-pipelines/rolling-upgrade-azure-image.jenkinsfile
  sdcm/sct_config.py
  vars/createSctRunner.groovy
  vars/getCloudProviderFromBackend.groovy
  vars/rollingUpgradePipeline.groovy
Labels: No Backport Needed

#5329 fix(scylla.yaml): change default for compaction throughput limit
  sdcm/provision/scylla_yaml/scylla_yaml.py
  unit_tests/test_scylla_yaml.py
Labels: No Backport Needed

#5361 Azure rolling upgrade 2022.2
  configurations/azure/azure_rolling_upgrade.yaml
  jenkins-pipelines/rolling-upgrade-azure-image.jenkinsfile
  sdcm/sct_config.py
  vars/createSctRunner.groovy
  vars/getCloudProviderFromBackend.groovy
  vars/rollingUpgradePipeline.groovy
Labels: No Backport Needed

#5365 ci(k8s-gke): use dynamic loader run type for the longevity-3h job
  configurations/operator/loader-run-type-dynamic.yaml
  jenkins-pipelines/operator/gke/longevity-scylla-operator-3h-gke.jenkinsfile
Labels: No Backport Needed, Ready for review
