Repository scylladb/scylla-cluster-tests, pull requests merged in 2023-04, with the labels that each got.

#5782 test(longevity): new longevity for MV running in synchronous mode
  data_dir/mv_synchronous_updates.yaml
  data_dir/mv_synchronous_updates_lwt.yaml
  data_dir/mv_synchronous_updates_on_standard.yaml
  jenkins-pipelines/longevity_mv_synchronous_updates-12h.jenkinsfile
  sdcm/stress_thread.py
  sdcm/utils/common.py
  sdcm/utils/data_validator.py
  sdcm/utils/user_profile.py
  test-cases/longevity/longevity-mv-synchronous-updates-12h.yaml
  unit_tests/test_cluster.py
Labels: Ready for review, Backport-5.2, Backport-2023.1

#5899 fix(wait_for_init): fail fast on boot failure
  sdcm/cluster.py
Labels: No Backport Needed, Ready for review

#5960 improvement(k8s): allow to set cpu and memory limits for Scylla pods
  docs/configuration_options.md
  functional_tests/scylla_operator/test_functional.py
  sdcm/cluster_k8s/__init__.py
  sdcm/nemesis.py
  sdcm/sct_config.py
Labels: No Backport Needed, Ready for review, scylla-operator

#5971 fix(argus): properly check the node type
  sdcm/cluster.py
  sdcm/cluster_k8s/__init__.py
  sdcm/cluster_k8s/mini_k8s.py
Labels: No Backport Needed, Ready for review, scylla-operator

#5976 fix(common.py):set GCE filter for new image name
  sdcm/utils/common.py
Labels: Backport-5.2, Backport-2023.1

#5955 ci(serverless): add configs for testing 1 and 2 vcpus Scylla clusters
  configurations/operator/perf-serverless-thrpt-1vcpu.yaml
  configurations/operator/perf-serverless-thrpt-2vcpu.yaml
Labels: No Backport Needed, Ready for review, serverless

#5897 feature(adaptive-timeouts): calculate timeouts based on node load
  sdcm/cluster.py
  sdcm/cluster_k8s/__init__.py
  sdcm/nemesis.py
  sdcm/sct_events/system.py
  sdcm/utils/adaptive_timeouts/__init__.py
  sdcm/utils/adaptive_timeouts/load_info_store.py
  unit_tests/test_adaptive_timeouts.py
  unit_tests/test_events.py
Labels: No Backport Needed

#5972 fix(k8s): use exclusive nemesis lock for cluster health validation too
  sdcm/nemesis.py
  test-cases/scylla-operator/longevity-scylla-operator-3h-multitenant.yaml
Labels: No Backport Needed, Ready for review, scylla-operator

#5983 fix(Compaction): remove InMemoryCompactionStrategy
  longevity_in_memory_test.py
  longevity_test.py
  performance_regression_in_memory_test.py
  performance_regression_row_level_repair_test.py
  sdcm/tester.py
  test_lib/compaction.py
Labels: No Backport Needed, Ready for review

#5987 fix(k8s): use proper K8S class attr for getting memory limit value
  functional_tests/scylla_operator/libs/helpers.py
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review, scylla-operator

#5980 fix(refresh nemesis): fix folder for sstable uploading
  sdcm/nemesis.py
  sdcm/utils/sstable/load_utils.py
Labels: test-provision-k8s-eks

#6001 fix(unit_test): prevent logging from raising exceptions after tests
  unit_tests/conftest.py
Labels: No Backport Needed

#5984 feature(jupyter): added example jupyter notebooks
  jupyter/functional-test.ipynb
  jupyter/provision-test.ipynb
  jupyter/readme.md
Labels: No Backport Needed

#6010 fix(provisioner): fix after multi-az
  sdcm/sct_provision/aws/cluster.py
  sdcm/sct_provision/aws/instance_parameters_builder.py
Labels: test-provision-aws, Backport-5.2, Backport-2023.1

#5949 improvement(Materialized View): Add-remove MV nemesis
  data_dir/nemesis.yml
  data_dir/nemesis_classes.yml
  sdcm/nemesis.py
  sdcm/utils/nemesis_utils/indexes.py
  test-cases/nemesis/longevity-5gb-1h-AddRemoveMvNemesis.yaml
  unit_tests/test_nemesis.py
  unit_tests/test_nemesis_sisyphus.py
Labels: Backport-5.2

#6012 fix(event_analyzer): call 'kill_test' only once
  sdcm/sct_events/events_analyzer.py
Labels: Ready for review, Backport-5.2, Backport-2023.1

#6014 fix(raft): make 'get_group0_members' work correctly when raft disabled
  sdcm/cluster.py
Labels: Ready for review, Backport-5.2, Backport-2023.1

#6013 fix(cdc-replication): Remove cdc-replication-jenkins pipeline
  jenkins-pipelines/features-cdc-replication-gemini-postimage.jenkinsfile
  jenkins-pipelines/features-cdc-replication-gemini-preimage.jenkinsfile
  jenkins-pipelines/features-cdc-replication-gemini.jenkinsfile
  jenkins-pipelines/features-cdc-replication-longevity.jenkinsfile
  jenkins-pipelines/features-cdc-replication.jenkinsfile
Labels: Ready for review

#6024 fix(parallel topology changes): c-s command is wrong
  test-cases/longevity/longevity-multidc-parallel-topology-schema-changes-12h.yaml
Labels: Backport-5.2, Backport-2023.1

#6025 fix(perf-1tb): Increase test duration
  jenkins-pipelines/perf-regression-latency-1TB-ebs-gp3-volumes.jenkinsfile
  jenkins-pipelines/perf-regression-latency-1TB-ebs-volumes.jenkinsfile
  jenkins-pipelines/perf-regression-latency-1TB.jenkinsfile
  jenkins-pipelines/perf-regression-latency-non-shard-aware-1TB.jenkinsfile
  jenkins-pipelines/perf-regression-latency-shard-aware-1TB.jenkinsfile
  test-cases/performance/perf-regression-latency-1TB.yaml
Labels: Ready for review, Backport-perf-v14

#6029 fix(gemini oracle version): bump oracle version
  test-cases/gemini/gemini-1tb-10h.yaml
  test-cases/gemini/gemini-3h-ics-cdc-with-nemesis.yaml
  test-cases/gemini/gemini-3h-with-nemesis.yaml
  test-cases/gemini/gemini-3h-with-nondisruptive-nemesis.yaml
  test-cases/gemini/gemini-basic-3h.yaml
Labels: No Backport Needed

#6021 fix(longevity-cdc-4h): fix datacenter name
  test-cases/longevity/longevity-cdc-100gb-4h.yaml
Labels: Backport-5.2, Backport-2023.1

#6031 fix(get_non_system_ks_cf_list): Filter out 'audit' keyspace
  sdcm/cluster.py
Labels: Backport-2022.1, Backport-2022.2, Backport-5.2, Backport-2023.1

#6027 improvement(managerPipeline): include the provision type in the trigger
  vars/managerPipeline.groovy
Labels: Backport-manager-3.1

#6023 fix(ToggleTableIcsMonkey): check if selected CF is a view
  sdcm/nemesis.py
  sdcm/utils/nemesis_utils/indexes.py
Labels: Backport-5.1, Backport-2023.1

#6032 fix(db stats): query scheduler runtime with different irate step
  sla_per_user_system_test.py
Labels: Backport-5.2, Backport-2023.1

#5962 fix(200k-pk-i4i): Additional nodes capacity to resolve storage shortage
  jenkins-pipelines/longevity-large-partition-200k-pks-2days-aws-i4i.jenkinsfile
  test-cases/longevity/longevity-large-partition-200k_pks-2days-i4i.yaml
Labels: Backport-5.2, Backport-2023.1

#6034 fix(nonroot-artifcat-test): fix the location of cqlsh
  artifacts_test.py
  sdcm/cluster.py
Labels: No Backport Needed

#5769 feature(sct-builders): use aws ASGs as Azure builders
  test-cases/artifacts/azure-image.yaml
  vars/getJenkinsLabels.groovy
Labels: No Backport Needed

#6036 improvement(cluster): find datacenter according to region
  sdcm/cluster.py
  unit_tests/test_cluster.py
Labels: Backport-2022.2, Backport-5.2, Backport-2023.1

#6038 fix(get_group0_members): catch exception for cql commands
  sdcm/cluster.py
Labels: Ready for review, Backport-5.2, Backport-2023.1

#6039 fix(health_events): add retry and did not raise exception
  sdcm/cluster.py
Labels: Backport-5.2, Backport-2023.1

#6003 fix(perf-search-best-config): New parameter to pipeline
  defaults/test_default.yaml
  vars/perfSearchBestConfigParallelPipeline.groovy
Labels: Ready for review, Backport-perf-v14

#6049 fix(get_group0_members): Use python-driver instead cqlsh
  sdcm/cluster.py
Labels: Ready for review, Backport-5.2, Backport-2023.1

#6033 fix(longevity): query scheduler runtime with different irate step
  sdcm/sla/libs/sla_utils.py
Labels: Backport-2022.2, Backport-2023.1

#6053 fix(longevity): change db instance type for MV synch test
  test-cases/longevity/longevity-mv-synchronous-updates-12h.yaml
Labels: Backport-5.2, Backport-2023.1

#6052 Filter out collection types & get all columns for a primary-key
  sdcm/nemesis.py
  sdcm/utils/nemesis_utils/indexes.py
Labels: Backport-5.2, Backport-2023.1

#6054 fix(upgrade_test): shim-signed package removal workaround
  upgrade_test.py
Labels: Backport-5.2, Backport-2023.1

#6030 fix(oracle version): use latest 2021.1 version
  defaults/test_default.yaml
  test-cases/gemini/gemini-3h-ics-cdc-with-nemesis.yaml
  test-cases/gemini/gemini-3h-ics-with-nondisruptive-nemesis.yaml
  test-cases/gemini/gemini-basic-3h-ics.yaml
  unit_tests/test_config.py
  unit_tests/test_data/test_scylla_yaml_builders/PR-provision-test.yaml
  unit_tests/test_scylla_yaml_builders.py
Labels: No Backport Needed

#6058 fix(disrupt_mgmt_repair): Add task progress string on task failure
  sdcm/nemesis.py
Labels: Backport-5.2, Backport-2023.1

#5985 fix(multidc tests): create loader in each region
  test-cases/longevity/longevity-counters-multidc.yaml
  test-cases/longevity/longevity-lwt-24h-multidc.yaml
Labels: Ready for review, Backport-5.2, Backport-2023.1

#6060 fix(upgrade_test): workaround for shim-signed for deb only
  upgrade_test.py
Labels: Backport-5.2, Backport-2023.1

#6020 fix(k8s): enable kernel.perf_event_paranoid=0
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed, test-provision-k8s-local-kind-aws, test-provision-k8s-eks

#6062 fix(azure-artifact): support public address in `cql_ip_address`
  sdcm/cluster.py
Labels: No Backport Needed, test-provision-aws, test-provision-azure

#6064 fix(sct.log): remove warning event from being printed
  sdcm/db_log_reader.py
  sdcm/sct_events/file_logger.py
Labels: Backport-5.2, Backport-2023.1

#6063 fix(events_processes): stop logging on getting the process
  sdcm/sct_events/events_processes.py
Labels: Backport-5.2, Backport-2023.1

#6037 feature(k8s-ingress): add logging thread
  sdcm/cluster_k8s/__init__.py
  sdcm/logcollector.py
  sdcm/utils/remote_logger.py
Labels: test-provision-k8s-local-kind-aws, test-provision-k8s-eks

#6061 fix(rebuild): make sure we don't ever retry rebuild
  sdcm/nemesis.py
Labels: Backport-5.2, Backport-2023.1

#6076 improvement(scylla-bench): use latest v0.1.17 tag
  defaults/test_default.yaml
  docs/configuration_options.md
Labels: Ready for review, Backport-5.2, Backport-2023.1

#6078 fix(logs): reduce verbosity for listing runners when updating tags
  sdcm/sct_runner.py
Labels: Backport-5.2, Backport-2023.1
