Repository scylladb/scylla-cluster-tests, pull requests merged in 2023-06, with the labels that each got.

#6207 fix(arm-centos8): replace deprecated ARM image
  configurations/arm/centos8.yaml
  sdcm/utils/common.py
  unit_tests/test_config.py
Labels: Backport-5.0, Backport-2022.1, Backport-5.1, Backport-2022.2, Backport-5.2, Backport-2023.1

#6208 fix(k8s): make static loaders work again
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed, Ready for review, scylla-operator

#6212 fix(k8s): set Scylla storage size in 14 tenants longevity
  test-cases/scylla-operator/longevity-scylla-operator-12h-multitenant-14-clients.yaml
Labels: No Backport Needed

#6211 feature(gemini): update gemini to 1.8.2
  defaults/test_default.yaml
  docker/gemini/README.md
  docker/gemini/image
  sdcm/gemini_thread.py
  unit_tests/test_config.py
Labels: test-integration

#6213 fix(tox): use config syntax compatible for 3.x and 4.x versions
  tox.ini
Labels: No Backport Needed, Ready for review

#6219 fix(K8S): make coredump events be published in any case
  sdcm/db_log_reader.py
Labels: No Backport Needed

#6199 docs(README): refactor the readme into several parts
  README.md
  README.rst
  docs/contrib.md
  docs/faq.md
  docs/install-local-env.md
  docs/k8s-functional-test.md
  docs/longevity.md
  docs/sct-runners.md
Labels: No Backport Needed

#6222 fix(test): fix oracle instance type for gemini tests
  sdcm/sct_provision/aws/cluster.py
Labels: Backport-5.0, Backport-2022.1, Backport-5.1, Backport-2022.2, Backport-5.2, Backport-2023.1

#6167 fix(images account): ScyllaDB images are moving account
  sdcm/utils/aws_utils.py
  sdcm/utils/common.py
Labels: No Backport Needed, Ready to be Merged

#6220 improvement(scylla-bench): use latest v0.1.18 tag
  defaults/test_default.yaml
  docs/configuration_options.md
Labels: Ready for review, test-integration, Backport-5.2, Backport-2023.1

#6227 fix(cdc-100gb): use any-region compatible replication config
  test-cases/longevity/longevity-cdc-100gb-4h.yaml
Labels: Ready for review, Backport-2023.1

#6233 fix(cluster): support case where `availability_zone` not defined
  sdcm/cluster.py
Labels: No Backport Needed, test-provision-k8s-local-kind-aws, test-provision-k8s-eks

#6118 improvement(manager): Use i4i instances for all aws (small) scenarios
  test-cases/manager/manager-regression-ipv6.yaml
  test-cases/manager/manager-regression-multiDC-set-distro.yaml
  test-cases/manager/manager-repair-control.yaml
  test-cases/manager/manager-repair-intensity-multiple-repaired-nodes.yaml
  test-cases/manager/manager-repair-intensity-single-repaired-nodes.yaml
Labels: Ready to be Merged, Backport-manager-3.1

#6203 fix(test-cases/nemesis): use public IPs when we use extra NIC
  jenkins-pipelines/nemesis/longevity-5gb-1h-BlockNetworkMonkey-aws.jenkinsfile
  jenkins-pipelines/nemesis/longevity-5gb-1h-BlockNetworkMonkey-azure.jenkinsfile
  jenkins-pipelines/nemesis/longevity-5gb-1h-RandomInterruptionNetworkMonkey-aws.jenkinsfile
  jenkins-pipelines/nemesis/longevity-5gb-1h-RandomInterruptionNetworkMonkey-azure.jenkinsfile
  jenkins-pipelines/nemesis/longevity-5gb-1h-StopStartInterfacesNetworkMonkey-aws.jenkinsfile
  jenkins-pipelines/nemesis/longevity-5gb-1h-StopStartInterfacesNetworkMonkey-azure.jenkinsfile
  test-cases/nemesis/longevity-5gb-1h-BlockNetworkMonkey.yaml
  test-cases/nemesis/longevity-5gb-1h-RandomInterruptionNetworkMonkey.yaml
  test-cases/nemesis/longevity-5gb-1h-StopStartInterfacesNetworkMonkey.yaml
Labels: Ready for review, Backport-5.2, Backport-2023.1

#6091 feature(audit): new short longevity with audit enabled
  jenkins-pipelines/audit/longevity-100gb-4h.jenkinsfile
  jenkins-pipelines/audit/longevity-schema-changes-3h.jenkinsfile
  sct.py
Labels: Backport-5.2, Backport-2023.1

#6244 fix(sct-runner): call the correct API for deletion
  sdcm/sct_runner.py
Labels: No Backport Needed, Urgent

#6252 fix(upgrade): fix InfoEvent message in test_generic_cluster_upgrade
  upgrade_test.py
Labels: Ready for review, Backport-5.2, Backport-2023.1

#6253 fix(upgrade): remove end-line character from stdout
  upgrade_test.py
Labels: Ready for review, Backport-5.2, Backport-2023.1

#6257 fix(yaml): set correct c-s commands parameters
  data_dir/cs_mv_si_keyspace1.yaml
  test-cases/longevity/longevity-change-cluster-size-by-2-times.yaml
Labels: Ready for review, Backport-5.2, Backport-2023.1

#6223 fix(k8s-eks): use proper disk sizes for Scylla pods
  configurations/operator/perf-regression-latency-and-throughput-multitenant-2-clients.yaml
  configurations/operator/perf-regression-latency-and-throughput-multitenant-7-clients.yaml
  configurations/operator/perf-regression-latency-multitenant-2-clients.yaml
  configurations/operator/perf-regression-latency-multitenant-7-clients.yaml
  defaults/k8s_eks_config.yaml
  test-cases/scylla-operator/longevity-scylla-operator-3h-multitenant.yaml
Labels: No Backport Needed, Ready for review, scylla-operator

#6258 fix(gke-cleanup): create GkeCleaner instance per k8s cluster
  sdcm/utils/common.py
Labels: No Backport Needed

#6264 fix(longevity-topology-changes-3h): don't specify DC names
  test-cases/longevity/longevity-topology-changes-3h.yaml
Labels: No Backport Needed

#6251 fix(perf-latency-nemesis): Set large test duration
  test-cases/performance/perf-regression-latency-650gb-with-nemesis.yaml
Labels: Ready for review, Backport-perf-v14

#6263 fix(nemesis): match non-digit prefix sstable identifier as well
  sdcm/nemesis.py
Labels: No Backport Needed

#6261 fix(test_backup_feature): only backup a specific keyspace for a restore
  mgmt_cli_test.py
Labels: Ready to be Merged, Backport-manager-3.1

#6267 fix(azure-artifacts): make shard aware port public
  sdcm/provision/security.py
Labels: Backport-5.2, Backport-2023.1

#6265 fix(event filter): exclude 'libabsl' from stacktrace regex
  sdcm/sct_events/database.py
Labels: Backport-5.2, Backport-2023.1

#6228 fix(Rollback): disable recover_system_tables
  test-cases/scylla-operator/kubernetes-scylla-upgrade.yaml
  test-cases/upgrades/generic-rolling-upgrade.yaml
  test-cases/upgrades/multi-dc-rolling-upgrade.yaml
  test-cases/upgrades/rolling-upgrade.yaml
  unit_tests/test_data/test_scylla_yaml_builders/rolling-upgrade.yaml
Labels: No Backport Needed, Ready for review

#6274 fix(mgmt_upgrade_test): discover the format of next_run before parsing
  mgmt_upgrade_test.py
Labels: Ready to be Merged, Backport-manager-3.1

#6270 fix(manager debian 10): update ami id
  configurations/manager/debian10.yaml
Labels: Ready to be Merged, Backport-manager-3.1

#6276 fix(longevity-parallel-nemesis): Add exclude disruptive flag
  test-cases/longevity/longevity-change-cluster-size-by-2-times.yaml
  test-cases/longevity/longevity-multidc-parallel-network-schema-changes-12h.yaml
  test-cases/longevity/longevity-multidc-parallel-topology-schema-changes-12h.yaml
  test-cases/longevity/longevity-parallel-schema-changes-12h.yaml
Labels: Ready for review, Urgent, Backport-5.2, Backport-2023.1

#6279 fix(list images): avoid getting exception
  sdcm/utils/common.py
Labels: No Backport Needed

#6239 fix(wait_for): stop using `tenacity.RetryError`
  sdcm/wait.py
Labels: Backport-5.2, Backport-2023.1

#6277 fix(perf_simple_query): adjust email report
  sdcm/report_templates/results_perf_simple_query.html
  sdcm/utils/microbenchmarking/perf_simple_query_reporter.py
Labels: Ready for review, Backport-perf-v14

#6280 fix(releng account images): check owner_id
  sdcm/utils/common.py
Labels: No Backport Needed

#6273 fix(upgrade test): not stop test on execute session timeout
  upgrade_test.py
Labels: Ready for review, Backport-5.2, Backport-2023.1

#6275 fix(upgrade test): not retry drain operation
  upgrade_test.py
Labels: No Backport Needed

#6260 improvement(azure): add feature for cloud_provider initial support.
  sct.py
  unit_tests/test_base_version.py
  utils/get_supported_scylla_base_versions.py
Labels: Backport-5.2, Backport-2023.1

#6288 fix(k8s-perf): set correct PVC size for K8S thrpt tests
  test-cases/performance/perf-regression.100threads.30M-keys.yaml
Labels: No Backport Needed, scylla-operator

#6287 fix(k8s): enable alpha TLS feature for operator after upgrade
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed, scylla-operator

#6255 fix(alternator): fix three nemesis with ignore_ycsb_connection_refused
  sdcm/nemesis.py
Labels: Backport-5.2, Backport-2023.1

#6283 fix(10gb-3h-gce-longevity): Modify test duration to avoid timeout
  test-cases/longevity/longevity-10gb-3h.yaml
Labels: No Backport Needed

#6069 fix(ICS SAG): 4 loaders + i4i.4xlarge. Added is_compaction_running
  ics_space_amplification_goal_test.py
  sdcm/tester.py
  test-cases/features/ics_space_amplification_goal_test.yaml
Labels: Backport-2023.1

#6245 fix(k8s): make `fstrim_scylla_disks` work correctly
  sdcm/cluster_k8s/__init__.py
Labels: serverless, scylla-operator

#6296 fix(nemesis.py): fix skip toggle-cdc nemesis
  sdcm/nemesis.py
Labels: No Backport Needed

#6278 fix(perf_stress): Split stress multiplier by stress workload
  defaults/test_default.yaml
  docs/configuration_options.md
  performance_regression_test.py
  sdcm/sct_config.py
  test-cases/performance/perf-regression.100threads.30M-keys.yaml
Labels: Backport-perf-v14

#6291 fix(longevity-counters-multidc): unping scylla-bench
  test-cases/longevity/longevity-counters-multidc.yaml
Labels: Backport-5.2, Backport-2023.1

#6301 fix(artifacts): remove defaults for Scylla repos/machine images
  test-cases/artifacts/amazon2.yaml
  test-cases/artifacts/ami.yaml
  test-cases/artifacts/azure-image.yaml
  test-cases/artifacts/centos7.yaml
  test-cases/artifacts/centos8-selinux.yaml
  test-cases/artifacts/centos8.yaml
  test-cases/artifacts/debian10.yaml
  test-cases/artifacts/debian11.yaml
  test-cases/artifacts/docker.yaml
  test-cases/artifacts/gce-image.yaml
  test-cases/artifacts/oel76.yaml
  test-cases/artifacts/oel81.yaml
  test-cases/artifacts/rhel7.yaml
  test-cases/artifacts/rhel8.yaml
  test-cases/artifacts/rocky8.yaml
  test-cases/artifacts/ubuntu2004.yaml
Labels: No Backport Needed, Ready for review

#6238 fix(k8s-manager): implement `delete_task`
  functional_tests/scylla_operator/test_functional.py
  sdcm/cluster_k8s/__init__.py
  sdcm/mgmt/cli.py
  sdcm/mgmt/operator.py
  sdcm/nemesis.py
Labels: No Backport Needed, test-provision-k8s-local-kind-aws, test-provision-k8s-eks

#6297 fix(add_remove_dc): fix dc name when GossipingPropertyFileSnitch is used
  sdcm/nemesis.py
Labels: Backport-5.2, Backport-2023.1

#6303 refactor(append_scylla_args): Cleanup all different usages of it
  internal_test_data/complex_test_case_with_version.yaml
  test-cases/features/limit-streaming-io.yaml
  test-cases/longevity/longevity-cdc-100gb-4h.yaml
  test-cases/longevity/longevity-mini-test-1h.yaml
  test-cases/longevity/longevity-multi-keyspaces.yaml
  test-cases/performance/perf-regression-alternator-latency-500gb-30min.yaml
  test-cases/performance/perf-regression-gradual-throughput-grow.yaml
  test-cases/performance/perf-regression-latency-125gb.yaml
  test-cases/performance/perf-regression-latency-1TB.yaml
  test-cases/performance/perf-regression-latency-250gb-with-nemesis.yaml
  test-cases/performance/perf-regression-latency-500gb-30min.yaml
  test-cases/performance/perf-regression-latency-650gb-with-nemesis.yaml
  test-cases/performance/perf-regression-latency-cdc-mixed-poll-batching.yaml
  test-cases/performance/perf-regression-latency-in-memory.yaml
  test-cases/performance/perf-regression-latency-lwt-big.yaml
  test-cases/performance/perf-regression-latency-lwt-small.yaml
  test-cases/performance/perf-regression-throughput-125gb.yaml
  test-cases/performance/perf-regression-throughput-cdc-mixed-poll-batching.yaml
  test-cases/performance/perf-regression-throughput-lwt-big.yaml
  test-cases/performance/perf-regression-throughput-lwt-small.yaml
  test-cases/performance/perf-regression-user-profiles.yaml
  test-cases/performance/perf-regression-write-latency-cdc.yaml
  test-cases/performance/perf-regression-write-throughput-cdc.yaml
  test-cases/performance/perf-row-level-repair-1TB.yaml
  test-cases/scale/longevity-5000-tables.yaml
  test-cases/scylla-operator/kubernetes-scylla-upgrade.yaml
  test-cases/upgrades/generic-rolling-upgrade.yaml
  test-cases/upgrades/rolling-upgrade.yaml
  unit_tests/test_data/test_scylla_yaml_builders/rolling-upgrade.yaml
Labels: Backport-perf-v14, Backport-2023.1

#6282 fix(elastic): store ami name
  sdcm/cluster.py
  sdcm/db_stats.py
  sdcm/sct_config.py
  sdcm/utils/common.py
Labels: Ready for review, Ready to be Merged, Backport-perf-v14

#6311 fix(install_scylla): use install_package for software-properties-common
  sdcm/cluster.py
Labels: No Backport Needed

#6310 improvement(ScyllaLogCollector): Added scylla-manager-agent.yaml
  sdcm/logcollector.py
Labels: Backport-manager-3.0, Backport-5.2, Backport-2023.1, Backport-manager-3.1
