Repository scylladb/scylla-cluster-tests, pull requests merged in 2023-02, with the labels that each got.

#5750 fix(distro): added support for linux mint 21
  sdcm/mgmt/common.py
  sdcm/utils/distro.py
Labels: No Backport Needed

#5734 Fix streaming err raciness
  sdcm/nemesis.py
Labels: Backport-5.1, Backport-2022.2

#5755 fix(Unit tests): fix EventsUtilsMixin teardown
  unit_tests/conftest.py
  unit_tests/test_scan_operation_thread.py
Labels: Ready for review, test-integration

#5747 fix(hydra): fix tab completion
  docker/env/version
  requirements.in
  requirements.txt
  sct.py
  utils/.bash_completion
Labels: No Backport Needed, New Hydra Version

#5395 improvement(mv-si longevity): explicitly set STCS
  data_dir/c-s_profile_3si_5queries.yaml
  data_dir/c-s_profile_4mv_5queries.yaml
Labels: No Backport Needed

#5762 fix(tester.py): fix copy_table method
  sdcm/tester.py
Labels: No Backport Needed

#5761 improvement(monitor): Change default annotations
  data_dir/scylla-dash-per-server-nemesis.master.json
Labels: No Backport Needed

#5758 fix(sla system): fix run_fullscan parameter
  test-cases/enterprise-features/workload-prioritization/longevity/longevity-sla-system-24h.yaml
Labels: Ready for review

#5726 fix(longevityPipeline): Add gemini seed to longevityPipeline
  vars/longevityPipeline.groovy
  vars/runSctTest.groovy
Labels: Ready for review, Backport-5.1, Backport-2022.2, Backport-5.2, Backport-2023.1

#5764 fix(node_benchmark): correctly count average if metric is missing
  sdcm/utils/benchmarks.py
Labels: Ready for review, Backport-5.2

#5746 ci(k8s): use K8sSetMonkey nemesis for 2clients setup
  test-cases/scylla-operator/longevity-scylla-operator-3h-multitenant.yaml
Labels: No Backport Needed, scylla-operator

#5770 fix(artifacts offline): remove unecessary jobs
  sct.py
Labels: No Backport Needed

#5773 fix(es_index_mapping): change order of date formats
  configurations/es_mapping/performance_index_mapping.json
Labels: Ready for review, Backport-perf-v14

#5774 fix(performance_email_title): Add email title parameter to pipeline
  jenkins-pipelines/perf-regression-latency-non-shard-aware-125gb.jenkinsfile
  jenkins-pipelines/perf-regression-latency-non-shard-aware-1TB.jenkinsfile
  jenkins-pipelines/perf-regression-latency-non-shard-aware-250gb-with-nemesis.jenkinsfile
  jenkins-pipelines/perf-regression-latency-shard-aware-125gb.jenkinsfile
  jenkins-pipelines/perf-regression-latency-shard-aware-1TB.jenkinsfile
  jenkins-pipelines/perf-regression-latency-shard-aware-250gb-with-nemesis.jenkinsfile
  jenkins-pipelines/perf-regression-throughput-non-shard-aware-125gb.jenkinsfile
  jenkins-pipelines/perf-regression-throughput-non-shard-aware-30min.jenkinsfile
  jenkins-pipelines/perf-regression-throughput-shard-aware-125gb.jenkinsfile
  jenkins-pipelines/perf-regression-throughput-shard-aware-30min.jenkinsfile
  sdcm/results_analyze/__init__.py
  vars/perfRegressionParallelPipeline.groovy
Labels: Ready for review, Backport-perf-v12

#5772 fix(artifacts offline generator): re-introduce amazon2
  sct.py
Labels: No Backport Needed

#5775 feature(consistent-cluster-management): Disable feature for several jobs
  configurations/raft/consistent_cluster_management_off.yaml
  jenkins-pipelines/consistent_cluster_management_disabled/longevity-1tb-7days.jenkinsfile
  jenkins-pipelines/consistent_cluster_management_disabled/longevity-large-collections-12h.jenkinsfile
  jenkins-pipelines/consistent_cluster_management_disabled/longevity-large-partition-8h.jenkinsfile
  jenkins-pipelines/consistent_cluster_management_disabled/longevity-mv-si-4days.jenkinsfile
  jenkins-pipelines/consistent_cluster_management_disabled/longevity-schema-changes-3h-with-raft.jenkinsfile
  sct.py
Labels: Ready for review, Backport-5.2

#5776 fix(csrangehistogram): Increase max value for hdr histogram
  sdcm/utils/csrangehistogram.py
Labels: Ready for review, Backport-5.2

#5780 improvement(sct.py): Add nemesis jobs to the create_test_release_jobs
  sct.py
Labels: No Backport Needed

#5788 revert(invoke): revert fabrio/invoke
  docker/env/version
  requirements.in
  requirements.txt
Labels: No Backport Needed, test-provision-aws, test-provision-gce, test-provision-docker, test-provision-azure

#5787 fix(jenkins pipeline): Increase timeout of the 'Get test duration' stage
  vars/jepsenPipeline.groovy
  vars/longevityPipeline.groovy
  vars/managerPipeline.groovy
  vars/perfSearchBestConfigParallelPipeline.groovy
  vars/rollingOperatorUpgradePipeline.groovy
Labels: Backport-5.2, Backport-2023.1

#5792 fix(parse_scylla_version): better check the version
  sdcm/fill_db_data.py
  sdcm/utils/version_utils.py
  unit_tests/test_version_utils.py
Labels: Backport-5.2, Backport-2023.1

#5784 fix(data validator): rows were not deleted
  sdcm/utils/data_validator.py
Labels: Ready for review, Backport-2022.1, Backport-5.1, Backport-2022.2, Backport-5.2

#5638 refactor(tester): add support for truncate timeout
  sdcm/tester.py
Labels: No Backport Needed

#5791 fix(csrangehistogram): skip empty built histogram
  performance_regression_test.py
  sdcm/utils/csrangehistogram.py
Labels: Ready for review, Backport-5.2, Backport-2023.1

#5466 improvement(k8s): increase load in K8S jobs
  test-cases/scylla-operator/longevity-scylla-operator-3h-add-remove-rack.yaml
  test-cases/scylla-operator/longevity-scylla-operator-3h-backup.yaml
  test-cases/scylla-operator/longevity-scylla-operator-3h-cluster-rolling.yaml
  test-cases/scylla-operator/longevity-scylla-operator-3h-grow-shrink.yaml
  test-cases/scylla-operator/longevity-scylla-operator-3h-repair.yaml
  test-cases/scylla-operator/longevity-scylla-operator-3h-replace.yaml
  test-cases/scylla-operator/longevity-scylla-operator-3h-stop-start.yaml
  test-cases/scylla-operator/longevity-scylla-operator-3h-terminate-decommission-add.yaml
  test-cases/scylla-operator/longevity-scylla-operator-3h-terminate-replace.yaml
  test-cases/scylla-operator/longevity-scylla-operator-3h.yaml
Labels: No Backport Needed, Ready for review

#5801 revert(sct)config): revert added default param for get method
  defaults/test_default.yaml
  longevity_test.py
  sdcm/sct_config.py
Labels: No Backport Needed, Ready for review

#5804 fix(sla): limit SLA nemesis only to sla test cases
  sdcm/nemesis.py
Labels: Ready for review

#5797 refactor(full aggregation scan): rework full aggregation scan according to task https://github.com/scylladb/qa-tasks/issues/1004
  sdcm/scan_operation_thread.py
  unit_tests/test_scan_operation_thread.py
Labels: Ready for review, Backport-5.2, Backport-2023.1

#5808 fix(decommission_streaming_err): remove timeout/retry from rebuild
  sdcm/nemesis.py
Labels: Backport-5.1, Backport-2022.2

#5809 fix(alternator): create role with ConsistencyLevel.ALL
  sdcm/tester.py
Labels: Backport-5.2, Backport-2023.1

#5803 improvement(run_fullscan): implement param validation functionality
  internal_test_data/negative_fullscan_param.yaml
  internal_test_data/positive_fullscan_param.yaml
  sdcm/scan_operation_thread.py
  sdcm/sct_config.py
  test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml
  test-cases/longevity/longevity-large-partition-3h.yaml
  test-cases/longevity/longevity-large-partition-4days.yaml
  test-cases/longevity/longevity-large-partition-8h.yaml
  unit_tests/test_config.py
Labels: Ready for review, Backport-5.2, Backport-2023.1

#5810 fix(longevity-sla-100gb-4h): move under WLP folder
  jenkins-pipelines/workload-prioritization/longevity-sla-100gb-4h.jenkinsfile
Labels: Backport-5.2, Backport-2023.1

#5825 revert(tag_ami): remove a `tag_ami` feature that is not in use
  docs/configuration_options.md
  sdcm/sct_config.py
  sdcm/tester.py
  sdcm/utils/common.py
  unit_tests/test_utils_common.py
  vars/byoLongevityPipeline.groovy
  vars/cdcReplicationPipeline.groovy
  vars/longevityPipeline.groovy
  vars/managerPipeline.groovy
  vars/provisionResources.groovy
  vars/runSctTest.groovy
Labels: No Backport Needed

#5802 feature(node): support new 'replace_node_first_boot' Scylla option
  sdcm/cluster.py
  sdcm/cluster_aws.py
  sdcm/cluster_docker.py
  sdcm/nemesis.py
  sdcm/provision/scylla_yaml/scylla_yaml.py
  unit_tests/test_scylla_yaml.py
Labels: Ready for review, Backport-5.2, Backport-2023.1

#5815 fix(K8S): use latest stable scylla-operator v1.8.0
  defaults/k8s_local_kind_config.yaml
  test-cases/scylla-operator/functional.yaml
Labels: No Backport Needed, Ready for review, test-provision-k8s-local-kind-aws, scylla-operator

#5828 Revert "test(k8s-functional): skip `deploy_helm_with_default_values` for EKS"
  functional_tests/scylla_operator/test_functional.py
Labels: No Backport Needed, Ready for review, scylla-operator

#5827 fix(gce_download): Skip first element by name upon download
  sdcm/utils/common.py
Labels: Ready for review, Backport-5.1, Backport-2022.2, Backport-5.2, Backport-2023.1

#5829 fix(get_supported_scylla_base_versions): adding 2023.1
  utils/get_supported_scylla_base_versions.py
Labels: Backport-5.2, Backport-2023.1

#5817 feature(versions): add classes for scylla versions comparisons
  functional_tests/scylla_operator/conftest.py
  sdcm/cluster.py
  sdcm/cluster_k8s/__init__.py
  sdcm/utils/version_utils.py
  unit_tests/test_version_utils.py
Labels: No Backport Needed, Ready for review

#5832 fix(pipeline): dont fallback to builder when no sct runner. part2
  vars/byoLongevityPipeline.groovy
  vars/cdcReplicationPipeline.groovy
  vars/jepsenPipeline.groovy
  vars/managerPipeline.groovy
  vars/perfRegressionParallelPipeline.groovy
  vars/perfSearchBestConfigParallelPipeline.groovy
  vars/rollingOperatorUpgradePipeline.groovy
  vars/rollingUpgradePipeline.groovy
Labels: Ready for review, Backport-5.2, Backport-2023.1

#5814 fix(nemesis): fix prepare_start_stop_compaction
  sdcm/nemesis.py
Labels: Ready for review, Backport-5.2, Backport-2023.1

#5833 improvement(versions): Use ComparableScyllaVersion in more places
  sdcm/fill_db_data.py
  sdcm/utils/version_utils.py
  unit_tests/test_version_utils.py
  utils/get_supported_scylla_base_versions.py
Labels: No Backport Needed, Ready for review

#5381 improvement(latency with ops): adjust to follow acceptance criteria
  jenkins-pipelines/perf-regression-latency-650gb-with-nemesis.jenkinsfile
  sdcm/results_analyze/__init__.py
  test-cases/performance/perf-regression-latency-650gb-with-nemesis.yaml
Labels: Backport-perf-v14

#5839 fix(instance_root_disk_size): lower duration requirement for extra space
  sdcm/sct_runner.py
Labels: Backport-5.2, Backport-2023.1, Backport-manager-3.1

#5837 improvement(k8s-eks): cleanup OIDC providers
  sdcm/utils/aws_utils.py
Labels: Ready for review, Backport-5.2, Backport-2023.1

#5850 fix(test_case_lint): remove 4.6.9 from test configuration
  defaults/test_default.yaml
  docs/configuration_options.md
  unit_tests/test_data/test_scylla_yaml_builders/PR-provision-test.yaml
  unit_tests/test_scylla_yaml_builders.py
Labels: Ready for review

#5845 fix(FullScanAggregatesOperation): fixing forward_request validation
  sdcm/scan_operation_thread.py
Labels: Ready for review

#5844 fix(perf-nemesis-latency): Add operation duration to report
  sdcm/report_templates/results_latency_during_ops_short.html
  sdcm/utils/decorators.py
  sdcm/utils/latency.py
Labels: Ready for review, Backport-perf-v14

#5849 fix(build_range_histogram): return empty dict if histogrma empty
  sdcm/tester.py
Labels: Ready for review, Backport-perf-v14

#5857 fix(io.conf): remove kernel bug workarounds
  configurations/azure/azure_rolling_upgrade.yaml
  configurations/io.conf
  configurations/io_properties.yaml
  docs/configuration_options.md
  jenkins-pipelines/rolling-upgrade-ami-arm.jenkinsfile
  jenkins-pipelines/rolling-upgrade-ami.jenkinsfile
  jenkins-pipelines/rolling-upgrade-centos7-ldap-authorization.jenkinsfile
  jenkins-pipelines/rolling-upgrade-centos7.jenkinsfile
  jenkins-pipelines/rolling-upgrade-centos8.jenkinsfile
  jenkins-pipelines/rolling-upgrade-debian10.jenkinsfile
  jenkins-pipelines/rolling-upgrade-debian11.jenkinsfile
  jenkins-pipelines/rolling-upgrade-multidc.jenkinsfile
  jenkins-pipelines/rolling-upgrade-ubuntu18.04-ldap-authorization.jenkinsfile
  jenkins-pipelines/rolling-upgrade-ubuntu18.04.jenkinsfile
  jenkins-pipelines/rolling-upgrade-ubuntu20.04.jenkinsfile
  jenkins-pipelines/rolling-upgrade-ubuntu22.04.jenkinsfile
  jenkins-pipelines/upgrade-with-raft/rolling-upgrade-centos8-with-raft.jenkinsfile
  jenkins-pipelines/upgrade-with-raft/rolling-upgrade-debian11-with-raft.jenkinsfile
  jenkins-pipelines/upgrade-with-raft/rolling-upgrade-ubuntu22.04-with-raft.jenkinsfile
  query_limits_test.py
  sdcm/cluster.py
  sdcm/sct_config.py
  test-cases/PR-provision-test.yaml
  test-cases/scale/scale-cluster.yaml
  unit_tests/test_data/test_scylla_yaml_builders/PR-provision-test.yaml
  vars/rollingUpgradePipeline.groovy
Labels: No Backport Needed

#5854 improvement(nemesis.py): truncate nemesis using timeout
  sdcm/nemesis.py
Labels: Backport-5.2, Backport-2023.1

#5836 test(create release jobs): upgrade with raft enabled
  sct.py
Labels: Backport-5.2, Backport-2023.1

#5858 Branch 2021.1 revert jdk workaround
  sdcm/cluster.py
Labels: No Backport Needed

#5855 test(multi-keyspace): Use installed stressed tools instead of dockers
  test-cases/longevity/longevity-multi-keyspaces.yaml
Labels: Backport-5.2, Backport-2023.1

#5863 Revert "fix(install_scylla): adding workaround to JDK"
  sdcm/cluster.py
Labels: No Backport Needed

#5864 fix(artifacts): enable `aws_fallback_to_next_availability_zone`
  test-cases/artifacts/amazon2.yaml
  test-cases/artifacts/oel76.yaml
  test-cases/artifacts/oel81.yaml
Labels: Backport-5.2, Backport-2023.1

#5866 fix(clean-resources): ignore missing ip in cache
  sdcm/provision/azure/ip_provider.py
  sdcm/provision/azure/provisioner.py
Labels: Backport-5.2, Backport-2023.1
