Repository scylladb/scylla-cluster-tests, pull requests merged in 2023-11, with the labels that each got.

#6745 fix(cluster): install_scylla failing on debian based OS
  sdcm/cluster.py
Labels: Backport-5.4

#6749 fix(k8s): use `preferred podAntiAffinity rules` in `ScyllaCluster` K8S objects
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed, Ready for review, scylla-operator

#6750 improvement(k8s): make `check Scylla cleanups` K8S func test save logs
  functional_tests/scylla_operator/test_functional.py
  sdcm/utils/k8s/__init__.py
Labels: No Backport Needed, Ready for review, scylla-operator

#6691 test(k8s-func): add func test with quasi multiDC setup
  functional_tests/scylla_operator/test_functional.py
Labels: No Backport Needed, Ready for review, scylla-operator

#6707 fix(perfRegression pipeline): don't call supportedUpgradeFromVersions
  vars/perfRegressionParallelPipeline.groovy
Labels: Backport-perf-v14

#6753 improvement(k8s): add support of the multiple kubeconfig files
  sdcm/cluster_k8s/__init__.py
  sdcm/cluster_k8s/eks.py
  sdcm/cluster_k8s/gke.py
  sdcm/cluster_k8s/mini_k8s.py
  sdcm/logcollector.py
  sdcm/tester.py
  sdcm/utils/common.py
  sdcm/utils/gce_utils.py
  sdcm/utils/k8s/__init__.py
Labels: No Backport Needed, Ready for review, test-provision-k8s-local-kind-aws, scylla-operator

#6746 fix(monitor-setup): stop using `mikefarah/yq` docker
  sdcm/cluster.py
Labels: test-provision-docker, Backport-5.2, Backport-2023.1, Backport-5.4

#6754 improvement(k8s): assign and use `k8s_cluster` attr for node/pod objects
  sdcm/cluster_k8s/__init__.py
  sdcm/cluster_k8s/eks.py
  sdcm/cluster_k8s/gke.py
  sdcm/cluster_k8s/mini_k8s.py
  sdcm/nemesis.py
  sdcm/utils/k8s/chaos_mesh.py
  sdcm/utils/remote_logger.py
  unit_tests/test_chaos_mesh.py
Labels: No Backport Needed, Ready for review, scylla-operator

#6759 fix(monitor): call `disable_daily_triggered_services` on all node types
  sdcm/cluster.py
Labels: Backport-5.2, Backport-2023.1, Backport-5.4

#6748 fix(cluster): add missing comment to #6740
  sdcm/cluster.py
Labels: Backport-5.4

#6756 improvement(k8s): use region_name as label in loggers
  sdcm/cluster_k8s/__init__.py
  sdcm/cluster_k8s/eks.py
  sdcm/cluster_k8s/gke.py
  sdcm/cluster_k8s/mini_k8s.py
  sdcm/cluster_k8s/operator_monitoring.py
  sdcm/utils/k8s/__init__.py
  sdcm/utils/k8s/chaos_mesh.py
  unit_tests/test_chaos_mesh.py
  unit_tests/test_utils_k8s.py
Labels: No Backport Needed, Ready for review, scylla-operator

#6762 fix(perf-upgrade): rename configuration file
  configurations/perf-regression-upgrade.yaml
Labels: Backport-perf-v14

#6765 fix(sct.py): add jepsen test to release jobs
  sct.py
Labels: No Backport Needed

#6768 improvement(jepsenPipeline): not run first build
  vars/jepsenPipeline.groovy
Labels: No Backport Needed

#6772 fix(group_common_events): Expand regexp to filter more messages
  sdcm/sct_events/group_common_events.py
Labels: Ready for review, Backport-5.4

#6777 fix(k8s): collect all the logs keeping the directories structure
  sdcm/logcollector.py
Labels: No Backport Needed, Ready for review, scylla-operator

#6781 fix(large-partition-200k-pk): Change default AZ
  jenkins-pipelines/longevity-large-partition-200k-pks-4days.jenkinsfile
Labels: Backport-5.4

#6780 fix(longevity-alternator-3h): set different default AZ
  jenkins-pipelines/longevity-alternator-3h.jenkinsfile
Labels: Backport-5.4

#6773 feature(k8s): add general support for multiple K8S clusters
  functional_tests/scylla_operator/conftest.py
  functional_tests/scylla_operator/test_functional.py
  longevity_operator_multi_tenant_test.py
  sdcm/cluster_k8s/__init__.py
  sdcm/cluster_k8s/eks.py
  sdcm/cluster_k8s/gke.py
  sdcm/cluster_k8s/mini_k8s.py
  sdcm/nemesis.py
  sdcm/tester.py
  sdcm/utils/operator/multitenant_common.py
  unit_tests/test_utils__operator__multitenant_common.py
Labels: No Backport Needed, Ready for review, test-provision-k8s-local-kind-aws, scylla-operator, test-provision-k8s-eks

#6783 fix(email_report): pick up proper region values for all backends
  sdcm/tester.py
Labels: Ready for review, Backport-5.2, Backport-2023.1, Backport-5.4

#6784 improvement(k8s): use region_name in the loader pods names
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed, Ready for review, scylla-operator

#6788 fix(disrupt_create_index): ignore apply view update errors
  sdcm/nemesis.py
  sdcm/sct_events/group_common_events.py
Labels: Ready for review, Backport-2023.1, Backport-5.4

#6789 fix(k8s): make quasi-multidc func test be more stable
  functional_tests/scylla_operator/test_functional.py
Labels: No Backport Needed, Ready for review, scylla-operator

#6792 fix(clean-resources): fix `filter_gce_by_tags`
  sdcm/utils/common.py
Labels: Urgent, Backport-5.4

#6793 fix(events): ignore error with MV related error in shutdown
  sdcm/sct_events/setup.py
Labels: Backport-5.4

#6785 fix(k8s): wait for pods readiness in `add_nodes` method
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed, Ready for review, scylla-operator

#6786 feature(k8s-eks): support multi K8S clusters creation (multiDC) in EKS
  sdcm/cluster_k8s/eks.py
  sdcm/tester.py
  sdcm/utils/common.py
Labels: No Backport Needed, Ready for review, scylla-operator

#6801 fix(k8s): fix `flush and reshard` nemesis for K8S
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review, scylla-operator

#6802 improvement(k8s): handle better the target node change in K8S nemesis
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review, scylla-operator

#6797 feature(cluster): add `instance_type` to `add_nodes()` call
  sdcm/cluster.py
  sdcm/cluster_aws.py
  sdcm/cluster_azure.py
  sdcm/cluster_baremetal.py
  sdcm/cluster_docker.py
  sdcm/cluster_gce.py
  sdcm/cluster_k8s/__init__.py
  sdcm/cluster_k8s/eks.py
  sdcm/cluster_k8s/gke.py
  sdcm/sct_provision/region_definition_builder.py
  unit_tests/test_scylla_yaml_builders.py
Labels: Backport-5.4

#6800 fix(install packages): retry install when fail
  sdcm/cluster.py
Labels: Backport-5.2, Backport-2023.1, Backport-5.4

#6822 improvement(k8s): use bigger K8S pod readiness timeout
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed, Ready for review, scylla-operator

#6791 improvement(restore nemesis): remove created keyspaces
  sdcm/nemesis.py
Labels: Backport-5.4

#6820 fix(k8s): make setting of seeds for K8S multiDC setup work correctly
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed, Ready for review, scylla-operator

#6818 fix(get_branched_repo): handle OSS/enterprise releases
  sct.py
  sdcm/sct_config.py
  sdcm/utils/common.py
  sdcm/utils/version_utils.py
  utils/get_supported_scylla_base_versions.py
Labels: test-integration

#6821 ci(k8s-eks): add CI job configuration for the EKS multiDC setups
  jenkins-pipelines/operator/eks/longevity-scylla-operator-multidc-12h-eks.jenkinsfile
  jenkins-pipelines/operator/eks/longevity-scylla-operator-multidc-3h-eks.jenkinsfile
  test-cases/scylla-operator/longevity-scylla-operator-multidc-12h.yaml
  test-cases/scylla-operator/longevity-scylla-operator-multidc-3h.yaml
Labels: No Backport Needed, Ready for review, scylla-operator

#6838 fix(k8s): make scylla-manager pod waiter work correctly
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed, Ready for review, scylla-operator

#6839 fix(get_scylla_versions): handle offline installer case
  sdcm/db_stats.py
Labels: Backport-2023.1, Backport-5.4

#6845 improvement(k8s): make `scylla_operator_chart_version` attr be public
  functional_tests/scylla_operator/conftest.py
  functional_tests/scylla_operator/libs/helpers.py
  functional_tests/scylla_operator/test_functional.py
  sdcm/cluster_k8s/__init__.py
  sdcm/tester.py
Labels: No Backport Needed, Ready for review, scylla-operator

#6850 fix(events-setup): fix regex for ignoring scylladb/scylladb#15672
  sdcm/sct_events/setup.py
  unit_tests/test_events.py
Labels: Backport-5.4, Backport-2024.1

#6857 fix(rolling-upgrade): use correctly versions to cover rc versions
  upgrade_test.py
Labels: Backport-5.4, Backport-2024.1

#6844 fix(k8s): make mgmt work in K8S multiDC setup
  sdcm/cluster_k8s/__init__.py
  sdcm/cluster_k8s/eks.py
  test-cases/scylla-operator/longevity-scylla-operator-multidc-12h.yaml
  test-cases/scylla-operator/longevity-scylla-operator-multidc-3h.yaml
Labels: No Backport Needed, Ready for review, scylla-operator

#6853 feature(k8s): add MultiDC support to GKE backend
  sdcm/cluster_k8s/gke.py
  sdcm/sct_config.py
  sdcm/tester.py
Labels: No Backport Needed, Ready for review, scylla-operator

#6854 ci(k8s-gke): add MultiDC CI jobs
  configurations/operator/multidc-gke-12h.yaml
  configurations/operator/multidc-gke-3h.yaml
  jenkins-pipelines/operator/gke/longevity-scylla-operator-multidc-12h-gke.jenkinsfile
  jenkins-pipelines/operator/gke/longevity-scylla-operator-multidc-3h-gke.jenkinsfile
  test-cases/scylla-operator/longevity-scylla-operator-multidc-12h.yaml
  test-cases/scylla-operator/longevity-scylla-operator-multidc-3h.yaml
Labels: No Backport Needed, Ready for review, scylla-operator

#6855 feature(k8s): add support for the `must-gather` operator command
  sdcm/cluster_k8s/__init__.py
  sdcm/logcollector.py
  sdcm/tester.py
  sdcm/utils/k8s/__init__.py
Labels: No Backport Needed, Ready for review, scylla-operator

#6858 fix(rolling-upgrade): Change rollling upgrades loader to c7i
  test-cases/upgrades/rolling-upgrade.yaml
Labels: Backport-5.4, Backport-2024.1

#6860 fix(azure): do not run `disable_daily_triggered_services` on loaders
  sdcm/cluster.py
Labels: Ready for review, Azure
