Repository scylladb/scylla-cluster-tests, pull requests merged in 2023-03, with the labels that each got.

#5871 fix(cluster.py): ensure iptables is installed on DB node
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review

#5877 fix(azure instance type): change to use V4
  sdcm/cluster_azure.py
  sdcm/sct_runner.py
  sdcm/tester.py
Labels: Backport-5.2, Backport-2023.1

#5862 fix(disk-and-cache): use ssh transport for logs
  test-cases/performance/perf-regression-latency-125gb.yaml
  test-cases/performance/perf-regression-throughput-125gb.yaml
Labels: Ready for review, Backport-perf-v12

#5859 fix(create release jobs): fix upgrade with raft jobs
  sct.py
Labels: Backport-5.2, Backport-2023.1

#5881 fix(cluster.py): install s-b commands went broken
  sdcm/cluster.py
Labels: No Backport Needed, Bug

#5813 fix(k8s-functional): add refresh_ip in def test_operator_managed_tls
  functional_tests/scylla_operator/test_functional.py
Labels: test-provision-k8s-local-kind-aws, serverless, scylla-operator

#5865 fix(Ldap nemesis): skip toggle-connection-disrupt if not using open-Ldap
  sdcm/nemesis.py
Labels: Backport-2022.1, Backport-2022.2, Backport-2023.1

#5879 improvement(nemesis.py): adding `using <timeout>` to truncate
  sdcm/nemesis.py
Labels: Backport-5.2, Backport-2023.1

#5882 fix(output-conf): fix missing region setup
  vars/getJobTimeouts.groovy
Labels: Backport-5.0

#5885 fix(parallelperfpipeline): Use update_db_packages
  vars/perfRegressionParallelPipeline.groovy
Labels: Ready for review, Backport-perf-v14

#5869 fix(nodetool_status): reduce number of api calls
  sdcm/cluster.py
Labels: test-provision-aws, test-provision-k8s-local-kind-aws, test-provision-k8s-eks

#5887 fix(manager): set monitor image in all manager tests to centos
  test-cases/manager/manager-regression-azure.yaml
  test-cases/manager/manager-regression-ipv6.yaml
  test-cases/upgrades/manager-upgrade.yaml
Labels: Ready to be Merged, Backport-manager-3.1

#5891 fix(getJobTimeouts.groovy): convert region params to json before export
  vars/getJobTimeouts.groovy
Labels: Backport-5.0, Backport-manager-3.1

#5889 improvement(scylla-bench): use newest version with better retries
  defaults/test_default.yaml
  docs/configuration_options.md
Labels: Ready for review, test-integration, Backport-5.2, Backport-2023.1

#5886 fix(search_best_perf): add client encryption
  vars/perfSearchBestConfigParallelPipeline.groovy
Labels: Ready for review, Backport-perf-v14

#5893 fix(cluster.py): publish ScyllaYamlUpdateEvent
  sdcm/cluster.py
Labels: No Backport Needed, Ready for review, Bug

#5826 fix(_destroy_data_and_restart_scylla): continue inspite of lack of files
  sdcm/nemesis.py
Labels: Backport-5.2, Backport-2023.1

#5895 fix(centos-manager-sanity-ipv6): set region to us-east-1
  jenkins-pipelines/manager/centos-manager-sanity-ipv6.jenkinsfile
Labels: Backport-manager-3.1

#5876 improvement(sct.py): add support to list azure images
  sct.py
  sdcm/provision/azure/utils.py
  sdcm/utils/version_utils.py
Labels: Ready for review, Backport-5.2, Backport-2023.1

#5900 fix(host_id): get host id from `nodetool info`
  sdcm/cluster.py
Labels: scylla-operator, test-provision-k8s-eks

#5905 fix(autorizer): change to CassandraAuthorizer
  test-cases/features/sl-workloads-test.yaml
  test-cases/features/system-sla-test.yaml
Labels: Ready for review, Backport-2022.1, Backport-5.1, Backport-2022.2, Backport-5.2, Backport-2023.1

#5906 fix(nemesis.py): use BaseNode.install_package for iptables installation
  sdcm/nemesis.py
Labels: Ready for review, Backport-5.2, Backport-2023.1

#5890 fix(longevity): keyspace for data validator
  longevity_lwt_test.py
  sdcm/utils/data_validator.py
Labels: Ready for review

#5901 fix(argus.py): Handle cases where we can't use argus
  sct.py
  sdcm/test_config.py
  sdcm/utils/argus.py
  sdcm/utils/common.py
Labels: Backport-5.2, Backport-2023.1

#5915 improvement(hydra): Upgrade argus client to 0.10.2
  docker/env/version
  requirements.in
Labels: Backport-5.2, Backport-2023.1

#5841 test(nemesis): added create index nemesis
  data_dir/nemesis.yml
  data_dir/nemesis_classes.yml
  jenkins-pipelines/nemesis/longevity-5gb-1h-CreateIndexNemesis-aws.jenkinsfile
  sdcm/nemesis.py
  sdcm/utils/common.py
  sdcm/utils/nemesis_utils/__init__.py
  sdcm/utils/nemesis_utils/indexes.py
  test-cases/nemesis/longevity-5gb-1h-CreateIndexNemesis.yaml
  unit_tests/test_nemesis.py
  unit_tests/test_nemesis_sisyphus.py
Labels: Backport-5.2, Backport-2023.1

#5913 fix(cs_multidc_si_lcs.yaml): fix create query
  data_dir/cs_multidc_si_lcs.yaml
Labels: Backport-5.2, Backport-2023.1

#5922 fix(cluster.py): install s-b commands still broken
  sdcm/cluster.py
Labels: No Backport Needed

#5918 fix(in memory): in-memory longevity is not supported anymore
  jenkins-pipelines/longevity-in-memory-36gb-1d.jenkinsfile
  test-cases/longevity/longevity-in-memory-36GB-1day.yaml
Labels: No Backport Needed, Ready for review

#5892 improvement(logcollector): Implement log rotation
  sdcm/log_archive.sh
  sdcm/logcollector.py
  sdcm/tester.py
Labels: No Backport Needed, Ready for review

#5908 fix(autorizer): change authorizer for old SLA tests
  sla_per_user_system_test.py
Labels: Backport-2022.1, Backport-5.1, Backport-2022.2, Backport-5.2, Backport-2023.1

#5920 fix(get base version): LTS vs short term versions
  utils/get_supported_scylla_base_versions.py
Labels: Ready for review, Urgent, Backport-5.2, Backport-2023.1

#5335 improvement(reversed queries): Added select-order-by to scylla-bench
  jenkins-pipelines/longevity-large-partition-2days-reversed-queries.jenkinsfile
  sdcm/tester.py
  test-cases/longevity/longevity-large-partition-2days.yaml
Labels: No Backport Needed

#5933 fix(scan operations): change log level to debug
  sdcm/scan_operation_thread.py
Labels: No Backport Needed, Ready for review

#5936 fix(data validator): ignore data validator for parallel nemeses test
  longevity_lwt_test.py
  sdcm/nemesis.py
Labels: Ready for review

#5937 fix(sct.log): sct.log tarball is missing the test_id
  sdcm/logcollector.py
Labels: No Backport Needed, Ready for review

#5896 fix(Jenkinsfile): create diffrent directory for each provision test
  Jenkinsfile
Labels: test-provision-azure

#5941 fix(loader-setup): install/update epel to avoid install issues
  sdcm/cluster.py
Labels: Backport-5.2, Backport-2023.1

#5939 fix(upgrade-tests): remove scylla-cqlsh when downgrading
  defaults/test_default.yaml
  docs/configuration_options.md
  sdcm/sct_config.py
  upgrade_test.py
Labels: No Backport Needed

#5931 fix(azure): add more timeout for hard reboots
  sdcm/nemesis.py
Labels: Backport-5.2, Backport-2023.1

#5946 fix(disrupt_decommission_streaming_err): skip failure log
  sdcm/sct_events/group_common_events.py
Labels: No Backport Needed

#5948 fix(network nemeses jobs): add right configuration
  test-cases/nemesis/longevity-5gb-1h-BlockNetworkMonkey.yaml
  test-cases/nemesis/longevity-5gb-1h-RandomInterruptionNetworkMonkey.yaml
  test-cases/nemesis/longevity-5gb-1h-StopStartInterfacesNetworkMonkey.yaml
Labels: Backport-5.2, Backport-2023.1

#5950 test(upgrade): support upgrade from OSS to Enterprise with SLA
  upgrade_test.py
Labels: Ready for review, Backport-2022.1, Backport-2022.2

#5953 fix(Ldap connection): Lower severity of connection-reset-by-peer event
  defaults/severities.yaml
  sdcm/sct_events/database.py
  unit_tests/test_sct_events_database.py
Labels: Backport-2022.1, Backport-2022.2, Backport-2023.1

#5923 test(Ldap): Add/remove Ldap role permissions during stress
  jenkins-pipelines/features-ldap-authorization-add-remove-role-permissions.jenkinsfile
  sdcm/utils/ldap.py
  test-cases/features/test_add_remove_ldap_role_permission.yaml
  test_add_remove_ldap_role_permission.py
Labels: No Backport Needed

#5924 refactor(CSRangeHistogram): Refactor csrangehistogram builders
  sdcm/loader.py
  sdcm/tester.py
  sdcm/utils/csrangehistogram.py
Labels: Ready for review

#5957 improvement(thrpt-perf): allow to change the number of stress threads
  performance_regression_test.py
  test-cases/performance/perf-regression-throughput-125gb.yaml
  test-cases/performance/perf-regression.100threads.30M-keys.yaml
Labels: No Backport Needed, Ready for review, serverless

#5958 improvement(k8s): allow to configure the auxiliary nodes instance type
  defaults/k8s_eks_config.yaml
  defaults/k8s_gke_config.yaml
  docs/configuration_options.md
  sdcm/sct_config.py
  sdcm/tester.py
Labels: No Backport Needed, Ready for review, scylla-operator

#5965 fix(nemesis.py): truncate using timeout check versions
  sdcm/nemesis.py
Labels: No Backport Needed, Ready for review
