Repository scylladb/scylla-cluster-tests, pull requests merged in 2023-07, with the labels that each got.

#6304 fix(jepsen-test): remove `use_legacy_cluster_init`
  test-cases/jepsen/jepsen.yaml
  test-cases/jepsen/jepsen_with_raft.yaml
Labels: No Backport Needed, Ready for review

#6075 fix(disrupt_mgmt_repair_cli): stop task in case of timeout
  sdcm/nemesis.py
Labels: No Backport Needed

#6318 test(longevity): remove multi-rack from longevity topology changes
  jenkins-pipelines/longevity-topology-changes-3h.jenkinsfile
  test-cases/longevity/longevity-topology-changes-3h.yaml
Labels: Backport-5.2

#6231 feature(perf-i4i): New perf throughput non-shard aware i4i tests
  jenkins-pipelines/perf-regression-throughput-non-shard-aware-30min-i4i-enterprise.jenkinsfile
  jenkins-pipelines/perf-regression-throughput-non-shard-aware-30min-i4i.jenkinsfile
  test-cases/performance/perf-regression.100threads.30M-keys-i4i-enterprise.yaml
  test-cases/performance/perf-regression.100threads.30M-keys-i4i.yaml
Labels: Ready for review, Backport-perf-v14

#6322 feature(gemini): update gemini to 1.8.4
  defaults/test_default.yaml
  unit_tests/test_config.py
Labels: No Backport Needed, test-integration

#6323 fix(k8s): do not run nemesis during prepare in 2 tenants longevity test
  test-cases/scylla-operator/longevity-scylla-operator-3h-multitenant.yaml
Labels: No Backport Needed, Ready for review, scylla-operator

#6324 Multiple fixes to test_enospc_before_restore in mgmt_cli_test.py
  mgmt_cli_test.py
Labels: Backport-manager-3.1

#6234 fix(k8s): switch to use and test manager 3.1
  defaults/k8s_eks_config.yaml
  defaults/k8s_gke_config.yaml
  defaults/k8s_local_kind_config.yaml
  functional_tests/scylla_operator/test_functional.py
Labels: No Backport Needed, test-provision-k8s-local-kind-aws, scylla-operator, test-provision-k8s-eks

#6315 fix(topology-change-3h): Decrease partition size for stress
  test-cases/longevity/longevity-topology-changes-3h.yaml
Labels: Ready for review, Backport-5.2, Backport-2023.1

#6335 fix(upgrade test): do not specfiy -a when "nodetools upgradesstables"
  upgrade_test.py
Labels: Backport-2022.1, Backport-5.1, Backport-2022.2, Backport-5.2, Backport-2023.1

#6332 fix(test_config): version ami branch unittest
  unit_tests/test_config.py
Labels: test-integration, Backport-5.2, Backport-2023.1, Backport-5.3

#6333 fix(gemini): update version to 1.8.6
  defaults/test_default.yaml
  unit_tests/test_config.py
Labels: test-integration

#6340 fix(k8s): gather K8S logs when a CI job gets aborted
  sdcm/cluster_k8s/__init__.py
  sdcm/logcollector.py
  sdcm/utils/k8s/__init__.py
Labels: No Backport Needed, Ready for review, scylla-operator

#6341 fix(perf-throughput): set reactor-stall-ms to 5
  test-cases/performance/perf-regression.100threads.30M-keys-i4i-enterprise.yaml
  test-cases/performance/perf-regression.100threads.30M-keys-i4i.yaml
  test-cases/performance/perf-regression.100threads.30M-keys.yaml
Labels: Ready for review, Backport-perf-v14

#6271 fix(major compaction nemesis): increase adaptive timeout to 8000
  sdcm/nemesis.py
Labels: Backport-5.2, Backport-2023.1

#6342 fix(gemini-3h-with-nemesis): set gemini version to 1.7.8
  test-cases/gemini/gemini-3h-with-nemesis.yaml
Labels: No Backport Needed, Urgent

#6343 fix(rolling-upgrade.yaml): set gemini version to 1.7.8
  test-cases/upgrades/rolling-upgrade.yaml
Labels: No Backport Needed, Urgent

#6344 fix(install_gsutil_dependencies): install gsutil with apt-get
  mgmt_cli_test.py
Labels: Backport-manager-3.0, Backport-manager-3.1

#6347 fix(AddRemoveDcNemesis): fix on simulated racks
  sdcm/nemesis.py
Labels: No Backport Needed

#5528 improvement(nemesis.py): refactor nodetool_cleanup to run in parallel
  sdcm/nemesis.py
Labels: No Backport Needed

#6348 fix(hydra): switch docker base to 3.10.12-slim-bullseye
  docker/env/Dockerfile
  docker/env/version
  requirements.txt
Labels: New Hydra Version, Backport-perf-v14

#6242 feature(k8s): raise the number of Pregenerate RSA keys
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed, serverless, scylla-operator

#6350 refactor(rollin-upgrades): Increase diversity of instance types
  configurations/gce/n2-highmem-16.yaml
  configurations/gce/n2-highmem-32.yaml
  configurations/gce/n2-highmem-48.yaml
  configurations/gce/n2-highmem-64.yaml
  configurations/gce/n2-higmem-8.yaml
  jenkins-pipelines/rolling-upgrade-centos7.jenkinsfile
  jenkins-pipelines/rolling-upgrade-centos8.jenkinsfile
  jenkins-pipelines/rolling-upgrade-debian10.jenkinsfile
  jenkins-pipelines/rolling-upgrade-debian11.jenkinsfile
  jenkins-pipelines/rolling-upgrade-ubuntu20.04.jenkinsfile
  jenkins-pipelines/rolling-upgrade-ubuntu22.04.jenkinsfile
Labels: Backport-2022.1, Backport-2022.2, Backport-2023.1

#6351 fix(k8s-local): install helm
  sdcm/cluster_k8s/mini_k8s.py
Labels: No Backport Needed, scylla-operator

#6358 fix(sshd_config): enable keep-alive configuration
  sdcm/provision/common/utils.py
Labels: Backport-5.2, Backport-2023.1

#6365 fix(configuration/gce): typo in configuration filename
  configurations/gce/n2-highmem-8.yaml
Labels: No Backport Needed

#5398 feature(pipeline_test_duration): Generic test_duration for longevity
  defaults/test_default.yaml
  sdcm/sct_config.py
  sdcm/test_config.py
  sdcm/tester.py
  test-cases/longevity/longevity-large-partition-8h.yaml
  vars/getJobTimeouts.groovy
  vars/longevityPipeline.groovy
  vars/runSctTest.groovy
Labels: No Backport Needed, Ready for review

#6366 fix(get_scylla_ami_versions): filter debug versions
  sdcm/sct_config.py
  sdcm/utils/common.py
Labels: Backport-5.1, Backport-2022.2, Backport-perf-v14, Backport-5.2, Backport-2023.1

#6379 fix(Jenkins): use correct shebang string
  Jenkinsfile
  vars/getJobTimeouts.groovy
Labels: No Backport Needed, Ready for review

#6377 fix(sct_runner): fix create-runner-image on GCP
  sdcm/sct_runner.py
Labels: No Backport Needed, Ready for review

#6382 fix(cluster): use external_address in cql_ip_address
  sdcm/cluster.py
Labels: Ready for review, Backport-5.2, Backport-2023.1

#6380 fix(logcollector): don't fail if no builders found
  sdcm/utils/common.py
Labels: No Backport Needed, Ready for review

#6378 fix(remote): allow use non-RSA private keys
  sdcm/remote/remote_cmd_runner.py
Labels: No Backport Needed, Ready for review

#6374 improvement(report_templates): Sort performance results by version
  sdcm/report_templates/results_performance.html
Labels: Backport-perf-v14

#6387 fix(artifacts-amazon2-test): install java 11
  sdcm/cluster.py
Labels: Backport-5.3

#6385 fix(azure utils): get_scylla_images using version flag
  sdcm/provision/azure/utils.py
Labels: No Backport Needed

#6390 fix(upgrade_test): handle uuid sstable identifier on upgradesstable
  upgrade_test.py
Labels: No Backport Needed

#6397 fix(sct_config): remove unused parameter gce_image
  docs/configuration_options.md
  internal_test_data/complex_test_case_with_version.yaml
  sdcm/sct_config.py
  sdcm/tester.py
Labels: No Backport Needed, Ready for review

#6399 improvement(MonitorLogCollector): Added scylla-manager.yaml
  sdcm/logcollector.py
Labels: Backport-manager-3.1

#6405 fix(test-cases): Remove WITH COMMENT from CREATE INDEX query
  test-cases/longevity/longevity-large-partition-3h.yaml
Labels: Backport-2022.1, Backport-2022.2, Backport-5.2, Backport-2023.1, Backport-5.3

#6396 fix(system_auth): speed up repair system_auth during node setup
  sdcm/tester.py
Labels: Backport-5.2, Backport-2023.1

#6294 test(test): perf GCE throughput test
  jenkins-pipelines/perf-regression-throughput-shard-aware-30min-gce.jenkinsfile
  jenkins-pipelines/perf-search-throughput-best-config-gce.jenkinsfile
  sdcm/db_stats.py
  test-cases/performance/perf-regression.100threads.30M-keys.yaml
  test-cases/performance/perf-search-best-throughput-config.yaml
Labels: Backport-perf-v14

#6401 fix(perf_simple_query): fix email reporting
  sdcm/report_templates/results_perf_simple_query.html
  sdcm/utils/microbenchmarking/perf_simple_query_reporter.py
Labels: Ready for review, Ready to be Merged, Backport-perf-v14

#6431 fix(artifacts-gce-image): set the number of local SSDs to 16
  test-cases/artifacts/gce-image.yaml
Labels: Backport-2023.1

#6421 fix(scan_operation_thread): Disable tracing
  sdcm/scan_operation_thread.py
Labels: No Backport Needed, Ready for review
