Repository scylladb/scylla-cluster-tests, pull requests merged in 2023-09, with the labels that each got.

#6557 fix(nemesis.py): Use apt to install stress-ng on ubuntu
  sdcm/nemesis.py
Labels: Backport-5.2, Backport-2023.1

#6564 fix(db node): return scylla_shard as int always
  sdcm/cluster.py
Labels: Backport-5.2, Backport-2023.1

#6561 fix(event_process): fix stop events process under stream of events
  sdcm/sct_events/events_device.py
  unit_tests/test_sct_events_events_analyzer.py
Labels: Backport-5.2, Backport-2023.1, Backport-manager-3.1, Backport-manager-3.2

#6574 fix(kms): allow to run KMS nemesis starting with 2023.1.1 Scylla version
  sdcm/nemesis.py
Labels: Ready for review, Backport-2023.1

#6570 improvement(hydra): Update hydra image to contain PyYAML==6.0.1
  docker/env/version
  requirements.in
  requirements.txt
Labels: No Backport Needed, Ready to be Merged

#6581 fix(nemesis): init new nodes must set them as seeds
  sdcm/nemesis.py
Labels: Backport-5.2, Backport-2023.1

#6571 feature(sct.py): list/delete aws palecement groups
  sct.py
  sdcm/utils/common.py
Labels: Ready for review, Backport-perf-v14

#6586 fix(nemesis): init new node when they are seeds
  sdcm/nemesis.py
Labels: Backport-5.2, Backport-2023.1

#6583 fix(sla-rolling-upgrade): move to run on ubuntu 22.04
  jenkins-pipelines/rolling-upgrade-with-sla-no-shares.jenkinsfile
  jenkins-pipelines/rolling-upgrade-with-sla.jenkinsfile
Labels: Backport-2023.1

#6588 fix(nemesis publisher): add Scylla commit date to ES
  sdcm/nemesis_publisher.py
Labels: No Backport Needed

#6597 fix(event): ignore Azure audit messages
  sdcm/sct_events/database.py
Labels: Backport-2022.2, Backport-5.2, Backport-2023.1, Backport-5.4

#6595 fix(KillNemesis): report killed nemesis based on critical events
  sdcm/nemesis.py
Labels: test-provision-docker

#6499 fix(gemini-ics): Increase loader and db instance types
  test-cases/gemini/gemini-3h-ics-cdc-with-nemesis.yaml
  test-cases/gemini/gemini-basic-3h-ics.yaml
Labels: Backport-2023.1

#6435 fix(mv_si_4d): improve prepare stress
  test-cases/longevity/longevity-mv-si-4days.yaml
Labels: No Backport Needed

#6594 feature(aws): placement group creation
  defaults/test_default.yaml
  sdcm/provision/aws/utils.py
  sdcm/sct_config.py
  sdcm/sct_provision/aws/__init__.py
  sdcm/sct_provision/aws/cluster.py
  sdcm/sct_provision/aws/instance_parameters_builder.py
  sdcm/sct_provision/aws/layout.py
  sdcm/utils/common.py
  test-cases/performance/perf-regression.100threads.30M-keys-i4i.yaml
  vars/perfRegressionParallelPipeline.groovy
Labels: Ready for review, test-provision-aws, Backport-perf-v14

#6596 fix(Nemesis.add_node): support using `use_preinstalled_scylla: false`
  sdcm/nemesis.py
Labels: Backport-2023.1

#5367 feature(log_collector): add scripts debug logs
  sdcm/logcollector.py
Labels: No Backport Needed

#6604 fix(nemesis): make MgmtCorruptThenRepair nemesis be out of limited group
  sdcm/nemesis.py
Labels: Ready for review, Backport-2023.1

#6610 fix(node utils): health check started failing
  sdcm/utils/node.py
  sdcm/utils/sstable/load_utils.py
Labels: No Backport Needed

#6613 fix(healthcheck): fix silent flag in curl
  sdcm/utils/node.py
Labels: No Backport Needed

#6617 fix(random region): add region resolution to getJobTimeouts
  vars/getJobTimeouts.groovy
Labels: No Backport Needed

#6605 feature(gce): block external network for test resources
  sdcm/cluster_gce.py
  sdcm/logcollector.py
  sdcm/utils/gce_region.py
Labels: Backport-5.2, Backport-2023.1

#6621 fix(k8s): fix decommission DB event filter for K8S
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed, scylla-operator

#6620 fix(k8s): add class providing key based locks and use it for K8S
  sdcm/remote/kubernetes_cmd_runner.py
  sdcm/utils/common.py
Labels: No Backport Needed, scylla-operator

#6631 fix(sct_runner): don't call ssh_run_cmd during cleanup if there is no public IP
  sdcm/sct_runner.py
Labels: No Backport Needed, Ready for review

#6633 fix(stress-ng): install the correct way
  sdcm/nemesis.py
Labels: No Backport Needed

#6630 test(perf): use placement group in latency performance test
  test-cases/performance/perf-regression-latency-1TB.yaml
Labels: Ready for review, Backport-perf-v14

#6515 improvement(performance): add perf growShrink test multi-AZ
  jenkins-pipelines/perf-regression-latency-650gb-grow-shrink.jenkinsfile
  sdcm/nemesis.py
  test-cases/performance/perf-regression-latency-650gb-grow-shrink.yaml
Labels: Backport-perf-v14

#6634 fix(k8s): make the `cleanup` test be more stable
  functional_tests/scylla_operator/test_functional.py
Labels: No Backport Needed, test-provision-k8s-local-kind-aws, scylla-operator
