Repository scylladb/scylla-cluster-tests, pull requests merged in 2023-05, with the labels that each got.

#6065 fix(nemesis.py): Remove retry of adding a new node
  sdcm/nemesis.py
Labels: Backport-2022.1, Backport-2022.2, Backport-5.2, Backport-2023.1

#6086 fix(nemesis): stream error wait full restart
  sdcm/nemesis.py
Labels: Backport-5.2, Backport-2023.1

#6090 fix(get_group0_members): re-raise the exception to make retry work
  sdcm/cluster.py
Labels: Backport-5.2, Backport-2023.1

#6081 fix(disrupt_add_remove_mv): choose node without running nemesis
  sdcm/nemesis.py
Labels: Ready for review, Backport-5.2, Backport-2023.1

#6079 fix(FileFollower): refactor iterator
  sdcm/utils/common.py
Labels: Ready for review, Ready to be Merged, Backport-5.2, Backport-2023.1

#6073 fix(large-partitions): update config file for 4days
  test-cases/longevity/longevity-large-partition-4days.yaml
Labels: Ready for review, Backport-5.2, Backport-2023.1

#6015 fix(cluster): Add checks for raft disabling
  sdcm/cluster.py
  sdcm/nemesis.py
  sdcm/tester.py
  sdcm/utils/health_checker.py
  sdcm/utils/raft/__init__.py
  sdcm/utils/raft/common.py
Labels: Ready for review, Backport-5.2, Backport-2023.1

#5979 fix(search_max_througput): stop iteration on 0 num of loaders
  performance_search_max_throughput_test.py
Labels: Ready for review, Ready to be Merged, Backport-perf-v14

#5927 feature(k8s): k8s client based scylla pod logger
  sdcm/cluster.py
  sdcm/cluster_k8s/__init__.py
  sdcm/utils/remote_logger.py
Labels: test-provision-k8s-eks

#6097 fix(k8s): make raft checks work on K8S
  sdcm/utils/raft/__init__.py
Labels: Ready for review, Backport-5.2, Backport-2023.1

#6092 fix(yaml): Add config yaml to disable speculative retry
  configurations/disable_speculative_retry.yaml
Labels: Ready for review, Backport-perf-v14

#6102 fix(createTestJobPipeline): fix enterprise job name
  vars/createTestJobPipeline.groovy
Labels: No Backport Needed

#6100 fix(ICS-1TB-5d): Decrease c-s duration to fit test duration
  test-cases/enterprise-features/ics/longevity/ics-longevity-1TB-7days-authorization-and-tls-ssl.yaml
Labels: Backport-2022.1, Backport-2022.2, Backport-2023.1

#6101 fix(k8s): run only one 'node.init()' method at once
  sdcm/cluster_k8s/__init__.py
Labels: Ready for review

#6104 improvement(k8s): bump the K8S version
  defaults/k8s_eks_config.yaml
  defaults/k8s_gke_config.yaml
Labels: No Backport Needed, Ready for review

#6112 fix(manager jenkinfiles): removed outdated 'manager' parameter
  jenkins-pipelines/manager/centos-manager-repair-control.jenkinsfile
  jenkins-pipelines/manager/centos-manager-repair-intensity-multiple-repaired-nodes.jenkinsfile
  jenkins-pipelines/manager/centos-manager-repair-intensity-single-repaired-nodes.jenkinsfile
  jenkins-pipelines/manager/centos-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/centos-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/debian10-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/debian11-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/enterprise-ami-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu18-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu20-manager-upgrade.jenkinsfile
Labels: No Backport Needed

#6113 fix(spot price): increase max spot price to 80% of on_demand price
  defaults/aws_config.yaml
Labels: test-provision-aws

#6107 improvement(k8s-eks): Update K8S node tags and SGs only once
  sdcm/cluster_k8s/eks.py
Labels: Ready for review, scylla-operator

#6120 fix(udf): replace xwasm with wasm
  data_dir/c-s_uda_udf.yaml
  sdcm/utils/udf.py
  sdcm/utils/udf_scripts/wasm_div.yaml
  sdcm/utils/udf_scripts/wasm_div_fin.yaml
  sdcm/utils/udf_scripts/wasm_plus.yaml
  sdcm/utils/udf_scripts/wasm_plus_acc.yaml
  sdcm/utils/udf_scripts/wasm_simple_return_int.yaml
  test-cases/features/uda_udf.yaml
  uda_udf_test.py
  unit_tests/test_uda.py
  unit_tests/test_udf.py
Labels: No Backport Needed

#6117 fix(load_and_stream): fix log followers
  sdcm/nemesis.py
  sdcm/utils/sstable/load_utils.py
  unit_tests/test_utils_common.py
Labels: No Backport Needed

#6122 fix(manager): bumping manager version
  defaults/manager_versions.yaml
  defaults/test_default.yaml
Labels: No Backport Needed, test-provision-aws

#6124 fix(ubuntu18): since this version is EOL, we remove it
  configurations/manager/ubuntu18.yaml
  docs/artifacts_test.md
  jenkins-pipelines/artifacts-ubuntu1804.jenkinsfile
  jenkins-pipelines/manager/ubuntu18-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/ubuntu18-manager-upgrade.jenkinsfile
  jenkins-pipelines/nonroot-offline-install/artifacts-ubuntu1804.jenkinsfile
  jenkins-pipelines/rolling-upgrade-ubuntu18.04-ldap-authorization.jenkinsfile
  jenkins-pipelines/rolling-upgrade-ubuntu22.04-ldap-authorization.jenkinsfile
  test-cases/artifacts/ubuntu1804.yaml
Labels: Backport-2021.1, Backport-2022.1, Backport-2022.2, Backport-5.2, Backport-2023.1

#6125 fix(artifacts_test.md): replace ubuntu18 to ubuntu22
  docs/artifacts_test.md
Labels: No Backport Needed

#6116 improvement(LogCollector): Added the log of the manager's scylla backend
  sdcm/logcollector.py
Labels: Backport-manager-3.0, Backport-manager-3.1

#6127 fix(sct_config): `get_scylla_gce_images_versions` filters
  sdcm/sct_config.py
Labels: Backport-5.2, Backport-2023.1

#5785 feature(k8s): add support for dynamic local volume provisioner
  defaults/k8s_eks_config.yaml
  defaults/k8s_gke_config.yaml
  defaults/k8s_local_kind_config.yaml
  docker/env/hydra.sh
  sdcm/cluster_k8s/__init__.py
  sdcm/cluster_k8s/eks.py
  sdcm/cluster_k8s/mini_k8s.py
  sdcm/k8s_configs/eks/scylla-node-prepare.yaml
  sdcm/k8s_configs/node-config-crd.yaml
  sdcm/sct_config.py
  sdcm/tester.py
Labels: No Backport Needed, Ready for review, scylla-operator

#6057 test(Microbenchmarking): introduse perf-simple-query
  docs/microbenchmarking.md
  jenkins-pipelines/perf-simple-query.jenkinsfile
  microbenchmarking_test.py
  sdcm/report_templates/results_perf_simple_query.html
  sdcm/send_email.py
  sdcm/utils/microbenchmarking/__init__.py
  sdcm/utils/microbenchmarking/perf_simple_query_reporter.py
  test-cases/microbenchmarking/amazon_perf_simple_query.yaml
Labels: Ready for review, Backport-perf-v14

#6006 test(k8s): add 'nodetool drain' K8S functional test
  functional_tests/scylla_operator/test_functional.py
Labels: No Backport Needed, Ready for review, test-provision-k8s-local-kind-aws

#5991 improvement(grafana): properly calculate nodes number in K8S's grafana
  data_dir/scylla-dash-per-server-nemesis.master.json
Labels: No Backport Needed, Ready for review, scylla-operator

#6141 fix(microbenchmarking): Switch to use new index
  sdcm/microbenchmarking.py
Labels: No Backport Needed, Ready for review

#6066 fix(LatencyDuringOperationsPerformanceAnalyzer): Add best version result
  sdcm/report_templates/results_latency_during_ops_short.html
  sdcm/results_analyze/__init__.py
Labels: Ready for review, Backport-perf-v14

#6074 fix(longevity): use LOCAL consistency level in multiDC tests
  test-cases/longevity/longevity-lwt-24h-multidc.yaml
Labels: Backport-5.2, Backport-2023.1

#6151 fix(k8s-local): do not run docker images cache in 'reuse setup' cases
  sdcm/cluster_k8s/mini_k8s.py
Labels: No Backport Needed, scylla-operator

#6093 fix(yaml): Update c-s parametes for multidc schema-topology test
  data_dir/cs_multidc_si_lcs.yaml
  data_dir/cs_mv_si_keyspace1.yaml
  test-cases/longevity/longevity-multidc-parallel-topology-schema-changes-12h.yaml
Labels: Ready for review, Backport-5.2, Backport-2023.1

#6147 fix(microbenchmarking): pass es index as cli parameter
  sdcm/microbenchmarking.py
  unit_tests/test_microbenchmarking.py
Labels: No Backport Needed, Ready for review

#6149 fix(k8s): make 'stop' close K8sClientLogger's log stream fast
  sdcm/utils/remote_logger.py
Labels: No Backport Needed, scylla-operator

#6150 fix(cluster.py): make stop of threads do less redundant sleeps
  sdcm/cluster.py
Labels: No Backport Needed

#6154 fix(sct_config): do not check AZ num for K8S
  sdcm/sct_config.py
  unit_tests/test_config.py
Labels: No Backport Needed

#6148 fix(nemesis.py): Remove the 120% allocation from disrupt_memory_stress
  sdcm/nemesis.py
Labels: Backport-2022.1, Backport-2022.2, Backport-5.2, Backport-2023.1

#6159 fix(replication_strategy): use python driver for cql command
  sdcm/utils/replication_strategy_utils.py
  unit_tests/test_replication_strategy_utils.py
Labels: Backport-5.2, Backport-2023.1

#6161 fix(yaml): Set larget duration for latency-with-ops
  test-cases/performance/perf-regression-latency-650gb-with-nemesis.yaml
Labels: Ready for review, Backport-perf-v14

#6152 fix(LatencyDuringOperationsPerformanceAnalyzer): Add best version result
  sdcm/report_templates/results_latency_during_ops_short.html
  sdcm/results_analyze/__init__.py
Labels: No Backport Needed

#6171 fix(indexes.py): fix regex for filter event
  sdcm/utils/nemesis_utils/indexes.py
Labels: Backport-5.2, Backport-2023.1

#6155 fix(large partitions): use paged-queries in collect_partitions_info
  sdcm/tester.py
Labels: Backport-2022.1, Backport-2022.2, Backport-5.2, Backport-2023.1

#6179 feature(Jenkinsfile): scylla 5.2.0 as default in SCT CI
  Jenkinsfile
Labels: No Backport Needed

#6142 feature(SisyphusNemesis): add network interruptions to kubernetes filter
  data_dir/nemesis.yml
  data_dir/nemesis_classes.yml
  sdcm/nemesis.py
Labels: No Backport Needed

#6162 improvement(cleanup): remove redundancy from the 'clean-resources'
  sct.py
  sdcm/provision/azure/provisioner.py
  sdcm/utils/common.py
  unit_tests/test_clean_cloud_resources_func.py
Labels: Ready for review, test-provision-aws, test-provision-gce, test-provision-azure, test-provision-k8s-eks, Backport-5.2, Backport-2023.1

#6188 improvement(k8s): use latest stable scylla by default in K8S
  defaults/k8s_eks_config.yaml
  defaults/k8s_gke_config.yaml
  defaults/k8s_local_kind_config.yaml
Labels: No Backport Needed, Ready for review, scylla-operator

#6158 improvement(Argus): Catch failed runs earlier
  docker/env/version
  requirements.in
  requirements.txt
  sct.py
  sdcm/tester.py
  vars/artifactsPipeline.groovy
  vars/createArgusTestRun.groovy
  vars/finishArgusTestRun.groovy
  vars/longevityPipeline.groovy
  vars/managerPipeline.groovy
  vars/rollingOperatorUpgradePipeline.groovy
  vars/rollingUpgradePipeline.groovy
Labels: No Backport Needed, Ready for review

#6080 fix(parallel-schema-chanages): Update stress parameters
  test-cases/longevity/longevity-parallel-schema-changes-12h.yaml
Labels: Backport-5.2, Backport-2023.1

#6176 fix(perf_search_best_config): use base threads if counted thread is 0
  performance_search_max_throughput_test.py
Labels: Ready for review, Ready to be Merged, Backport-perf-v14

#6187 fix(k8s): use latest scylla-operator by default
  defaults/k8s_local_kind_config.yaml
  test-cases/scylla-operator/functional.yaml
Labels: No Backport Needed, Ready for review, test-provision-k8s-local-kind-aws, scylla-operator

#6184 fix(tester.py): Submit correct amount of total events to Argus
  sdcm/tester.py
  unit_tests/test_tester.py
Labels: No Backport Needed, Ready for review

#6198 fix(LatencyPerfAnalyzer): Fix query search parameter
  sdcm/results_analyze/__init__.py
Labels: Ready for review

#6197 improvement(longevity): change DB instance type in lwt-multidc-24h
  test-cases/longevity/longevity-lwt-24h-multidc.yaml
Labels: No Backport Needed, Ready for review

#6190 fix(cluster.py): do not print false errors not finding 'cpu_set' value
  sdcm/cluster.py
  unit_tests/test_cluster.py
Labels: No Backport Needed, Ready for review

#6193 fix(k8sLogger): fix stop logger when stream is closed
  sdcm/utils/remote_logger.py
Labels: No Backport Needed, test-provision-k8s-local-kind-aws, test-provision-k8s-eks

#6201 fix(k8s): remove redundant dc setup in node_setup
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed

#6111 feature(multi-az): add possibility to simulate racks
  defaults/test_default.yaml
  jenkins-pipelines/longevity-cdc-100gb-4h.jenkinsfile
  jenkins-pipelines/longevity-counters-multidc.jenkinsfile
  jenkins-pipelines/longevity-topology-changes-3h.jenkinsfile
  sdcm/cluster.py
  sdcm/cluster_aws.py
  sdcm/nemesis.py
  sdcm/sct_config.py
  sdcm/snitch_configuration.py
  sdcm/utils/properties.py
  test-cases/longevity/longevity-cdc-100gb-4h.yaml
  test-cases/longevity/longevity-counters-multidc.yaml
  test-cases/longevity/longevity-topology-changes-3h.yaml
Labels: No Backport Needed, test-provision-k8s-eks

#6202 fix(k8s-ci): use the same `cluster_name` in all K8S monitoring methods
  functional_tests/scylla_operator/test_functional.py
Labels: No Backport Needed, Ready for review, test-provision-k8s-local-kind-aws, scylla-operator

#6204 fix(snitch): don't update snitch properties when no need
  sdcm/cluster.py
  sdcm/snitch_configuration.py
Labels: test-provision-aws, test-provision-gce, test-provision-azure
