Repository scylladb/scylla-cluster-tests, pull requests merged in 2023-10, with the labels that each got.

#6642 fix(artifacts): use default logs_transport for Docker test
  test-cases/artifacts/docker.yaml
Labels: No Backport Needed, Ready for review

#6643 fix(azure): Creating instances didn't respected `disk_size`
  sdcm/provision/azure/virtual_machine_provider.py
Labels: test-provision-azure

#6626 fix(nemesis): fix time skew in reading audit logs
  sdcm/nemesis.py
Labels: Backport-2023.1

#6551 fix(azure-vm): disable azure agents
  sdcm/provision/azure/virtual_machine_provider.py
  unit_tests/provisioner/fake_azure_service.py
Labels: test-provision-azure, Backport-5.2, Backport-2023.1

#6646 fix(artifact test): remove 'developer-mode' arg for t3.micro
  sdcm/cluster.py
Labels: Backport-2023.1

#6650 fix(compaction_params): pass only supported params
  sdcm/nemesis.py
  sdcm/tester.py
  test_lib/compaction.py
Labels: No Backport Needed, Ready for review

#6639 improvement(kms): add check for KMS encryption fact
  sdcm/cluster.py
  sdcm/nemesis.py
  sdcm/utils/sstable/sstable_utils.py
Labels: Ready for review, Backport-2023.1

#6360 fix(raft_operation): Timeout for log message depend on appearence in log
  sdcm/cluster.py
  sdcm/nemesis.py
  sdcm/sct_events/group_common_events.py
  sdcm/utils/raft/__init__.py
Labels: Backport-5.2, Backport-2023.1, Backport-5.4

#6648 fix(manager_cli): extend timeout on test_restore_backup_with_task
  mgmt_cli_test.py
Labels: Backport-manager-3.2

#6657 fix(syslog): set millisecond resolution
  sdcm/utils/syslogng.py
Labels: No Backport Needed, Ready for review, test-provision-aws, test-provision-gce, test-provision-azure

#6658 fix(k8s-local): stop caching the scylla-operator docker image
  sdcm/cluster_k8s/mini_k8s.py
Labels: Ready for review, scylla-operator

#6655 improvement(manager_cli): use adaptive_timeout instead of large timeout
  mgmt_cli_test.py
  sdcm/utils/adaptive_timeouts/__init__.py
Labels: Backport-manager-3.2

#6659 improvement(k8s-local): use latest versions for K8S and Scylla
  defaults/k8s_local_kind_config.yaml
Labels: Ready for review, scylla-operator

#6662 fix(gke-upgrade): configure the correct k8s base version
  test-cases/scylla-operator/kubernetes-platform-upgrade.yaml
Labels: scylla-operator

#6669 fix(k8s): make `replace` op after disruption not raise false errors
  sdcm/nemesis.py
Labels: Ready for review, scylla-operator

#6676 fix(k8s-functional): update `pytest.ini` to contain all the markers we use
  functional_tests/scylla_operator/pytest.ini
Labels: No Backport Needed, Ready for review, scylla-operator

#6675 improvement(k8s-local-kind): cache chaos-mesh docker images
  sdcm/cluster_k8s/mini_k8s.py
Labels: No Backport Needed, Ready for review, test-provision-k8s-local-kind-aws, scylla-operator

#6674 improvement(k8s-local-kind): make pod network be available for host
  sdcm/cluster_k8s/mini_k8s.py
Labels: No Backport Needed, Ready for review, test-provision-k8s-local-kind-aws, scylla-operator

#6683 fix(longevity 4h): move default to new AZ
  jenkins-pipelines/longevity-100gb-4h.jenkinsfile
Labels: No Backport Needed

#5977 test(custom_profile_d): Longevity with custom_d profile
  jenkins-pipelines/longevity-user-profile-d.jenkinsfile
  longevity_sla_test.py
  sdcm/sct_config.py
  sdcm/stress_thread.py
  sdcm/utils/user_profile.py
  test-cases/longevity/longevity-user-profile-d.yaml
  test_lib/sla.py
Labels: Ready for review, Backport-2023.1, Backport-5.4

#6666 improvement(perf regression pipeline): add base version calculator
  vars/perfRegressionParallelPipeline.groovy
Labels: Backport-perf-v14

#6622 test(perfor): add use_placement_group into nemesis
  sdcm/cluster_aws.py
  sdcm/ec2_client.py
  test-cases/performance/perf-regression-latency-650gb-with-nemesis.yaml
Labels: Ready for review, Ready to be Merged, Backport-perf-v14

#6692 feature(k8s): support direct usage of the `PodIP` addresses for DB pods
  docs/configuration_options.md
  sdcm/cluster_k8s/__init__.py
  sdcm/sct_config.py
Labels: No Backport Needed, Ready for review, scylla-operator

#6394 improvement(test-cases): Add bare metal performance test
  jenkins-pipelines/perf-regression-throughput-baremetal-example.jenkinsfile
  sdcm/cluster_baremetal.py
  sdcm/keystore.py
  sdcm/node_exporter_setup.py
  sdcm/provision/common/utils.py
  sdcm/sct_config.py
  sdcm/tester.py
  test-cases/performance/perf-regression-throughput-baremetal-5gb.yaml
  unit_tests/test_config.py
  vars/getCloudProviderFromBackend.groovy
Labels: Ready for review, Backport-perf-v14

#6700 fix(unit-test): update TestBaseVersion.test_master to be `5.4`
  unit_tests/test_base_version.py
Labels: Ready for review

#6235 fix(wait_for): Support stop wait_for by event
  sdcm/exceptions.py
  sdcm/wait.py
  unit_tests/test_wait.py
Labels: Ready for review, Backport-5.2, Backport-2023.1

#6705 fix(install_syslogng_service): clear all syslog-ng packages
  sdcm/provision/common/utils.py
Labels: test-provision-aws, test-provision-gce

#6713 improvement(k8s): use `0.2.0-rc.0` for `k8s-local-volume-provisioner`
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed, Ready for review, scylla-operator

#6715 improvement(K8S): use smaller instance type on EKS running func-l tests
  configurations/operator/functional-eks.yaml
  jenkins-pipelines/operator/functional/functional-eks.jenkinsfile
Labels: No Backport Needed, Ready for review, scylla-operator

#6679 fix(perf-latency): use `email_subject_postfix` for subject
  configurations/disable_cluster_health_check.yaml
  configurations/perf-regresssion-upgrade.yaml
  jenkins-pipelines/perf-regression-latency-650gb-during-rolling-upgrade.jenkinsfile
  performance_regression_test.py
  sdcm/results_analyze/__init__.py
  sdcm/tester.py
  test-cases/performance/perf-regression-latency-650gb-grow-shrink.yaml
  test-cases/performance/perf-regression-latency-650gb-with-nemesis.yaml
Labels: Backport-perf-v14

#6710 improvement(node setup): Configure a hybrid RAID on GCE
  defaults/gce_config.yaml
  docs/configuration_options.md
  sdcm/cluster.py
  sdcm/sct_config.py
Labels: Backport-2022.1, Backport-2023.1

#6732 improvement(k8s): add `create_namespace` method to KubernetesCluster
  functional_tests/scylla_operator/test_functional.py
  sdcm/cluster_k8s/__init__.py
  sdcm/utils/k8s/chaos_mesh.py
Labels: No Backport Needed, Ready for review, scylla-operator

#6731 improvement(k8s): remove redundant config options for K8S backends
  defaults/k8s_eks_config.yaml
  defaults/k8s_gke_config.yaml
  defaults/k8s_local_kind_config.yaml
  docs/configuration_options.md
  functional_tests/scylla_operator/test_functional.py
  sdcm/cluster_k8s/__init__.py
  sdcm/cluster_k8s/mini_k8s.py
  sdcm/sct_config.py
  upgrade_test.py
Labels: No Backport Needed, Ready for review, scylla-operator

#6739 fix(k8s-gke): define missing `region_name` attr
  sdcm/cluster_k8s/gke.py
Labels: No Backport Needed, Ready for review, scylla-operator

#6740 fix(cluster): node setup - install package wait for package manager
  sdcm/cluster.py
Labels: Backport-5.4
