Repository scylladb/scylla-cluster-tests, pull requests merged in 2023-12, with the labels that each got.

#6883 improvement(defaults): use latest `5.2.x` as default scylla version
  Jenkinsfile
  defaults/k8s_eks_config.yaml
  defaults/k8s_gke_config.yaml
  defaults/k8s_local_kind_config.yaml
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed, test-provision, Ready for review

#6881 fix(k8s): make k8s log collectors not overlap in log dir names
  sdcm/logcollector.py
  sdcm/utils/k8s/__init__.py
Labels: No Backport Needed, Ready for review, scylla-operator

#6882 fix(k8s): make `use_mgmt=false` work again for K8S
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed, Ready for review, scylla-operator

#6888 fix(docker): enable the ssh service back
  docker/scylla-sct/centos/Dockerfile
  docker/scylla-sct/centos/etc/scylla-manager.conf
  docker/scylla-sct/centos/etc/sshd-service.sh
  docker/scylla-sct/centos/etc/sshd.conf
  docker/scylla-sct/ubuntu/Dockerfile
  docker/scylla-sct/ubuntu/etc/scylla-manager.conf
  docker/scylla-sct/ubuntu/etc/sshd-service.sh
  docker/scylla-sct/ubuntu/etc/sshd.conf
Labels: test-provision-docker

#6894 fix(k8s-gke): set AZ explicitly as non-`a` for the `us-east1` region
  defaults/k8s_gke_config.yaml
  jenkins-pipelines/operator/gke/longevity-scylla-operator-3h-gke-add-remove-rack.jenkinsfile
  jenkins-pipelines/operator/gke/longevity-scylla-operator-3h-gke-backup.jenkinsfile
  jenkins-pipelines/operator/gke/longevity-scylla-operator-3h-gke-cluster-rolling.jenkinsfile
  jenkins-pipelines/operator/gke/longevity-scylla-operator-3h-gke-grow-shrink.jenkinsfile
  jenkins-pipelines/operator/gke/longevity-scylla-operator-3h-gke-nodetool-flush-and-reshard.jenkinsfile
  jenkins-pipelines/operator/gke/longevity-scylla-operator-3h-gke-repair.jenkinsfile
  jenkins-pipelines/operator/gke/longevity-scylla-operator-3h-gke-replace.jenkinsfile
  jenkins-pipelines/operator/gke/longevity-scylla-operator-3h-gke-scylla-enterprise.jenkinsfile
  jenkins-pipelines/operator/gke/longevity-scylla-operator-3h-gke-stop-start.jenkinsfile
  jenkins-pipelines/operator/gke/longevity-scylla-operator-3h-gke-terminate-decommission-add.jenkinsfile
  jenkins-pipelines/operator/gke/longevity-scylla-operator-3h-gke-terminate-replace.jenkinsfile
  jenkins-pipelines/operator/gke/longevity-scylla-operator-3h-gke.jenkinsfile
  jenkins-pipelines/operator/gke/longevity-scylla-operator-basic-12h-gke-scylla-enterprise.jenkinsfile
  jenkins-pipelines/operator/gke/longevity-scylla-operator-basic-12h-gke.jenkinsfile
  jenkins-pipelines/operator/upgrade/upgrade-major-scylla-k8s-gke.jenkinsfile
  jenkins-pipelines/operator/upgrade/upgrade-operator-k8s-gke.jenkinsfile
  jenkins-pipelines/operator/upgrade/upgrade-platform-k8s-gke.jenkinsfile
  jenkins-pipelines/operator/upgrade/upgrade-scylla-k8s-gke.jenkinsfile
  vars/rollingOperatorUpgradePipeline.groovy
Labels: No Backport Needed, Ready for review, scylla-operator

#6897 fix(run_cqlsh): make sure we escape double quotes
  sdcm/cluster.py
  unit_tests/test_run_cqlsh.py
Labels: Backport-5.4, Backport-2024.1

#6903 ci(k8s): disable K8S `SNI/TLS` feature for the github PR testing
  Jenkinsfile
Labels: No Backport Needed, Ready for review, scylla-operator

#6902 improvement(k8s): stabilize `test_deploy_quasi_multidc_db_cluster` test
  functional_tests/scylla_operator/test_functional.py
Labels: No Backport Needed, Ready for review, scylla-operator

#6918 fix(run_cqlsh): make it work having new line and space symbols in cmd
  sdcm/cluster.py
  unit_tests/test_run_cqlsh.py
Labels: Ready for review, test-integration, Backport-5.4, Backport-2024.1

#6914 fix(quota): skip quota nemesis on not aws backends
  sdcm/nemesis.py
Labels: Backport-5.4, Backport-2024.1

#6919 fix(sstables_utils): do not use multiline string defining cqlsh command
  sdcm/utils/sstable/load_utils.py
Labels: Ready for review, Backport-5.4, Backport-2024.1

#6891 fix(large-partition-200k): remove partition validation
  test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml
Labels: Backport-5.4, Backport-2024.1

#6886 fix(longevity): remove MV creation in large partition tests
  test-cases/longevity/longevity-large-partition-3h.yaml
Labels: Backport-5.4, Backport-2024.1

#6925 fix(k8s): guarantee K8S logs gathering
  sdcm/cluster_k8s/eks.py
  sdcm/cluster_k8s/gke.py
  sdcm/tester.py
Labels: No Backport Needed, Ready for review, scylla-operator

#6930 fix(install_package): install `lsof` package before using it
  sdcm/cluster.py
Labels: Ready for review, scylla-operator

#6931 fix(disrupt_add_remove_dc): put back c-s thread into context
  sdcm/nemesis.py
Labels: Backport-5.4, Backport-2024.1

#6940 improvement(k8s): bump the local volume provisioner version
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed, Ready for review, scylla-operator

#6938 fix(k8s): save logs in `deploy_helm_with_default_values` K8S func test
  functional_tests/scylla_operator/test_functional.py
Labels: No Backport Needed, Ready for review, scylla-operator

#6951 improvement(k8s): reuse operator's `NodeConfig` for static vol provisioner
  sdcm/cluster_k8s/__init__.py
  sdcm/k8s_configs/eks/scylla-node-prepare.yaml
  sdcm/k8s_configs/gke/scylla-node-prepare.yaml
  sdcm/k8s_configs/static-local-volume-provisioner.yaml
Labels: No Backport Needed, Ready for review, scylla-operator

#6953 ci(k8s-eks): add ARM CI jobs configurations
  configurations/arm/eks.yaml
  configurations/operator/functional-eks-arm.yaml
  functional_tests/scylla_operator/test_functional.py
  jenkins-pipelines/operator/eks/longevity-scylla-operator-3h-eks-arm.jenkinsfile
  jenkins-pipelines/operator/functional/functional-eks-arm.jenkinsfile
  sdcm/cluster_k8s/eks.py
Labels: No Backport Needed, Ready for review, scylla-operator

#6958 fix(docker): handle correctly older sshd versions
  docker/scylla-sct/ubuntu/Dockerfile
Labels: test-provision-docker, Backport-2022.1, Backport-2022.2, Backport-5.4, Backport-2024.1

#6956 fix(syslog-ng): remove log to local file
  sdcm/provision/common/utils.py
Labels: test-provision-aws, test-provision-gce, Backport-2023.1, Backport-5.4, Backport-2024.1

#6954 fix(prepare_kms_host): enable kms only for supported versions
  sdcm/tester.py
Labels: Backport-2023.1, Backport-5.4, Backport-2024.1

#6961 fix(k8s): ignore timeout error deleting quasi-milti-dc ns
  functional_tests/scylla_operator/test_functional.py
Labels: No Backport Needed, Ready for review, scylla-operator

#6963 fix(k8s): fix scylla-operator upgrade test
  sdcm/cluster_k8s/__init__.py
  upgrade_test.py
Labels: No Backport Needed, Ready for review, scylla-operator

#6964 fix(prepare_kms_host): skip KMS configuration if there an oracle
  sdcm/tester.py
Labels: Backport-2024.1

#6970 improvement(version_utils): support more version options
  sdcm/utils/version_utils.py
  unit_tests/test_version_utils.py
Labels: Ready for review, Backport-5.4, Backport-2024.1

#6965 fix(MV-errors): skip all view update error globaly
  sdcm/nemesis.py
  sdcm/sct_events/group_common_events.py
  sdcm/sct_events/setup.py
  sdcm/utils/nemesis_utils/indexes.py
  unit_tests/test_events.py
Labels: Backport-5.4, Backport-2024.1

#6971 test_default.yaml: set monitoring branch to 4.6
  defaults/test_default.yaml
Labels: test-provision-aws, test-provision-docker, Backport-2024.1

#6949 fix(aws-root-disk): make sure we are using gp3 for disks in AWS
  sdcm/sct_provision/aws/instance_parameters_builder.py
  sdcm/sct_runner.py
  sdcm/tester.py
  sdcm/utils/aws_utils.py
  unit_tests/test_scylla_yaml_builders.py
Labels: test-provision-aws, test-integration, Backport-5.4, Backport-2024.1

#6976 fix(ComparableScyllaVersion): support version of release canidates
  sdcm/utils/version_utils.py
  unit_tests/test_version_utils.py
Labels: Backport-5.4, Backport-2024.1

#6957 fix(is_enterprise): check command output applying logic
  sdcm/cluster.py
Labels: test-provision-aws

#6975 fix(monitoring): don't specify scylla target ports
  sdcm/cluster.py
Labels: test-provision-aws, Backport-2022.1, Backport-2022.2, Backport-5.2, Backport-2023.1, Backport-5.4, Backport-2024.1

#6980 refactor(alter_test_tables_encryption): use only when really needed
  sdcm/tester.py
Labels: Backport-5.4, Backport-2024.1

#6986 fix(get_builder_by_test_id): don't list stopped builders
  sdcm/utils/common.py
Labels: Urgent, Bug, Backport-2022.1, Backport-5.1, Backport-2022.2, Backport-5.2, Backport-2023.1, Backport-5.4, Backport-2024.1

#6985 fix(dns): Change monitor instance type
  test-cases/features/dns-cluster-5min.yaml
Labels: Backport-5.4, Backport-2024.1

#6981 improvement(k8s): copy `must-gather` binary from local docker container
  sdcm/utils/k8s/__init__.py
Labels: No Backport Needed, Ready for review, scylla-operator

#6988 fix(oracle_scylla_version): Bump oracle version to 2021.1.23
  defaults/test_default.yaml
  test-cases/gemini/gemini-3h-ics-cdc-with-nemesis.yaml
  test-cases/gemini/gemini-3h-ics-with-nondisruptive-nemesis.yaml
  test-cases/gemini/gemini-basic-3h-ics.yaml
Labels: Backport-2022.1, Backport-2022.2, Backport-5.2, Backport-2023.1, Backport-5.4, Backport-2024.1

#6989 fix(kms-cases): remove kms logging
  configurations/kms-ear.yaml
Labels: Backport-5.4, Backport-2024.1

#6991 improvement(k8s): bump version for `k8s-local-volume-provisioner`
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed, Ready for review, scylla-operator

#6987 ci(k8s): add scylla upgrade jobs using pod IPs
  configurations/operator/expose-pod-ips.yaml
  jenkins-pipelines/operator/upgrade/upgrade-major-scylla-podips-k8s-eks.jenkinsfile
  jenkins-pipelines/operator/upgrade/upgrade-major-scylla-podips-k8s-gke.jenkinsfile
Labels: No Backport Needed, Ready for review, scylla-operator

#6982 fix(upgrade_test): `scylla sstable dump` verify with scylla.yaml
  upgrade_test.py
Labels: Backport-5.4, Backport-2024.1

#6990 fix(disrupt_add_remove_mv): Increase session connection timeout
  sdcm/nemesis.py
Labels: Backport-5.4, Backport-2024.1

#6983 fix(aws_builder): change the builders to configure gp3 root disks
  sdcm/utils/aws_builder.py
Labels: Infrastructure

#6994 fix(nemesis): disable `disrupt_memory_stress`
  sdcm/nemesis.py
Labels: Backport-5.4, Backport-2024.1

#6995 fix(alter_test_tables_encryption): fix the walrus operation
  sdcm/tester.py
Labels: Backport-5.4, Backport-2024.1

#6999 fix(create role): fix role name in test_workload_types
  sla_per_user_system_test.py
Labels: Backport-2023.1, Backport-5.4, Backport-2024.1

#6997 fix(disrupt_add_drop_column): to not pick audit tables
  sdcm/nemesis.py
Labels: Backport-5.4, Backport-2024.1

#6923 fix(run_cqlsh): stop specifying host and port on call to cqlsh
  sdcm/cluster.py
Labels: test-provision-docker, Backport-5.4, Backport-2024.1

#7003 fix(disrupt_add_remove_dc): mark as disruptive=True
  sdcm/nemesis.py
Labels: Backport-5.4, Backport-2024.1

#7000 fix(modify_table_speculative_retry): Set to reasonable numbers
  sdcm/nemesis.py
Labels: Backport-5.4, Backport-2024.1

#6998 fix(KMS_encryption_check): make the node used as `running_nemesis`
  sdcm/cluster.py
  sdcm/utils/context_managers.py
Labels: Backport-5.4, Backport-2024.1

#7002 gpg: add the 2024 pub key
  defaults/test_default.yaml
  docs/configuration_options.md
  test-cases/artifacts/debian10.yaml
  test-cases/artifacts/debian11.yaml
  test-cases/artifacts/ubuntu2004.yaml
Labels: No Backport Needed

#6996 feature(get_any_ks_cf_list): get more accurate data if table empty
  sdcm/cluster.py
Labels: Backport-5.4, Backport-2024.1

#7005 fix(nemesis): cycle the nememsis_list
  sdcm/nemesis.py
Labels: Backport-5.4, Backport-2024.1

#6955 fix(logging): remove any usage of rsyslog
  defaults/test_default.yaml
  sct.py
  sdcm/cluster.py
  sdcm/cluster_aws.py
  sdcm/localhost.py
  sdcm/provision/common/configuration_script.py
  sdcm/provision/common/utils.py
  sdcm/sct_config.py
  sdcm/test_config.py
  sdcm/tester.py
  sdcm/utils/rsyslog.py
  unit_tests/provisioner/conftest.py
Labels: test-provision, Backport-5.4, Backport-2024.1

#7009 fix(upgrade_test): Extend connection timeout for query session
  upgrade_test.py
Labels: Backport-5.4, Backport-2024.1

#7007 fix(scylla-dash-per-server-nemesis): make by instance,shard work
  data_dir/scylla-dash-per-server-nemesis.2019.1.json
  data_dir/scylla-dash-per-server-nemesis.2021.1.json
  data_dir/scylla-dash-per-server-nemesis.master.json
  data_dir/scylla-dash-per-server-nemesis.master.patch
  data_dir/scylla-dash-timeout-metrics.json
  data_dir/scylla-data-source.json
  data_dir/scylla.repo
  data_dir/scylla.repo.downgrade
  data_dir/scylla.repo.upgrade
Labels: test-provision-aws

#7011 fix(longevity-mv-si-4days.yaml): enlarge runner disk
  test-cases/longevity/longevity-mv-si-4days.yaml
Labels: Backport-5.4, Backport-2024.1

#7004 fix(NodeBootstrapAbortManager): use correct timeouts for operations
  sdcm/nemesis.py
  sdcm/utils/raft/common.py
Labels: Ready for review, Backport-5.4, Backport-2024.1

#7006 feature(start_scylla_server): add adaptive timeout
  sdcm/cluster.py
  sdcm/utils/adaptive_timeouts/__init__.py
Labels: test-provision-aws, Backport-5.4, Backport-2024.1

#7013 fix(docker): copy cqlshrc as needed
  docker/scylla-sct/ubuntu/Dockerfile
Labels: test-provision-docker, Backport-5.4, Backport-2024.1

#7017 fix(longevity-fips): Set the longevity to run non-disruptive nemesis
  configurations/longevity-fips-and-encryptions.yaml
Labels: Backport-2023.1, Backport-2024.1

#7018 revert(instance type): use i3 type in SLA feature test
  test-cases/features/system-sla-test.yaml
Labels: Backport-5.4, Backport-2024.1

#7020 feature(restart_scylla_server): add adaptive timeout
  sdcm/cluster.py
  sdcm/cluster_docker.py
  sdcm/cluster_k8s/__init__.py
  sdcm/utils/adaptive_timeouts/__init__.py
Labels: Backport-5.4, Backport-2024.1

#7023 fix(longevity-large-partitions): disable nemesis during prepare
  test-cases/longevity/longevity-large-partition-3h.yaml
  test-cases/longevity/longevity-large-partition-8h.yaml
Labels: Backport-5.4, Backport-2024.1

#7022 fix(longevity-2TB-48h-*-ssl-1dis-2nondis): strong sct runner
  test-cases/longevity/longevity-2TB-48h-authorization-and-tls-ssl-1dis-2nondis-nemesis.yaml
Labels: Backport-5.4, Backport-2024.1

#7039 fix(preview_instance.yaml): Fix typo in file name
  jenkins-pipelines/artifacts-ubuntu2204-gcp-preview.jenkinsfile
Labels: Backport-5.4, Backport-2024.1

#7034 fix(featrues-testcases): disable manager on too small monitor nodes
  query_limits_test.py
  sdcm/sct_runner.py
  test-cases/features/compaction-throughput-limit.yaml
  test-cases/features/enospc-30mins.yaml
  test-cases/features/per-partition-limit.yaml
Labels: Backport-5.4, Backport-2024.1
