Repository scylladb/scylla-cluster-tests, pull requests merged in 2024-11, with the labels that each got.

#9005 refactor(SCHEMA_FAILURE): Change default severity of SCHEMA_FAILURE
  sdcm/sct_events/database.py
  unit_tests/test_cluster.py
  unit_tests/test_data/system.log
Labels: backport/2024.1, backport/2024.2, backport/6.1, backport/6.2

#9049 fix(advanced-rpc-compression): set up internode_compression_enable_advanced
  configurations/advanced-rpc-compression.yaml
  sdcm/provision/scylla_yaml/scylla_yaml.py
  unit_tests/test_scylla_yaml.py
Labels: backport/2024.2

#9136 improvement(scylla-bench): bump version to v0.1.24
  defaults/test_default.yaml
  docker/scylla-bench/README.md
  docs/configuration_options.md
Labels: Ready for review, backport/2024.1, backport/manager-3.3, backport/2024.2, backport/6.1, backport/6.2, backport/perf-v16

#9144 fix(unit-tests): add `2024.2` scylla version to list of base versions
  unit_tests/test_base_version.py
Labels: Ready for review, backport/2024.1, backport/perf-v15, backport/2024.2, backport/6.1, backport/6.2, backport/perf-v16

#9153 fix(_rotate_kms_key): remove SkipPerIssues since the ticket is resolved
  sdcm/cluster.py
Labels: backport/2023.1, backport/2024.1, backport/2024.2

#9137 test(large-partitions-1h): Introduce new short longevity with large partitions
  jenkins-pipelines/oss/longevity/longevity-large-partitions-with-network-nemesis-1h.jenkinsfile
  test-cases/longevity/longevity-large-partitions-with-network-nemesis-1h.yaml
Labels: backport/2024.1, backport/2024.2

#9154 fix(manager): fix awscli installation on Ubuntu24 nodes
  mgmt_cli_test.py
Labels: backport/none

#9163 fix(longevity): restore contents of "longevity-mv-si-4days.jenkinsfile"
  jenkins-pipelines/oss/longevity/longevity-mv-si-4days.jenkinsfile
Labels: backport/2024.2, backport/6.2, status/merge candidate, backport/perf-v16

#9164 fix(artifacts): retire amazon2
  configurations/arm/amazon2.yaml
  docs/artifacts_test.md
  jenkins-pipelines/oss/artifacts-offline-install/artifacts-amazon2-arm.jenkinsfile
  jenkins-pipelines/oss/artifacts-offline-install/artifacts-amazon2.jenkinsfile
  jenkins-pipelines/oss/artifacts/artifacts-amazon2-arm.jenkinsfile
  jenkins-pipelines/oss/artifacts/artifacts-amazon2.jenkinsfile
  sdcm/cluster.py
  sdcm/cluster_aws.py
  sdcm/utils/distro.py
  test-cases/artifacts/amazon2.yaml
  unit_tests/test_data/test_scylla_yaml_builders/artifact_amazon2.result.json
  unit_tests/test_data/test_scylla_yaml_builders/artifact_amazon2.yaml
  unit_tests/test_utils_distro.py
  utils/scylla_doctor.py
Labels: backport/none

#8788 feature(artifact_test): testing the output of perftune.py
  artifacts_test.py
  defaults/severities.yaml
  sdcm/cluster.py
  sdcm/sct_events/system.py
  sdcm/utils/perftune_validator.py
Labels: backport/2024.1, backport/2024.2, backport/6.2

#9070 docs(full-scan): Add a guide doc for using full-scan and full-partition-scan
  docs/using-full-scan-and-full-partition-scan-in-longevity.md
Labels: backport/none

#9179 fix(azure): fix log collector
  sdcm/logcollector.py
Labels: backport/2024.2, backport/6.2

#9188 fix(capacity_reservation): use it when adding nodes in runtime
  sdcm/cluster_aws.py
Labels: backport/perf-v15, backport/perf-v16

#5368 feature(list_resources): list resources per backend
  sct.py
Labels: backport/none

#9196 fix(rolling-upgrades): remove procedure for downgrade cqlsh
  upgrade_test.py
Labels: backport/2024.2, backport/6.1, backport/6.2

#9195 fix(manager): fix upgrade flow to use apt install instead dist-upgrade
  sdcm/cluster.py
Labels: backport/none

#9205 fix(add_remove_dc): Use correct method to get cluster status
  sdcm/nemesis.py
Labels: Ready for review, backport/6.2

#9203 improvement(stress_thread): HDR file collection
  defaults/severities.yaml
  sdcm/sct_events/loaders.py
  sdcm/stress_thread.py
Labels: backport/perf-v16

#9208 fix(tests): fix integration tests
  sdcm/stress/latte_thread.py
  unit_tests/test_config_get_version_based_on_conf.py
Labels: test-integration, backport/2024.1, backport/2024.2, backport/6.1, backport/6.2, backport/perf-v16

#9192 fix(artifact-centos9-arm): change fixed AMI to resolve by owner
  configurations/arm/centos9.yaml
Labels: backport/2024.2, backport/6.2

#9217 fix(requirements.in): update to `paramiko==3.5.0`
  docker/env/version
  requirements.in
  requirements.txt
Labels: backport/perf-v15, backport/2024.2, backport/6.2, backport/perf-v16

#9231 fix(artifacts): fixes around amazon 2 support removel
  sdcm/cluster.py
  utils/scylla_doctor.py
Labels: backport/none

#9236 fix(manager): up manager default version to the latest released 3.4
  defaults/test_default.yaml
Labels: backport/2024.1, backport/2024.2, backport/6.2, backport/perf-v16

#9233 fix(test_parallelobject): replace `self.assertAlmostEqual` with `pytest.approx`
  unit_tests/test_parallelobject.py
Labels: backport/none

#9232 build(deps): bump mysql-connector-python from 8.0.26 to 9.1.0
  docker/env/version
  requirements.in
  requirements.txt
Labels: New Hydra Version, dependencies, backport/perf-v15, backport/2024.2, backport/6.2, backport/perf-v16

#9221 improvement(azure): add instance state debug log after provision
  sdcm/provision/azure/virtual_machine_provider.py
  unit_tests/provisioner/fake_azure_service.py
Labels: backport/2024.1, backport/2024.2, backport/6.1, backport/6.2

#9197 fix(raft): generator was not correctly implemented in check_group0_to_kenring_consistency
  sdcm/utils/raft/__init__.py
Labels: backport/2024.1, backport/2024.2, backport/6.1, backport/6.2

#9235 fix(stress-threads): kill only labeled docker containers on loaders
  sdcm/cluster.py
  sdcm/utils/docker_remote.py
Labels: backport/none, test-provision-docker

#9180 refactor(instance_provision_fallback): Change default to true in AWS
  defaults/aws_config.yaml
  vars/longevityPipeline.groovy
Labels: backport/2024.2

#9260 ci(latte): bump latte version to `0.28.1-scylladb`
  defaults/test_default.yaml
  docker/latte/README.md
Labels: backport/2024.1, backport/2024.2, backport/6.1, backport/6.2

#9288 Revert "fix(FullScan): rename forward_service to mapreduce_service"
  sdcm/scan_operation_thread.py
  unit_tests/test_scan_operation_thread.py
Labels: backport/none

#9280 fix(perfRegressionParallelPipeline): add correct support for multidc
  vars/perfRegressionParallelPipeline.groovy
Labels: backport/none

#9282 improvement(gradual): run test-write with real loader
  jenkins-pipelines/performance/branch-perf-v16/scylla-enterprise/perf-regression/scylla-enterprise-perf-regression-predefined-throughput-steps-tablets.jenkinsfile
  jenkins-pipelines/performance/branch-perf-v16/scylla-enterprise/perf-regression/scylla-enterprise-perf-regression-predefined-throughput-steps-vnodes.jenkinsfile
  jenkins-pipelines/performance/branch-perf-v16/scylla-enterprise/perf-regression/scylla-enterprise-perf-regression-predefined-throughput-steps-write-tablets.jenkinsfile
  jenkins-pipelines/performance/branch-perf-v16/scylla-enterprise/perf-regression/scylla-enterprise-perf-regression-predefined-throughput-steps-write-vnodes.jenkinsfile
Labels: backport/perf-v16

#9297 fix(tests): make version unit tests work after release of the Scylla 2024.2
  unit_tests/test_base_version.py
Labels: backport/2024.1, backport/2024.2, backport/6.1, backport/6.2, backport/perf-v16

#9315 fix(dependabot): fix the python version to use in dependabot
  .python-version
Labels: backport/none

#9285 fix(capacity-reservation): disable for multi-dc
  sdcm/provision/aws/capacity_reservation.py
Labels: backport/perf-v15, backport/2024.2, backport/6.2, backport/perf-v16

#9316 fix(setup): stabilise manager repo file download
  sdcm/cluster.py
Labels: test-provision-aws, backport/perf-v15, backport/2024.2, backport/6.2, backport/perf-v16

#8803 fix(offline-artifact-tests): use the correct nodetool script
  sdcm/cluster.py
Labels: backport/6.2

#9339 improvement(docs): actualize docs for SCT config options
  docs/configuration_options.md
Labels: backport/none, Ready for review

#9343 fix(setup): remove `--retry-all-errors` from manager repo file download
  sdcm/cluster.py
Labels: test-provision-aws, test-provision-gce, backport/perf-v15, backport/2024.2, backport/6.2, backport/perf-v16

#9189 fix(SLA): adjust SLA resources verification
  sdcm/db_stats.py
  sdcm/sla/libs/sla_utils.py
  sdcm/sla/sla_tests.py
  unit_tests/test_sla_utils.py
Labels: Ready for review, backport/2024.2

#9332 fix(gce-backend): replace GCP instance types n1 with n2
  configurations/nemesis/longevity-5gb-1h-nemesis.yaml
  defaults/gce_config.yaml
  defaults/k8s_gke_config.yaml
  internal_test_data/complex_test_case_with_version.yaml
  sdcm/cluster_gce.py
  sdcm/cluster_k8s/gke.py
  sdcm/utils/gce_utils.py
  templates/test_config/template-longevity-5gb-1h-base.yaml.j2
  test-cases/artifacts/centos7.yaml
  test-cases/artifacts/centos9-selinux.yaml
  test-cases/artifacts/centos9.yaml
  test-cases/artifacts/debian11.yaml
  test-cases/artifacts/debian12.yaml
  test-cases/artifacts/gce-image-persistent-disk.yaml
  test-cases/artifacts/gce-image.yaml
  test-cases/artifacts/rhel7.yaml
  test-cases/artifacts/rhel8.yaml
  test-cases/artifacts/rocky8.yaml
  test-cases/artifacts/rocky9-selinux.yaml
  test-cases/artifacts/rocky9.yaml
  test-cases/artifacts/ubuntu2004.yaml
  test-cases/artifacts/ubuntu2204.yaml
  test-cases/artifacts/ubuntu2404.yaml
  test-cases/jepsen/jepsen.yaml
  test-cases/jepsen/jepsen_with_raft.yaml
  test-cases/longevity/longevity-nosqlbench-3h.yaml
  test-cases/manager/manager-backup-1TB-gce.yaml
  test-cases/nemesis/longevity-5gb-1h-EndOfQuotaNemesis.yaml
  test-cases/scylla-operator/longevity-scylla-operator-3h-nodetool-flush-and-reshard.yaml
  test-cases/scylla-operator/longevity-scylla-operator-basic-12h.yaml
  test-cases/scylla-operator/longevity-scylla-operator-multidc-12h.yaml
  test-cases/scylla-operator/longevity-scylla-operator-multidc-3h.yaml
  test-cases/upgrades/customer-profile/rolling-upgrade-custom-d1.yaml
  unit_tests/test_data/test_scylla_yaml_builders/jepsen.yaml
  unit_tests/test_data/test_scylla_yaml_builders/longevity-10gb-3h.yaml
  unit_tests/test_data/test_scylla_yaml_builders/manager-backup-1TB-gce.yaml
  unit_tests/test_data/test_scylla_yaml_builders/multi_network_interfaces/longevity-10gb-3h.yaml
Labels: backport/none

#9331 fix(docker-backend): do not start scylla-manager installation
  sdcm/sct_config.py
  unit_tests/test_config.py
  unit_tests/test_config_get_version_based_on_conf.py
Labels: backport/none

#9342 fix(nemesis): skip truncate large partition nemesis with zero node
  sdcm/nemesis.py
  test-cases/longevity/longevity-multi-dc-rack-aware-with-znode-in-diff_dc.yaml
Labels: backport/2024.2, backport/6.2

#9367 fix(docker-artifacts-test): add missing `,` between params
  jenkins-pipelines/oss/artifacts/artifacts-docker.jenkinsfile
Labels: backport/none

#9345 fix(test_user_batch_custom_time): handle stress command correctly
  Jenkinsfile
  longevity_test.py
  unit_tests/test_cluster.py
  unit_tests/test_longevity.py
  unit_tests/test_utils_common.py
Labels: backport/2024.2, backport/6.2

#9298 Make `test_restore_benchmark` results comparable
  mgmt_cli_test.py
Labels: backport/none

#9373 fix(sct_config): remove special characters from `user_perfix`
  sdcm/sct_config.py
Labels: backport/2024.1, backport/perf-v15, backport/2024.2, backport/6.1, backport/6.2, backport/perf-v16

#9307 Add backup benchmarking under read stress
  configurations/manager/100GB_dataset.yaml
  mgmt_cli_test.py
  sdcm/argus_results.py
  sdcm/mgmt/cli.py
Labels: backport/none

#9369 improvement(upgrade-test): upgrade node system early in the test
  defaults/test_default.yaml
  docs/configuration_options.md
  sdcm/sct_config.py
  upgrade_test.py
Labels: backport/none

#9329 improvement(logcollector): collect schema info
  sdcm/cluster.py
  sdcm/logcollector.py
  sdcm/tester.py
  unit_tests/test_tester.py
Labels: backport/2024.1, backport/perf-v15, backport/2024.2, backport/6.2, backport/perf-v16

#9352 fix(upgrade_test): ignore topology change coordinator errors during upgrades
  sdcm/sct_events/group_common_events.py
  unit_tests/test_cluster.py
  upgrade_test.py
Labels: backport/2024.2, backport/6.1, backport/6.2

#9340 fix(raft): drop stale log pattern as trigger for interrupting decommission
  sdcm/utils/raft/__init__.py
Labels: backport/2023.1, backport/2024.1, backport/6.0, backport/2024.2, backport/6.1, backport/6.2

#9372 fix(sstables_upload): skip large sstables upload
  sdcm/logcollector.py
  sdcm/utils/s3_remote_uploader.py
Labels: backport/perf-v15, backport/2024.2, backport/6.2, backport/perf-v16
