Repository scylladb/scylla-cluster-tests, pull requests merged in 2024-07, with the labels that each got.

#7775 fix(jepsen): hack tcpdump to work as jepsen needs
  jepsen_test.py
Labels: backport/none

#7787 fix(hot_reloading): pass correct patterns to `follow_system_log`
  sdcm/nemesis.py
Labels: backport/2023.1, backport/5.4, backport/2024.1, backport/6.0, backport/2024.2

#7806 fix(tester): reduce noise in the logs if there is no gemini_results attribute
  sdcm/tester.py
Labels: backport/2023.1, backport/5.4, backport/2024.1, backport/6.0, backport/manager-3.3, backport/2024.2

#7763 fix(hydra-ssh): tunnel shouldn't pick bastions with other keys
  sct_ssh.py
  sdcm/utils/common.py
Labels: backport/6.0

#7816 fix(loader): update loader ami with tablet aware driver
  defaults/aws_config.yaml
Labels: backport/6.0, backport/2024.2

#7799 feature(perf-tests): disable tablets by default
  jenkins-pipelines/performance/Perf-Regression/scylla-release-perf-regression-latency-shard-aware-1TB.jenkinsfile
  jenkins-pipelines/performance/Perf-Regression/scylla-release-perf-regression-throughput-non-shard-aware.jenkinsfile
  jenkins-pipelines/performance/Perf-Regression/scylla-release-perf-regression-throughput-shard-aware.jenkinsfile
  jenkins-pipelines/performance/scylla-enterprise/perf-regression-throughput-shard-aware-gce-z3-enterprise.jenkinsfile
  jenkins-pipelines/performance/scylla-enterprise/scylla-enterprise-perf-regression-latency-650gb-during-rolling-upgrade.jenkinsfile
  jenkins-pipelines/performance/scylla-enterprise/scylla-enterprise-perf-regression-latency-650gb-grow-shrink.jenkinsfile
  jenkins-pipelines/performance/scylla-enterprise/scylla-enterprise-perf-regression-latency-650gb-with-nemesis.jenkinsfile
  jenkins-pipelines/performance/scylla-enterprise/scylla-enterprise-perf-regression-latency-shard-aware-1TB.jenkinsfile
  jenkins-pipelines/performance/scylla-enterprise/scylla-enterprise-perf-regression-throughput-non-shard-aware-i4i.jenkinsfile
  jenkins-pipelines/performance/scylla-master/scylla-master-perf-regression-latency-650gb-during-rolling-upgrade.jenkinsfile
  jenkins-pipelines/performance/scylla-master/scylla-master-perf-regression-latency-650gb-grow-shrink.jenkinsfile
  jenkins-pipelines/performance/scylla-master/scylla-master-perf-regression-latency-650gb-with-nemesis.jenkinsfile
  jenkins-pipelines/performance/scylla-master/scylla-master-perf-regression-latency-shard-aware-1TB.jenkinsfile
  jenkins-pipelines/performance/scylla-master/scylla-master-perf-regression-throughput-non-shard-aware-i4i.jenkinsfile
Labels: backport/perf-v14

#7815 fix(manager): add links to .list/.repo files for release 3.3
  defaults/manager_versions.yaml
Labels: backport/manager-3.3

#7756 fix(nemesis): `hot_reloading_internode_certificate` to update correct certs
  sdcm/cluster.py
  sdcm/nemesis.py
  sdcm/provision/helpers/certificate.py
Labels: backport/none

#7779 Manager add stress read cmd into ipv6 config file
  test-cases/manager/manager-regression-ipv6.yaml
Labels: backport/manager-3.3

#7832 fix(perf-simple-query): fix results table
  sdcm/utils/microbenchmarking/perf_simple_query_reporter.py
Labels: backport/perf-v14

#7839 ci(latte): bump latte version to `0.26.1-scylladb`
  defaults/test_default.yaml
  docker/latte/README.md
  docs/configuration_options.md
  unit_tests/test_config.py
Labels: Ready for review, backport/6.0, backport/2024.2

#7827 fix(parallel-operations): disable when force gossip
  configurations/force-gossip-topology-changes.yaml
  sdcm/cluster.py
  sdcm/provision/scylla_yaml/scylla_yaml.py
  unit_tests/test_scylla_yaml.py
Labels: backport/6.0, backport/2024.2

#7847 fix(nemesis): parallel cleanups in all nemesis using cleanups
  sdcm/nemesis.py
Labels: backport/2023.1, backport/5.4, backport/2024.1

#7822 fix(artifacts-test): make creation of CA and Java truststore idempotent
  mgmt_cli_test.py
  sdcm/cluster.py
  sdcm/provision/helpers/certificate.py
  sdcm/tester.py
  unit_tests/conftest.py
  unit_tests/test_tester.py
Labels: backport/none, test-integration

#7862 fix(email): send email for failed tests
  sct.py
Labels: backport/perf-v14, backport/6.0, backport/perf-v15, backport/2024.2

#7859 feature(ruff): check for `unused-import (F401)`
  pyproject.toml
  sdcm/cluster_baremetal.py
  sdcm/cluster_k8s/__init__.py
  sdcm/fill_db_data.py
  sdcm/mgmt/__init__.py
  sdcm/provision/scylla_yaml/__init__.py
  sdcm/sct_provision/__init__.py
  sdcm/utils/alternator/__init__.py
  sdcm/utils/cdc/__init__.py
  sdcm/utils/cloud_monitor/__init__.py
  sdcm/utils/k8s/__init__.py
  sdcm/utils/raft/__init__.py
  unit_tests/lib/alternator_utils.py
  unit_tests/test_nemesis.py
  unit_tests/test_version_utils.py
Labels: test-provision-aws, test-provision-docker, test-integration, backport/6.0, backport/2024.2

#7853 fix(perf-pipeline): handle can of GCP_PROJECT isn't defined
  vars/perfRegressionParallelPipeline.groovy
  vars/perfSearchBestConfigParallelPipeline.groovy
Labels: backport/perf-v15

#7864 feature(perf-test): add option for `perf_extra_jobs_to_compare`
  sct.py
  sdcm/results_analyze/__init__.py
  sdcm/sct_config.py
  sdcm/tester.py
  sdcm/utils/es_queries.py
  vars/perfRegressionParallelPipeline.groovy
Labels: backport/perf-v15

#7879 fix(nemeses): disable `toggle_table` nemeses due to expected issue
  sdcm/nemesis.py
Labels: backport/2023.1, backport/2024.1, backport/2024.2

#7886 fix(Jenkinsfile): integration and provision test should run regardless
  Jenkinsfile
Labels: test-provision-docker, test-integration, backport/2023.1, backport/5.4, backport/2024.1, backport/6.0, backport/2024.2

#7896 fix(wait-port-down): case for abrupt scylla kill
  sdcm/cluster.py
  sdcm/utils/common.py
Labels: backport/2023.1, backport/5.4, backport/2024.1, backport/6.0, backport/2024.2

#7908 fix(upgrades): stop using centos-7 as basis image
  jenkins-pipelines/rolling-upgrade-alternator.jenkinsfile
  jenkins-pipelines/rolling-upgrade-centos7.jenkinsfile
Labels: backport/2023.1

#7910 feature(kms): sct configuration to disable kms
  defaults/test_default.yaml
  sdcm/sct_config.py
  sdcm/tester.py
Labels: backport/2023.1, backport/5.4, backport/2024.1, backport/6.0, backport/2024.2

#7927 fix(decommission): increase timeout
  sdcm/nemesis.py
Labels: backport/6.0, backport/perf-v15, backport/2024.2

#7926 improvement(open_system_log): added debug line
  sdcm/cluster.py
Labels: backport/6.0, backport/2024.2

#7922 improvement(byo): make CI jobs fail fast if BYO fails
  vars/longevityPipeline.groovy
Labels: Ready for review, backport/5.4, backport/2024.1, backport/6.0, backport/2024.2

#7807 improvement(sdcm/tester.py): Add TEST_ERROR Argus status support
  sdcm/tester.py
Labels: backport/5.4, backport/2024.1, backport/6.0, backport/2024.2

#7955 ci(perf): add BYO ScyllaDB support for the perf pipeline
  vars/perfRegressionParallelPipeline.groovy
Labels: Ready for review, backport/5.4, backport/2024.1, backport/6.0, backport/perf-v15, backport/2024.2

#7943 improvement(nemesis): ignore raft transport error
  sdcm/sct_events/group_common_events.py
  sdcm/utils/raft/common.py
Labels: backport/2023.1, backport/5.4, backport/2024.1, backport/6.0, backport/2024.2

#7911 fix(byo): make BYO ScyllaDB work with multidc setups
  vars/byoScylladb.groovy
Labels: Ready for review, backport/5.4, backport/2024.1, backport/6.0, backport/2024.2

#7957 improvement(pylint): disable f-string-interpolation error
  pylintrc
Labels: backport/2023.1, backport/5.4, backport/2024.1, backport/perf-v15

#7994 fix(pylint): disable logging not lazy check
  pylintrc
Labels: backport/2023.1, backport/5.4, backport/2024.1, backport/perf-v15

#7983 fix(perf-tests): fix names and triggers of jobs
  jenkins-pipelines/performance/branch-perf-v15/Perf-Regression/scylla-release-perf-regression-latency-shard-aware-1TB-test.jenkinsfile
  jenkins-pipelines/performance/branch-perf-v15/Perf-Regression/scylla-release-perf-regression-throughput-non-shard-aware-test.jenkinsfile
  jenkins-pipelines/performance/branch-perf-v15/Perf-Regression/scylla-release-perf-regression-throughput-shard-aware-test.jenkinsfile
  jenkins-pipelines/performance/branch-perf-v15/scylla-master/perf-regression/scylla-master-perf-regression-throughput-shard-aware-i4i.jenkinsfile
  jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-enterprise-performance-trigger.xml
  jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-master-performance-trigger.xml
  utils/build_system/create_test_release_jobs.py
Labels: backport/perf-v15

#7939 improvement(upgrade): make upgrade CI jobs fail fast if BYO fails
  vars/rollingUpgradePipeline.groovy
Labels: Ready for review, backport/5.4, backport/2024.1, backport/6.0, backport/2024.2

#7830 test(elasticity): grow-shrink cluster perf test with doubling load
  configurations/performance/cassandra-stress-650gb-8-col-i4i-80-percent-throughput-ent.yaml
  configurations/performance/cassandra-stress-650gb-8-col-i4i-80-percent-throughput-oss.yaml
  configurations/performance/cql-stress-650gb-8-col-i4i-80-percent-throughput-ent.yaml
  configurations/performance/cql-stress-650gb-8-col-i4i-80-percent-throughput-oss.yaml
  defaults/test_default.yaml
  jenkins-pipelines/performance_staging/scylla-master-perf-regression-latency-650gb-elasticity.jenkinsfile
  performance_regression_test.py
  sdcm/cql_stress_cassandra_stress_thread.py
  sdcm/nemesis.py
  sdcm/sct_config.py
  sdcm/tester.py
  test-cases/performance/perf-regression-latency-650gb-elasticity.yaml
Labels: backport/6.0, backport/perf-v15, backport/2024.2

#8011 fix(et_supported_scylla_base_versions): make upgrade work for minor version
  unit_tests/test_base_version.py
  utils/get_supported_scylla_base_versions.py
Labels: backport/5.4, backport/2024.1, backport/6.0, backport/2024.2

#8023 fix(azure): remove the usage of `build-id` from filtering images
  sdcm/provision/azure/utils.py
Labels: backport/5.4, backport/2024.1, backport/6.0, backport/2024.2

#8041 fix(kms): disable enterprise file stream
  sdcm/tester.py
Labels: backport/2024.1, backport/2024.2

#8047 fix(perf-jobs): correct `perf_extra_jobs_to_compare` for ops jobs
  jenkins-pipelines/performance/branch-perf-v15/scylla-enterprise/perf-regression/scylla-enterprise-perf-regression-latency-650gb-grow-shrink.jenkinsfile
  jenkins-pipelines/performance/branch-perf-v15/scylla-enterprise/perf-regression/scylla-enterprise-perf-regression-latency-650gb-with-nemesis.jenkinsfile
  jenkins-pipelines/performance/branch-perf-v15/scylla-master/perf-regression/scylla-master-perf-regression-latency-650gb-grow-shrink.jenkinsfile
  jenkins-pipelines/performance/branch-perf-v15/scylla-master/perf-regression/scylla-master-perf-regression-latency-650gb-with-nemesis.jenkinsfile
Labels: backport/perf-v15

#8024 feature(perf-tests): change histogram max bar for P90/P99
  sdcm/report_templates/results_latency_during_ops_short.html
  sdcm/utils/latency.py
Labels: backport/perf-v15

#7942 defaults/test_default.yaml: update Manager default to use 3.3.0
  defaults/test_default.yaml
Labels: test-provision, backport/5.4, backport/2024.1, backport/6.0, backport/2024.2

#8059 fix(createTestJobPipeline): uncomment closing of an if
  vars/createTestJobPipeline.groovy
Labels: backport/perf-v15

#8061 fix(create_test_release_jobs): copy over actions/properties
  utils/build_system/create_test_release_jobs.py
Labels: backport/perf-v15

#8067 feature(mergify): add support for branch-6.1
  .github/mergify.yml
Labels: backport/none

#8066 fix(certificates): don't include empty dns/ip into extensions
  sdcm/provision/helpers/certificate.py
Labels: test-provision-aws, backport/2024.2, backport/6.1

#7692 fix(update_db_packages): fix issues with hanging threads during update
  sdcm/cluster.py
Labels: backport/5.4, backport/2024.1, backport/6.0, backport/2024.2, backport/6.1

#8085 fix(sdcm/reporting/tooling_reporting): Add exception handler for Argus
  sdcm/reporting/tooling_reporter.py
Labels: backport/2023.1, backport/5.4, backport/2024.1, backport/6.0, backport/perf-v15, backport/2024.2, backport/6.1

#8093 fix(sdcm/reporting): ruff ignore broad exception
  sdcm/reporting/tooling_reporter.py
Labels: backport/2023.1, backport/5.4, backport/2024.1, backport/6.0, backport/perf-v15, backport/2024.2, backport/6.1

#8084 ci(byo): use defaults specific to branch-6.1
  vars/byoScylladb.groovy
  vars/longevityPipeline.groovy
  vars/perfRegressionParallelPipeline.groovy
  vars/rollingUpgradePipeline.groovy
Labels: backport/none, Ready for review

#8053 feature(aws): introduce way to find images by owners
  sdcm/utils/aws_utils.py
  sdcm/utils/common.py
  unit_tests/test_config.py
Labels: backport/none, test-integration

#8102 feature(triggers): add rolling upgrade trigger
  jenkins-pipelines/master-triggers/sct_triggers/weekly-master-rolling-upgrades-trigger.xml
Labels: backport/none

#8054 improvement(cleanup): job for cleanup test resources
  jenkins-pipelines/qa/hydra-clean-test-resources.jenkinsfile
Labels: backport/none

#8109 feature(grow-shrink): option to set the instance type for grow-shrink
  sdcm/nemesis.py
  sdcm/sct_config.py
  sdcm/utils/aws_utils.py
  sdcm/utils/azure_utils.py
  sdcm/utils/gce_utils.py
  unit_tests/test_config.py
Labels: backport/none

#8119 fix(.github/search_commit.py): backport pattern for perf branches
  .github/search_commits.py
Labels: backport/perf-v15

#8116 fix(cqlshrc): safely update cqlshrc
  sdcm/provision/scylla_yaml/certificate_builder.py
Labels: backport/2024.2, backport/6.1

#8111 fix(logcollector): do not fail the whole log collection phase on a failure of one collector
  sdcm/logcollector.py
Labels: backport/2023.1, backport/5.4, backport/2024.1, backport/6.0, backport/manager-3.3, backport/2024.2, backport/6.1

#8110 fix(upgrade-tests): skip counter test if tablets enabled
  sdcm/fill_db_data.py
Labels: backport/6.0, backport/2024.2, backport/6.1

#8112 feature(elasticsearch): move to using api key
  sdcm/es.py
  sdcm/keystore.py
  sdcm/nemesis_publisher.py
  sdcm/results_analyze/__init__.py
  sdcm/results_analyze/test.py
  utils/fix_es_mapping.py
  utils/migrate_nemesis_data.py
  utils/update_field.py
Labels: backport/2023.1, backport/5.4, backport/manager-3.2, backport/2024.1, backport/6.0, backport/perf-v15, backport/manager-3.3, backport/2024.2, backport/6.1

#8134 fix(hydra-tunnel): wait for connectivity
  sct_ssh.py
Labels: backport/2024.2, backport/6.1

#8147 improvement(documentation): config AWS locally
  README.md
Labels: backport/none

#8152 fix(aws): adapt metadata query to IMDSv2
  sdcm/cluster_aws.py
  sdcm/provision/aws/utils.py
Labels: test-provision-aws, backport/2023.1, backport/2024.1, backport/6.0, backport/2024.2, backport/6.1

#8158 fix(nemesis-tests-trigger): disable trigger
  jenkins-pipelines/master-triggers/sct_triggers/nightly-%(sct_branch)s-nemesis-tests-trigger.xml
Labels: backport/none

#8161 fix(artifacts_test): assert row isn't empty
  artifacts_test.py
Labels: backport/2024.2, backport/6.1

#8159 fix(fill_db_data): remove cache form properties
  sdcm/fill_db_data.py
Labels: backport/6.0, backport/2024.2, backport/6.1

#8149 fix(screenshots): report screenshots to argus from all tests
  cdc_replication_test.py
  gemini_test.py
  jepsen_test.py
  longevity_test.py
  performance_scale_up_test.py
  sct.py
  sdcm/cluster.py
  sdcm/db_stats.py
  sdcm/report_templates/results_base.html
  sdcm/report_templates/results_base_custom.html
  sdcm/report_templates/results_base_new.html
  sdcm/report_templates/results_performance_multi_baseline.html
  sdcm/report_templates/results_performance_multi_baseline_single_metric.html
  sdcm/results_analyze/__init__.py
  sdcm/results_analyze/test.py
  sdcm/send_email.py
  sdcm/tester.py
  sla_per_user_system_test.py
  upgrade_test.py
Labels: test-provision-aws, test-provision-docker, backport/perf-v15

#8173 fix(apt-keys): update the apt key for 2024
  defaults/test_default.yaml
  test-cases/artifacts/debian11.yaml
  test-cases/artifacts/ubuntu2004.yaml
Labels: backport/2023.1, backport/5.4, backport/2024.1, backport/6.0, backport/perf-v15, backport/manager-3.3

#8171 fix(alternator): create a role with "login" and "superuser" flags
  sdcm/tester.py
  unit_tests/test_ycsb_thread.py
Labels: backport/6.0, backport/2024.2, backport/6.1

#8160 fix(upgrade_test): add DEBIAN_FRONTEND=noninteractive to apt-get commands
  upgrade_test.py
Labels: backport/2024.2

#8185 fix(FullScan): rename forward_service to mapreduce_service
  sdcm/scan_operation_thread.py
  unit_tests/test_scan_operation_thread.py
Labels: backport/6.1

#8187 fix(hydra): don't running any python code outside hydra image
  docker/env/hydra.sh
  unit_tests/test_hydra_sh.py
Labels: backport/none, test-provision

#8190 fix(jmx): fix wait for jmx up
  sdcm/cluster.py
Labels: backport/2024.1, backport/6.0, backport/perf-v15, backport/2024.2, backport/6.1

#8207 test(tablets): new pipelines with disabled-tablets for unsupported features
  jenkins-pipelines/oss/no_tablets/longevity-cdc-100gb-4h-no-tablets.jenkinsfile
  jenkins-pipelines/oss/no_tablets/longevity-lwt-3h-no-tablets.jenkinsfile
Labels: backport/6.1

#8204 improvement(investigation): add test_method to config
  sct.py
  sdcm/sct_config.py
Labels: test-provision-aws, backport/2024.1, backport/6.0, backport/perf-v15, backport/2024.2, backport/6.1
