Repository scylladb/scylla-cluster-tests, pull requests merged in 2024-10, with the labels that each got.

#8890 fix(setup): add retrying to download sm repo file
  sdcm/cluster.py
Labels: backport/2024.1, backport/6.0, backport/perf-v15, backport/2024.2, backport/6.1, backport/6.2

#8889 fix(disrupt_snapshot_operations): filter out virtual tables as needed
  sdcm/cluster.py
  sdcm/nemesis.py
  unit_tests/test_cluster.py
Labels: backport/none, test-integration

#8884 fix(sct_events): ignore 'aborting on shard' events on rpc errors
  sdcm/sct_events/setup.py
Labels: backport/2024.1, backport/2024.2

#8856 improvement(latte): improve latte errors parsing
  sdcm/stress/latte_thread.py
Labels: Ready for review, backport/2024.1, backport/2024.2, backport/6.2

#8891 improvement(argus): disable argus for local runs
  sdcm/nemesis.py
  sdcm/test_config.py
Labels: backport/none

#8837 improvement(results): update Argus Client
  docker/env/version
  requirements.in
  requirements.txt
  sdcm/argus_results.py
Labels: New Hydra Version, backport/perf-v15, backport/manager-3.3, backport/2024.2, backport/6.1, backport/6.2

#8589 fix(artifacts): add rocky9-selinux
  jenkins-pipelines/oss/artifacts/artifacts-rocky9-selinux.jenkinsfile
  test-cases/artifacts/rocky9-selinux.yaml
Labels: backport/2024.2, backport/6.2

#8922 fix(test_workload_types): adjust workload comparison
  sla_per_user_system_test.py
Labels: backport/none, SLA

#8920 improvement(results): store cycle's 'start time'
  sdcm/argus_results.py
  sdcm/utils/decorators.py
  unit_tests/test_argus_results.py
  utils/migrate_latency_results_to_argus.py
Labels: backport/perf-v15, backport/2024.2, backport/6.1, backport/6.2, backport/perf-v16

#8947 fix(sla): explicit ServisLevel creation
  test_lib/sla.py
Labels: backport/none, SLA

#8952 improvement(reporting): Add argus links to email template and elastic
  sdcm/report_templates/results_base.html
  sdcm/reporting/elastic_reporter.py
Labels: backport/2023.1, backport/2024.1, backport/perf-v15, backport/2024.2, backport/6.1, backport/6.2, backport/perf-v16

#8921 improvement(monitoring): restore monitor with test time range
  sdcm/cluster.py
  sdcm/tester.py
  unit_tests/test_tester.py
Labels: backport/2024.1, backport/6.0, backport/2024.2, backport/6.1, backport/6.2

#6984 feature(cluster): remove apt-key refs
  sdcm/cluster.py
Labels: backport/2024.2, backport/6.1, backport/6.2

#8925 fix(nemesis): get bytes total for correct network device
  sdcm/cluster.py
  sdcm/cluster_aws.py
  sdcm/nemesis.py
  sdcm/provision/network_configuration.py
  unit_tests/test_scylla_yaml_builders.py
Labels: backport/2024.1, backport/2024.2, backport/6.1, backport/6.2

#8974 fix(gradual): run post_prepare_cql_cmds
  performance_regression_gradual_grow_throughput.py
Labels: backport/perf-v16

#8972 fix(manager): upload new backup snapshot for nemesis
  defaults/manager_persistent_snapshots.yaml
Labels: backport/2024.1, backport/2024.2

#8883 fix(multinetwork): remove second network interface configuration
  sdcm/provision/aws/configuration_script.py
  sdcm/provision/aws/utils.py
Labels: backport/2024.2, backport/6.1, backport/6.2

#8992 fix(gradual): run post_prepare_cql_cmds after prepare
  performance_regression_gradual_grow_throughput.py
Labels: backport/perf-v16

#8995 fix(tearown): fix set grafana time range when no monitors
  sdcm/cluster.py
Labels: backport/2024.1, backport/6.0, backport/2024.2, backport/6.1, backport/6.2

#8994 fix(gradulal): do not get compaction from default
  performance_regression_gradual_grow_throughput.py
Labels: backport/perf-v16

#8913 fix(manager): add --force-conf options to apt cmd for Manager upgrade
  sdcm/cluster.py
Labels: backport/manager-3.3

#9012 fix(util): fix skip_optional_stage logic
  sdcm/utils/common.py
Labels: backport/none

#9014 fix(test_workload_types): adjust workload comparison for 2024.2
  sla_per_user_system_test.py
Labels: SLA, backport/2024.2

#9004 feature(hydra on MacOS): Add support to run hydra on MacOS
  docker/env/hydra.sh
Labels: backport/none

#9003 improvement(sct.py/show-logs): Add --update-argus argument
  sct.py
Labels: backport/2024.1, backport/2024.2, backport/6.1, backport/6.2

#9029 fix(monitor): don't call monitor method when no monitors
  sdcm/tester.py
Labels: backport/2024.1, backport/6.0, backport/2024.2, backport/6.1, backport/6.2

#9026 fix(kms): set proper node regions in multi-dc setups
  sdcm/cluster.py
Labels: Ready for review, backport/manager-3.2, backport/2024.1, backport/manager-3.3, backport/2024.2, backport/6.1, backport/6.2

#9013 fix(SLA) fix 1to5 ratio test for 2024.3
  sla_per_user_system_test.py
  test-cases/features/system-sla-test.yaml
Labels: SLA, backport/2024.2

#8867 fix(RAFT) fix wrong raft.is_enabled usage
  sdcm/utils/health_checker.py
  sdcm/utils/raft/__init__.py
  sdcm/utils/tablets/common.py
Labels: backport/2023.1, backport/2024.1, backport/6.0, backport/2024.2, backport/6.1, backport/6.2

#9015 improvement(argus-client): ship argus client within sct
  .pre-commit-config.yaml
  argus/__init__.py
  argus/client/__init__.py
  argus/client/base.py
  argus/client/driver_matrix_tests/cli.py
  argus/client/driver_matrix_tests/client.py
  argus/client/generic/cli.py
  argus/client/generic/client.py
  argus/client/generic_result.py
  argus/client/sct/client.py
  argus/client/sct/types.py
  argus/client/sirenada/client.py
  argus/common/__init__.py
  argus/common/enums.py
  argus/common/sct_types.py
  argus/common/sirenada_types.py
  argus/how_to_update.md
  argus/version
  docker/env/version
  requirements.in
  requirements.txt
  sct.py
  sdcm/cluster.py
  sdcm/nemesis.py
  sdcm/tester.py
  utils/update_argus_client.py
Labels: backport/2023.1, backport/2024.1, backport/6.0, backport/perf-v15, backport/2024.2, backport/6.1, backport/6.2, backport/perf-v16

#8912 fix(cleanup): cleanup sct-runner when logs collected
  sdcm/sct_runner.py
Labels: backport/perf-v15, backport/2024.2, backport/6.2, backport/perf-v16

#9088 fix(nemesis): Remove incorrect definition of config_changes
  sdcm/nemesis.py
Labels: backport/none

#9086 ci(latte): bump latte version to `0.28.0-scylladb`
  defaults/test_default.yaml
  docker/latte/README.md
Labels: Ready for review, backport/2024.1, backport/2024.2, backport/6.1, backport/6.2

#9084 improvement(scylla-bench): bump version to `v0.1.23`
  defaults/test_default.yaml
  docker/scylla-bench/README.md
  docs/configuration_options.md
Labels: test-integration, backport/2024.1, backport/manager-3.3, backport/2024.2, backport/6.1, backport/6.2, backport/perf-v16

#8705 fix(full scan thread): Added missing fetch-next-page to fetch_result_pages
  sdcm/scan_operation_thread.py
Labels: Ready to be Merged, backport/2024.1, backport/6.0, backport/2024.2, backport/6.1

#9087 improvement(custom-d1-w2): use multi-row partitions
  test-cases/longevity/longevity-gce-custom-d1-workload2-hybrid-raid.yaml
Labels: Ready for review, backport/2024.1, backport/2024.2, backport/6.1, backport/6.2
