Repository scylladb/scylla-cluster-tests, pull requests merged in 2024-02, with the labels that each got.

#7178 fix(k8s-eks): make iamserviceaccount for s3 access be shorter
  sdcm/cluster_k8s/eks.py
Labels: No Backport Needed, Ready for review, scylla-operator

#7176 fix(commit log): add exceeding time gate
  sdcm/commit_log_check_thread.py
Labels: No Backport Needed

#7181 fix(cloud-report): fix Azure's instances state
  sdcm/utils/cloud_monitor/resources/instances.py
Labels: No Backport Needed

#7183 fix(alternator): skip YSCB `Connection refused` during restore nemesis
  sdcm/nemesis.py
Labels: Backport-2023.1, Backport-5.4, Backport-2024.1

#7185 improvement(upgrade): retry on count from truncated table
  upgrade_test.py
Labels: Backport-2023.1, Backport-5.4, Backport-2024.1

#7187 fix(gemini): Increase instance size and max retries
  test-cases/gemini/gemini-1tb-10h.yaml
  test-cases/gemini/gemini-3h-with-nemesis.yaml
  test-cases/gemini/gemini-3h-with-nondisruptive-nemesis.yaml
  test-cases/gemini/gemini-8h-large-num-columns.yaml
Labels: Backport-2023.1, Backport-5.4, Backport-2024.1

#7186 fix(log-tunnel): enable back log tunnelling
  sdcm/cluster.py
Labels: No Backport Needed

#7193 fix(pipelines): dereference all symlink
  jenkins-pipelines/oss/artifacts-offline-install/artifacts-amazon2-arm.jenkinsfile
  jenkins-pipelines/oss/artifacts-offline-install/artifacts-amazon2.jenkinsfile
  jenkins-pipelines/oss/artifacts-offline-install/artifacts-centos7.jenkinsfile
  jenkins-pipelines/oss/artifacts-offline-install/artifacts-centos8-arm.jenkinsfile
  jenkins-pipelines/oss/artifacts-offline-install/artifacts-centos8-selinux.jenkinsfile
  jenkins-pipelines/oss/artifacts-offline-install/artifacts-centos8.jenkinsfile
  jenkins-pipelines/oss/artifacts-offline-install/artifacts-debian10-arm.jenkinsfile
  jenkins-pipelines/oss/artifacts-offline-install/artifacts-debian10.jenkinsfile
  jenkins-pipelines/oss/artifacts-offline-install/artifacts-debian11.jenkinsfile
  jenkins-pipelines/oss/artifacts-offline-install/artifacts-oel76.jenkinsfile
  jenkins-pipelines/oss/artifacts-offline-install/artifacts-oel81.jenkinsfile
  jenkins-pipelines/oss/artifacts-offline-install/artifacts-rocky8.jenkinsfile
  jenkins-pipelines/oss/artifacts-offline-install/artifacts-rocky9.jenkinsfile
  jenkins-pipelines/oss/artifacts-offline-install/artifacts-ubuntu2004-arm.jenkinsfile
  jenkins-pipelines/oss/artifacts-offline-install/artifacts-ubuntu2004.jenkinsfile
  jenkins-pipelines/oss/artifacts-offline-install/artifacts-ubuntu2204-arm.jenkinsfile
  jenkins-pipelines/oss/artifacts-offline-install/artifacts-ubuntu2204.jenkinsfile
  jenkins-pipelines/performance/scylla-enterprise/scylla-enterprise-perf-regression-latency-650gb-during-rolling-upgrade.jenkinsfile
  jenkins-pipelines/performance/scylla-enterprise/scylla-enterprise-perf-regression-latency-650gb-grow-shrink.jenkinsfile
  jenkins-pipelines/performance/scylla-enterprise/scylla-enterprise-perf-regression-latency-650gb-with-nemesis.jenkinsfile
  jenkins-pipelines/performance/scylla-enterprise/scylla-enterprise-perf-regression-latency-shard-aware-1TB.jenkinsfile
  jenkins-pipelines/performance/scylla-enterprise/scylla-enterprise-perf-simple-query-weekly-microbenchmark.jenkinsfile
  jenkins-pipelines/performance/scylla-enterprise/scylla-enterprise-perf-simple-query-weekly-microbenchmark_x86_64.jenkinsfile
Labels: Urgent, Bug

#6950 sla_tests: use SL REST API instead of binary protocol on/off workaround
  sdcm/sla/sla_tests.py
Labels: No Backport Needed

#7192 fix(azure): find formal images in community gallary
  docker/env/version
  requirements.in
  requirements.txt
  sct.py
  sdcm/provision/azure/utils.py
  sdcm/provision/azure/virtual_machine_provider.py
  sdcm/sct_config.py
Labels: New Hydra Version, test-provision-azure, Backport-5.2, Backport-2023.1, Backport-5.4, Backport-2024.1

#7195 fix(create_test_release_jobs): reconfig_job shouldn't drop data
  utils/build_system/create_test_release_jobs.py
Labels: No Backport Needed, Urgent, Bug

#7197 fix(integration-tests): use latest OSS image
  sdcm/cluster.py
  unit_tests/conftest.py
  unit_tests/test_cluster.py
Labels: No Backport Needed, test-integration

#7202 fix(perf): destroy monitors after tests
  vars/perfRegressionParallelPipeline.groovy
Labels: Backport-perf-v14

#7201 feature(tablets): add trigger for one tablets case in weekly runs (branch-perf-v14)
  jenkins-pipelines/perf-regression-latency-650gb-grow-shrink-tablets.jenkinsfile
Labels: No Backport Needed

#7210 fix(cassandra-stress): use `hard_timeout` in `get_results()`
  sdcm/stress/base.py
  sdcm/stress_thread.py
Labels: test-provision-aws, Backport-2023.1, Backport-5.4, Backport-2024.1

#7206 fix(hydra): remove the `awscli` dependency
  docker/env/hydra.sh
  unit_tests/test_hydra_sh.py
Labels: test-provision-aws, test-provision-docker

#7214 Fix base trigger
  jenkins-pipelines/upgrade-with-raft/rolling-upgrade-centos8-with-raft.jenkinsfile
  jenkins-pipelines/upgrade-with-raft/rolling-upgrade-debian11-with-raft.jenkinsfile
  jenkins-pipelines/upgrade-with-raft/rolling-upgrade-ubuntu22.04-with-raft.jenkinsfile
Labels: No Backport Needed

#7212 fix(nemesis): disable end_of_quota nemesis
  sdcm/nemesis.py
Labels: Backport-2023.1, Backport-5.4, Backport-2024.1

#7216 fix(index/mv): enlarge timeout on creation of Indexes/MVs
  sdcm/tester.py
  sdcm/utils/nemesis_utils/indexes.py
Labels: Backport-2023.1, Backport-5.4, Backport-2024.1

#7215 fix(PageFetcher): wait for first page correctly
  sdcm/utils/common.py
Labels: test-provision-aws, Backport-2023.1, Backport-5.4, Backport-2024.1

#7222 fix(nemesis): `set_target_node` should first give up current target
  sdcm/nemesis.py
Labels: No Backport Needed

#7227 fix(disrupt_abort_repair): enable verbose for repair command
  sdcm/nemesis.py
Labels: Backport-2023.1, Backport-5.4, Backport-2024.1

#7233 fix(fetch_all_rows): handle default `timeout=None` correctly
  sdcm/utils/database_query_utils.py
  unit_tests/test_utils_database_query_utils.py
Labels: test-integration, Backport-2023.1, Backport-5.4, Backport-2024.1
