Repository scylladb/scylla-cluster-tests, pull requests merged in 2024-05, with the labels that each got.

#7389 improvement(distro): use ubuntu for loader and monitor nodes
  defaults/aws_config.yaml
  defaults/azure_config.yaml
  defaults/gce_config.yaml
  defaults/k8s_gke_config.yaml
  defaults/test_default.yaml
  sct_ssh.py
  sdcm/sct_config.py
  test-cases/manager/manager-backup-1TB-gce.yaml
  unit_tests/test_config.py
Labels: Ready for review

#7386 improvement(loader-latte): build small latte image
  defaults/test_default.yaml
  docker/latte/Dockerfile
  docker/latte/README.md
  unit_tests/test_config.py
Labels: Ready for review

#7296 improvement(custom_d1): use greatly improved latte+rune scripts
  jenkins-pipelines/oss/longevity/longevity-gce-custom-d1-worklod1-hybrid-raid.jenkinsfile
  sdcm/logcollector.py
  test-cases/longevity/longevity-gce-custom-d1-hybrid-raid.yaml
  test-cases/longevity/longevity-gce-custom-d1-workload1-hybrid-raid.yaml
Labels: Ready for review

#7400 fix(logging): improve logging for deleting placement groups
  sdcm/utils/common.py
Labels: Backport-perf-v14

#7394 improvement(distro): use ubuntu for loader and monitor nodes
  defaults/aws_config.yaml
  defaults/azure_config.yaml
  defaults/gce_config.yaml
  defaults/k8s_gke_config.yaml
  defaults/test_default.yaml
  sct_ssh.py
  sdcm/sct_config.py
  test-cases/manager/manager-backup-1TB-gce.yaml
  unit_tests/test_config.py
Labels: Ready for review

#7395 improvement(distro): use ubuntu for loader and monitor nodes
  defaults/aws_config.yaml
  defaults/azure_config.yaml
  defaults/gce_config.yaml
  defaults/k8s_gke_config.yaml
  defaults/test_default.yaml
  sdcm/sct_config.py
  test-cases/manager/manager-backup-1TB-gce.yaml
  unit_tests/test_config.py
Labels: Ready for review

#7194 test(scale-up): test write and rebuild perf
  configurations/scale-up/c3-standard-22-lssd.yaml
  configurations/scale-up/c3-standard-44-lssd.yaml
  configurations/scale-up/c3-standard-8-lssd.yaml
  configurations/scale-up/c3-standard-88-lssd.yaml
  configurations/scale-up/scale-up-base.yaml
  jenkins-pipelines/scale-up-c3-standard-lssd.jenkinsfile
  performance_scale_up_test.py
  sdcm/report_templates/results_scale_up.html
  sdcm/send_email.py
Labels: No Backport Needed

#7358 test(customd1): add `custom_d1/workload2` test
  jenkins-pipelines/oss/longevity/longevity-gce-custom-d1-worklod2-hybrid-raid.jenkinsfile
  sdcm/stress/latte_thread.py
  test-cases/longevity/longevity-gce-custom-d1-workload2-hybrid-raid.yaml
Labels: Ready for review

#7404 fix(cloud-init): make cloud init lock file kept across reboot
  sdcm/provision/user_data.py
  unit_tests/provisioner/test_provision_sct_resources.py
  unit_tests/provisioner/test_user_data_builder.py
Labels: Backport-2023.1, Backport-5.4, Backport-2024.1

#7289 feature(provision): enable capacity reservation for aws
  configurations/capacity_reservation.yaml
  defaults/test_default.yaml
  sdcm/cluster_aws.py
  sdcm/ec2_client.py
  sdcm/exceptions.py
  sdcm/provision/aws/capacity_reservation.py
  sdcm/provision/aws/provisioner.py
  sdcm/sct_config.py
  sdcm/sct_provision/aws/layout.py
  sdcm/tester.py
  sdcm/utils/common.py
  test-cases/performance/perf-regression-latency-1TB.yaml
  test-cases/performance/perf-regression-latency-650gb-with-nemesis.yaml
  test-cases/performance/perf-regression.100threads.30M-keys-i4i.yaml
  unit_tests/provisioner/test_capacity_reservation.py
Labels: Backport-perf-v14

#7412 fix(manager): wait after Scylla config change to let SM pick up the change
  mgmt_cli_test.py
  sdcm/cluster.py
Labels: Backport-manager-3.2

#7402 switch oracle cluster to i4i for gemini tests
  defaults/test_default.yaml
  test-cases/gemini/gemini-1tb-10h.yaml
  test-cases/gemini/gemini-3h-ics-cdc-with-nemesis.yaml
  test-cases/gemini/gemini-3h-ics-with-nondisruptive-nemesis.yaml
  test-cases/gemini/gemini-3h-with-nemesis.yaml
  test-cases/gemini/gemini-3h-with-nondisruptive-nemesis.yaml
  test-cases/gemini/gemini-basic-3h-ics.yaml
  test-cases/gemini/gemini-basic-3h.yaml
Labels: Backport-5.4, Backport-2024.1

#7421 fix(scylla doctor): read vitals file
  utils/scylla_doctor.py
Labels: No Backport Needed

#7196 improvement(bisection): add bisect decorator
  docs/bisecting-with-sct.md
  sdcm/sct_config.py
  sdcm/tester.py
  sdcm/utils/bisect_test.py
Labels: No Backport Needed

#7424 fix(scylla doctor): amazon2 tests
  utils/scylla_doctor.py
Labels: No Backport Needed

#7422 fix(alternator): use CREATE ROLE for `alternator_enforce_authorization`
  sdcm/tester.py
  sdcm/utils/alternator/api.py
  sdcm/ycsb_thread.py
Labels: Backport-2023.1, Backport-5.4, Backport-2024.1

#7431 fix(c-s): use 5.4.6 image for c-s
  defaults/test_default.yaml
Labels: No Backport Needed

#7365 fix(manager): upgrade Scylla version used in Manager to latest
  configurations/manager/debian10.yaml
  defaults/manager_versions.yaml
  defaults/test_default.yaml
  unit_tests/test_sdcm_mgmt_common.py
  vars/managerPipeline.groovy
Labels: Ready for review, Backport-manager-3.2

#7443 ci(manager): switch singleDC jobs to us-east-1 region
  configurations/manager/debian10.yaml
  configurations/manager/debian11.yaml
  configurations/manager/ubuntu20.yaml
  jenkins-pipelines/manager/debian10-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/debian11-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/ubuntu22-manager-sanity-ipv6.jenkinsfile
Labels: Backport-manager-3.2

#7414 fix(perf): fix display_single_result method
  performance_regression_test.py
Labels: Backport-perf-v14

#7455 fix(manager): update debian10 image used in tests
  configurations/manager/debian10.yaml
Labels: Ready for review, Backport-manager-3.2

#7433 improvement(sdcm/cluster): Store dc and rack information in argus
  docker/env/version
  requirements.in
  requirements.txt
  sdcm/cluster.py
Labels: New Hydra Version

#7449 fix(cluster): remove deprecated `system_init` property
  sdcm/cluster.py
  sdcm/cluster_docker.py
  sdcm/utils/remote_logger.py
  unit_tests/test_scylla_yaml_builders.py
Labels: No Backport Needed

#7460 fix(cluster): ipv6 address in network_interfaces object
  sdcm/cluster.py
  sdcm/cluster_aws.py
Labels: No Backport Needed

#7454 improvement(sct.py): Add junit argus client call
  sct.py
Labels: No Backport Needed

#7469 fix(managerPipeline): add provision stage to pipeline
  vars/managerPipeline.groovy
Labels: Backport-manager-3.2

#7445 improvement(speed): speed up wait db up
  sdcm/cluster.py
Labels: Backport-2023.1, Backport-5.4, Backport-2024.1

#7473 fix(sdcm/sct_config): Submit parsed scylla version to argus
  sdcm/sct_config.py
  sdcm/utils/version_utils.py
  unit_tests/test_version_utils.py
Labels: Backport-6.0

#7438 fix(logging): add hostname to RemoteCommandRunner output watcher
  sdcm/cluster.py
  sdcm/remote/base.py
Labels: No Backport Needed, test-provision-aws

#7489 fix(artifact-tests): retry housekeeping version checks
  artifacts_test.py
Labels: Backport-2023.1, Backport-5.4, Backport-2024.1, Backport-6.0

#7486 Revert "fix(nodetool): workaround wrong placement of cassandra-rackdc.properties"
  upgrade_test.py
Labels: Backport-2023.1, Backport-5.4, Backport-2024.1, Backport-6.0

#7488 feature(artifact-tests): introduce Amazon Linux 2023 tests
  configurations/arm/amazon2023.yaml
  jenkins-pipelines/oss/artifacts-offline-install/artifacts-amazon2023-arm.jenkinsfile
  jenkins-pipelines/oss/artifacts-offline-install/artifacts-amazon2023-nonroot.jenkinsfile
  jenkins-pipelines/oss/artifacts-offline-install/artifacts-amazon2023.jenkinsfile
  jenkins-pipelines/oss/artifacts/artifacts-amazon2023-arm.jenkinsfile
  jenkins-pipelines/oss/artifacts/artifacts-amazon2023.jenkinsfile
  sdcm/mgmt/common.py
  sdcm/utils/distro.py
  test-cases/artifacts/amazon2023.yaml
  unit_tests/test_utils_distro.py
Labels: Backport-6.0

#7482 fix(manager): add -y to utils gce packages installation cmd
  mgmt_cli_test.py
Labels: Ready for review, Backport-manager-3.2

#7463 improvement(speed-up): move syslogng-exporter install to cloud-init
  sdcm/cluster.py
  sdcm/node_exporter_setup.py
  sdcm/provision/common/configuration_script.py
  sdcm/provision/common/utils.py
  sdcm/sct_provision/region_definition_builder.py
  sdcm/sct_provision/user_data_objects/syslog_ng.py
Labels: Ready for review, test-provision-aws, test-provision-gce, test-provision-azure, Backport-6.0

#7479 fix(test_base_version): stop hardcoding the current latest branch
  unit_tests/test_base_version.py
Labels: Backport-2023.1, Backport-5.4, Backport-2024.1, Backport-6.0

#7498 fix(kafka-localstack): fix broken configuration file
  test-cases/kafka/longevity-kafka-cdc.yaml
Labels: No Backport Needed

#7501 fix(artifact-centos8-arm): update to lastet AMI
  configurations/arm/centos8.yaml
Labels: Backport-2023.1, Backport-5.4, Backport-2024.1, Backport-6.0

#7452 fix(group_common_events): filter expected raft_topology error messages
  sdcm/nemesis.py
  sdcm/sct_events/group_common_events.py
  sdcm/utils/raft/common.py
Labels: Ready for review, backport/6.0

#7411 refactor(longevity-large-partition-200k): Refactor stress commands
  test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml
Labels: backport/2023.1, backport/5.4, backport/2024.1, backport/6.0

#7505 fix(cloud-init): stabilise syslogng installation
  sdcm/provision/common/utils.py
Labels: test-provision-aws

#7506 fix(rolling_restart): Wait all nodes to be UN after each restart
  sdcm/cluster.py
  sdcm/nemesis.py
Labels: backport/6.0

#7499 fix(manager): fix google-cloud-cli package installation
  mgmt_cli_test.py
Labels: Ready for review, backport/manager-3.2

#7494 fix(teardown): stop sending email within SCT test
  configurations/scale-up/scale-up-base.yaml
  defaults/test_default.yaml
  sdcm/sct_config.py
  sdcm/tester.py
  test-cases/features/limit-streaming-io.yaml
  test-cases/performance/perf-regression-2mv.yaml
  test-cases/performance/perf-regression-alternator-latency-500gb-30min.yaml
  test-cases/performance/perf-regression-alternator.100threads.30M-keys.yaml
  test-cases/performance/perf-regression-gradual-throughput-grow.yaml
  test-cases/performance/perf-regression-latency-125gb.yaml
  test-cases/performance/perf-regression-latency-1TB.yaml
  test-cases/performance/perf-regression-latency-250gb-with-nemesis.yaml
  test-cases/performance/perf-regression-latency-500gb-30min.yaml
  test-cases/performance/perf-regression-latency-650gb-grow-shrink.yaml
  test-cases/performance/perf-regression-latency-650gb-upgrade.yaml
  test-cases/performance/perf-regression-latency-650gb-with-nemesis.yaml
  test-cases/performance/perf-regression-latency-cdc-mixed-poll-batching.yaml
  test-cases/performance/perf-regression-latency-k8s-multitenant.yaml
  test-cases/performance/perf-regression-latency-lwt-big.yaml
  test-cases/performance/perf-regression-latency-lwt-small.yaml
  test-cases/performance/perf-regression-throughput-125gb.yaml
  test-cases/performance/perf-regression-throughput-baremetal-5gb.yaml
  test-cases/performance/perf-regression-throughput-cdc-mixed-poll-batching.yaml
  test-cases/performance/perf-regression-throughput-lwt-big.yaml
  test-cases/performance/perf-regression-throughput-lwt-small.yaml
  test-cases/performance/perf-regression-write-latency-cdc.yaml
  test-cases/performance/perf-regression-write-throughput-cdc.yaml
  test-cases/performance/perf-regression.100threads.100M-keys-z3-enterprise.yaml
  test-cases/performance/perf-regression.100threads.30M-keys-i4i-enterprise.yaml
  test-cases/performance/perf-regression.100threads.30M-keys-i4i.yaml
  test-cases/performance/perf-regression.100threads.30M-keys.yaml
  test-cases/performance/perf-row-level-repair-1TB.yaml
  test-cases/performance/perf-search-best-throughput-config.yaml
  test-cases/performance/ycsb/perf-base.yaml
  unit_tests/test_data/test_scylla_yaml_builders/perf-regression.100threads.30M-keys.yaml
  unit_tests/test_tester.py
Labels: backport/6.0, backport/perf-v15

#7508 fix(gce-logcollector): use private addresses as default
  sdcm/logcollector.py
Labels: test-provision-aws, test-provision-gce, test-provision-azure, backport/2023.1, backport/5.4, backport/2024.1, backport/6.0

#7509 feature(mergify): introduce automatic backport process
  .github/mergify.yml
Labels: backport/none

#7511 fix(manager): remove unnecessary whitespace from repair jenkinsfile
  jenkins-pipelines/manager/centos-manager-repair-intensity-single-repaired-nodes.jenkinsfile
Labels: Ready for review, backport/manager-3.2
