Repository scylladb/scylla-cluster-tests, pull requests merged in 2024-04, with the labels that each got.

#7326 fix(loaders): use proper loader indexes when `round_robin` is enabled
  sdcm/stress/base.py
Labels: Ready for review, Backport-perf-v14, Backport-2023.1, Backport-5.4, Backport-2024.1

#7313 improvement(cluster): setup nodes in parallel
  sdcm/cluster.py
  sdcm/cluster_azure.py
  sdcm/cluster_docker.py
  sdcm/cluster_k8s/__init__.py
  sdcm/utils/raft/common.py
Labels: Ready for review, Backport-2023.1, Backport-5.4, Backport-2024.1

#7332 fix(loaders): use proper loader indexes - part2
  sdcm/stress_thread.py
Labels: Ready for review, Backport-perf-v14, Backport-2023.1, Backport-5.4, Backport-2024.1

#7346 fix(s3_uploader): fix class for mimicking a file
  sdcm/utils/s3_remote_uploader.py
Labels: Backport-2023.1, Backport-5.4, Backport-2024.1

#7350 fix(perf): prolong wait for no compactions
  performance_regression_test.py
Labels: Backport-perf-v14

#7341 feature(multidc): add possibility to use simulated regions
  defaults/test_default.yaml
  docs/configuration_options.md
  sdcm/cluster.py
  sdcm/cluster_aws.py
  sdcm/cluster_azure.py
  sdcm/cluster_baremetal.py
  sdcm/cluster_docker.py
  sdcm/cluster_gce.py
  sdcm/cluster_k8s/__init__.py
  sdcm/sct_config.py
  sdcm/tester.py
  unit_tests/dummy_remote.py
Labels: Ready for review

#7355 fix(offline_installer): print io.conf from correct path
  sdcm/cluster.py
Labels: Backport-2023.1, Backport-2024.1

#7356 fix(RemoteBrowser): stop assuming `parent_cluster` exists
  sdcm/utils/remotewebbrowser.py
Labels: No Backport Needed

#7360 fix(perf): add datasize to perf upgrade test
  jenkins-pipelines/performance/scylla-enterprise/scylla-enterprise-perf-regression-latency-650gb-during-rolling-upgrade.jenkinsfile
  jenkins-pipelines/performance/scylla-master/scylla-master-perf-regression-latency-650gb-during-rolling-upgrade.jenkinsfile
  test-cases/performance/perf-regression-latency-650gb-upgrade.yaml
Labels: Backport-perf-v14

#7363 improvement(logging): add hostname info to RemoteCmdRunner
  sdcm/remote/base.py
  sdcm/remote/remote_base.py
Labels: No Backport Needed

#7316 fix(cs-profiles): use user profiles located at `/tmp` be used `as-is`
  sdcm/utils/user_profile.py
Labels: test-integration, Backport-2023.1, Backport-5.4, Backport-2024.1

#7362 improvement(distro): use ubuntu for loader and monitor nodes
  defaults/aws_config.yaml
  defaults/azure_config.yaml
  defaults/gce_config.yaml
  defaults/k8s_gke_config.yaml
  defaults/test_default.yaml
  sct_ssh.py
  sdcm/sct_config.py
  test-cases/manager/manager-backup-1TB-gce.yaml
  unit_tests/test_config.py
Labels: Ready for review, Backport-2022.1, Backport-perf-v14, Backport-5.2, Backport-2023.1, Backport-5.4, Backport-manager-3.2, Backport-2024.1

#7317 ci(tablets): add scale (multi-ks, multi-cf) CI jobs for testing tablets
  jenkins-pipelines/oss/tablets/longevity-multi-keyspaces-60h.jenkinsfile
  jenkins-pipelines/oss/tablets/scale-5000-tables.jenkinsfile
Labels: No Backport Needed, Ready for review

#7369 Support for manager-master jenkins pipeline
  mgmt_cli_test.py
  sdcm/mgmt/cli.py
Labels: Backport-manager-3.2

#7371 fix(artifact test): check 'node_boot_time_seconds' instead available memory
  artifacts_test.py
  sdcm/utils/adaptive_timeouts/load_info_store.py
Labels: Backport-2023.1, Backport-5.4, Backport-2024.1

#7380 fix(k8s): catch "'NoneType' object has no attribute 'fileno'" errors
  sdcm/utils/remote_logger.py
Labels: No Backport Needed, Ready for review, scylla-operator

#7378 improvement(init): skip instance setup script if already ran
  sdcm/provision/common/configuration_script.py
  sdcm/sct_provision/aws/user_data.py
Labels: test-provision

#7377 fix(set-tags): fix setting of tags onto SCT runners
  sdcm/sct_runner.py
  sdcm/utils/common.py
Labels: Ready for review, Backport-5.4, Backport-2024.1

#7374 fix(perf-simple-query): fix name of file
  jenkins-pipelines/performance/Perf-Regression/scylla-release-perf-simple-query-microbenchmark_arm64.jenkinsfile
Labels: Backport-perf-v14

#7368 fix(coredump): remove unnecessary info
  sdcm/coredump.py
  sdcm/sct_events/system.py
  unit_tests/test_data/test_coredump/filebased/fail_upload_test_results.json
  unit_tests/test_data/test_coredump/filebased/success_test_results.json
  unit_tests/test_data/test_coredump/systemd/exceptions_limit_not_reached_test_results.json
  unit_tests/test_data/test_coredump/systemd/fail_upload_test_results.json
  unit_tests/test_data/test_coredump/systemd/success_test_results.json
  unit_tests/test_data/test_coredump/systemd/success_test_systemd_248_remoter.json
  unit_tests/test_data/test_coredump/systemd/success_test_systemd_248_results.json
  unit_tests/test_sct_events_system.py
Labels: Backport-2023.1, Backport-5.4, Backport-2024.1

#7354 test(perf): set initial tablets to 32 in perf tests
  configurations/tablets-initial-32.yaml
  jenkins-pipelines/performance/scylla-enterprise/scylla-enterprise-perf-regression-latency-650gb-grow-shrink-tablets.jenkinsfile
  jenkins-pipelines/performance/scylla-master/scylla-master-perf-regression-latency-650gb-grow-shrink-tablets.jenkinsfile
Labels: Backport-perf-v14

#7367 fix(is_cluster_topology_consistent): Make sure non-voters don't remain in the group0.
  sdcm/utils/raft/__init__.py
Labels: Ready for review, Backport-2023.1, Backport-5.4

#7382 fix(integration_tests): add node_index to LocalNode
  unit_tests/dummy_remote.py
Labels: Backport-perf-v14, test-integration, Backport-2023.1, Backport-5.4, Backport-2024.1
