Repository scylladb/scylla-cluster-tests, pull requests merged in 2024-09, with the labels that each got.

#8531 fix(artifacts): skip configuring syslog-ng for artifacts test
  sdcm/provision/common/configuration_script.py
Labels: backport/none, test-provision-gce-reuse

#8524 fix(provision): shorten node name when Azure and simulated dc
  sdcm/sct_config.py
Labels: test-provision-aws, backport/2024.1, backport/6.0, backport/perf-v15, backport/2024.2, backport/6.1

#8526 fix(manager): get rid of whitelisting for sctool restore cmd parameters
  docs/configuration_options.md
  jenkins-pipelines/manager/ubuntu22-manager-backup-restore-custom-dataset.jenkinsfile
  mgmt_cli_test.py
  sdcm/mgmt/cli.py
  sdcm/mgmt/common.py
  sdcm/report_templates/results_manager.html
  sdcm/sct_config.py
  vars/managerPipeline.groovy
Labels: backport/manager-3.3

#8549 improvement(scylla.yaml): support `allowed_repair_based_node_ops` option
  sdcm/provision/scylla_yaml/scylla_yaml.py
  unit_tests/test_scylla_yaml.py
Labels: backport/2023.1, backport/5.4, backport/2024.1, backport/6.0, backport/2024.2, backport/6.1

#8555 improvement(sct.py): Collect argus events if they don't exist
  docker/env/version
  requirements.in
  requirements.txt
  sct.py
  sdcm/utils/argus.py
Labels: backport/2024.1, backport/6.0, backport/perf-v15, backport/2024.2, backport/6.1

#8342 test(nemesis): update manager persistent snapshots
  defaults/manager_persistent_snapshots.yaml
Labels: backport/6.0, backport/2024.2, backport/6.1

#8564 fix(hdr file): latency from HDR file for untrottled load
  sdcm/utils/csrangehistogram.py
Labels: backport/2023.1, backport/2024.1, backport/perf-v15, backport/6.1

#8583 fix(reuse_cluster): fix reuse_cluster flow for Azure backend
  sdcm/cluster_azure.py
Labels: backport/none, test-provision-azure-reuse

#8586 fix(capacity_reservation): take `nemesis_grow_shrink_instance_type` into account
  sdcm/provision/aws/capacity_reservation.py
Labels: backport/6.0, backport/perf-v15, backport/2024.2, backport/6.1

#8562 improvement(oel support): Take the latest oel8 and oel9 from aws
  jenkins-pipelines/oss/artifacts-offline-install/artifacts-oel8.jenkinsfile
  jenkins-pipelines/oss/artifacts/artifacts-oel8.jenkinsfile
  jenkins-pipelines/oss/artifacts/artifacts-oel9.jenkinsfile
  sdcm/utils/distro.py
  test-cases/artifacts/oel8.yaml
  test-cases/artifacts/oel9.yaml
Labels: backport/2024.1, backport/2024.2, backport/6.1

#8209 improvement(Alternator): support creating tablets-enabled tables
  sdcm/tester.py
  sdcm/utils/alternator/api.py
Labels: area/tablets, backport/6.0, backport/2024.2, backport/6.1

#8588 fix(fips): pick ubuntu pro fips straight from marketplace
  configurations/longevity-fips-and-encryptions.yaml
  defaults/test_default.yaml
  docs/configuration_options.md
  sdcm/cluster.py
  sdcm/sct_config.py
  test-cases/artifacts/ubuntu2004-fips.yaml
Labels: backport/2023.1, backport/2024.1, backport/2024.2

#8550 fix(disrupt_mgr): skip take_snapshot error per issue
  sdcm/nemesis.py
  sdcm/sct_events/group_common_events.py
Labels: test-provision-aws, backport/2023.1, backport/2024.1, backport/6.0, backport/perf-v15, backport/2024.2, backport/6.1

#8640 fix(sct.py): Ignore TEST_ERROR inside finish_argus_test_run
  sct.py
Labels: backport/2024.1, backport/6.0, backport/perf-v15, backport/2024.2, backport/6.1

#8646 fix(c-s): working directory for docker running c-s
  sdcm/stress_thread.py
Labels: test-integration, backport/2023.1, backport/2024.1, backport/6.0, backport/perf-v15, backport/2024.2, backport/6.1

#8630 fix(loader): update loader images to `scylla-qa-loader-ami-v22-ubuntu22`
  defaults/aws_config.yaml
  utils/copy_ami_to_all_regions.sh
Labels: test-provision-aws, backport/2024.1, backport/6.0, backport/perf-v15, backport/2024.2, backport/6.1, test-provision-aws-reuse

#8631 fix(aws-provision): have a default for `user_data_format_version`
  sdcm/sct_config.py
Labels: backport/2023.1, backport/2024.1, backport/perf-v15, backport/2024.2

#8660 fix(oel8): new oel8 image was missing tar
  sdcm/cluster.py
Labels: backport/2024.1, backport/2024.2, backport/6.1

#8608 fix(is_enterprise): don't cache if no scylla is installed
  sdcm/cluster.py
Labels: backport/6.0, backport/perf-v15, backport/2024.2, backport/6.1

#8632 improvement(decorator): adapt latency_calculator_decorator
  sdcm/utils/decorators.py
Labels: backport/2023.1, backport/2024.1, backport/6.0, backport/perf-v15, promoted-to-master, backport/2024.2, backport/6.1

#8599 feature(sdcm/reporting): Add initial simple elasticsearch reporter
  sdcm/reporting/elastic_reporter.py
  sdcm/tester.py
Labels: backport/none

#8611 improvement(results): send latency decorator screenshots to Argus
  docker/env/version
  requirements.in
  requirements.txt
  sdcm/argus_results.py
  unit_tests/test_argus_results.py
Labels: New Hydra Version, backport/perf-v15, backport/2024.2, backport/6.1

#8606 test(trigger): trigger tablets performance tests
  jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-enterprise-performance-tablets-trigger.xml
  jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-enterprise-performance-trigger.xml
  jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-master-performance-tablets-trigger.xml
  jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-master-performance-trigger.xml
Labels: backport/none

#8613 fix(scylla-sstable): switch from `--scylla-yaml-file` to `SCYLLA_CONF` env variable
  sdcm/utils/sstable/sstable_utils.py
  upgrade_test.py
Labels: backport/2023.1, backport/2024.1, backport/6.0, backport/2024.2, backport/6.1

#8695 fix(_get_keyspaces_to_decrease_rf): Address a case where no keyspace RF value of DC
  sdcm/utils/replication_strategy_utils.py
Labels: backport/6.0, backport/2024.2, backport/6.1

#8668 fix(oel9): stop/disable iptables and firewalld
  sdcm/cluster.py
Labels: backport/2024.1, backport/2024.2, backport/6.1

#8704 fix(aws-provision): set default for `user_data_format_version=3`
  sdcm/sct_config.py
Labels: backport/2023.1, backport/2024.1, backport/perf-v15, backport/2024.2

#8709 fix(auth_v2): don't change system_auth
  add_new_dc_test.py
  sdcm/nemesis.py
  sdcm/tester.py
Labels: backport/6.0, backport/2024.2, backport/6.1

#8735 improvement(logs): collect db logs upon VM termination
  sdcm/cluster.py
Labels: backport/2024.1, backport/6.0, backport/perf-v15, backport/2024.2, backport/6.1

#8742 fix(tests): fix integration tests
  unit_tests/test_config.py
  unit_tests/test_config_get_version_based_on_conf.py
Labels: test-integration, backport/2024.1, backport/6.0, backport/perf-v15, backport/2024.2, backport/6.1

#8725 fix(latte): parse latte latency and thrpt info correctly
  .pre-commit-config.yaml
  data_dir/latte_stress_output.log
  sdcm/stress/latte_thread.py
  unit_tests/test_latte_thread.py
Labels: test-integration, backport/2024.1, backport/6.0, backport/2024.2, backport/6.1

#8760 ci(.github/mergify.yml): start backports process for scylla 6.2
  .github/mergify.yml
Labels: backport/none

#8759 fix(get_my_public_ip): update the list of services
  sdcm/utils/net.py
Labels: backport/2023.1, backport/2024.1, backport/6.0, backport/2024.2, backport/6.1, backport/6.2

#8736 test(elasticity): add mini elasticity test for pre-testing
  configurations/performance/cql-stress-6gb-8-col-i4i-mini-test-throughput.yaml
Labels: backport/none

#8675 fix(hydra): overmount "%home%/.local" dir
  docker/env/hydra.sh
Labels: test-provision, test-integration, backport/2023.1, backport/2024.1, backport/6.0, backport/2024.2, backport/6.1

#8783 fix(email): latency during ops template
  sdcm/report_templates/results_latency_during_ops.html
Labels: backport/perf-v15

#8790 fix(sdcm/tester.py): Handle ZonalAllocationFailed in check_error
  sdcm/tester.py
Labels: backport/2024.1, backport/2024.2, backport/6.1, backport/6.2

#8800 fix(trigger): gradual enterprise test
  jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-enterprise-performance-trigger.xml
Labels: backport/perf-v15

#8795 fix(byo): use proper BYO `scylla-6.2` defaults after branching from master
  vars/byoScylladb.groovy
  vars/longevityPipeline.groovy
  vars/perfRegressionParallelPipeline.groovy
  vars/rollingUpgradePipeline.groovy
Labels: backport/none, Ready for review

#8805 fix(unittest): remove config tests 35 and 36
  unit_tests/test_config.py
Labels: backport/perf-v15

#8743 fix(wait_for_log_lines): fix saturating cpu when waiting for log lines
  sdcm/wait.py
  unit_tests/test_wait.py
Labels: backport/perf-v15, backport/2024.2, backport/6.1, backport/6.2

#8814 fix(oel9): use the new ssh key for oel9 artifact test
  configurations/aws/new_ssh_key.yaml
  jenkins-pipelines/artifacts-oel9.jenkinsfile
Labels: backport/none

#8808 fix(perf test): remove dataset size from name in gradual test
  jenkins-pipelines/performance/branch-perf-v15/scylla-enterprise/perf-regression/scylla-enterprise-perf-regression-scylla-gradual-throughput-vnodes.jenkinsfile
  jenkins-pipelines/performance/branch-perf-v15/scylla-master/perf-regression/scylla-master-perf-regression-scylla-gradual-throughput-vnodes.jenkinsfile
  jenkins-pipelines/performance_staging/perf-regression-scylla-gradual-throughput-grow-uniform.jenkinsfile
  jenkins-pipelines/performance_staging/perf-regression-scylla-gradual-throughput-vnodes.jenkinsfile
  test-cases/performance/perf-regression-gradual-throughput.yaml
Labels: backport/perf-v15

#8724 test(perf): add mv write test that increases latency of regular reads
  jenkins-pipelines/performance_staging/perf-regression-latency-mv-read-concurrency.jenkinsfile
  performance_regression_test.py
  test-cases/performance/perf-regression-latency-mv-read-concurrency.yaml
Labels: backport/none

#8823 fix(oel9-offline-installer): don't install python2
  sdcm/cluster.py
Labels: backport/2024.1, backport/2024.2, backport/6.1, backport/6.2

#8828 fix(pipeline): missed comma
  jenkins-pipelines/performance/branch-perf-v15/scylla-master/perf-regression/scylla-master-perf-regression-latency-650gb-with-nemesis-tablets.jenkinsfile
Labels: backport/perf-v15

#8802 fix(nemesis): skip `disrupt_no_corrupt_repair` if needed
  sdcm/nemesis.py
Labels: backport/2024.2, backport/6.1, backport/6.2

#8833 fix(trigger): set aws_region
  jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-master-performance-tablets-trigger.xml
Labels: backport/perf-v15

#8845 fix(config): Raise proper error for missing config file
  sdcm/sct_config.py
Labels: backport/2022.1, backport/2022.2, backport/perf-v15, backport/6.1, backport/6.2

#8854 improvement(loader): set loader version hardcoded
  test-cases/performance/perf-regression-predefined-throughput-steps.yaml
Labels: backport/perf-v15

#8852 improvement(ruff): enable `F821` and `F823` rules
  multiple_dc_test.py
  pyproject.toml
  sdcm/audit.py
  sdcm/cluster_k8s/mini_k8s.py
  sdcm/coredump.py
  sdcm/node_exporter_setup.py
  sdcm/provision/aws/instance_parameters.py
  sdcm/provision/common/builders.py
  sdcm/provision/scylla_yaml/scylla_yaml.py
  sdcm/sct_events/handlers/__init__.py
  sdcm/sct_events/handlers/schema_disagreement.py
  sdcm/snitch_configuration.py
  sdcm/utils/adaptive_timeouts/__init__.py
  sdcm/utils/adaptive_timeouts/load_info_store.py
  sdcm/utils/benchmarks.py
  sdcm/utils/common.py
  sdcm/utils/k8s/__init__.py
  sdcm/utils/k8s/chaos_mesh.py
  sdcm/utils/raft/__init__.py
  sdcm/utils/remote_logger.py
  sdcm/utils/sstable/sstable_utils.py
  unit_tests/test_alternator_streams_kcl.py
Labels: Ready for review, backport/6.0, backport/2024.2, backport/6.1, backport/6.2

#8863 fix(trigger): set 'region' in perf master triggers
  jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-enterprise-performance-trigger.xml
  jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-master-performance-tablets-trigger.xml
  jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-master-performance-trigger.xml
Labels: backport/perf-v15

#8866 fix(triggers): run perf tests in defferent time
  jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-enterprise-performance-tablets-trigger.xml
  jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-master-performance-tablets-trigger.xml
  jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-master-performance-trigger.xml
Labels: backport/perf-v15

#8865 fix(trigger): params for upgrade tablet tests
  jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-enterprise-performance-tablets-trigger.xml
  jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-master-performance-tablets-trigger.xml
Labels: backport/perf-v15

#8857 fix(update-db-packages): stop only updated nodes
  sdcm/cluster.py
Labels: backport/2024.1, backport/perf-v15, backport/2024.2, backport/6.1, backport/6.2

#8842 fix(client_encrypt): make it work when server encryption is disabled
  sdcm/cluster.py
Labels: Ready for review, backport/2024.2, backport/6.1, backport/6.2

#7485 fix(nodebootstrapabortmanager): always clean scylla data before rebootstrap
  sdcm/nemesis.py
  sdcm/sct_events/group_common_events.py
  sdcm/utils/raft/__init__.py
  sdcm/utils/raft/common.py
Labels: Ready for review, backport/6.0, tier1, backport/2024.2, backport/6.1, backport/6.2

#8836 improvement(gradual test): warm up commands as parameter
  performance_regression_gradual_grow_throughput.py
  sdcm/sct_config.py
  test-cases/performance/perf-regression-predefined-throughput-steps.yaml
Labels: backport/perf-v15
