Repository scylladb/scylla-cluster-tests, pull requests merged in 2024-03, with the labels that each got.

#7238 fix(k8s-ci): make weekly triggers use proper CI jobs and it's parameters
  jenkins-pipelines/operator/functional/weekly-trigger.xml
Labels: No Backport Needed, Ready for review, scylla-operator

#7236 improvement(kms): improve KMS enc-on checks when nodetool cfstats fails
  sdcm/cluster.py
Labels: Ready for review, Backport-2023.1, Backport-5.4, Backport-2024.1

#7235 fix(manager_cli): set --force-non-ssl-session-port if encryption enabled but port not defined
  mgmt_cli_test.py
  sdcm/mgmt/cli.py
  sdcm/mgmt/operator.py
Labels: Backport-manager-3.2

#7239 improvement(k8s): stabilize namespace deletions in quasi-multidc test
  functional_tests/scylla_operator/test_functional.py
Labels: No Backport Needed, Ready for review, scylla-operator

#7225 fix(hydra): remove call to awscli to download keys
  docker/env/hydra.sh
  sct.py
  sdcm/keystore.py
  sdcm/utils/aws_utils.py
Labels: No Backport Needed, test-provision-aws, test-provision-docker, test-integration

#7228 New trigger for tablets longevities and new multi dc and multi rack tablets longevity
  configurations/tablets_multidc_multirack.yaml
  jenkins-pipelines/master-triggers/tablets_weekly_trigger.xml
  jenkins-pipelines/oss/tablets/longevity-multidc-multirack.jenkinsfile
Labels: Backport-2024.1

#7150 fix(raft): Raft always enabled
  sdcm/cluster.py
  sdcm/utils/health_checker.py
  sdcm/utils/raft/__init__.py
  sdcm/utils/raft/common.py
  upgrade_test.py
Labels: No Backport Needed, Ready for review

#7245 improvement(kms): disable encryption fact check
  sdcm/cluster.py
Labels: Ready for review, Backport-2023.1, Backport-5.4, Backport-2024.1

#7246 fix(update_repo_cache): stop calling `debconf-set-selections`
  sdcm/cluster.py
Labels: test-provision-aws, test-provision-gce, Backport-perf-v14, Backport-5.2, Backport-2023.1, Backport-5.4, Backport-2024.1

#7249 fix(azure): make upgrade work on Azure
  upgrade_test.py
Labels: No Backport Needed, Ready for review

#7151 fix(raft-exp-yaml): rename raft experimetal feature flag
  configurations/raft/enable_raft_experimental.yaml
Labels: No Backport Needed, Ready for review

#7259 improvement(k8s): use newest scylla-manager version - 3.2.6
  defaults/test_default.yaml
  docs/configuration_options.md
  functional_tests/scylla_operator/test_functional.py
  sdcm/cluster_k8s/__init__.py
  sdcm/cluster_k8s/mini_k8s.py
Labels: No Backport Needed, Ready for review, scylla-operator

#7247 improvement(get_username.py): User impersonation for automated builds
  sdcm/utils/get_username.py
  vars/artifactsPipeline.groovy
  vars/createArgusTestRun.groovy
  vars/createSctRunner.groovy
  vars/jepsenPipeline.groovy
  vars/longevityPipeline.groovy
  vars/managerPipeline.groovy
  vars/perfRegressionParallelPipeline.groovy
  vars/provisionResources.groovy
  vars/rollingOperatorUpgradePipeline.groovy
  vars/rollingUpgradePipeline.groovy
  vars/runSctTest.groovy
Labels: Backport-2023.1, Backport-5.4, Backport-2024.1

#7260 fix(audit): add 'ignore_ycsb_connection_refused' to audit config
  sdcm/audit.py
Labels: Backport-2023.1, Backport-5.4, Backport-2024.1

#7258 fix(install_packages): add proper frontent and options
  sdcm/cluster.py
Labels: Backport-perf-v14, Backport-5.2, Backport-2023.1, Backport-5.4, Backport-2024.1

#7268 fix(test_default_filters): remove unneed log filter
  sdcm/sct_events/setup.py
  unit_tests/test_events.py
Labels: Backport-2023.1, Backport-5.4, Backport-2024.1

#7265 fix(disrupt_memory_stress): Change the SkipPerIssue to actual issue
  sdcm/nemesis.py
Labels: No Backport Needed

#7272 fix(k8s): update pkg info before installing packages inside of K8S pods
  sdcm/cluster.py
Labels: No Backport Needed, Ready for review, scylla-operator

#7266 improvement(perf-report): added test_id to perf regression reports
  sdcm/report_templates/results_performance.html
  sdcm/report_templates/results_performance_baseline.html
  sdcm/results_analyze/__init__.py
Labels: Backport-perf-v14

#7278 fix(k8s): make static loaders work
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed, Ready for review, scylla-operator

#7267 fix(tablets_weekly_trigger.xml): changed predefined properties
  jenkins-pipelines/master-triggers/tablets_weekly_trigger.xml
Labels: No Backport Needed

#7273 improvement(aws region): configure region with few subnets
  sdcm/utils/aws_peering.py
  sdcm/utils/aws_region.py
Labels: No Backport Needed

#7281 fix(issues): handle call to github api a bit better
  sdcm/utils/issues.py
Labels: Backport-2023.1, Backport-5.4, Backport-2024.1

#7283 fix(issues): don't raise errors from rate-limit failure
  sdcm/utils/issues.py
Labels: Backport-2023.1, Backport-5.4, Backport-2024.1

#7270 fix(RollingConfigChangeInternodeCompression): properly identify None
  sdcm/nemesis.py
Labels: Backport-5.2, Backport-2023.1, Backport-5.4, Backport-2024.1

#7285 fix(sct.py): make `scan-skip-issues` more smart
  sct_scan_issues.py
  sdcm/utils/issues.py
Labels: Ready for review

#7288 fix(perf_simple_query_x86): switch to c7i.large
  test-cases/microbenchmarking/amazon_perf_simple_query_x86.yaml
Labels: Backport-perf-v14

#7292 fix(k8s): allow to specify full registry path for operator images
  sdcm/cluster_k8s/__init__.py
Labels: No Backport Needed, Ready for review, scylla-operator

#7291 fix(test_default_filters): take it out of unittest
  unit_tests/lib/events_utils.py
  unit_tests/test_events.py
Labels: Backport-2023.1, Backport-5.4, Backport-2024.1

#7299 fix(oel8): revert usage of i4i
  test-cases/artifacts/oel81.yaml
Labels: Backport-2023.1, Backport-5.4, Backport-2024.1

#7304 fix(alternator-dns): move ycsb runs into it's own docker network
  configurations/rolling-upgrade-alternator.yaml
  sdcm/utils/docker_remote.py
  sdcm/ycsb_thread.py
  test-cases/features/alternator-ttl/longevity-alternator-1h-scan-12h-ttl-no-lwt-2h-grace-4loaders-sisyphus.yaml
  test-cases/features/alternator-ttl/longevity-alternator-4m-scan-36m-ttl-8m-grace-sisyphus-rewrite-expired-data.yaml
  test-cases/features/alternator-ttl/longevity-alternator-4m-scan-36m-ttl-no-lwt-8m-grace-sisyphus.yaml
  test-cases/features/alternator-ttl/longevity-alternator-4m-scan-multiple-ttl-8m-grace.yaml
  test-cases/features/alternator-ttl/longevity-alternator-disable-enable-ttl.yaml
  test-cases/features/alternator-ttl/longevity-alternator-ttl-big-dataset.yaml
  test-cases/features/alternator-ttl/longevity-alternator-ttl-large-writes.yaml
  test-cases/features/alternator-ttl/longevity-alternator-ttl-lwt.yaml
  test-cases/longevity/longevity-alternator-200GB-48h.yaml
  test-cases/longevity/longevity-alternator-3h-multidc.yaml
  test-cases/longevity/longevity-alternator-3h.yaml
  test-cases/longevity/longevity-alternator-streams-100gb-12h.yaml
  unit_tests/conftest.py
  unit_tests/lib/alternator_utils.py
  unit_tests/test_ycsb_thread.py
Labels: Backport-2023.1, Backport-5.4, Backport-2024.1

#7303 fix(alternator): enable back the ycsb based tests
  sdcm/utils/alternator/api.py
  unit_tests/test_ycsb_thread.py
Labels: No Backport Needed, test-integration

#7301 fix(k8s): stabilize K8S functional tests
  functional_tests/scylla_operator/test_functional.py
Labels: No Backport Needed, Ready for review, scylla-operator

#7312 improvement(docker-backend): add a dedicated test config for local runs
  configurations/nemesis/additional_configs/docker_backend_local.yaml
Labels: No Backport Needed

#7314 fix(sct-runner): remove keep-alive network tag on GCE
  sdcm/sct_runner.py
Labels: Backport-perf-v14, Backport-5.2, Backport-2023.1, Backport-5.4, Backport-2024.1

#7306 fix(upgrades): stop using centos-7 as basis image
  jenkins-pipelines/enterprise/rolling-upgrade/rolling-upgrade-centos7-ldap-authorization.jenkinsfile
  jenkins-pipelines/enterprise/rolling-upgrade/rolling-upgrade-ubuntu22.04-ldap-authorization.jenkinsfile
  jenkins-pipelines/oss/rolling-upgrade/rolling-upgrade-alternator.jenkinsfile
  jenkins-pipelines/oss/rolling-upgrade/rolling-upgrade-centos7.jenkinsfile
Labels: No Backport Needed
