Repository scylladb/scylla-cluster-tests, pull requests merged in 2025-10, with the labels that each got.

#12062 fix(tester.py): improve checking kms enabling conditions
  sdcm/tester.py
Labels: backport/2025.4

#12017 fix(manager): restart Scylla after schema restoration only for Scylla 2024.1 or lower
  sdcm/mgmt/operations.py
Labels: backport/none

#12093 fix(logcollector): fix getting monitoring version
  sdcm/logcollector.py
Labels: Ready to be Merged, backport/2025.1, backport/2025.2, backport/2025.3, backport/2025.4

#12117 fix(cluster): fix getting monitoring version when scylla_version is a branch
  sdcm/cluster.py
Labels: backport/2025.4
