Repository scylladb/scylla-cluster-tests, pull requests merged in 2025-01, with the labels that each got.

#9633 fix(sct_config): don't fail on empty instance type
  sdcm/sct_config.py
  sdcm/utils/aws_utils.py
Labels: backport/none

#9586 feature(sct-runner): version 1.9 with java 21.0.5
  sdcm/sct_runner.py
  sdcm/utils/aws_builder.py
Labels: backport/none, test-provision-aws, test-provision-gce, test-provision-azure

#9622 fix(manager): update default Scylla version to 2024.2 for Manager tests
  defaults/manager_versions.yaml
  jenkins-pipelines/manager/debian11-manager-install.jenkinsfile
  jenkins-pipelines/manager/debian11-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/debian11-manager-upgrade.jenkinsfile
  jenkins-pipelines/manager/ubuntu22-manager-vnodes-tablets-enterprise.jenkinsfile
  unit_tests/test_sdcm_mgmt_common.py
  vars/managerPipeline.groovy
Labels: backport/none

#9636 fix(gpg): add timeout and debug
  sdcm/cluster.py
Labels: test-provision-aws, backport/2024.1, backport/2024.2

#9585 fix(nemesis.py): abort nemesis on stress command failure
  sdcm/cassandra_harry_thread.py
  sdcm/exceptions.py
  sdcm/kcl_thread.py
  sdcm/ndbench_thread.py
  sdcm/nemesis.py
  sdcm/nosql_thread.py
  sdcm/scylla_bench_thread.py
  sdcm/stress/latte_thread.py
  sdcm/ycsb_thread.py
Labels: backport/2024.1, backport/2024.2, backport/6.2

#9654 fix(nemesis.py): fix evaluation of stress command result
  sdcm/nemesis.py
Labels: backport/2024.1, backport/2024.2, backport/6.2

#9651 fix(distro): add back ubuntu 24.04 support
  sdcm/utils/distro.py
Labels: backport/none, test-integration

#9652 fix(offline-installer): stop installing python2 and java
  sdcm/cluster.py
Labels: backport/none

#9649 fix(manager): update jenkinsfile for Manager Azure tests
  jenkins-pipelines/manager/rhel-manager-backup-azure.jenkinsfile
Labels: backport/none

#9659 fix(offline-install): return back `tar` pkg installation
  sdcm/cluster.py
Labels: backport/none

#9663 fix(pipeline): config params for predefined write test
  jenkins-pipelines/performance/branch-perf-v16/scylla-enterprise/perf-regression/scylla-enterprise-perf-regression-predefined-throughput-steps-write-vnodes.jenkinsfile
Labels: backport/perf-v16

#9658 fix(integration-tests): update versions used
  unit_tests/test_config_get_version_based_on_conf.py
Labels: backport/none, test-integration, backport/2024.1, backport/perf-v15, backport/2024.2, backport/6.2, backport/perf-v16

#9590 fix(manager): update expected error message for enospc restore test
  mgmt_cli_test.py
Labels: backport/none

#9650 fix(hydra): limit tmpfs to 256m
  docker/env/hydra.sh
Labels: test-provision-aws, test-provision-gce, test-integration, backport/2023.1, backport/2024.1, backport/6.0, backport/perf-v15, backport/6.1, backport/6.2, backport/perf-v16

#9632 improvement(events): add rack aware policy event
  defaults/severities.yaml
  sdcm/report_templates/results_base.html
  sdcm/sct_events/loaders.py
  sdcm/send_email.py
  sdcm/tester.py
  unit_tests/test_sct_events_loaders.py
Labels: backport/2024.2

#9638 fix(sct_config): `scylla-server-upgrade-target` wasn't reported to Argus
  sdcm/sct_config.py
  sdcm/utils/version_utils.py
  unit_tests/test_version_utils.py
Labels: test-integration, backport/2024.1, backport/perf-v15, backport/2024.2, backport/6.2, backport/perf-v16

#9693 fix(dependabot): remove quotes from docker configurations
  defaults/docker_images/alternator-dns/values_alternator-dns.yaml
  defaults/docker_images/cassandra-stress/values_cassandra-stress.yaml
  defaults/docker_images/cdc-stresser/values_cdc-stresser.yaml
  defaults/docker_images/cql-stress-cassandra-stress/values_cql-stress-cassandra-stress.yaml
  defaults/docker_images/gemini/values_gemini.yaml
  defaults/docker_images/harry/values_harry.yaml
  defaults/docker_images/kcl/values_kcl.yaml
  defaults/docker_images/latte/values_latte.yaml
  defaults/docker_images/ndbench/values_ndbench.yaml
  defaults/docker_images/nosqlbench/values_nosqlbench.yaml
  defaults/docker_images/scylla-bench/values_scylla-bench.yaml
  defaults/docker_images/ycsb/values_ycsb.yaml
Labels: backport/none

#9696 Revert "test(nemesis): update manager persistent snapshots"
  defaults/manager_persistent_snapshots.yaml
Labels: backport/none

#9706 feature(commitlint.config.js): add `chore` to the context list
  commitlint.config.js
Labels: backport/2024.1, backport/perf-v15, backport/2024.2, backport/6.1, backport/6.2, backport/perf-v16

#9714 chore(renovate): update to renovate.json
  renovate.json
Labels: backport/none

#9726 chore(renovate.json): enable docker, scan `requirements.in`
  renovate.json
Labels: backport/none

#9697 feature(auto-backport.py): replace Mergify
  .github/scripts/auto-backport.py
  .github/scripts/search_commits.py
  .github/workflows/add-label-when-promoted.yaml
Labels: backport/manager, backport/perf-v14, backport/2023.1, backport/2024.1, backport/perf-v15, backport/2024.2, backport/6.1, backport/6.2, backport/perf-v16

#9621 improvement(node_exporter): upgrade to v1.8.2, remove unneeded collectors
  sdcm/node_exporter_setup.py
Labels: backport/none, test-provision-aws

#9499 fix(sstbale dump): select the suitable sstable-dump command everywhere it is used
  sdcm/utils/sstable/sstable_utils.py
  upgrade_test.py
Labels: Ready for review, Ready to be Merged, backport/2024.1, backport/6.0, backport/2024.2, backport/6.1, backport/6.2

#9750 fix(auto-backport) wrong target branch
  .github/scripts/auto-backport.py
Labels: backport/2023.1, backport/2024.1, backport/perf-v15, backport/2024.2, backport/6.1, backport/6.2, backport/perf-v16

#9776 fix(mgmt-agent): setup it using the code existing in the branch-2024.2
  sdcm/cluster.py
Labels: backport/none

#9687 improvement(perf_simple_query): add validation rules for Argus
  microbenchmarking_test.py
  sdcm/argus_results.py
Labels: backport/perf-v15, backport/perf-v16

#9637 feature(client-encrypt): enable peer verification for stress commands
  artifacts_test.py
  defaults/test_default.yaml
  docs/configuration_options.md
  sdcm/provision/helpers/certificate.py
  sdcm/sct_config.py
  sdcm/scylla_bench_thread.py
  sdcm/stress/latte_thread.py
  sdcm/stress_thread.py
  unit_tests/conftest.py
Labels: backport/none, test-integration

#9791 fix(region_name): improvre retreving `region_name` in nemesis
  sdcm/nemesis.py
Labels: test-provision-aws, test-provision-gce, backport/2024.2, backport/6.1, backport/6.2

#9774 fix(nemesis.py): log nemesis start/end on db nodes logs
  sdcm/cluster.py
  sdcm/nemesis.py
  unit_tests/test_nemesis.py
Labels: backport/2024.1, backport/perf-v15, backport/2024.2, backport/6.2, backport/perf-v16

#9779 fix(upgrade-tests): enlarge timeout for truncate commands
  sdcm/fill_db_data.py
Labels: backport/2024.1, backport/2024.2, backport/6.2

#9788 fix(bucket-locations): add templating to `backup_bucket_location`
  defaults/aws_config.yaml
  functional_tests/scylla_operator/test_functional.py
  mgmt_cli_test.py
  sdcm/nemesis.py
Labels: backport/2024.2, backport/6.2

#9802 fix(force_run_iotune): run `scylla_io_setup` and not directly iotune
  sdcm/cluster.py
Labels: backport/perf-v15, backport/perf-v16

#9810 fix(auto_assign): skip `scylladbbot` assignment
  .github/workflows/auto_assign.yaml
Labels: backport/2024.1, backport/perf-v15, backport/2024.2, backport/6.1, backport/6.2, backport/perf-v16

#9786 feature(pipelines): collect builders logs
  sdcm/utils/common.py
  vars/collectBuilderLogs.groovy
  vars/runCollectLogs.groovy
Labels: backport/none, test-provision-aws

#8953 improvement(gemini): run gemini from scylladb/gemini
  defaults/docker_images/gemini/values_gemini.yaml
  docker/gemini/Dockerfile
  docker/gemini/README.md
  docker/gemini/image
  sdcm/gemini_thread.py
  sdcm/logcollector.py
  sdcm/sct_config.py
  test-cases/gemini/gemini-1tb-10h.yaml
  test-cases/gemini/gemini-3h-cdc-postimage-write.yaml
  test-cases/gemini/gemini-3h-cdc-preimage-write.yaml
  test-cases/gemini/gemini-3h-cdc-write.yaml
  test-cases/gemini/gemini-3h-ics-cdc-with-nemesis.yaml
  test-cases/gemini/gemini-3h-ics-with-nondisruptive-nemesis.yaml
  test-cases/gemini/gemini-3h-with-nemesis.yaml
  test-cases/gemini/gemini-3h-with-nondisruptive-nemesis.yaml
  test-cases/gemini/gemini-8h-large-num-columns.yaml
  test-cases/gemini/gemini-basic-3h-ics.yaml
  test-cases/gemini/gemini-basic-3h.yaml
  unit_tests/test_gemini_thread.py
Labels: backport/none, test-integration

#9777 fix(get_supported_scylla_base_version): skip upgrade from 6.0 to 2024.2
  unit_tests/test_base_version.py
  utils/get_supported_scylla_base_versions.py
Labels: backport/none, Ready to be Merged

#9545 test(hdr logs): use thread instead process
  sdcm/stress_thread.py
Labels: backport/2024.1, backport/perf-v15, backport/2024.2, backport/perf-v16

#9820 improvement(perf test): change steps for predefined write test
  configurations/performance/cassandra_stress_gradual_load_steps.yaml
  configurations/performance/cassandra_stress_gradual_load_steps_enterprise.yaml
Labels: backport/perf-v16

#9829 fix(sla.py): raise value error
  test_lib/sla.py
Labels: backport/2023.1, backport/2024.1, backport/6.0, backport/2024.2, backport/6.1, backport/6.2

#9836 fix(sct): raise errors where it should be raised
  artifacts_test.py
  upgrade_test.py
Labels: backport/2024.2, backport/6.2

#9843 fix(test-case): update 5000 tables test case configuration
  jenkins-pipelines/oss/tier2/scale-5000-tables.jenkinsfile
  sdcm/provision/scylla_yaml/scylla_yaml.py
  test-cases/scale/longevity-5000-tables.yaml
  unit_tests/test_scylla_yaml.py
Labels: backport/2024.1, backport/2024.2, backport/6.1, backport/6.2

#9851 [Backport 2023.1] improvement(sdcm/cluster): Store dc and rack information in argus
  sdcm/cluster.py
Labels: backport/none

#9841 fix(hydra): enable python faulthandler by default
  docker/env/hydra.sh
Labels: backport/none, test-provision-aws, test-provision-gce, test-provision-docker

#9856 fix(nemesis): fix typo in the `mgmt_restore` nemesis
  sdcm/nemesis.py
Labels: backport/2024.2, backport/6.1, backport/6.2

#9735 fix(createindex): Disable nemesis to run in parallel nemesis jobs
  sdcm/nemesis.py
Labels: Ready for review, backport/2024.2, backport/6.2

#9600 fix(scan_operations): add retry policy to cql query
  sdcm/scan_operation_thread.py
Labels: tests/longevity-tier1, backport/2024.2, backport/6.1, backport/6.2

#9821 fix(common): change wait_for_tablets_balanced to represent what it actualy does
  sdcm/nemesis.py
  sdcm/utils/replication_strategy_utils.py
  sdcm/utils/tablets/common.py
Labels: backport/none

#9844 feature(createArgusTestRun.groovy): Add argus link
  vars/createArgusTestRun.groovy
Labels: backport/2024.1, backport/perf-v15, backport/2024.2, backport/6.1, backport/6.2, backport/perf-v16

#9877 fix(perf test): remove 100K step in write test
  configurations/performance/cassandra_stress_gradual_load_steps.yaml
  configurations/performance/cassandra_stress_gradual_load_steps_enterprise.yaml
Labels: backport/perf-v16

#9868 feature(ruff): scan for mutable-argument-default (B006)
  pyproject.toml
  sdcm/cluster_k8s/eks.py
  sdcm/remote/kubernetes_cmd_runner.py
  sdcm/remote/libssh2_client/session.py
  sdcm/sct_events/events_analyzer.py
  sdcm/stress_thread.py
  sdcm/utils/k8s/__init__.py
  sdcm/ycsb_thread.py
Labels: backport/perf-v15, backport/2024.2, backport/6.2, backport/perf-v16

#9615 feature(views-with-tablets): enable testing materialized views with tablets
  configurations/enable_views_with_tablets_on_upgrade.yaml
  defaults/test_default.yaml
  docs/configuration_options.md
  sdcm/sct_config.py
  upgrade_test.py
Labels: backport/none

#9870 feature(Jenkinsfile): get latest scylla release automaticlly
  Jenkinsfile
  vars/getLatestScyllaRelease.groovy
Labels: backport/none, test-provision-aws, test-provision-docker

#9895 fix(sct_config): `param.get()` doesn't accept default argument
  defaults/test_default.yaml
  sdcm/sct_config.py
  unit_tests/test_config.py
Labels: backport/none

#9840 feature(logcollector): switch to using zstd
  docker/env/Dockerfile
  docker/env/version
  requirements.txt
  sdcm/log_archive.sh
  sdcm/logcollector.py
  sdcm/monitorstack/__init__.py
Labels: backport/none, test-provision-aws, test-provision-docker, New Hydra Version

#9884 fix(_run_all_stress_cmds): skip and warn about using counters
  sdcm/utils/loader_utils.py
Labels: test-provision-aws, test-provision-docker, backport/2024.2, backport/6.2

#9885 fix(gpg): remove debug log from gpg command
  sdcm/cluster.py
Labels: backport/2024.1, backport/2024.2

#9901 fix(get_version_based_on_conf): master is now "enterprise"
  unit_tests/test_config_get_version_based_on_conf.py
Labels: backport/2024.1, backport/2024.2, backport/6.2

#9900 fix(sstables_validator): fix upload sstables
  sdcm/logcollector.py
  sdcm/teardown_validators/sstables.py
  sdcm/utils/sstable/sstable_utils.py
Labels: backport/2024.1, backport/2024.2

#9581 test(manager): update version of Manager in upgrade test
  jenkins-pipelines/manager/ubuntu24-manager-upgrade.jenkinsfile
Labels: backport/none

#9719 feature(sdcm) wait less for schema agreement
  sdcm/cluster.py
  sdcm/utils/health_checker.py
Labels: backport/none, test-provision-aws

#9912 fix(certificates): use real DNS names in SAN extension
  sdcm/cluster.py
  sdcm/cluster_aws.py
  sdcm/cluster_azure.py
  sdcm/cluster_gce.py
  sdcm/utils/net.py
Labels: backport/none

#9917 improvement(artifacts): switch to syslog-ng logs transport
  test-cases/artifacts/azure-image.yaml
  test-cases/artifacts/centos7.yaml
  test-cases/artifacts/centos9-selinux.yaml
  test-cases/artifacts/centos9.yaml
  test-cases/artifacts/debian11.yaml
  test-cases/artifacts/debian12.yaml
  test-cases/artifacts/gce-image-persistent-disk.yaml
  test-cases/artifacts/gce-image.yaml
  test-cases/artifacts/rhel7.yaml
  test-cases/artifacts/rhel8.yaml
  test-cases/artifacts/rocky8.yaml
  test-cases/artifacts/rocky9-selinux.yaml
  test-cases/artifacts/rocky9.yaml
  test-cases/artifacts/ubuntu2004.yaml
  test-cases/artifacts/ubuntu2204.yaml
  test-cases/artifacts/ubuntu2404.yaml
Labels: backport/none

#9828 fix(base_versions): add OSS mapping for 2025.1
  unit_tests/test_base_version.py
  utils/get_supported_scylla_base_versions.py
Labels: backport/none, backport/2025.1

#9922 fix(performance): add sleep after warm-up
  performance_regression_gradual_grow_throughput.py
Labels: backport/perf-v16

#9931 fix(cleanup): fix capacity reservation in clean resources
  sdcm/provision/aws/capacity_reservation.py
  sdcm/utils/resources_cleanup.py
Labels: backport/perf-v14, backport/perf-v15, backport/2024.2, backport/perf-v16

#9921 ci(cql-stress): use newest cql-stress benchmarking tool
  defaults/docker_images/cql-stress-cassandra-stress/values_cql-stress-cassandra-stress.yaml
  docker/cql-stress-cassandra-stress/Dockerfile
  docker/cql-stress-cassandra-stress/image
Labels: test-integration, backport/2024.1, backport/2024.2, backport/6.1, backport/6.2, backport/perf-v16, backport/2025.1

#9927 fix(sct_config): change type of perf_gradual_ params
  sdcm/sct_config.py
Labels: backport/perf-v16

#9949 improvement(capacity_reservations): add RunByUser and JenkinsJobTag tags
  sdcm/provision/aws/capacity_reservation.py
Labels: backport/perf-v15, backport/2024.2, backport/perf-v16, backport/2025.1

#9946 fix(perf trigger): change Scylla version from enterprise to master
  jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-enterprise-performance-tablets-trigger.xml
  jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-enterprise-performance-trigger.xml
  jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-master-performance-tablets-trigger.xml
  jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-master-performance-trigger.xml
Labels: backport/perf-v15, backport/perf-v16

#9948 improvement(cleanup): add capacity reservation cleanup
  utils/cloud_cleanup/aws/clean_aws.py
Labels: backport/none

#9958 improvement(cloud_usage_report): add capacity reservations
  sdcm/utils/cloud_monitor/cloud_monitor.py
  sdcm/utils/cloud_monitor/report.py
  sdcm/utils/cloud_monitor/resources/capacity_reservations.py
  sdcm/utils/cloud_monitor/templates/per_user_summary.html
Labels: backport/none

#9957 fix(capacity_reservation): reduce nemesis_add_node_cnt when not needed
  test-cases/performance/perf-regression-latency-1TB.yaml
  test-cases/performance/perf-regression-latency-650gb-upgrade.yaml
  test-cases/performance/perf-regression-predefined-throughput-steps.yaml
  test-cases/performance/perf-regression.100threads.30M-keys-i4i.yaml
Labels: backport/2024.1, backport/perf-v15, backport/perf-v16, backport/2025.1
