Repository scylladb/scylla-cluster-tests, pull requests merged in 2025-09, with the labels that each got.

#11874 fix(performance): disable parallel node operations
  test-cases/performance/perf-regression-latency-650gb-with-nemesis.yaml
Labels: backport/perf-v17

#11873 fix(performance): add thresholds to RBNO disabled test
  jenkins-pipelines/performance/branch-perf-v17/scylla-enterprise/perf-regression/scylla-enterprise-perf-regression-latency-650gb-with-nemesis-rbno-disabled.jenkinsfile
Labels: backport/perf-v17

#11756 Revert "fix(treewide): Disable Tombstone GC for now"
  test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml
  test-cases/longevity/longevity-large-partition-8h.yaml
  test-cases/longevity/longevity-lwt-500G-3d.yaml
Labels: backport/2025.3

#11788 fix(upgrade): make latte-based upgrade test use round_robin only
  upgrade_test.py
Labels: backport/perf-v15, backport/perf-v16, backport/2025.1, backport/2025.2, backport/2025.3, backport/perf-v17

#11353 test(Manager Backup): add native/rclone backup benchmarking under read/write stress
  configurations/manager/2TB_backup_dataset.yaml
  configurations/manager/manager_native_backup_nemesis.yaml
  configurations/manager/manager_rclone_backup_nemesis.yaml
  configurations/performance/latency-decorator-error-thresholds-nemesis-ent-tablets.yaml
  data_dir/nemesis.yml
  data_dir/nemesis_classes.yml
  jenkins-pipelines/manager/manager-backup-native-backup.jenkinsfile
  jenkins-pipelines/performance/branch-perf-v15/scylla-enterprise/perf-regression/scylla-enterprise-perf-manager-native-backup-nemesis.jenkinsfile
  jenkins-pipelines/performance/branch-perf-v15/scylla-enterprise/perf-regression/scylla-enterprise-perf-manager-rclone-backup-nemesis.jenkinsfile
  mgmt_cli_test.py
  mgmt_upgrade_test.py
  performance_regression_manager_backup_test.py
  performance_regression_test.py
  sdcm/argus_results.py
  sdcm/mgmt/argus_report.py
  sdcm/mgmt/cli.py
  sdcm/mgmt/common.py
  sdcm/mgmt/operations.py
  sdcm/nemesis.py
  sdcm/provision/scylla_yaml/scylla_yaml.py
  sdcm/utils/cluster_tools.py
  sdcm/utils/common.py
  test-cases/performance/perf-regression-latency-backup-nemesis.yaml
  unit_tests/test_scylla_yaml.py
Labels: backport/none, Ready for review, Ready to be Merged, status/merge candidate

#11905 fix(manager): up SM DB version to the latest 2025.3
  defaults/manager_versions.yaml
  unit_tests/test_sdcm_mgmt_common.py
Labels: backport/2025.1, backport/2025.2, backport/2025.3, backport/perf-v17

#11906 ci(manager): update default ScyllaDB version to 2025.3
  jenkins-pipelines/manager/ubuntu22-manager-install.jenkinsfile
  jenkins-pipelines/manager/ubuntu22-manager-sanity.jenkinsfile
  jenkins-pipelines/manager/ubuntu22-manager-upgrade.jenkinsfile
  vars/managerPipeline.groovy
Labels: backport/none

#11891 fix(provision): remove counter commands from provision tests
  test-cases/PR-provision-test-docker.yaml
  test-cases/PR-provision-test.yaml
Labels: backport/none

#11886 feature(xcloud): introduce provising test CI
  Jenkinsfile
  vars/getJenkinsLabels.groovy
Labels: backport/none, test-provision-xcloud-aws, test-provision-xcloud-gce

#11924 ci(latte): bump latte version to `0.33.0-scylladb`
  defaults/docker_images/latte/values_latte.yaml
Labels: backport/perf-v15, backport/perf-v16, backport/2025.1, backport/2025.2, backport/2025.3, backport/perf-v17

#10927 Add performance regression tests to Alternator
  configurations/alternator/enforce-authorization.yaml
  docs/configuration_options.md
  jenkins-pipelines/performance/branch-perf-v16/scylla-master/perf-regression/scylla-release-perf-regression-alternator.jenkinsfile
  performance_regression_alternator_test.py
  performance_regression_test.py
  sdcm/argus_results.py
  sdcm/sct_config.py
  sdcm/send_email.py
  sdcm/stress/base.py
  sdcm/tester.py
  sdcm/utils/decorators.py
  sdcm/utils/hdrhistogram.py
  sdcm/utils/remote_logger.py
  sdcm/utils/version_utils.py
  sdcm/ycsb_thread.py
  test-cases/longevity/longevity-ycsb-a-100M.yaml
  test-cases/longevity/longevity-ycsb-a-10M.yaml
  test-cases/longevity/longevity-ycsb-a-1B.yaml
  test-cases/longevity/longevity-ycsb-a-1M.yaml
  test-cases/performance/perf-regression-alternator-basic.yaml
  test-cases/performance/perf-regression-alternator-full.yaml
  test-cases/performance/perf-regression-alternator-latency-500gb-30min.yaml
  vars/perfRegressionParallelPipelinebyRegion.groovy
Labels: backport/perf-v17

#11952 fix(trigger): missed comma in performance trigger
  vars/perfRegressionParallelPipelinebyRegion.groovy
Labels: backport/perf-v16, backport/perf-v17

#11890 fix(hdr analyze): HDR histogram summary
  sdcm/utils/hdrhistogram.py
Labels: backport/perf-v16, backport/perf-v17

#11982 fix(racks): Increase amount of nodes for `custom-d1/workflow2` config
  test-cases/longevity/longevity-gce-custom-d1-workload2-hybrid-raid.yaml
Labels: backport/2025.1, backport/2025.2, backport/2025.3, backport/perf-v17

#11983 fix(racks): Increase amount of nodes for `custom-d1/workflow1` config
  test-cases/longevity/longevity-gce-custom-d1-workload1-hybrid-raid.yaml
Labels: backport/2025.1, backport/2025.2, backport/2025.3, backport/perf-v17

#11927 improvement(actions_log): added more actions log lines
  artifacts_test.py
  sdcm/nemesis.py
  sdcm/sct_events/base.py
  sdcm/tester.py
  sdcm/utils/raft/common.py
  upgrade_test.py
Labels: backport/2025.1, backport/2025.2, backport/2025.3, backport/perf-v17

#11995 improvement(performance): move throughput tests to branch-perf-v17
  jenkins-pipelines/performance/branch-perf-v17/scylla-enterprise/perf-regression/scylla-enterprise-perf-regression-predefined-throughput-steps-vnodes.jenkinsfile
  jenkins-pipelines/performance/branch-perf-v17/scylla-enterprise/perf-regression/scylla-enterprise-perf-regression-predefined-throughput-steps-write-vnodes.jenkinsfile
Labels: backport/perf-v17

#12008 fix(.pre-commit-config.yaml): disable detect-aws-credentials if no credentials
  .pre-commit-config.yaml
Labels: backport/2024.1, backport/2025.1, backport/2025.2, backport/2025.3, backport/perf-v17

#12024 feature(copilot): added AGENTS.md
  AGENTS.md
Labels: backport/none

#11926 fix(manager backup): remove obsolete pipeline
  jenkins-pipelines/manager/manager-backup-native-backup.jenkinsfile
  jenkins-pipelines/performance/branch-perf-v17/scylla-enterprise/perf-regression/scylla-enterprise-perf-manager-native-backup-nemesis.jenkinsfile
  jenkins-pipelines/performance/branch-perf-v17/scylla-enterprise/perf-regression/scylla-enterprise-perf-manager-rclone-backup-nemesis.jenkinsfile
Labels: Ready to be Merged, backport/perf-v17

#12002 feature(readme): update instructions for setup local dev env
  README.md
  docs/install-local-env.md
Labels: backport/none

#11810 fix(performance): disable simulated racks for vnodes operation tests in branch-v17
  configurations/disable_simulated_racks.yaml
  jenkins-pipelines/performance/branch-perf-v17/scylla-enterprise/perf-regression/scylla-enterprise-perf-regression-latency-650gb-with-nemesis-rbno-disabled.jenkinsfile
  jenkins-pipelines/performance/branch-perf-v17/scylla-enterprise/perf-regression/scylla-enterprise-perf-regression-latency-650gb-with-nemesis.jenkinsfile
Labels: backport/perf-v17

#12066 Increate future timeout
  sdcm/utils/hdrhistogram.py
Labels: backport/perf-v17
