Repository scylladb/scylla-cluster-tests, pull requests merged in 2025-05, with the labels that each got.

#10749 improvement(send_email): don't fail having no recipients
  vars/runSendEmail.groovy
Labels: backport/2024.1, backport/perf-v15, backport/2024.2, backport/6.2, backport/perf-v16, backport/2025.1

#10759 fix(k8s-pod-watcher): check for uninitialized watcher in conditionals
  sdcm/remote/kubernetes_cmd_runner.py
Labels: backport/none

#10753 improvement(cluster): Remove pylint disables
  cluster_configuration_tests.py
  sdcm/cluster.py
  sdcm/cluster_aws.py
  sdcm/cluster_azure.py
  sdcm/cluster_baremetal.py
  sdcm/cluster_docker.py
  sdcm/cluster_gce.py
  sdcm/provision/scylla_yaml/cluster_builder.py
  sdcm/sct_provision/aws/cluster.py
Labels: backport/2024.1, backport/2024.2, backport/6.2, backport/perf-v16, backport/2025.1

#10752 improvement(nemesis): Remove pylint disables
  sdcm/nemesis.py
Labels: backport/2024.2, backport/6.2, backport/perf-v16, backport/2025.1

#10801 fix(github-actions): generated code validation to post to correct repo
  .github/actions/run-validation/action.yml
Labels: backport/none

#10802 Revert "chore(deps): bump s-b version to 0.2.3"
  defaults/docker_images/scylla-bench/values_scylla-bench.yaml
Labels: backport/2024.1, backport/2024.2, P0, backport/2025.1

#10807 fix(microbanchmark): skip update_test_with_errors
  microbenchmarking_test.py
Labels: backport/perf-v15

#10779 fix(coredump): wait for active coredumps completion
  sdcm/cluster.py
  sdcm/coredump.py
  unit_tests/test_data/test_coredump/systemd/exceptions_limit_not_reached_test_remoter.json
  unit_tests/test_data/test_coredump/systemd/exceptions_limit_reached_test_remoter.json
  unit_tests/test_data/test_coredump/systemd/fail_get_list_test_remoter.json
  unit_tests/test_data/test_coredump/systemd/fail_upload_test_remoter.json
  unit_tests/test_data/test_coredump/systemd/success_test_remoter.json
  unit_tests/test_data/test_coredump/systemd/success_test_systemd_248_remoter.json
Labels: backport/2024.1, backport/perf-v15, backport/6.2, backport/perf-v16, backport/2025.1

#10827 fix(integration): make scylla container have shared volume mounts
  unit_tests/conftest.py
Labels: backport/none, test-integration

#10823 fix(syslogng): update installation sequence for syslogng
  sdcm/provision/common/configuration_script.py
  sdcm/provision/common/utils.py
Labels: backport/none

#10831 Revert "improvement(adaptive_timeout): lower timeout values when using tablets"
  defaults/severities.yaml
  sdcm/sct_events/system.py
  sdcm/utils/adaptive_timeouts/__init__.py
  unit_tests/test_adaptive_timeouts.py
Labels: backport/none

#10814 fix(builders): limit executors to one
  sdcm/utils/aws_builder.py
  sdcm/utils/gce_builder.py
Labels: backport/none

#10830 fix(hydra.sh): correctly parse SCT_* env var values containing `=`
  docker/env/hydra.sh
Labels: backport/none

#10829 fix(logcollector): omit copying a non-exisintg remote log file
  sdcm/logcollector.py
Labels: backport/2024.2, backport/2025.1, backport/2025.2

#10846 fix(oneline_backtrace_decoding): decode oversized allocation correctly
  sdcm/db_log_reader.py
  unit_tests/test_cluster.py
  unit_tests/test_data/system_one_line_backtrace.log
Labels: backport/2025.1, backport/2025.2

#10758 fix(nemesis): enhance disrupt_mgmt_restore to restore schema out of Manager
  sdcm/mgmt/helpers.py
  sdcm/nemesis.py
Labels: backport/2024.1, backport/2024.2, backport/2025.1, backport/2025.2

#10495 feature(gemini): run latest gemini version as Tier 1 testing tool
  defaults/docker_images/gemini/values_gemini.yaml
  jenkins-pipelines/master-triggers/sct_triggers/tier1-custom-time-trigger.xml
  jenkins-pipelines/oss/tier1/gemini-1tb-10h.jenkinsfile
  sdcm/gemini_thread.py
  unit_tests/test_gemini_thread.py
Labels: test-integration, backport/2025.1, backport/2025.2

#10833 fix(result analyze): handle missed doc in EC exception
  sdcm/results_analyze/__init__.py
Labels: backport/perf-v15, backport/perf-v16

#10872 fix(renovate): improve labeling of PRs
  renovate.json
Labels: backport/none

#10875 fix(syslogng): use backoff timeout in retries in installation sequence
  sdcm/provision/common/configuration_script.py
  sdcm/provision/common/utils.py
Labels: backport/2024.2, backport/2025.1, backport/2025.2

#10877 fix(logcollector): ignore changes in log files when creating archive
  sdcm/logcollector.py
Labels: test-provision-aws, backport/2025.1, backport/2025.2

#10717 fix(large-partition-200k-test): adjust s-b retry number/interval values
  test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml
Labels: backport/2024.1, backport/2024.2, backport/2025.1, backport/2025.2

#10841 improvement(logging): added 'actions' log
  artifacts_test.py
  sdcm/logcollector.py
  sdcm/sct_events/base.py
  sdcm/tester.py
  sdcm/utils/action_logger.py
  sdcm/utils/log.py
  upgrade_test.py
Labels: backport/2025.1, backport/2025.2

#10904 ci(perf): add latency steady state perf test using latte
  configurations/performance/latte-perf-regression-latency-steady-state-custom-d1-workload1.yaml
  jenkins-pipelines/performance/latte-perf-regression-latency-steady-state-custom-d1-workload1.jenkinsfile
  vars/perfRegressionParallelPipeline.groovy
Labels: backport/perf-v15, backport/perf-v16, backport/2025.1, backport/2025.2

#10853 Check limited voters feature after upgrade
  sdcm/exceptions.py
  upgrade_test.py
Labels: backport/2025.2

#10210 fix(manager): skip test_enospc_before_restore if tablets enabled
  mgmt_cli_test.py
Labels: backport/none

#10941 fix(siren): introduce cloud_cluster_name config parameter
  docs/configuration_options.md
  sdcm/sct_config.py
Labels: backport/none

#10944 fix(unit-test): skip the T`estBaseVersion.test_2025_1_release_centos` test
  unit_tests/test_base_version.py
Labels: backport/none

#10939 fix(database_events): Set ALLOCATION_MEMERY AS WARNING
  defaults/severities.yaml
  sdcm/sct_events/database.py
Labels: backport/2025.2

#10912 improvement(nemesis_tests): Make tests independant from production Nemesis
  unit_tests/nemesis/__init__.py
  unit_tests/nemesis/fake_cluster.py
  unit_tests/nemesis/test_registry.py
  unit_tests/nemesis/test_sisyphus.py
  unit_tests/nemesis/test_specific_nemesis.py
  unit_tests/test_nemesis.py
Labels: backport/2025.1, backport/2025.2

#10931 improvement(Pipeline): Make use of separator plugin
  vars/artifactsPipeline.groovy
  vars/byoLongevityPipeline.groovy
  vars/managerPipeline.groovy
  vars/rollingUpgradePipeline.groovy
Labels: backport/2025.2

#10964 chore(cql-stess): update to 0.2.3
  defaults/docker_images/cql-stress-cassandra-stress/values_cql-stress-cassandra-stress.yaml
Labels: backport/perf-v16, backport/2025.2

#10975 fix(scylla_yaml): Allow usage of any option in append_scylla_yaml
  sdcm/provision/scylla_yaml/scylla_yaml.py
  unit_tests/test_data/test_scylla_yaml_builders/functional.result.json
  unit_tests/test_data/test_scylla_yaml_builders/functional.yaml
Labels: backport/perf-v15, backport/2025.1, backport/2025.2

#10757 test(performance): add lz4 and zstd dict compression test
  configurations/compression/lz4_dict_compression.yaml
  configurations/compression/zstd_dict_compression.yaml
  jenkins-pipelines/performance/branch-perf-v16/scylla-master/perf-features/compression/_display_name
  jenkins-pipelines/performance/branch-perf-v16/scylla-master/perf-features/compression/features-lz4-dict-compression.jenkinsfile
  jenkins-pipelines/performance/branch-perf-v16/scylla-master/perf-features/compression/features-zstd-dict-compression.jenkinsfile
Labels: backport/perf-v16, backport/2025.2
