Repository scylladb/scylla-cluster-tests, pull requests merged in 2025-07, with the labels that each got.

#11237 feature(cloud_cleanup): cleanup unattached security groups
  utils/cloud_cleanup/aws/clean_aws.py
Labels: backport/none, Infrastructure

#11139 feature(nemesis): introduce nemesis node allocator
  sdcm/cluster_aws.py
  sdcm/cluster_azure.py
  sdcm/cluster_docker.py
  sdcm/cluster_gce.py
  sdcm/cluster_k8s/eks.py
  sdcm/cluster_k8s/gke.py
  sdcm/nemesis.py
  sdcm/tester.py
  sdcm/utils/nemesis_utils/__init__.py
  sdcm/utils/nemesis_utils/node_allocator.py
  unit_tests/nemesis/fake_cluster.py
  unit_tests/nemesis/test_node_allocator.py
  unit_tests/nemesis/test_sisyphus.py
Labels: backport/none

#11272 feature(perf-test): throttle/limit performance test per region
  vars/perfRegressionParallelPipeline.groovy
Labels: backport/perf-v15, backport/perf-v16

#11215 fix(nemesis): clearing keyspaces after mngmt restore operations
  sdcm/nemesis.py
Labels: backport/2025.1, backport/2025.2, backport/2025.3

#11346 fix(longevity): Increase back node size in longevity-large-partition-200k_pks-4days.yaml
  test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml
Labels: area/tablets, backport/2025.2, backport/2025.3

#11349 fix(longevity): Increase back node size in longevity-parallel-schema-changes-12h.yaml
  test-cases/longevity/longevity-parallel-schema-changes-12h.yaml
Labels: backport/2025.2, backport/2025.3

#11310 improvement(images): do not rebuild scylladb image
  artifacts_test.py
  sdcm/cluster_docker.py
  sdcm/remote/docker_cmd_runner.py
  sdcm/utils/docker_utils.py
  unit_tests/test_docker_cmd_runner.py
Labels: backport/none, test-provision-aws, test-provision-docker

#11252 chore: upgrade s-b to 0.2.5
  defaults/docker_images/scylla-bench/values_scylla-bench.yaml
Labels: test-integration, backport/2024.1, backport/2024.2, backport/2025.1, backport/2025.2, backport/2025.3

#11343 fix(sct_event): improve ignoring `auth_service - Unexpected exception` events
  sdcm/sct_events/setup.py
Labels: backport/none

#11393 fix(pull_image): correctly check if node is a docker container
  sdcm/utils/docker_remote.py
Labels: test-provision-aws, test-provision-gce, test-integration, backport/2025.1, backport/2025.2, backport/2025.3

#11416 ci(latte): bump latte version to `0.31.1-scylladb`
  defaults/docker_images/latte/values_latte.yaml
Labels: test-integration, backport/perf-v15, backport/perf-v16, backport/2025.1, backport/2025.2, backport/2025.3

#11418 fix(cqlshrc): update cqlshrc only once
  sdcm/provision/scylla_yaml/certificate_builder.py
  sdcm/tester.py
Labels: backport/2024.2, backport/2025.1, backport/2025.2, backport/2025.3

#11395 feature(skip_on_capacity_issues): check cluster layout before skipping
  docs/configuration_options.md
  sdcm/nemesis.py
  sdcm/sct_config.py
  sdcm/utils/cluster_tools.py
  sdcm/utils/decorators.py
  unit_tests/test_utils_cluster_tools.py
Labels: backport/2025.2, backport/2025.3

#11255 improvement(sdcm/utils/common.py): Add `public` flag to upload_file
  sct.py
  sdcm/logcollector.py
  sdcm/utils/common.py
Labels: backport/2025.2, backport/2025.3

#11410 feature(cloud_backend): add a new backend for Scylla cloud
  defaults/cloud_config.yaml
  docs/configuration_options.md
  sdcm/cloud_api_client.py
  sdcm/cluster.py
  sdcm/cluster_cloud.py
  sdcm/keystore.py
  sdcm/sct_config.py
  sdcm/tester.py
  sdcm/utils/cloud_api_utils.py
  sdcm/utils/resources_cleanup.py
Labels: backport/none

#11466 fix(audit_parsing): add support for comma separated values
  sdcm/audit.py
  unit_tests/test_audit.py
  unit_tests/test_data/test_audit_comma_sep.log
Labels: backport/none

#11475 feature(skip_on_capacity_issues): check for gce ServiceUnavailable errors
  sdcm/utils/decorators.py
Labels: backport/2025.1, backport/2025.2, backport/2025.3

#11371 feature(gemini): use new gemini version 2.0
  defaults/docker_images/gemini/values_gemini.yaml
  sdcm/gemini_thread.py
  test-cases/gemini/gemini-1tb-10h.yaml
  test-cases/gemini/gemini-3h-cdc-postimage-write.yaml
  test-cases/gemini/gemini-3h-cdc-preimage-write.yaml
  test-cases/gemini/gemini-3h-cdc-write.yaml
  test-cases/gemini/gemini-3h-ics-cdc-with-nemesis.yaml
  test-cases/gemini/gemini-3h-ics-with-nondisruptive-nemesis.yaml
  test-cases/gemini/gemini-3h-with-nemesis.yaml
  test-cases/gemini/gemini-3h-with-nondisruptive-nemesis.yaml
  test-cases/gemini/gemini-8h-large-num-columns.yaml
  test-cases/gemini/gemini-basic-3h-ics.yaml
  test-cases/gemini/gemini-basic-3h.yaml
  unit_tests/test_gemini_thread.py
Labels: backport/none, test-integration

#11502 improvement(trigger): few changes and fixes in performance tests trigger module
  vars/perfRegressionParallelPipelinebyRegion.groovy
Labels: backport/perf-v15

#11515 fix(trigger): missed '{'
  vars/perfRegressionParallelPipelinebyRegion.groovy
Labels: backport/perf-v15

#11518 fix(trigger): sub-tests names
  vars/perfRegressionParallelPipelinebyRegion.groovy
Labels: backport/perf-v15

#11528 fix(trigger): remove quotes in timer
  vars/perfRegressionParallelPipelinebyRegion.groovy
Labels: backport/perf-v15

#11505 fix(artifact): prevent teardown race condition
  sdcm/utils/remote_logger.py
Labels: test-provision-aws, test-provision-docker, test-integration, backport/perf-v15, backport/perf-v16, backport/2025.3

#11429 fix(nemesis): assertion added for case when no user table found
  sdcm/nemesis.py
Labels: backport/none

#11514 improvement(provision_resources): Handle provision errors for Argus
  sct.py
Labels: backport/2025.2, backport/2025.3

#11519 feature(copy_ami_to_all_regions): support copy permissions
  utils/copy_ami_to_all_regions.py
Labels: backport/none

#11539 improvement(performance): set max throughput
  configurations/performance/latency-decorator-error-thresholds-steps-ent-tablets.yaml
  configurations/performance/latency-decorator-error-thresholds-steps-ent-vnodes.yaml
Labels: backport/perf-v16

#11552 improvement(latte): use host network and disable secure computing mode
  sdcm/stress/latte_thread.py
Labels: test-integration, backport/perf-v15, backport/perf-v16, backport/2025.1, backport/2025.2, backport/2025.3

#11563 test(trigger): run scylla-bench with rackaware validation in tier1
  jenkins-pipelines/master-triggers/sct_triggers/tier1-custom-time-trigger.xml
Labels: backport/none

#11568 ci(latte): bump latte version to `0.32.0-scylladb`
  defaults/docker_images/latte/values_latte.yaml
Labels: backport/perf-v15, backport/perf-v16, backport/2025.1, backport/2025.2, backport/2025.3

#11576 fix(cleanup): fix cleanup of AWS KMS key aliases
  sdcm/provision/aws/dedicated_host.py
Labels: test-provision-aws, backport/perf-v15, backport/perf-v16, backport/2025.3
