Repository scylladb/scylla-cluster-tests, pull requests merged in 2025-04, with the labels that each got.

#10541 fix(artifact_test): switch the skip issue for scylla-doctor of non-root
  artifacts_test.py
Labels: backport/2024.2, backport/6.2, backport/2025.1

#10520 improvement(latte): add tag or operation type to log filenames
  sdcm/stress/latte_thread.py
  unit_tests/test_latte_thread.py
Labels: backport/perf-v15, backport/2024.2, backport/6.2, backport/perf-v16, backport/2025.1

#10479 improvement(vars/longevityPipeline.groovy): Make use of separator plugin
  vars/longevityPipeline.groovy
Labels: backport/none

#10336 fix(nemesis): TTL setter workaround added for non TWCS tables
  sdcm/nemesis.py
Labels: promoted-to-master, backport/2025.1

#9991 improvement(upgrade_test): Move InfoEvent message into their respective functions
  performance_regression_test.py
  upgrade_test.py
Labels: backport/none, promoted-to-master

#10535 fix(tearDown): Close DECODING_QUEUE
  sdcm/tester.py
Labels: backport/none, test-provision-aws, test-integration

#10552 improvement(latte): collect latte and rust driver versions
  sdcm/reporting/tooling_reporter.py
  sdcm/stress/latte_thread.py
  unit_tests/test_latte_thread.py
Labels: test-integration, backport/perf-v15, backport/2024.2, backport/6.2, backport/perf-v16, backport/2025.1

#10470 feature(argus): call client with extra headers
  argus/client/base.py
  argus/client/driver_matrix_tests/cli.py
  argus/client/driver_matrix_tests/client.py
  argus/client/generic/cli.py
  argus/client/generic/client.py
  argus/client/sct/client.py
  argus/client/sirenada/client.py
  argus/version
  sdcm/utils/argus.py
  utils/cloud_cleanup/__init__.py
  utils/migrate_latency_results_to_argus.py
Labels: test-provision-aws, test-integration, backport/2023.1, backport/2024.1, backport/perf-v15, backport/2024.2, backport/6.1, backport/6.2, backport/perf-v16, backport/2025.1

#10574 improvement(nemesis): Remove deprecated Nemesis
  sdcm/nemesis.py
Labels: backport/none

#10576 improvement(pyproject): Add autopep8 configuration
  .pre-commit-config.yaml
  pyproject.toml
Labels: backport/none

#10587 fix(azure): fetch offical source-available release correctly
  sdcm/provision/azure/utils.py
Labels: backport/2025.1

#10525 feature(cql-stress): add support for hdr histogram
  configurations/performance/cql-stress-650gb-8-col-i4i-80-percent-throughput-ent.yaml
  configurations/performance/cql-stress-650gb-8-col-i4i-80-percent-throughput-oss.yaml
  configurations/performance/cql-stress-6gb-8-col-i4i-mini-test-throughput.yaml
  defaults/docker_images/cql-stress-cassandra-stress/values_cql-stress-cassandra-stress.yaml
  sdcm/cql_stress_cassandra_stress_thread.py
  sdcm/loader.py
Labels: backport/perf-v16

#10596 fix(sdcm/iotune): Do not submit results if test doesn't exist
  sdcm/argus_results.py
  sdcm/utils/validators/iotune.py
Labels: backport/2024.2, backport/6.2, backport/2025.1

#10582 fix(perf-regression-test): parse stress results before pushing to ES
  sdcm/tester.py
Labels: backport/none

#10583 fix(gemini_thread.py): fix appending of gemini default flags
  sdcm/gemini_thread.py
  unit_tests/test_gemini_thread.py
Labels: backport/none, test-integration

#10607 [Backport perf-v16] fix(auto backport): trigger with labeled event
  .github/workflows/add-label-when-promoted.yaml
Labels: backport/none

#10608 [Backport perf-v15] fix(auto backport): trigger with labeled event
  .github/workflows/add-label-when-promoted.yaml
Labels: backport/none

#10606 fix(performance): change error threshold for steps test
  configurations/performance/latency-decorator-error-thresholds-steps-ent-tablets.yaml
  configurations/performance/latency-decorator-error-thresholds-steps-ent-vnodes.yaml
Labels: backport/perf-v16

#10585 fix(RemoteCmdRunner): fix scp destination string
  sdcm/remote/remote_base.py
Labels: backport/none, test-provision-aws

#10597 fix(performance): decrease nemesis test duration
  test-cases/performance/perf-regression-latency-650gb-with-nemesis.yaml
Labels: backport/perf-v15

#10612 fix(add-label-when-promoted): match regex for perf
  .github/workflows/add-label-when-promoted.yaml
Labels: backport/none

#10614 fix(ScyllaYaml): replace enable_tablets with tablets_mode_for_new_keyspaces
  configurations/force-gossip-topology-changes.yaml
  configurations/tablets-initial-32.yaml
  configurations/tablets_disabled.yaml
  docker/scylla-sct/entry.sh
  docker/scylla-sct/entry_ssl.sh
  sdcm/provision/scylla_yaml/scylla_yaml.py
  sdcm/utils/features.py
  test-cases/PR-provision-test-docker.yaml
  test-cases/PR-provision-test.yaml
  test-cases/longevity/longevity-aws-custom-d2-workload1-3dcs.yaml
  test-cases/longevity/longevity-aws-custom-d2-workload1-5dcs.yaml
  unit_tests/test_scylla_yaml.py
  upgrade_test.py
Labels: test-provision-aws, test-provision-docker, backport/perf-v15, backport/perf-v16, backport/2025.1

#10542 fix(sct): Dont require Okta for commands which do not need it
  sct.py
Labels: backport/none

#10386 fix(longevity_test): Set ignore 'raft topology connection close' error globally
  sdcm/sct_events/setup.py
Labels: Ready for review, backport/2025.1

#10621 fix(manager): apply dc-mapping only if restoring tables, not schema
  mgmt_cli_test.py
  sdcm/mgmt/cli.py
Labels: backport/none

#10634 fix(remote): add exception info to `_run_on_retryable_exception`
  sdcm/remote/kubernetes_cmd_runner.py
  sdcm/remote/remote_cmd_runner.py
  sdcm/remote/remote_libssh_cmd_runner.py
Labels: backport/2024.2, backport/2025.1

#10250 fix(wait_for_view_to_be_built) function did not return if only an ind…
  sdcm/utils/nemesis_utils/indexes.py
Labels: backport/none

#10642 improvement(sct): Do not require AWS for conf-docs and update-conf-docs
  sct.py
  sdcm/sct_config.py
Labels: backport/none

#10648 fix(docker): ignore warnings during stop
  sdcm/cluster_docker.py
Labels: backport/none

#10636 fix(limited_voters): validate non-voters as failed for scylla <=2025.1
  sdcm/cluster.py
  sdcm/utils/features.py
  sdcm/utils/raft/__init__.py
  sdcm/utils/raft/common.py
Labels: backport/none

#10650 fix(search_inconsistent_host_ids): use correct logic
  sdcm/utils/raft/__init__.py
Labels: backport/2025.1

#10652 fix(docker): stop checking housekeeping for ent
  artifacts_test.py
Labels: backport/2024.1, backport/2024.2, backport/6.2, backport/2025.1

#10564 feature(events): new event for catching oversized allocation
  defaults/severities.yaml
  sdcm/sct_events/database.py
Labels: backport/2025.1

#10661 fix(sct_runner.py): rename update_at_scope to begin_update_at_scope
  sdcm/sct_runner.py
Labels: backport/2025.1

#10573 fix(upgrade): make rolling upgrade use `cl=QUORUM` instead of `cl=ONE`
  test-cases/upgrades/rolling-upgrade.yaml
Labels: backport/2025.1

#10666 fix(performance): not validate P90 metrix
  configurations/performance/latency-decorator-error-thresholds-steps-ent-tablets.yaml
  configurations/performance/latency-decorator-error-thresholds-steps-ent-vnodes.yaml
Labels: backport/perf-v16

#10667 test(performance): add sanity throughput test
  jenkins-pipelines/performance/branch-perf-v16/scylla-master/perf-regression/_display_name
  jenkins-pipelines/performance/branch-perf-v16/scylla-master/perf-regression/perf-regression-predefined-throughput-steps-sanity-vnodes.jenkinsfile
Labels: backport/perf-v15, backport/perf-v16

#10664 feature(log-collect): collect content of system.truncated
  sdcm/logcollector.py
  sdcm/tester.py
Labels: backport/2025.1

#10505 improvement(scylla-bench): report scylla-bench version info in logs
  sdcm/reporting/tooling_reporter.py
  sdcm/scylla_bench_thread.py
Labels: backport/none

#10682 fix(trigger): new_scylla_repo param for upgrade with tablets
  jenkins-pipelines/performance/branch-perf-v15/scylla-master/weekly-enterprise-performance-tablets-trigger.xml
Labels: backport/perf-v15

#10679 test(trigger): trigger for daily short performance tests
  jenkins-pipelines/performance/branch-perf-v15/scylla-master/daily-master-performance-aws-sanily-trigger.xml
Labels: backport/perf-v15

#10678 fix(sct_event): ignore `auth_service - Unexpected exception` events
  sdcm/sct_events/setup.py
Labels: backport/none

#10638 fix(docker): disable `print_kernel_callstack` for docker backend
  defaults/docker_config.yaml
  sdcm/cluster.py
Labels: backport/2025.1

#10674 fix(preload): use proper timeout for preload stress commands
  add_new_dc_test.py
  admission_control_overload_test.py
  performance_regression_alternator_test.py
  performance_regression_gradual_grow_throughput.py
  performance_regression_operator_multi_tenant_test.py
  performance_regression_row_level_repair_test.py
  performance_regression_test.py
  sdcm/utils/loader_utils.py
Labels: test-provision-aws, test-integration, backport/2025.1

#10690 fix(is_scylla_installed): stop using package manager
  sdcm/cluster.py
Labels: backport/2025.1

#10691 fix(latte): avoid hdrh files reading and stress start race
  sdcm/stress/latte_thread.py
  sdcm/utils/remote_logger.py
Labels: test-integration, backport/perf-v15, backport/perf-v16, backport/2025.1

#10699 fix(gcp_cleanup): Fix gcp filter to collect correct disks for clean up
  sdcm/utils/gce_utils.py
Labels: backport/none

#10630 chore: saving schema with internals added while tearDown
  sdcm/logcollector.py
  sdcm/tester.py
Labels: backport/none

#10712 fix(is_scylla_installed): stop using package manager
  sdcm/cluster.py
Labels: backport/none

#10711 fix(is_scylla_installed): stop using package manager
  sdcm/cluster.py
Labels: backport/none

#10718 fix(performance): do not run cluster health validator
  test-cases/performance/perf-regression-latency-650gb-elasticity.yaml
  test-cases/performance/perf-regression-latency-650gb-with-nemesis.yaml
Labels: backport/perf-v15

#10509 fix(certificate_builder): Add ssl factory entrypoint for cqlshrc
  sdcm/provision/helpers/certificate.py
  sdcm/provision/scylla_yaml/certificate_builder.py
Labels: backport/2024.2, backport/6.2, backport/2025.1

#10390 setting the images for scylla monitoring 4.9.2
  defaults/aws_config.yaml
  defaults/gce_config.yaml
Labels: backport/none

#10487 fix(sdcm/cluster.py): Use microdnf on rhel-like docker backend
  docker/scylla-sct/centos/Dockerfile
  sdcm/cluster.py
  utils/scylla_doctor.py
Labels: backport/2024.2, backport/6.2, backport/2025.1

#10698 chore(deps): bump s-b version to 0.2.3
  defaults/docker_images/scylla-bench/values_scylla-bench.yaml
Labels: test-integration, backport/2024.1, backport/2024.2, backport/2025.1

#10646 improvement(decode_backtrace): improve logic
  sdcm/cluster.py
  sdcm/db_log_reader.py
  unit_tests/test_cluster.py
  unit_tests/test_decode_backtrace.py
Labels: backport/2024.1, backport/perf-v16, backport/2025.1

#10694 fix(enable_default_filters): move DB event filter for raft error to default filters
  sdcm/sct_events/group_common_events.py
  sdcm/sct_events/setup.py
  unit_tests/test_events.py
Labels: test-provision, test-integration, backport/2025.1

#10729 fix(performance): use docker with 3.17.5 in operations/upgrade
  test-cases/performance/perf-regression-latency-650gb-upgrade.yaml
  test-cases/performance/perf-regression-latency-650gb-with-nemesis.yaml
Labels: backport/perf-v15

#10751 improvement(pylintrc): Remove pylintrc
  pylintrc
Labels: backport/2024.2, backport/perf-v16, backport/2025.1

#10726 fix(hydra): fix podman support
  docker/env/hydra.sh
Labels: backport/2025.1

#10756 fix(perf-pipeline): add Argus step to pipeline
  vars/perfRegressionParallelPipeline.groovy
Labels: backport/perf-v15, backport/perf-v16
