Repository scylladb/scylla-cluster-tests, pull requests merged in 2025-02, with the labels that each got.

#9914 fix(cdc_reader): overwrite "run" method in cdc_reader_thread
  sdcm/cdclog_reader_thread.py
  sdcm/tester.py
Labels: backport/2024.2, backport/6.1, backport/6.2, backport/2025.1

#9985 fix(ci-pipeline): fix integration and provision test
  Jenkinsfile
  test-cases/PR-provision-test.yaml
  unit_tests/conftest.py
  unit_tests/test_cassandra_stress_thread.py
Labels: test-integration, backport/2025.1

#9987 fix(FullScanAggregate): use "warning" severity on some errors
  sdcm/scan_operation_thread.py
  unit_tests/test_scan_operation_thread.py
Labels: backport/2025.1

#10011 fix(integration-test): fix test_03_cassandra_stress_client_encrypt test
  sdcm/utils/docker_remote.py
  unit_tests/conftest.py
  unit_tests/test_cassandra_stress_thread.py
Labels: backport/none, test-integration, backport/2025.1

#10015 ci(latte): bump latte version to 0.28.2-scylladb
  defaults/docker_images/latte/values_latte.yaml
Labels: backport/perf-v15, backport/2024.2, backport/6.2, backport/perf-v16, backport/2025.1

#10018 fix(nemesis.py): use system logger to log nemesis start/end on nodes
  sdcm/cluster.py
  sdcm/nemesis.py
  unit_tests/dummy_remote.py
  unit_tests/test_nemesis.py
Labels: backport/2024.1, backport/perf-v15, backport/2024.2, backport/6.2, backport/perf-v16, backport/2025.1

#10042 fix(Azure): enable WaLinuxAgent
  sdcm/sct_provision/region_definition_builder.py
  sdcm/sct_provision/user_data_objects/walinuxagent.py
Labels: backport/2025.1

#10021 improvement(monitor): refactor benchmarking tools panels
  data_dir/scylla-dash-per-server-nemesis.master.json
Labels: backport/perf-v15, backport/2024.2, backport/6.2, backport/perf-v16, backport/2025.1

#9959 fix(gemini-cmd): broken gemini commands on upgrades
  defaults/docker_images/gemini/values_gemini.yaml
  sdcm/gemini_thread.py
  test-cases/cdc/cdc-15m-replication-gemini.yaml
  test-cases/cdc/cdc-15m-replication-postimage.yaml
  test-cases/cdc/cdc-15m-replication-preimage.yaml
  test-cases/cdc/cdc-replication-longevity.yaml
  test-cases/upgrades/rolling-upgrade.yaml
  unit_tests/test_data/test_scylla_yaml_builders/multi_network_interfaces/cdc-replication-longevity.yaml
  unit_tests/test_data/test_scylla_yaml_builders/rolling-upgrade.yaml
Labels: test-integration, backport/2024.2, backport/6.1, backport/6.2, backport/2025.1

#10064 fix(latte): run latte docker container setting entrypoint explicitly
  sdcm/stress/latte_thread.py
Labels: test-integration, backport/perf-v15, backport/2024.2, backport/6.2, backport/perf-v16, backport/2025.1

#10008 fix(BaseNode): fix is_enterprise property for 2025.1
  sdcm/cluster.py
  unit_tests/test_cluster.py
  unit_tests/test_utils_common.py
Labels: backport/2025.1

#10072 fix(nemesis.py): ignore networkd coredump in RandomInterruptionNetwork
  sdcm/cluster.py
  sdcm/nemesis.py
Labels: backport/2025.1

#10071 chore(deps): update argus client
  argus/client/generic/cli.py
  argus/client/generic/client.py
  argus/client/generic_result.py
  argus/client/sct/client.py
  argus/version
  unit_tests/test_argus_results.py
Labels: backport/perf-v15, backport/perf-v16, backport/2025.1

#9978 fix(DecommissionStreamingErr): new log lines added
  sdcm/utils/raft/__init__.py
Labels: backport/2024.2, backport/6.1, backport/6.2

#10073 refactor(hdrh): support HDR histograms for multiple benchmarking tools
  performance_regression_gradual_grow_throughput.py
  performance_regression_test.py
  sdcm/cluster.py
  sdcm/loader.py
  sdcm/logcollector.py
  sdcm/nemesis.py
  sdcm/scylla_bench_thread.py
  sdcm/stress/base.py
  sdcm/stress_thread.py
  sdcm/tester.py
  sdcm/utils/decorators.py
  sdcm/utils/hdrhistogram.py
  ycsb_performance_regression_test.py
Labels: test-integration, backport/perf-v15, backport/2024.2, backport/6.2, backport/perf-v16, backport/2025.1

#9924 improvement(artifacts): switch to syslog-ng logs transport
  sdcm/cluster.py
  sdcm/provision/common/configuration_script.py
  sdcm/provision/common/utils.py
  sdcm/utils/aws_builder.py
  sdcm/utils/remote_logger.py
  test-cases/artifacts/ami.yaml
  test-cases/artifacts/azure-image.yaml
  test-cases/artifacts/centos7.yaml
  test-cases/artifacts/centos9-selinux.yaml
  test-cases/artifacts/centos9.yaml
  test-cases/artifacts/debian11.yaml
  test-cases/artifacts/debian12.yaml
  test-cases/artifacts/gce-image-persistent-disk.yaml
  test-cases/artifacts/gce-image.yaml
  test-cases/artifacts/oel76.yaml
  test-cases/artifacts/oel8.yaml
  test-cases/artifacts/oel9.yaml
  test-cases/artifacts/rhel7.yaml
  test-cases/artifacts/rhel8.yaml
  test-cases/artifacts/rocky8.yaml
  test-cases/artifacts/rocky9-selinux.yaml
  test-cases/artifacts/rocky9.yaml
  test-cases/artifacts/ubuntu2004-fips.yaml
  test-cases/artifacts/ubuntu2004.yaml
  test-cases/artifacts/ubuntu2204.yaml
  test-cases/artifacts/ubuntu2404.yaml
Labels: backport/none

#10093 fix(tier1): Reintroduce tier1 tablet tests
  jenkins-pipelines/oss/tier1/longevity-150gb-asymmetric-cluster-12h.jenkinsfile
  jenkins-pipelines/oss/tier1/longevity-1tb-5days-azure.jenkinsfile
  jenkins-pipelines/oss/tier1/longevity-50gb-3days.jenkinsfile
  jenkins-pipelines/oss/tier1/longevity-large-partition-200k-pks-4days-gce.jenkinsfile
  jenkins-pipelines/oss/tier1/longevity-multidc-schema-topology-changes-12h.jenkinsfile
  jenkins-pipelines/oss/tier1/longevity-mv-si-4days-streaming.jenkinsfile
  jenkins-pipelines/oss/tier1/longevity-schema-topology-changes-12h.jenkinsfile
  jenkins-pipelines/oss/tier1/longevity-twcs-48h.jenkinsfile
Labels: backport/2025.1

#10078 fix(unit-test): unflake cdc cluster test
  unit_tests/test_cluster.py
Labels: backport/2024.1, backport/perf-v15, backport/2024.2, backport/perf-v16, backport/2025.1

#10100 fix(performance): split base versions for rolling upgrade test
  vars/perfRegressionParallelPipeline.groovy
Labels: backport/perf-v15, backport/perf-v16

#10101 fix(rolling-upgrade): remove branch filter
  vars/supportedUpgradeFromVersions.groovy
Labels: backport/none

#9993 fix(LoaderUtilsMixin): table_enabled was allways True as this feature is allways enabled
  sdcm/cluster.py
  sdcm/fill_db_data.py
  sdcm/nemesis.py
  sdcm/tester.py
  sdcm/utils/features.py
  sdcm/utils/loader_utils.py
  sdcm/utils/tablets/common.py
  sla_per_user_system_test.py
Labels: backport/2025.1

#10088 fix(manager): clean up non-supported SCT_BACKUP_BUCKET_REGION var
  jenkins-pipelines/manager/helpers/prepare-backup-snapshot.jenkinsfile
Labels: backport/none

#10058 refactor(upgrade_test): Support only smooth upgrades for 2025.1 and above
  upgrade_test.py
Labels: backport/none

#10010 fix(kubernetis): get device name for k8s node
  sdcm/cluster_k8s/__init__.py
  sdcm/nemesis.py
  sdcm/provision/network_configuration.py
Labels: backport/2025.1

#9995 fix(web_install): always use scylla as product
  sdcm/cluster.py
  sdcm/utils/version_utils.py
  unit_tests/test_version_utils.py
Labels: backport/2025.1

#9796 test(elacticity with nemesis): test 90 percent with supported nemesis
  data_dir/nemesis.yml
  jenkins-pipelines/oss/features/elasticity/elasticity-90-percent-with-nemesis.jenkinsfile
  sdcm/nemesis.py
  test-cases/features/elasticity/elasticity-90-percent-with-nemesis.yaml
Labels: backport/none, area/elastic cloud

#10107 fix(upgrade-test): fix is_enterprise on rollback to oss
  sdcm/cluster.py
Labels: backport/none

#10116 fix(Nemesis): is_tablets_feature_enabled wrong keyword argument
  sdcm/nemesis.py
  sdcm/tester.py
Labels: backport/2025.1

#10118 fix(gemini): make gemini work without oracle passed
  sdcm/gemini_thread.py
  unit_tests/test_gemini_thread.py
Labels: test-integration, backport/2025.1

#10124 improvement(pyproject.toml): Add Argus client to ignores for Ruff
  pyproject.toml
Labels: backport/none

#10122 fix(nemesis): disrupt_snapshot_operations expects MV in snapshot
  sdcm/nemesis.py
Labels: backport/2025.1

#10129 fix(hdr_tags): fix getting of HDR tags in the perf predefined steps test
  sdcm/utils/decorators.py
  unit_tests/test_utils_decorators.py
Labels: backport/perf-v15, backport/2024.2, backport/6.2, backport/perf-v16, backport/2025.1

#10146 fix(list-image): improve handling of rc versions listing
  sdcm/utils/common.py
Labels: backport/2025.1

#9484 fix(performance): change loader type
  test-cases/performance/perf-regression-latency-650gb-elasticity.yaml
  test-cases/performance/perf-regression-latency-650gb-upgrade.yaml
  test-cases/performance/perf-regression-latency-650gb-with-nemesis.yaml
Labels: backport/perf-v15

#10145 fix(cleanup): fix cleaning CRs when no region provided
  sdcm/provision/aws/capacity_reservation.py
  sdcm/utils/resources_cleanup.py
Labels: backport/2024.2, backport/2025.1

#10143 improvement(setup): enable parallel node operations by default
  defaults/test_default.yaml
Labels: backport/none

#10125 fix(wait_no_tablets_migration_running): add soft timeout
  sdcm/utils/adaptive_timeouts/__init__.py
  sdcm/utils/tablets/common.py
Labels: backport/2025.1

#10130 fix(modify_table_compaction): filter_out_table_with_counter is not filtering counter tables
  sdcm/cluster.py
  sdcm/nemesis.py
Labels: backport/2025.1

#10172 fix(logcollector): introduce correct check to zstd only file
  sdcm/logcollector.py
Labels: backport/2025.1

#10171 refactor(upgrade_test): align filter events into decorators
  upgrade_test.py
Labels: backport/2025.1

#10153 fix(DataCenterTopologyRfControl): stop taking region to RF=0
  sdcm/utils/replication_strategy_utils.py
Labels: backport/2025.1

#10016 fix(nemesis): add node with same token type after topology operation
  sdcm/nemesis.py
Labels: Ready for review, backport/6.2, backport/2025.1

#9992 improvement(nemesis): allow specify different seeds for parallel nemesis
  sdcm/cluster.py
  sdcm/nemesis.py
  sdcm/sct_config.py
  sdcm/tester.py
  sdcm/utils/operations_thread.py
  test-cases/longevity/longevity-multidc-parallel-topology-schema-changes-12h.yaml
Labels: backport/none

#10190 test(default): set 'tablets_initial_scale_factor' scylla config option
  defaults/test_default.yaml
  unit_tests/test_scylla_yaml_builders.py
Labels: backport/none

#10189 test(add_remove_dc): write more data and flush
  sdcm/nemesis.py
Labels: backport/none

#10194 fix(aws_builder): disable java new http max values
  sdcm/utils/aws_builder.py
Labels: backport/none

#10211 fix(NodeBase): add missing `_set_keep_duration` implementations
  sdcm/cluster_azure.py
  sdcm/cluster_k8s/__init__.py
  unit_tests/dummy_remote.py
Labels: backport/perf-v15, backport/6.2, backport/perf-v16, backport/2025.1

#10216 refactor(check_nodes_up_and_normal) - return a better exception message
  sdcm/cluster.py
Labels: backport/none, test-provision-aws

#10218 fix(cluster_docker): add missing `_set_keep_duration` implementation
  sdcm/cluster_docker.py
Labels: test-provision-docker, backport/2024.1, backport/perf-v15, backport/2024.2, backport/6.2, backport/perf-v16, backport/2025.1
